Add a voiding mode for Super/Quantum tanks
GTNewHorizons/GT5-Unofficial pull request #1009
Opened 2022-04-04 16:33 UTC by MuXiu1997

closed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7565

2022-04-07 23:55 UTC, Glease commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalTankBase.java
> +        return commonSizeCompute(mTier);
I'd say return Integer.MAX_VALUE if mVoidOverflow is on. There are smart logisitics tools that try to figure out how much to fill before calling #fill()

2022-04-08 02:10 UTC, MuXiu1997 commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalTankBase.java
> +        return commonSizeCompute(mTier);
Awesome!

2022-04-08 07:30 UTC, Glease requested changes

2022-04-08 07:30 UTC, Glease commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalTankBase.java
> +            if (aFluid.amount <= getCapacity()) {
getCapacity is no longer reliable once we change perceived capacity when mVoidMode is on. We will probably need a getRealCapacity or something...

2022-04-08 08:54 UTC, MuXiu1997 commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalTankBase.java
> +            if (aFluid.amount <= getCapacity()) {
I was too careless
Fixed

2022-04-08 19:00 UTC, Glease approved these changes

2022-04-08 19:02 UTC, merged