Allows sorting of configuration circuits
GTNewHorizons/GT5-Unofficial pull request #1012
Opened 2022-04-06 17:09 UTC by MuXiu1997

Closed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9809

2022-04-06 17:12 UTC, MuXiu1997 commented on src/main/java/gregtech/api/GregTech_API.java
> +                .sorted(getConfigurationCircuitsComparator())
The reason for sorting here and not elsewhere is the reference above to `DO NOT MODIFY THE ItemStacks!`

2022-04-08 01:13 UTC, Glease approved these changes

2022-04-08 01:28 UTC, Glease requested changes

2022-04-08 01:28 UTC, Glease commented on src/main/java/gregtech/loaders/preload/GT_PreLoad.java
> +        final String[] Circuits = GregTech_API.sClientDataFile.get("interface", "CircuitsOrder", "").split(";");
There is an overload in GT_Config that returns String[] and uses the proper string list property in the underlying forge Configuration class. Please use that instead of inventing our own.

2022-04-08 01:48 UTC, MuXiu1997 commented on src/main/java/gregtech/loaders/preload/GT_PreLoad.java
> +        final String[] Circuits = GregTech_API.sClientDataFile.get("interface", "CircuitsOrder", "").split(";");
Modified

2022-04-08 07:23 UTC, Glease approved these changes

2022-04-08 13:41 UTC, merged