Change Super Fuels and Added Advanced Glue
GTNewHorizons/GT5-Unofficial pull request #1042
Opened 2022-04-27 17:14 UTC by Steelux8

- Changed Super Fuel recipes to accept HOG input instead of CBD. The amount of input is proportional to the fuel value, so that both recipes match in the fuel value of inputs;
- Added a new early-game glue, Advanced Glue, which replaces Refined Glue in the recipes that use Polyvinyl Acetate and Methyl Acetate/Acetone;
- Changed the Super Fuel Binder recipes to use this new glue instead of the old one;
- Added recipes with the new glue for making Graphene Dust with the first two wafers, Glowstone and Naquadah. My intent is to replace the old glue altogether in these recipes.

This new glue will possibly replace Refined Glue in some early-mid game recipes. I plan to make a set of tiered glues, in the same fashion to the Glue -> Plastic -> PTFE -> PBI, but as Glue -> Advanced Glue -> Super Glue -> Reinforced Super Glue (last one yet to be implemented).

Will also add Nitrobenzene as a possible input for Super Fuels. All three main combustion/gas fuels that don't have any further progression (HOG, CBD, Nitrobenzene) can be progressed with Super Fuels, which afford more EU but need further processing. Nitrobenzene is a GT++ fluid, so I will code for it in Dreamcraft.

2022-06-19 18:42 UTC, eigenraven requested changes
Just a couple of minor questions

2022-06-19 18:42 UTC, eigenraven commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java
> +                        if (GT_Utility.getFluidForFilledItem(tInput, true) == null && (this.mMaxProgresstime = GT_ModHandler.getFuelValue(tInput) / 80) > 0 && (GT_ModHandler.getFuelValue(tInput) * 2
Is this change intended to be a part of this pr? Seems unrelated

2022-06-19 18:42 UTC, eigenraven commented on src/main/java/gregtech/loaders/preload/GT_Loader_Item_Block_And_Fluid.java
> +        //GT_Mod.gregtechproxy.addFluid("advancedGlue", "Advanced Glue", Materials.AdvancedGlue, 1, 295, GT_OreDictUnificator.get(OrePrefixes.cell, Materials.AdvancedGlue, 1L), ItemList.Cell_Empty.ge
Why is this in a comment?

2022-06-19 19:12 UTC, Steelux8 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java
> +                        if (GT_Utility.getFluidForFilledItem(tInput, true) == null && (this.mMaxProgresstime = GT_ModHandler.getFuelValue(tInput) / 80) > 0 && (GT_ModHandler.getFuelValue(tInput) * 2
I could have added a comment to explain, but I forgot to do so. That change is there because the Large Steel Boiler did not accept Charcoal because the fuel value was too low compared to that boiler's EU/t. I increased that fuel value in the comparison here so it would be allowed.

2022-06-22 10:09 UTC, eigenraven approved these changes

2022-06-22 10:43 UTC, merged