Plasma forge fixes
GTNewHorizons/GT5-Unofficial pull request #1086
Opened 2022-06-20 00:22 UTC by Connor-Colenso

2022-06-20 09:54 UTC, Dream-Master commented
Why this pr add so many commits ? It just change 2 files so far i can see.

2022-06-22 14:22 UTC, eigenraven requested changes

2022-06-22 14:22 UTC, eigenraven commented on src/main/java/gregtech/api/enums/Materials.java
> +            System.out.println("ABC1234 " + aMaterial.mHasPlasma + aMaterial.mHasGas);
This debugging printing should be removed

2022-06-22 14:22 UTC, eigenraven commented on src/main/java/gregtech/api/enums/TextureSet.java
> +import javax.xml.soap.Text;
Wrong/unnecessary import?

2022-06-22 14:22 UTC, eigenraven commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PlasmaForge.java
> +        byte tier_of_hatch = mEnergyHatches.get(0).mTier;
Move this below the energy hatch count check, if someone builds this without a single energy hatch this would be an NPE.

2022-06-22 20:08 UTC, Connor-Colenso commented
I kinda ended up refactoring a bunch as I needed a better way to handle the plasma forge in the GT NEI default handler to render items properly. Ended up gutting like 200 lines of redundant code.

2022-06-22 22:03 UTC, merged