Add Advanced Gas Turbine and Limit Original LGT
GTNewHorizons/GT5-Unofficial pull request #1106
Opened 2022-07-01 13:24 UTC by Steelux8

- Added an Advanced LGT, made out of HSS-S, that only accepts gas fuels with a fuel value above 800k per bucket;
- Capped the EU/t output of the regular LGT at 8192 EU/t, regardless of dynamo (it will never explode);

I have made this implementation as a countermeasure for Benzene, when used in IV. Due to some multiblocks, such as the TGS and the ICO, this MV powergen can be stretched to IV without a lot of setup, and it turns out to be really powerful.

In summary, the LGT, which is HV-tier, will be capped to the EU/t of a single IV amp. It will not explode if the turbine inside is too powerful, it will just void the excess energy. To produce more than this from one turbine, the Advanced LGT is implemented here, but it's made out of HSS-S (around 20 Osmium and 40 Iridium per turbine). Additionally, the very strong mar-ce turbine material can also have a countermeasure here, since it's too powerful for the original LGT.

2022-07-05 04:10 UTC, GlodBlock requested changes

2022-07-05 04:10 UTC, GlodBlock commented on src/main/java/gregtech/common/blocks/GT_Block_Casings8.java
> +            Textures.BlockIcons.casingTexturePages[0][i + 32] = TextureFactory.of(this, i);
don't change the texture index

2022-07-05 06:43 UTC, Steelux8 commented on src/main/java/gregtech/common/blocks/GT_Block_Casings8.java
> +            Textures.BlockIcons.casingTexturePages[0][i + 32] = TextureFactory.of(this, i);
I was unable to fetch the new textures I added if I had them on casingTexturePages[1]. I don't know what I need to change to look in a place other than casingTexturePages[0], which I believe is the default.

2022-07-08 06:49 UTC, Steelux8 commented
![2022-07-08_07 28 13](https://user-images.githubusercontent.com/70096037/177933512-ae8fe119-8f42-46e4-ae1a-d49ec7edf24f.png)

Textures are now fixed. I apologize for my careless mistake.

2022-07-08 10:28 UTC, GlodBlock approved these changes
code wise is okay now. but current gas fuel that fuel value is over 800eu/mb are only nitrobenzene and naquadah gas. naquadah gas is the byproduct for liquid naquadah fuel so it won't be avaible before luv. so only choice is nitrobenzene. i suggest to use 500eu/mb as the threshold so ppl can use ether from ethonal.
also don't forget set the nei catalysts for advanced gas turbine in nei. https://github.com/GTNewHorizons/NotEnoughItems/blob/master/src/main/resources/assets/nei/csv/catalysts.csv

2022-07-08 10:29 UTC, merged

2022-07-08 17:05 UTC, Steelux8 commented
> code wise is okay now. but current gas fuel that fuel value is over 800eu/mb are only nitrobenzene and naquadah gas. naquadah gas is the byproduct for liquid naquadah fuel so it won't be avaible before luv. so only choice is nitrobenzene. i suggest to use 500eu/mb as the threshold so ppl can use ether from ethonal. also don't forget set the nei catalysts for advanced gas turbine in nei. https://github.com/GTNewHorizons/NotEnoughItems/blob/master/src/main/resources/assets/nei/csv/catalysts.csv

I might tweak recipes to bring more gas fuels above 1M EU, or make new ones altogether. There should be at least another viable fuel in that range, the same way diesels have both CBD and HOG.