Fix IOOBE with DT structure check
GTNewHorizons/GT5-Unofficial pull request #1200
Opened 2022-08-04 08:06 UTC by miozune

Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10556

2022-08-04 15:41 UTC, Glease commented
Also fixed in #1117, btw why `XX - 1 < XX - 1`?

2022-08-04 16:14 UTC, miozune commented
It's typical list.size() - 1 < index. This PR is superseded anyway though

2022-08-08 22:03 UTC, leagris requested changes

2022-08-10 05:16 UTC, miozune commented
Superseded by #1117

2022-08-10 05:16 UTC, closed without merging