unlimit the lgt
GTNewHorizons/GT5-Unofficial pull request #1205
Opened 2022-08-05 02:48 UTC by GlodBlock

revert the limitation on lgt of https://github.com/GTNewHorizons/GT5-Unofficial/pull/1106

the limitation on lgt was for the abuse of benzene from tgs in early game like mv. now the tgs is tiered at iv so if you want reach such scale with eio farmer, you will need to power a hv or ev world acceralater which is expensive to affard in terms of energy and material.

also the advanced lgt is still kept, but its recipe is removed temparory. basically the so-called advanced lgt is just the copy of lgt which has no new or interesting mechanism. it will be kept unchanged in the this stable version (2.1.2.4) and a real rework on it will begin in next stable update. it will needs a new discord channel to discuss it properly with nh community

2022-08-05 15:19 UTC, Steelux8 commented
> the limitation on lgt was for the abuse of benzene from tgs in early game like mv.

No, it wasn't. The LGT isn't even available in MV, so I don't understand how you came to this conclusion. This limit, and the advanced LGT, were specifically developed to prevent Benzene as a main IV powergen choice, and the changed recipe of the TGS does not prevent that because it's still IV. 

Additionally, the EIO farmer can match its speed (as you mentioned), and it was the basis for the TGS's speed to begin with. The WA energy needed for it is minor compared to energy produced from the Benzene, so the TGS change is not enough to prevent IV Benzene. The LGT limit and the advanced LGT do it better.

2022-08-05 15:26 UTC, GlodBlock commented
> The LGT isn't even available in MV

then in hv, it is what you said in your origin pr

> WA energy needed for it is minor compared to energy produced from the Benzene

no

>prevent Benzene as a main IV powergen choice

one lgt is max to 1a luv output in iv and you don't have any good turbine to reach that output at iv

2022-08-05 15:32 UTC, Steelux8 commented
> then in hv, it is what you said in your origin pr
It is available at HV, yes, but the point was to limit Benzene at IV, not MV or HV. That is where the limit comes into play, unlike what you mentioned in this PR.

> no
What do you mean, "no"? You made the claim first, so can you show how an HV or EV WA is expensive in power compared to the final EU/t output of the setup?

> one lgt is max to 1a luv output in iv and you don't have any good turbine to reach that output at iv
Yes you do, I added them myself. Orichalcum should nearly cap an IV buffered dynamo, but only with 110% fuel efficiency, a necessary t3 rocket since it's a t3 ore, and an EBF recipe with HSS-S coils.

2022-08-05 15:40 UTC, GlodBlock commented
> It is available at HV, yes, but the point was to limit Benzene at IV, not MV or HV. That is where the limit comes into play, unlike what you mentioned in this PR.
You made the claim first, so can you show how an HV or EV WA is expensive in power compared to the final EU/t output of the setup?

do you ever made it? do you ever feed a luv gas turbine in iv?

> Yes you do, I added them myself

that is you adding unbalanced stuff.

2022-08-05 15:42 UTC, Steelux8 commented
> that is you adding unbalanced stuff.

Glod, I added the limitation specifically because of the new turbine materials I added, and I did that because I thought it was silly to have Oriharukon as the best IV material for turbines, but also unable to match an EV buffered dynamo. These changes work together, not separately.

2022-08-05 15:46 UTC, GlodBlock commented
a ev wa costs 3a ev. it means near 20% energy is consumed in a ev wa even you output full 1a luv. 

>I thought it was silly to have Oriharukon as the best IV material for turbines, but also unable to match an EV buffered dynamo.

it is just your personal idea

2022-08-05 15:48 UTC, GlodBlock commented
i will do a real game test tomorrow. the statistics can be more precise

2022-08-05 15:50 UTC, Steelux8 commented
> a ev wa costs 3a ev. it means near 20% energy is consumed in a ev wa even you output full 1a luv.

And what is the wood/s out of a EIO farmer with an EV WA? It could very well be fast enough to go beyond 1A LuV output in the end.

> it is just your personal idea

Can you contest it? Do you believe Oriharukon, as the best IV material, should make the IV Dynamo Hatch for the LGT pointless, given that it cannot even cap the EV buffered one?

2022-08-05 15:55 UTC, Steelux8 requested changes
Please provide an explanation about the current state of Benzene in IV, and why it would be unviable even without the LGT limitation. If the TGS continues to be IV, then Benzene should continue to be good in IV as well, if the LGT is not limited.

2022-08-05 16:29 UTC, GlodBlock commented
i find i almost get misleaded by arguing with you. all the problem you mentioned is a fuel problem, not a turbine problem

2022-08-05 16:35 UTC, Steelux8 commented
> i find i almost get misleaded by arguing with you. all the problem you mentioned is a fuel problem, not a turbine problem

That is because you don't understand the reason behind the changes I made, and yet you want to undo them.

2022-08-06 09:02 UTC, boubou19 commented
My main concern is that the LGT got hardcapped to prevent the benzene church from overscaling their benzene production, but, it impacts every fuel, not just benzene. ***__What are the collateral damages to players using other fuels?__*** Because i didn't see any consideration for the other fuels (i may be blind tho)

Also, hard capping something so you can add a copy of it without the limitation is not adding content, it's insulting people.
For example, Google did remove the background playing option of the youtube app years ago, so they could add it back in their shitty premium subscription, presenting this feature as a brand new option. In the current state of thing, ALGT was a solution in search of a problem.

But i don't think we should necessarily yeet the ALGT, as i think it has some potential. This is why I agree with Glod: a proper rework of the ALGT is required. 

To conclude, i wouldn't want to be in Steelux's shoes when people with the existing infra to generate power at IV out of the LGT will find out the hard way their base semi bricked because of the update. Because once again, a non trivial change is introduced without giving a warning to players, just to spank a very specific subset of the community because someone disliked it.

2022-08-06 09:59 UTC, Steelux8 commented
The collateral damage to other fuels is exactly the same: if you were meaning to use simple gases like Methane or Refinery Gas to set up your IV powergen to last until fusion, your best bet is Oriharukon LGTs, you can't use the better turbine materials. Upgrading to nitrobenzene lets you use the advanced LGT and the better materials.

A new ALGT with new mechanics is something I did want to do, but I haven't yet decided on the best approach to take. The progression of the new turbine materials is one thing, but the multi itself should have new mechanics as well. If this is important to do before next stable, I will do it.

Additionally, documentation is something I intend to do, on my quests as well as other related quests, the tooltip, etc.

2022-08-06 11:07 UTC, boubou19 commented
superseded by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1216

2022-08-06 11:07 UTC, closed without merging