Replace TSS Coils with Titanium-Platinum Ones
GTNewHorizons/GT5-Unofficial pull request #1211
Opened 2022-08-05 15:08 UTC by Steelux8

- Created a new material, TPV-Alloy, made from Titanium, Platinum and Vanadium (3/3/1);
- Replaced the Tungstensteel Coil Block with a TPV one, to make it properly included in EV while adding a Platinum sink in that tier;

The actual recipe for this new coil is not defined here, I'll have to change it in coremod. Additionally, the coil is still known internally as Tungstensteel, which can be changed later - I just wanted to make sure it works fine in-game.

The coil progression is not consistent with the tiers: LV has Cupronickel, MV has Kanthal, HV has Nichrome, and the next three are Tungstensteel, HSS-G and HSS-S. Since the TSS coils need 2 stacks of ingots for one EBF, it's easy to say that those three coil tiers are IV, and EV has none. That is the change this PR is for, to replace TSS coils with ones made of an alloy of Titanium, Platinum and Vanadium (the IRL alloy has Aluminium instead of Platinum and different proportions, but I wanted this to also be a plat sink while in EV).

2022-08-05 15:51 UTC, boubou19 commented
is it really necessary? for me the platinum sink is too much.

2022-08-05 16:02 UTC, Steelux8 commented
> is it really necessary? for me the platinum sink is too much.

It's 55 Platinum per EBF with these new coils. I found it to be a good amount, it that too much? If yes, the ratio of metals could be changed.

2022-08-05 16:04 UTC, chochem commented
EV is when you can make the platline (the platinum part) and where the quests for it are too. If you do that then 55 dusts is nothing. Sounds like a pretty good incentive for me - without being a hard wall.

2022-08-05 17:56 UTC, Steelux8 commented
I simplified the metal inputs (Titanium/Platinum/Vanadium), from 6/6/2 to 3/3/1 since it's the same thing.

2022-08-05 17:59 UTC, Connor-Colenso commented
Lets discuss this more after a stable release.

2022-10-22 08:30 UTC, Dream-Master commented
> Lets discuss this more after a stable release.

Stable is out so discussion can start.

2022-10-22 08:35 UTC, Dream-Master commented
> > Lets discuss this more after a stable release.
> 
> Stable is out so discussion can start.

I am Late EV now run a few cycles Platinum trough my chemical reactor and i see no issue about Plantinum.
And i am want to update my EBF to#. TSS rn so i can check if this is blance. TSS need much ebf time (HV 4 amp (EV) EBF with Nichrome coils)

2022-10-23 19:42 UTC, Connor-Colenso requested changes
There seems to be a lot of code in here that isn't actually related to new coils?

2022-10-23 19:42 UTC, Connor-Colenso commented on src/main/java/gregtech/common/GT_Proxy.java
> -
I don't understand what this code segment getting removed has to do with coils?

2022-10-23 19:42 UTC, Connor-Colenso commented on build.gradle
> +    if (usesMixins.toBoolean()) {
???

2022-10-23 19:46 UTC, Dream-Master commented on build.gradle
> +    if (usesMixins.toBoolean()) {
update buildscript

2022-10-23 19:46 UTC, Dream-Master commented on src/main/java/gregtech/common/GT_Proxy.java
> -
this are the beed conversion code was removed. Not sure why it appears in this pr

2022-10-23 19:47 UTC, boubou19 commented on build.gradle
> +    if (usesMixins.toBoolean()) {
this is just the buildscript udpate, nothing to worry too much about

2022-10-23 20:00 UTC, Connor-Colenso approved these changes

2022-10-23 20:00 UTC, merged