reworking drilling plant following 0lafe ticket
GTNewHorizons/GT5-Unofficial pull request #1286
Opened 2022-08-22 10:12 UTC by POPlol333

Everything asked except speed, I don't feel like touching it honestly, scared of breaking too much the balance or just doing garbage

On this mod work is done, still has to modify and add controller craft in nhcore and modify the infinite pump craft to take a rig IV instead of a III

close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8911

2022-08-22 10:14 UTC, Glease requested changes

2022-08-22 10:14 UTC, Glease commented on src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
> +        ItemList.OilDrill3.set(new GT_MetaTileEntity_OilDrill4(149, "multimachine.oildrill4", "Oil/Gas/Fluid Drilling Rig IV").getStackForm(1));
This is not going to work. Add a OilDrill4 in ItemList.

2022-08-22 10:18 UTC, POPlol333 commented on src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
> +        ItemList.OilDrill3.set(new GT_MetaTileEntity_OilDrill4(149, "multimachine.oildrill4", "Oil/Gas/Fluid Drilling Rig IV").getStackForm(1));
oh wait didn't notice right, but how does that worked on my client lmao
thanks  btw

2022-08-22 10:33 UTC, Dream-Master commented
Guess a recipe for control block need to be added

2022-08-22 10:35 UTC, POPlol333 commented
All the controller recipe are in nhcore (except the infinite which is in tectec) so I'll add the craft there

2022-08-22 10:35 UTC, Dream-Master commented
sure

2022-08-22 15:53 UTC, boubou19 requested changes

2022-08-22 15:53 UTC, boubou19 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OilDrill3.java
> +        return 50;
Same here

2022-08-22 15:53 UTC, boubou19 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OilDrill4.java
> +        return 48;
same here

2022-08-22 16:15 UTC, POPlol333 commented
if anyone tell me what that is and how it work then sure?

2022-08-23 10:10 UTC, Glease approved these changes
Code looks ok. We now just need to settle on the recipes..

2022-08-23 10:11 UTC, Dream-Master commented
Recipe comes in core mod like the others

2022-08-23 10:13 UTC, merged