various loading time optimization
GTNewHorizons/GT5-Unofficial pull request #1330
Opened 2022-08-31 15:30 UTC by Glease

no more stinky registerUsagesForMaterials yay! and I did it without parallelism!

2022-08-31 15:54 UTC, eigenraven commented on docs/structure_code.md
> +# GT5U Structure Code Guide
Did you include this file by mistake?

2022-08-31 16:06 UTC, leagris commented on src/main/java/gregtech/api/util/GT_RecipeRegistrator.java
> +import java.util.*;
There need to be some clean-up with imports.

2022-08-31 16:08 UTC, Dream-Master commented on docs/structure_code.md
> +# GT5U Structure Code Guide
i removed it

2022-08-31 16:22 UTC, Glease commented on docs/structure_code.md
> +# GT5U Structure Code Guide
bruh yeah it shouldn't be there. Thanks for the help.

2022-08-31 16:27 UTC, Glease commented on src/main/java/gregtech/api/util/GT_RecipeRegistrator.java
> +import java.util.*;
spotless complains if you place java in a separate block

2022-09-01 11:11 UTC, eigenraven requested changes

2022-09-01 11:11 UTC, eigenraven commented on src/main/java/gregtech/api/util/GT_RecipeRegistrator.java
> +                if (tRecipe instanceof ShapelessRecipes || tRecipe instanceof ShapelessOreRecipe) {
Move this if before the tStack checks, instanceof will be quicker than scanning lists

2022-09-01 11:17 UTC, Glease commented on src/main/java/gregtech/api/util/GT_RecipeRegistrator.java
> +                if (tRecipe instanceof ShapelessRecipes || tRecipe instanceof ShapelessOreRecipe) {
moved.

2022-09-01 11:19 UTC, eigenraven approved these changes

2022-09-01 11:22 UTC, Glease commented
Just come to think about this, wouldn't this also be a good way to speed up vanilla crafting bench recipe matching and not just GT loading?

2022-09-01 11:23 UTC, eigenraven commented
Probably, you could mixin it via hodgepodge into the shapedrecipe implementation I guess.

2022-09-01 11:25 UTC, merged