Adv debug structure writer
GTNewHorizons/GT5-Unofficial pull request #1362
Opened 2022-09-09 13:44 UTC by minecraft7771

Added an improved version of the debug structure writer to GT5U, so it can be used without the need to add TT.
Includes: 
New in world hologram
![](https://cdn.discordapp.com/attachments/386247221148123156/1017790042728583199/unknown.png)

New user interface
![](https://cdn.discordapp.com/attachments/386247221148123156/1017790075871969280/unknown.png)

2022-09-10 14:17 UTC, kuba6000 commented on src/main/java/gregtech/common/gui/GT_GUIContainer_AdvDebugStructureWriter.java
> +            fontRendererObj.drawString("C: " + dsw.numbers[5], 46, 86, 16448255);
Why ABC ? Why not XYZ

2022-09-10 14:22 UTC, kuba6000 commented on src/main/java/gregtech/common/gui/GT_Container_AdvDebugStructureWriter.java
> +        addSlotToContainer(new GT_Slot_Holo(mTileEntity, 2, 75, 129, false, false, 1));
Unused slot ?
![image](https://user-images.githubusercontent.com/53441451/189487662-bbf94706-d312-499f-95fd-fe3187e6ab74.png)

2022-09-10 14:51 UTC, Glease commented on src/main/java/gregtech/common/tileentities/debug/GT_MetaTileEntity_AdvDebugStructureWriter.java
> +            GT_MetaTileEntity_AdvDebugStructureWriter writer =
What? but why? Isn't this just a fancy and wasteful way of writing `this`?

2022-09-10 14:55 UTC, Glease commented on src/main/java/gregtech/common/gui/GT_GUIContainer_AdvDebugStructureWriter.java
> +            fontRendererObj.drawString("C: " + dsw.numbers[5], 46, 86, 16448255);
ABC is a structurelib term. It correspond to left-right axis coord, up-down axis coord, forward-backward axis coord when you are looking at the front of a controller. ABC is the same as minecraft XYZ only when controller has a particular facing no rotation.

2022-09-10 19:13 UTC, minecraft7771 commented on src/main/java/gregtech/common/gui/GT_Container_AdvDebugStructureWriter.java
> +        addSlotToContainer(new GT_Slot_Holo(mTileEntity, 2, 75, 129, false, false, 1));
Ye the plan was that it actually get another layout functions but will need to rewrite the structure lib method for that so its out for now.

2022-09-10 19:13 UTC, minecraft7771 commented on src/main/java/gregtech/common/gui/GT_GUIContainer_AdvDebugStructureWriter.java
> +    }
Didnt know about this, thats very neat. Thanks!

2022-09-10 22:48 UTC, kuba6000 requested changes

2022-09-10 22:48 UTC, kuba6000 commented on src/main/java/gregtech/common/gui/GT_GUIContainer_AdvDebugStructureWriter.java
> +        addToolTip(new GT_GuiSlotTooltip(getContainer().highlightSlot, mTooltipCache.getData("GT5U.machines.advdebugstructurewriter.gui.highlight")));
Please extract these strings to variables like here [GT_GUIContainer_BasicMachine.java#L40](https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/api/gui/GT_GUIContainer_BasicMachine.java#L40)
And perhaps add a ```.tooltip``` at the end of each one

2022-09-10 22:51 UTC, minecraft7771 commented on src/main/java/gregtech/common/gui/GT_GUIContainer_AdvDebugStructureWriter.java
> +        addToolTip(new GT_GuiSlotTooltip(getContainer().highlightSlot, mTooltipCache.getData("GT5U.machines.advdebugstructurewriter.gui.highlight")));
What's the reason behind extracting it?

2022-09-10 22:51 UTC, kuba6000 commented on src/main/java/gregtech/common/gui/GT_GUIContainer_AdvDebugStructureWriter.java
> +        addToolTip(new GT_GuiSlotTooltip(getContainer().highlightSlot, mTooltipCache.getData("GT5U.machines.advdebugstructurewriter.gui.highlight")));
Because its extracted everywhere else, and its easier to read then ?

2022-09-11 09:36 UTC, kuba6000 reviewed
Bounding boxes works only on SinglePlayer. I guess its debug tool so its not that important.

2022-09-11 09:38 UTC, kuba6000 approved these changes
It will be probably used on Singleplayer only anyway

2022-09-11 09:41 UTC, merged