Fix waila facings for basic machines
GTNewHorizons/GT5-Unofficial pull request #1368
Opened 2022-09-09 21:19 UTC by vlaetansky

Facings for basic machines is different than general meta tile entity, since it has a "main" facing.
![image](https://user-images.githubusercontent.com/87545780/189447170-a88a3766-13ec-4f65-9953-5a13a9289530.png)

2022-09-09 21:32 UTC, Alexdoru commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicMachine.java
> +                "Main Facing: %s", ForgeDirection.getOrientation(mMainFacing).name()));
can you change to "Machine Facing" please :3

2022-09-10 09:45 UTC, eigenraven requested changes
You should move the meta tile accesses into getWailaNBTData (also guard them for when getBaseMTE() is null just in case), and use the nbt fields in getWailaBody

2022-09-10 11:18 UTC, eigenraven commented on src/main/java/gregtech/api/util/GT_Waila.java
> +        StringBuilder stringBuilder = new StringBuilder(Strings.EMPTY);
This is a useless use of StringBuilder, you only append a String to it once - just make a `final String result` variable

2022-09-10 11:33 UTC, vlaetansky commented on src/main/java/gregtech/api/util/GT_Waila.java
> +        StringBuilder stringBuilder = new StringBuilder(Strings.EMPTY);
Oups yeah, initial implementation was different and included multiple appends to a single StringBuilder.

2022-09-10 11:39 UTC, eigenraven approved these changes

2022-09-10 13:24 UTC, merged