Nanite material and circuit board multi for later tiers
GTNewHorizons/GT5-Unofficial pull request #1513
Opened 2022-11-15 15:51 UTC by BlueWeabo

Still WIP. Just making it so that people can take a better look at it

2022-11-15 16:06 UTC, minecraft7771 requested changes

2022-11-15 16:06 UTC, minecraft7771 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +                                    .atLeast(InputHatch, OutputBus, InputBus, Maintenance, ExoticEnergy, Energy)
Same as above for energy

2022-11-15 17:29 UTC, BlueWeabo commented on src/main/java/gregtech/common/blocks/GT_Block_Casings8.java
> +        GT_LanguageManager.addStringLocalization(getUnlocalizedName() + ".11.name", "PCB Tier 1");
Casing names are temporary as I am bad at naming things

2022-11-24 22:41 UTC, BlueWeabo commented
Requires MUI merged in Master

2022-11-29 10:06 UTC, minecraft7771 requested changes

2022-11-29 10:06 UTC, minecraft7771 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_NanoForge.java
> +            ItemStack[] tItemInputs = getCompactedInputs();
Use `getStoredInputs()`, or else it can't process items over one stack

2022-11-29 10:06 UTC, minecraft7771 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +            ItemStack[] tItemInputs = getCompactedInputs();
Same as above.

2022-11-29 10:06 UTC, minecraft7771 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +                if (!depleteInput(new FluidStack(superCoolant, 10))) {
Please extract the amount of consumed coolant per second as const variable.

2022-11-29 10:12 UTC, minecraft7771 commented
Also you should probably put a description into the PR now that it is ready, so other devs also know what you're doing here.

2022-11-29 11:35 UTC, BlueWeabo commented
i have realised i missed one block's recipe. gonna add it in a lil bit

2022-11-29 13:53 UTC, minecraft7771 approved these changes

2022-11-29 14:01 UTC, Connor-Colenso submitted a review, later dismissed
Please do not merge this yet @Dream-Master, needs more discussion.

2022-11-29 16:42 UTC, Dream-Master commented
@Connor-Colenso more discussion about ?

2022-11-29 16:48 UTC, BlueWeabo commented
I was personally told about a few problems with recipes, which I will be fixing when I get home.

2022-12-09 12:04 UTC, Glease reviewed
I didn't actually read the UI code. I don't understand it yet. Nor did I read the recipe chain in detail. I just make sure it won't break without some external mod. However, the rest of the code looks mostly fine.

2022-12-09 12:04 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +                            mSetTier < 3
This will not do. You will need to synchronize the mSetTier to client somehow. See GT++ chemplant for reference. 

Or will modular UI do this for you?

2022-12-09 12:07 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +                            mSetTier < 3
In any case, you will always need to synchronize this yourself as the client might never open the GUI.

2022-12-09 12:14 UTC, minecraft7771 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_NanoForge.java
> +        if (mMaintenanceHatches.size() != 1 || mInputBusses.size() < 1 || mOutputBusses.size() < 1) {
He specifically doesn't want to allow more than 1 hatch too. Though I would agree that that is useless.

2022-12-09 19:30 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_NanoForge.java
> +        long tTotalEU = tVoltage / getExoticAndNormalEnergyHatchList().size() * tAmps;
because normally. the voltage gets added up together of all hatches placed. So for safety i am dividing by the amount of hatches to get the average voltage and then multiply it by the amps.

2022-12-09 20:01 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_NanoForge.java
> +        long tTotalEU = tVoltage / getExoticAndNormalEnergyHatchList().size() * tAmps;
gonna remove the dividing in a upcoming commit

2022-12-09 21:44 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +                            mSetTier < 3
Did I do it correctly?

2022-12-10 03:21 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +                            mSetTier < 3
Ah sorry I wasn't enough clear when I mentioned chemplant. you need to override getUpdateData to inform MTE system what you want to send, override receiveClientEvent to handle that data on client side when MTE syatem has delivered it to client for you (see [here](https://github.com/GTNewHorizons/GTplusplus/blob/7c0daec92b603657944b7d21dc10a207296b921a/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/GregtechMTE_ChemicalPlant.java#L581-L59)) and [tell MTE to send the data when it is changed](https://github.com/GTNewHorizons/GTplusplus/blob/7c0daec92b603657944b7d21dc10a207296b921a/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/chemplant/GregtechMTE_ChemicalPlant.java#L385). This method only allow sending a vart small value (iirc a byte or a short) but is usually enough when all you need is pass along a tier.

2022-12-10 08:15 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +                            mSetTier < 3
the gt++ code is such a mess i didn't even see that. gonna do it

2022-12-13 21:10 UTC, merged