Fix color override not working
GTNewHorizons/GT5-Unofficial pull request #1557
Opened 2022-12-18 08:02 UTC by miozune

2022-12-19 20:48 UTC, BlueWeabo commented on src/main/java/gregtech/nei/RecipeMapHandler.java
> +        colorOverride = GT_GUIColorOverride.get(ModularUITextures.VANILLA_BACKGROUND.location);
what does this mean? will it try to get the location of the file in the textures? So that texture packs can change it?

2022-12-19 21:07 UTC, OneEyeMaker requested changes

2022-12-19 21:07 UTC, OneEyeMaker commented on src/main/java/gregtech/api/util/ColorsMetadataSection.java
>      }
I suggest to save original intent of this method and just add exclamation mark (negation) after `&&` to fix logic. And then in methods above swap parts of ternary operators around (so fallback value `defaultColor` goes after real color).

Also, please, change name of this method (to `isColorInMap` or `isColorFound`). Just for readability.

2022-12-20 04:38 UTC, miozune commented on src/main/java/gregtech/nei/RecipeMapHandler.java
> +        colorOverride = GT_GUIColorOverride.get(ModularUITextures.VANILLA_BACKGROUND.location);
Yeah, this is rather oversight during MUI migration

2022-12-20 07:07 UTC, OneEyeMaker approved these changes

2022-12-20 07:14 UTC, merged