Improve NEI customizability
GTNewHorizons/GT5-Unofficial pull request #1583
Opened 2022-12-24 09:13 UTC by miozune

This PR aims at making NEI handler more flexible, so that addons don't need to make their own handler just for drawing some extra info.

2022-12-25 09:11 UTC, miozune commented
ready for review

2022-12-29 20:38 UTC, eigenraven requested changes

2022-12-29 20:38 UTC, eigenraven commented on src/main/java/gregtech/common/gui/modularui/UIHelper.java
> +    @Deprecated
Add a `/** @deprecated */` javadoc description of what to replace it with

2022-12-30 11:25 UTC, eigenraven approved these changes

2022-12-30 11:29 UTC, merged