Added Shortcut because simply dull
GTNewHorizons/GT5-Unofficial pull request #1594
Opened 2022-12-26 20:43 UTC by Runakai1

![image](https://user-images.githubusercontent.com/48415331/209582233-015cf214-5b6f-4aa4-9d70-f4391b087189.png)
Adds another recipe for Potassium Dichromate to avoid Chemical Reactor spam. The only use of Chromium Trioxide is Potassium Dichromate so players should be able to avoid making 2 extra reactors simply to make a nested chain.

2022-12-26 20:59 UTC, Pxx500 commented
From what I can see this whole chromium chain should be reworked, you can't get chromium trioxide from reacting chromium  with oxygen.

2022-12-26 21:00 UTC, Runakai1 commented
> From what I can see this whole chromium chain should be reworked, you can't get chromium trioxide from reacting chromium with oxygen.

You also can't get naquadah in real life and yet here we are

2022-12-26 21:00 UTC, Pxx500 commented
I'm not talking about unreal elements anyway.

2022-12-26 21:03 UTC, Runakai1 commented
I'm saying that the only use of Chromium trioxide is used in potassium dichromate. 
Don't make it artificially difficult and add to the gtnh grind because rEaLiSm. A proper chromium trioxide chain would be horribly overcomplicated for just this single use in a recipe

2022-12-26 21:11 UTC, Runakai1 commented
Let's stop moving in real life based chains and take the fun out of it (see kevlar)

2022-12-26 22:11 UTC, Dream-Master commented
No i would like @Pxx500 help us and not ignore his advise @Runakai1

2022-12-26 22:18 UTC, Runakai1 commented
> No i would like @Pxx500 help us and not ignore his advise @Runakai1

He basically told me "he doesn't care" when I argued about this on discord and then switched the topic to bees because he doesn't like bees too. 

He just did troll arguments and emojis and I can't see the help he is providing

2022-12-26 22:20 UTC, Sphyix commented
> From what I can see this whole chromium chain should be reworked, you can't get chromium trioxide from reacting chromium with oxygen.

Then rework it, don't come argue under stuff that actually removes useless machine spam

2022-12-26 22:21 UTC, BritishCynic commented
This is a much-desired and popular change. If the chain really does need reworking, perhaps @Pxx500 can dedicate some time to it.

The only reason to oppose this change is intransigence and a preference for the status quo.

2022-12-26 22:26 UTC, Pxx500 commented
> > No i would like @Pxx500 help us and not ignore his advise @Runakai1
> 
> He basically told me "he doesn't care" when I argued about this on discord and then switched the topic to bees because he doesn't like bees too.

No that's a manipulation, I do care about the realism, what you said is about unreal elements (naquadah) - since they don't have know properties I don't care about them specifically

2022-12-26 22:27 UTC, Pxx500 commented
> > No i would like @Pxx500 help us and not ignore his advise @Runakai1
> He just did troll arguments and emojis and I can't see the help he is providing.

> > From what I can see this whole chromium chain should be reworked, you can't get chromium trioxide from reacting chromium with oxygen.
> 
> Then rework it, don't come argue under stuff that actually removes useless machine spam If this PR goes trough, it's not going to influence a rework

I will start tomorrow when @kuba6000 is back from his trip so he can keep an eye on my code since I don't know shit about coding

2022-12-26 22:28 UTC, Runakai1 commented
I'd like to apologize for my harsh words if that seemed like that. I just want to include additional information that according to our conduct 
"You should avoid adding new content below IV tier, the game is already dense
enough as it is (especially the chemlines!)."
So in favour of the vision of the pack I don't think any additional difficulty on chromium should be included and removing two unnecessary chemical reactors for one single item is a good and healthy change.

2022-12-26 22:31 UTC, Runakai1 commented
In the meantime, I am absolutely convinced that until you can get your ideas and code ready, this should be merged with the idea of granting players what they demand. They shape the Modpack and we should he playing with our playerbase, not against them.

2022-12-26 22:33 UTC, Pxx500 commented
Of course it's not like I'm going to turn earlygame chromium into hell. I want to make it as simple as possible while being acceptable for new players, telling it will be a "line" was a joke I didn't properly disclose

2022-12-26 22:35 UTC, BritishCynic commented
> > > No i would like @Pxx500 help us and not ignore his advise @Runakai1
> > > He just did troll arguments and emojis and I can't see the help he is providing.
> 
> > > From what I can see this whole chromium chain should be reworked, you can't get chromium trioxide from reacting chromium with oxygen.
> > 
> > 
> > Then rework it, don't come argue under stuff that actually removes useless machine spam If this PR goes trough, it's not going to influence a rework
> 
> I will start tomorrow when @kuba6000 is back from his trip so he can keep an eye on my code since I don't know shit about coding

I fully endorse your choice to rework this process. In the meantime, while you collect yourself and plan how you intend to approach the task, this change should be approved so that player's lives can be made easier in time for the next stable release after which, assuming your task is completed in time for the stable release afterward, players can then begin to benefit from your process rework.

2022-12-26 22:36 UTC, Runakai1 commented
> Of course it's not like I'm going to turn earlygame chromium into hell. I want to make it as simple as possible while being acceptable for new players, telling it will be a "line" was a joke I didn't properly disclose

![image](https://user-images.githubusercontent.com/48415331/209586716-5e0355bd-dc1a-4273-9cd9-4bf27520fd72.png)
The only real viable real life form of producing it is that (I think so, at least) which requires the addition of sodium dichromate into the game which also requires:
![image](https://user-images.githubusercontent.com/48415331/209586755-93c967c5-dfba-49f1-8f95-987945350c0e.png)

So sorry, until you provide us with clear information on how you are going to make another way of achieving Chromium Trioxide while being realistic and at least as easy as the current way, I don't see it actually working out.

2022-12-26 22:37 UTC, Runakai1 commented
> > > > No i would like @Pxx500 help us and not ignore his advise @Runakai1
> > > > He just did troll arguments and emojis and I can't see the help he is providing.
> > 
> > 
> > > > From what I can see this whole chromium chain should be reworked, you can't get chromium trioxide from reacting chromium with oxygen.
> > > 
> > > 
> > > Then rework it, don't come argue under stuff that actually removes useless machine spam If this PR goes trough, it's not going to influence a rework
> > 
> > 
> > I will start tomorrow when @kuba6000 is back from his trip so he can keep an eye on my code since I don't know shit about coding
> 
> I fully endorse your choice to rework this process. In the meantime, while you collect yourself and plan how you intend to approach the task, this change should be approved so that player's lives can be made easier in time for the next stable release after which, assuming your task is completed in time for the stable release afterward, players can then begin to benefit from your process rework.

This is a nice idea.

2022-12-26 22:41 UTC, Pxx500 commented
> > Of course it's not like I'm going to turn earlygame chromium into hell. I want to make it as simple as possible while being acceptable for new players, telling it will be a "line" was a joke I didn't properly disclose
> 
> ![image](https://user-images.githubusercontent.com/48415331/209586716-5e0355bd-dc1a-4273-9cd9-4bf27520fd72.png) The only real viable real life form of producing it is that (I think so, at least) which requires the addition of sodium dichromate into the game which also requires: ![image](https://user-images.githubusercontent.com/48415331/209586755-93c967c5-dfba-49f1-8f95-987945350c0e.png)
> 
> So sorry, until you provide us with clear information on how you are going to make another way of achieving Chromium Trioxide while being realistic and at least as easy as the current way, I don't see it actually working out.
> 
> Additonally it would require more machines due to the process behind it: ![image](https://user-images.githubusercontent.com/48415331/209586930-b9d0a071-374f-4167-9ba4-bca6a62120a9.png)

But... why do you need chromium trioxide in the first place?
To make dichromate... which trioxide is made from.

2022-12-26 22:46 UTC, Runakai1 commented
> > > Of course it's not like I'm going to turn earlygame chromium into hell. I want to make it as simple as possible while being acceptable for new players, telling it will be a "line" was a joke I didn't properly disclose
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/48415331/209586716-5e0355bd-dc1a-4273-9cd9-4bf27520fd72.png) The only real viable real life form of producing it is that (I think so, at least) which requires the addition of sodium dichromate into the game which also requires: ![image](https://user-images.githubusercontent.com/48415331/209586755-93c967c5-dfba-49f1-8f95-987945350c0e.png)
> > So sorry, until you provide us with clear information on how you are going to make another way of achieving Chromium Trioxide while being realistic and at least as easy as the current way, I don't see it actually working out.
> > Additonally it would require more machines due to the process behind it: ![image](https://user-images.githubusercontent.com/48415331/209586930-b9d0a071-374f-4167-9ba4-bca6a62120a9.png)
> 
> But... why do you need chromium trioxide in the first place? To make dichromate... which trioxide is made from.

Are we still arguing about Chromium Trioxide or Potassium Dichromate? 
"From what I can see this whole chromium chain should be reworked, you can't get chromium trioxide from reacting chromium with oxygen." 
This whole arguing was based on you not liking Chromium Trioxide. Also, Dichromate needs Trioxide yes, but what exactly is the point in this? Sorry, I don't understand it 😅

2022-12-26 22:50 UTC, Pxx500 commented
New chain will have neither trioxide nor dioxide since what you need it potassium dichromate, and you don't need troxide to make it

2022-12-26 22:51 UTC, Runakai1 commented
> New chain will have neither trioxide nor dioxide since what you need is potassium dichromate, and you don't need troxide to make it

When is the new chain, what is the actual idea behind it, I'd like a formula

2022-12-26 23:22 UTC, Pxx500 commented
This can be merged for now,  I will make my changes later and then decide whether to revert this PR

2022-12-26 23:25 UTC, Dream-Master commented
isnt 5 seconds very short ? idk what the original recipe take @Pxx500 @Runakai1

2022-12-26 23:25 UTC, Runakai1 commented
> isnt 5 seconds very short ? idk what the original recipe take @Pxx500 @Runakai1

It's the original voltage and recipe

2022-12-27 11:53 UTC, boubou19 commented
just a simple question: at which tier is gated the current recipe chain?

2022-12-27 11:53 UTC, Runakai1 commented
> just a simple question: at which tier is gated the current recipe chain?

Chromium dioxide is LV recipe, Trioxide is MV and the Dichromate is HV iirc

2022-12-27 11:58 UTC, boubou19 commented
So as per our own developper's code of conduct: one doesn't change a line below luV anymore, except if there is a good reason for it. And i'm afraid adding a whole new chain just because ReAlIsM for a single use in the pack to replace a dumb two step process is not a good reason.

@Runakai1 imo the skip happens too early given it's replacing a 2 steps chain in a LCR, that's going to one tick a bit too early. IIRC this is used in PTFE right?

2022-12-27 12:03 UTC, Runakai1 commented
> So as per our own developper's code of conduct: one doesn't change a line below luV anymore, except if there is a good reason for it. And i'm afraid adding a whole new chain just because ReAlIsM for a single use in the pack to replace a dumb two step process is not a good reason.
> 
> @Runakai1 imo the skip happens too early given it's replacing a 2 steps chain in a LCR, that's going to one tick a bit too early. IIRC this is used in PTFE right?

It's used in PBI. Chemical reactors aren't a huge issue by then IMO. The Energy consumption is exactly the same as using all 3 chemical reactors simultaneously, that's why I didn't include an additional "tax" on the recipe

2022-12-27 12:37 UTC, Pxx500 commented
> So as per our own developper's code of conduct: one doesn't change a line below luV anymore, except if there is a good reason for it. And i'm afraid adding a whole new chain just because ReAlIsM for a single use in the pack to replace a dumb two step process is not a good reason.

![image](https://user-images.githubusercontent.com/81298696/209666318-e0be6bba-3006-4774-83f7-5a9485c4014f.png)
-Net 0 reactions added to the game,
-Net -1/0 items added to the game (red circles are items added to the game by the chain, sodium bicarbonate can be omited with slight changes)
-Complexity increase
-May need to add recipe to craft sodium carbonate (NaOH + CO2, would be net 1 reactions added to the game)
-Somehow the most basic chromium oxide (Cr2O3) is not in the game but some unstable oxides are (net 0/1 items added)

Also it's not adding a new chain just editing the existing one

Also perhaps this change could be made to make whole process 1 recipe shorter (potassium carbonate exists in game and has uses so no need to add recipes, though they could be changed to benefit the player)
![image](https://user-images.githubusercontent.com/81298696/209667472-cbf74752-0633-461e-8ec6-6c357b643691.png)

2022-12-27 12:46 UTC, Runakai1 commented
> > So as per our own developper's code of conduct: one doesn't change a line below luV anymore, except if there is a good reason for it. And i'm afraid adding a whole new chain just because ReAlIsM for a single use in the pack to replace a dumb two step process is not a good reason.
> 
> ![image](https://user-images.githubusercontent.com/81298696/209666318-e0be6bba-3006-4774-83f7-5a9485c4014f.png) -Net 0 reactions added to the game, -Net -1/0 items added to the game (red circles are items added to the game by the chain, sodium bicarbonate can be omited with slight changes) -Complexity increase -May need to add recipe to craft sodium carbonate (NaOH + CO2, would be net 1 reactions added to the game) -Somehow the most basic chromium oxide (Cr2O3) is not in the game but some unstable oxides are (net 0/1 items added)
> 
> Also it's not adding a new chain just editing the existing one
> 
> Also perhaps this change could be made to make whole process 1 recipe shorter (potassium carbonate exists in game and has uses so no need to add recipes, though they could be changed to benefit the player) ![image](https://user-images.githubusercontent.com/81298696/209667472-cbf74752-0633-461e-8ec6-6c357b643691.png)

Complexity increase is still against the code of conduct 🤷due to it not being a QOL update nor a bug fix.

2022-12-27 12:52 UTC, Pxx500 commented
![image](https://user-images.githubusercontent.com/81298696/209669303-68570435-6ed5-45f9-a70a-d0c73935ea5f.png)
- increase in complexity is not against code of conduct
- this is not a new content just editing the existing one

2022-12-27 12:57 UTC, mitchej123 commented
> * this is not a new content just editing the existing one

It didn't exist in the proposed form before, it is new content.

2022-12-27 12:57 UTC, Runakai1 commented
> ![image](https://user-images.githubusercontent.com/81298696/209669303-68570435-6ed5-45f9-a70a-d0c73935ea5f.png)
> 
> * increase in complexity is not against code of conduct
> * this is not a new content just editing the existing one

You're editing the existing one to make it more difficult. In what world does that mean it's adding to QOL features or fixing bugs?

2022-12-27 12:58 UTC, Pxx500 commented
> > ![image](https://user-images.githubusercontent.com/81298696/209669303-68570435-6ed5-45f9-a70a-d0c73935ea5f.png)
> > 
> > * increase in complexity is not against code of conduct
> > * this is not a new content just editing the existing one
> 
> You're editing the existing one to make it more difficult. In what world does that mean it's adding to QOL features or fixing bugs?

Code of conduct does not forbid doing that, it says they are always appreciated



> > * this is not a new content just editing the existing one
> 
> It didn't exist in the proposed form before, it is new content.

So is this PR then

2022-12-27 13:00 UTC, mitchej123 commented
> So is this PR then

Sure, but it's QOL and doesn't break any existing setups

2022-12-27 13:01 UTC, Runakai1 commented
> Code of conduct does not forbid doing that, it says they are always appreciated



> Code of conduct does not forbid doing that, it says they (QOL changes and bugfixes) are always appreciated

"However, bug fixes and QoL changes are always appreciated". I don't see an increase of complexity being a Quality of Life feature

2022-12-27 13:01 UTC, Runakai1 commented
> > Code of conduct does not forbid doing that, it says they (QOL changes and bugfixes) are always appreciated
> 
> "However, bug fixes and QoL changes are always appreciated". I don't see an increase of complexity being a Quality of Life feature

2022-12-27 13:01 UTC, Runakai1 commented
> > > Code of conduct does not forbid doing that, it says they (QOL changes and bugfixes) are always appreciated
"However, bug fixes and QoL changes are always appreciated". I don't see an increase of complexity being a Quality of Life feature

2022-12-27 13:02 UTC, Pxx500 commented
> > Code of conduct does not forbid doing that, it says they are always appreciated
> 
> > Code of conduct does not forbid doing that, it says they (QOL changes and bugfixes) are always appreciated
> 
> "However, bug fixes and QoL changes are always appreciated". I don't see an increase of complexity being a Quality of Life feature

And I can't see where is it stated that it has to be QoL

2022-12-27 13:02 UTC, Runakai1 commented
> And I can't see where is it stated that it has to be QoL

"However, bug fixes and QoL changes are always appreciated". I don't see an increase of complexity being a Quality of Life feature

2022-12-27 13:03 UTC, Pxx500 commented
> > And I can't see where is it stated that it has to be QoL
> 
> "However, bug fixes and QoL changes are always appreciated". I don't see an increase of complexity being a Quality of Life feature

And I can't see where is it stated that it has to be QoL

2022-12-27 13:03 UTC, BlueWeabo commented
![image](https://user-images.githubusercontent.com/76872108/209670691-6edb1e6c-466b-47b5-85ec-deeb9e364395.png)

2022-12-27 13:04 UTC, mitchej123 commented
> And I can't see where is it stated that it has to be QoL

Literally right in the text you quoted in the image

2022-12-27 13:04 UTC, BlueWeabo commented
Complexity and breaking setups != QoL

2022-12-27 13:04 UTC, Runakai1 commented
> And I can't see where is it stated that it has to be QoL
It basically says "Avoid adding new content co chemlines in those tiers. It may be allowed though if its a QOL feature or a bug"

2022-12-27 13:04 UTC, Pxx500 commented
appreciated != the only expected change

2022-12-27 13:05 UTC, mitchej123 commented
> appreciated != the only expected change

It says don't add new stuff or change existing stuff unless it's qol or a bugfix.  🙄

2022-12-27 13:06 UTC, Sphyix commented
@Pxx500 i don't understand what's your objective, you are arguing just for the sake of it, even quoting stuff that goes against you

2022-12-27 13:20 UTC, boubou19 commented
looks like the argument is settled: no edit will be done, only this shortcut to reduce machine spam.

2022-12-27 13:20 UTC, Pxx500 commented
> @Pxx500 i don't understand what's your objective, you are arguing just for the sake of it, even quoting stuff that goes against you

The recipe present in the game rn feels like a placeholder, just combining ingredients is not the way it should be imo, because if that's the way then why not just make everything that way? I just want consistency, what is in game rn doesn't feel right for me and I want to make it better (imo) and all you guys talk about is not that it's a bad change but that it's in breach of code of conduct. I don't think that respecting something that forces people to throw away good ideas is the right thing. I am not trying to be malicious or anything, I just try to make the pack just how I think it was always supposed to be - hard, complex and rewarding.

2022-12-27 13:24 UTC, mitchej123 commented
> 
> The recipe present in the game rn feels like a placeholder, just combining ingredients is not the way it should be imo, because if that's the way then why not just make everything that way? I just want consistency, what is in game rn doesn't feel right for me and I want to make it better (imo) and all you guys talk about is not that it's a bad change but that it's in breach of code of conduct. I don't think that respecting something that forces people to throw away good ideas is the right thing. I am not trying to be malicious or anything, I just try to make the pack just how I think it was always supposed to be - hard, complex and rewarding.

Sure that's reasonable. It needs it's own discussion and justification for changing the early game and breaking existing setups is all. It doesn't belong on a qol or, but it's own RRC

2022-12-27 13:24 UTC, Pxx500 commented
I also don't think that combining recipes to reduce machine spam is the real solution - you can do it with any existing line, and if you did then the whole platline (just an example) would be just one recipe with many inputs and outputs. This could too be considered QoL, and reduce machine spam recipe. But where's the fun in that?

2022-12-27 13:26 UTC, Runakai1 commented
> I also don't think that combining recipes to reduce machine spam is the real solution - you can do it with any existing line, and if you did then the whole platline (just an example) would be just one recipe with many inputs and outputs. This could too be considered QoL, and reduce machine spam recipe. But where's the fun in that?

The fun in platline is breaking a component into multiple outcomes. While this PR aims to remove machine spam for a very simple setup while not increasing difficulty of this process

2022-12-27 13:30 UTC, Pxx500 commented
> > I also don't think that combining recipes to reduce machine spam is the real solution - you can do it with any existing line, and if you did then the whole platline (just an example) would be just one recipe with many inputs and outputs. This could too be considered QoL, and reduce machine spam recipe. But where's the fun in that?
> 
> The fun in platline is breaking a component into multiple outcomes. While this PR aims to remove machine spam for a very simple setup while not increasing difficulty of this process

I don't understand how this is a valid counterargument, maybe because I don't understand what you mean. If you simplified platline to one recipe then it would too have many outputs (platinides) from one main input (PMPD).

2022-12-27 13:52 UTC, Runakai1 commented
![image](https://user-images.githubusercontent.com/48415331/209676312-14e4dbcf-6c58-480c-ac77-0d9589b4e697.png)
This is the new recipe for ZPM.

2022-12-27 15:08 UTC, boubou19 approved these changes

2022-12-27 15:08 UTC, Dream-Master commented
wait let me check this ingame

2022-12-27 15:08 UTC, BlueWeabo approved these changes

2022-12-27 15:09 UTC, Dream-Master requested changes
let me check first please

2022-12-28 21:02 UTC, Dream-Master commented
@Runakai1 relax i dont have forgotten it :P i just was busy with work today

2022-12-28 21:15 UTC, merged