Add a Overclock Calculator for multis and the like to use
GTNewHorizons/GT5-Unofficial pull request #1617
Opened 2022-12-31 13:46 UTC by BlueWeabo

I have decided to work on an Overclock calculator and this is its current form. I am accepting anything i should add to it and other tests I should do for it as I have no idea what else to test currently.

2022-12-31 19:08 UTC, mitchej123 commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        return mRecipeEUt;
Since you're not returning a new object, I'd put in a guard here (and the next method)
```java
if(!calculated) error();
```

2022-12-31 21:24 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        return mRecipeEUt;
Any good idea on how to make it give an error?

2023-01-01 09:12 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        return mRecipeEUt;
done

2023-01-01 17:10 UTC, minecraft7771 requested changes

2023-01-01 17:10 UTC, minecraft7771 commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +    private void CalculateOverclock() {
Nit: Begin function name in lower case.

2023-01-01 17:10 UTC, minecraft7771 commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        int heatDiscounts = (mMultiHeat - mRecipeHeat) / 900;
Would be nice if you could refactor the 900 and 1800 into const variables.

2023-01-01 17:10 UTC, minecraft7771 commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +                mDuration >>= 2;
Not really needed but maybe it would be good to also let the user be able to define this value in the builder.

2023-01-01 17:10 UTC, minecraft7771 commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +            if (!calculated) {
Doubled code here.

2023-01-01 17:10 UTC, minecraft7771 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +                        this.lEUt = calc.getConsumption();
I THINK this is not needed as processRecipe in itself already has a try-catch.

2023-01-01 17:14 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +                        this.lEUt = calc.getConsumption();
unless I make processRecipe throw Exception it gives an error, which is why I have put it in a try-catch

2023-01-01 17:14 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +                mDuration >>= 2;
do you mean about the mEUtIncrease?

2023-01-01 17:15 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        int heatDiscounts = (mMultiHeat - mRecipeHeat) / 900;
shall try for the 1800. also why const variables? do you mean to not have them as numbers?

2023-01-01 17:16 UTC, minecraft7771 commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +                mDuration >>= 2;
the mDuration decrease with perfect OC.

2023-01-01 17:16 UTC, minecraft7771 commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        int heatDiscounts = (mMultiHeat - mRecipeHeat) / 900;
Yes.

2023-01-01 17:16 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +                mDuration >>= 2;
ah i see. gonna do it

2023-01-01 21:55 UTC, minecraft7771 approved these changes

2023-01-01 21:58 UTC, merged