Allow earlier initialization of exotic fluid cells
GTNewHorizons/GT5-Unofficial pull request #1644
Opened 2023-01-09 05:20 UTC by miozune

2023-01-09 11:07 UTC, D-Cysteine approved these changes
Looks good! Just some nitpicky comments that you should feel free to ignore

2023-01-09 11:07 UTC, D-Cysteine commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_98.java
> +        aCell.init();
If my understanding is correct, I think that by calling `init()` prior to checking `fluid == null`, then if `fluid` is `null`, we'll mark the cell as initialized and then not create an item stack for it. If we did this due to an early call to `get()`, then we won't try to create the fluid cell during post-load even if the fluid has since been created and exists at that time.

Could fix this by moving `init()` after checking `fluid == null`, but I think you could also get rid of `mHasNotBeenInitialized` entirely and replace it with a check on whether `mStack == null`.

2023-01-09 11:49 UTC, miozune commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_98.java
> +        private void verify() {
Since enum is implicitly static, `FluidCell` cannot reference to `registeredFluidDataMap` or `GT_MetaGenerated_Item_98.this`.

2023-01-09 11:52 UTC, D-Cysteine commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_98.java
> +        private void verify() {
I was thinking that `GT_MetaGenerated_Item_98.INSTANCE.registeredFluidDataMap` should work, but it does look a bit messy

2023-01-09 12:35 UTC, D-Cysteine commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_98.java
> +        if (aCell.mStack != null) return;
With the always return item stack approach, I think this doesn't quite work. The issue is this situation:

1. Fluid does not yet exist during pre-load
2. We add a recipe which uses the fluid cell, which results in creating the item stack, but not the fluid registry entries due to missing fluid
3. Fluid gets created afterwards, before post-load
4. Post-load happens and we iterate through the fluid cells to set up fluid registry entries, but we skip this one because the item stack already exists

The solution I had in mind was something like, modify all of the `FluidCell.get()` methods to check if `mStack` is `null`, and if it is, initialize `mStack`, but don't do anything else. This also makes the `get()` methods non-nullable. (Here, we may want to move the initialization logic itself, which is just `mStack = new ItemStack(this, 1, id)`, to a helper method so we can reference it later, in `GT_MetaGenerated_Item_98.init()`)

Then, in `GT_MetaGenerated_Item_98.init()`, just as before, we'll iterate over all of the fluid cells and perform the fluid registration. This is when we actually register the cells into `FluidContainerRegistry`, `registeredFluidDataMap`, and `GT_LanguageManager`. The difference is that now, some fluid cells might have had their `mStack` initialized already, so we just need to check for that.

At this point, with the new logic, we can conveniently check: if we encounter a fluid cell that has a non-null `mStack`, but its fluid is `null`, then we can assume that this is a case where we tried to use a fluid cell in a recipe, but its fluid doesn't exist even during post-load. Then we can throw an exception, or maybe just log a warning that the fluid cell might not work properly since its fluid is missing. The part that I am not sure about, is what happens if we try to load up the game with such a fluid cell, that is missing an entry in `registeredFluidDataMap`. It might crash upon rendering, so we may need to insert dummy data in such a case.

2023-01-09 13:42 UTC, leagris requested changes

2023-01-09 13:42 UTC, leagris commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_98.java
> +        rgba[3] = (short) ((color & 0xFF000000) >> 24);
Maybe not reinvent the wheel:
```java
short[] rgba = GT_Util.getRGBaArray(color);
```

2023-01-09 18:53 UTC, D-Cysteine commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_98.java
> +         * Might return null if the fluid referenced does not exist.
I think we can never return `null` now, so these comments should probably be updated (and `@Nullable` could be removed). Maybe mention that this method will return an item stack even for non-existent fluids, so don't assume that the fluid exists?

2023-01-09 18:53 UTC, D-Cysteine commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_98.java
> +            this.tryToInitialize();
Up to you if you want to do this, but I was thinking that instead of calling `tryToInitialize` from these `get` methods, we could instead have a helper method in `FluidCell` that does just this (or just in-line it; it's only 3 lines):

```
if (mStack == null) {
  mStack = new ItemStack(this, 1, id);
}
```

and reference that method from these `get` methods, as well as from `tryToInitialize`. `tryToInitialize` would then be called only by `createAllItems`, so we could get rid of the `initAll` parameter, and could even just in-line it back into the `for`-loop in `createAllItems`.

2023-01-10 02:57 UTC, D-Cysteine approved these changes

2023-01-10 02:57 UTC, D-Cysteine commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_98.java
> +        if (!isStackAlreadySet && registeredFluidDataMap.containsKey(id)) {
Sorry for all the comments! I think that this looks really good; just one last thing:

Now that `mStack` can be initialized outside of calls to `tryToInitialize`, I think that we don't want to make assumptions about the initialization state of the fluid data based on `mStack != null`. Right now, I think a potential problem is, if we have two fluid cells A and B that have the same fluid ID, but both get initialized by a recipe prior to post-load, then we won't catch the colliding ID because `isStackAlreadySet` would be true for both, so we would skip this check.

Instead, I think we could just remove `isStackAlreadySet` entirely from this check: since this method is now only called by `createAllItems`, we know that it will be called exactly once for each fluid cell, so it's no longer necessary to check this.

2023-01-10 06:12 UTC, merged