EOH materials + Allow materials to pick their processing tier
GTNewHorizons/GT5-Unofficial pull request #1671
Opened 2023-01-20 22:51 UTC by Connor-Colenso

Spacetime -> UMV
Trans metal -> UIV
SC UMV -> UIV
SC UIV -> UEV
SC UEV -> UHV
SC UHV -> UV
SC UV -> ZPM
Cosmic Nt -> UV
Bedrockium -> LuV
Infinity -> UHV
Inf Catalyst -> UHV
Neutronium -> ZPM

Think that is all the adjustments, any recipe > IV will lose its crafting table equivalent and force machine usage. So no more frame boxes made in a crafting table at UHV. This should not really impact people given that barely anyone uses this due to how slow it is for AE to calculate due to tool usage.

Also added a new subtag that can disable all recipes for a material.

2023-01-20 23:55 UTC, POPlol333 commented
I'm completely against it, fuck PA (because who's going to craft stack of UMV machine for spacetime lmao), enforce gtpp, and is just here to piss everyone off

2023-01-21 00:05 UTC, Connor-Colenso commented
It makes 0 sense for a neutronium to require an LV extruder, or worse stuff like spacetime needing LV. It's bizarre and gives more of an energy sink for users endgame with 10 octillion billion trillion EU.

2023-01-21 00:06 UTC, POPlol333 commented
(just a reminder that you're the reason we need that amount of EU)

2023-01-21 00:07 UTC, POPlol333 commented
and I'm also ok with the fact that LV extruder recipe are weird, but I'm completely against pushing the jokes to umv machines, it's just going overboard, capping it to uhv max would be the ideal to me

2023-01-21 00:11 UTC, TheEpicGamer274 commented
This is also hard forcing gtpp for machines when you need to upgrade every tier, so far the only thing I know of that is gtpp forced is to get transcendent metal, the tesseract maceration, which is a one-time process, while this you would have to do every tier or almost every tier.

2023-01-21 00:14 UTC, Connor-Colenso commented
I don't see why this forces GT++, you can just use a PA?

In any case we are well passed the point of "forcing GT++" being a relevant argument, it is forced all over endgame now with quantum anomalies, optical smds, DTPF recipes, tesseracts etc.

2023-01-21 00:15 UTC, POPlol333 commented
I don't think because it's already forced all-over that you have to put even more into this.
And about the PA, who's going to craft entire PA of UMV machine except Sampsa? It's way too expensive just to be able to bend 1 fucking material

2023-01-21 00:16 UTC, GDCloudstrike commented
> This is also hard forcing gtpp for machines when you need to upgrade every tier, so far the only thing I know of that is gtpp forced is to get transcendent metal, the tesseract maceration, which is a one-time process, while this you would have to do every tier or almost every tier.

This only seems to be the case for trans metal and spacetime still, the SCs are tier-1 which shouldn't block anthing, CNt is used in UHV machines and is processable in UV machines so no forcing there either, Bedrockium doesn't really make a difference (except maybe for bedrockium drums), inf and inf cat being uhv doesn't block anthing either and zpm machines are required to make Neutronium anyways, so nothing forced there either

2023-01-21 00:16 UTC, POPlol333 commented
if there was tens of materials behind it I could consider it, but that's just spending hundreds of circuit to be able to bend 1 mats if you don't want that pink looking thingy

2023-01-21 00:17 UTC, TheEpicGamer274 commented
I say this because to get to the next tier of machines you have to use gtpp, which most of us endgame players don't usually have around a spare gtpp bender/whatever, unless you want to already bend lots and lots of the longer materials.

2023-01-21 00:17 UTC, Connor-Colenso commented
> if there was tens of materials behind it I could consider it, but that's just spending hundreds of circuit to be able to bend 1 mats if you don't want that pink looking thingy

This seems more like "I am taking an unintended path and don't like how much it is costing me", than an actual argument on balance?

2023-01-21 00:18 UTC, POPlol333 commented
well then you assume people have to go the gtpp path, which mean that you only have to put 2 more energy hatch to get the UMV voltage, well that doesn't add anything except a pink looking shit in your base ngl

2023-01-21 03:24 UTC, Connor-Colenso commented
I mean, it's quite simple, there is an easier path you are refusing to take. That is your right, but you don't also get to complain the alternate path is too expensive when you chose to walk it.

2023-01-21 07:26 UTC, BlueWeabo commented
Even MTEs won't be able to uptier on recipes. So at min material processing will need to be the tier its used it -1

2023-01-21 12:19 UTC, Steelux8 commented
Is it only the materials listed in the PR description that get their processing tier changed? If this has been analyzed to not cause any issues with machines not being craftable to process the materials, I'm good with it.

I honestly would like to see all materials have their own processing energy tier, instead of being defaulted to LV or MV, but that's a whole another deal.

2023-01-21 13:41 UTC, BlueWeabo commented on src/main/java/gregtech/api/enums/Tier.java
> +    public static final long RECIPE_ULV = (long) (RECIPE_DISCOUNT * V[0]);
Why does this exist when GT_Values.VP exists and has the same purpose

2023-01-21 13:52 UTC, Connor-Colenso commented on src/main/java/gregtech/api/enums/Tier.java
> +    public static final long RECIPE_ULV = (long) (RECIPE_DISCOUNT * V[0]);
The reason I added these was because GT_Values.VP[11] is way less readable than Tier.UEV or Tier.RECIPE_UEV for actual recipe generation.

2023-01-21 14:55 UTC, BlueWeabo commented on src/main/java/gregtech/api/enums/Tier.java
> +    public static final long RECIPE_ULV = (long) (RECIPE_DISCOUNT * V[0]);
can use GT_Values.VP instead of calculating it here then.

2023-01-21 15:04 UTC, boubou19 commented on src/main/java/gregtech/api/enums/Tier.java
> +    public static final long RECIPE_ULV = (long) (RECIPE_DISCOUNT * V[0]);
i'm actually in favor of an enum than an array because you'll need to plug in the tier in it. The enum is a no brainer to use.

2023-01-21 15:11 UTC, BlueWeabo commented on src/main/java/gregtech/api/enums/Tier.java
> +    public static final long RECIPE_ULV = (long) (RECIPE_DISCOUNT * V[0]);
yeah same, just that I don't see the need to recalculate when it was already done in GT_Values.VP

2023-01-21 15:13 UTC, boubou19 commented on src/main/java/gregtech/api/enums/Tier.java
> +    public static final long RECIPE_ULV = (long) (RECIPE_DISCOUNT * V[0]);
ah i see what you mean: use GT_Values.VP in the enum declaration right?

2023-01-21 15:15 UTC, BlueWeabo commented on src/main/java/gregtech/api/enums/Tier.java
> +    public static final long RECIPE_ULV = (long) (RECIPE_DISCOUNT * V[0]);
yes

2023-01-21 15:44 UTC, miozune commented on src/main/java/gregtech/api/enums/Materials.java
> +    public Materials setProcessingMaterialTierEU(int processingMaterialTierEU) {
what about making this take `long` so that `Tier`s don't need to be casted to int?

2023-01-23 17:37 UTC, RaitGamerGR commented
I think first you need to change this
![image](https://user-images.githubusercontent.com/70205464/214109771-2d752339-aa36-4342-b2d2-d80749db94e6.png)

2023-01-23 17:39 UTC, Dream-Master commented
> I think first you need to change this ![image](https://user-images.githubusercontent.com/70205464/214109771-2d752339-aa36-4342-b2d2-d80749db94e6.png)

cool i can smelt space time in vanilla furnace.

2023-01-23 17:48 UTC, Team1Warlord commented
What about bedrockium - bedrockium drums can be now crafted on hv, if bedrockium will become luv material i will not be able to craft bedrockium drums before luv, but on luv it a bit useless because u can craft tfft or yotta tanks that much better, so bedrockium drums becomes useless, dont you think so? On high-end tiers where u can use this drums as item storage for liquids its not necessary luv or lv it's proceeded, so its not necessary to redo bedrockium recepies and tier.

2023-01-23 18:13 UTC, Connor-Colenso commented
I don't think bedrockium drums will become useless because of this, I am endgame and still use them as a mass storage system. I can always adjust bedrockiums processing tier down.

2023-01-23 20:40 UTC, Team1Warlord commented
As i said, u can craft a lot of bedrockium drums on hv through magick, u dont need bedrockium ore at all. Ad as i mentioned, on hi-end tiers it will be used as mass storage, but they will become useless on tiers before, when u need like 10-20 of this drums to contain all of your liquid until u can make something better like tfft or yotta. And again - this change will make no any affect on tiers zpm+ but will destroy some of recepies and usage on tiers before (like duplicating will become useless because you cannot process it)

2023-01-24 08:35 UTC, POPlol333 commented
At the very beginning drums are meant to transport great quantity of a fluid by hand, and I don't think yotta or tfft gonna win on those point lol

2023-01-24 09:24 UTC, BlueWeabo requested changes

2023-01-24 09:24 UTC, BlueWeabo commented on src/main/java/gregtech/api/enums/Materials.java
> +    public static Materials Bedrockium              = new MaterialBuilder(395,TextureSet.SET_DULL, "Bedrockium").addOreItems().addDustItems().addMetalItems().setDurability(327680).setToolSpeed(8f).se
Bedrockium is needed for drums, which can be made at HV tier in theory. IMO it should be changed si that the processing tier is HV or EV depending on where you want to tier those drums

2023-01-24 09:24 UTC, BlueWeabo commented on src/main/java/gregtech/api/enums/Materials.java
> +    public static Materials SpaceTime                = new Materials(588, new TextureSet("spacetime", true)           ,   320.0F,      4*2621440,  25, 1|2|64|128,   255,   255, 255,  0,   "SpaceTime"
This should be 1  tier lower to be able to be processed at UIV. do not think of GT++ multis being able to do it. As later down the line if MuTEs get added and replace the gt++ ones. One will not be able to uptier.

2023-01-24 09:24 UTC, BlueWeabo commented on src/main/java/gregtech/api/enums/Materials.java
> +    public static Materials TranscendentMetal        = new Materials(581, TextureSet.SET_METALLIC          ,  290.0F,      3*2621440,  22, 1|2|64|128,   50,     50,  50,0,   "TranscendentMetal" ,   "
same here

2023-01-24 09:24 UTC, BlueWeabo commented on src/main/java/gregtech/api/enums/Materials.java
> +    public static Materials BlackDwarfMatter = new Materials(586, TextureSet.SET_METALLIC, 1.0F, 0, 2, 1|2|64|128, 0, 0, 0, 255, "BlackDwarfMatter", "Black Dwarf Matter", -1, -1, 0, 0, false, false,
same for all of these here too

2023-01-24 16:07 UTC, POPlol333 commented
What is this build error 🤔

2023-01-24 18:23 UTC, BlueWeabo requested changes

2023-01-24 18:23 UTC, BlueWeabo commented on src/main/java/gregtech/loaders/postload/chains/GT_NaniteChain.java
> +                2);
Putting the nanites at t2 will make them able to have Perfect OC at tier 3 nano forge. is this wanted?

2023-01-24 18:23 UTC, BlueWeabo commented on src/main/java/gregtech/loaders/postload/chains/GT_NaniteChain.java
> +                    getModItem("dreamcraft", "item.PicoWafer", 32),
why not use MOD_ID_DC like you did elsewhere lol

2023-01-24 18:23 UTC, BlueWeabo commented on src/main/java/gregtech/loaders/postload/chains/GT_NaniteChain.java
> +                    getModItem("bartworks", "gt.bwMetaGeneratedlens", 0, 36),
Please try to use oredict if possible. you should be able to for this item

2023-01-24 18:23 UTC, BlueWeabo commented on src/main/java/gregtech/loaders/postload/chains/GT_NaniteChain.java
> +                    getModItem(MOD_ID_GTPP, "MU-metaitem.01", 0, 32105),
same thins use oredict

2023-01-24 18:23 UTC, BlueWeabo commented on src/main/java/gregtech/loaders/postload/chains/GT_NaniteChain.java
> +                    getModItem("bartworks", "gt.bwMetaGeneratedlens", 0, 36),
same thing

2023-01-24 18:23 UTC, BlueWeabo commented on src/main/java/gregtech/loaders/postload/chains/GT_NaniteChain.java
> +                    getModItem(MOD_ID_GTPP, "MU-metaitem.01", 0, 32105),
again

2023-01-25 05:21 UTC, BlueWeabo approved these changes

2023-01-25 05:22 UTC, merged

2023-01-29 08:14 UTC, core-exe commented
This message is a conclusion of Chinese GTNH community at 2023-1-29 GTM+8 1:00 about colen's change on GT5U materials' processing tier (https://github.com/GTNewHorizons/GT5-Unofficial/pull/1671), and we reached a conclusion that this change will severely harm the experience of gameplay, and decided not to update the game if this change would persist.
 
This pull request consists of two significant changes:
(1) All materials post IV cannot be processed in crafting tables.
(2) All materials post UHV can only be processed by machines one tier lower.
 
We agree with the first change since processing materials in crafting table post IV is unreasonable.
 
We strongly disagree with the second change, for the following reasons:
The late game requires exponential amount of late game resources, while this changes make processing material have an almost constant cost.
This change will make PA practically not usable, since processing latest material requires T-1 tier machine, making it impossible to go beyond 16x parallel.
This change will force player to make every tier of machine for material processing, making gameplay tedious and redundant.
This change will induce more machine spam, and may cause more TPS issue.
 
We understand that it is unreasonable to make LV machine to process endgame materials, but the T-1 tier requirement is too harsh due to the exponential requirement of materials. We suggest a T/2 tier requirement to ensure the tier requirement, but also keep high parallel processing and reduce machines required in the late game.
 
Also, we suggest the development team to thoroughly consider the opinion and feedback of the community before merging such important changes.

2023-01-29 08:22 UTC, SafariXiu commented
Well, this change is not reasonable, which seriously reduces the production efficiency in the later period, wasting time in the pointless increase of the number of machines，A new machine can require millions or even tens of millions of items in post-production, I would urge you to ask the UEV+ players before making such changes。If so, then the latter phase will become an unplayable phase, after all, no one wants to wait 24 hours a day for a bunch of meaningless products。

2023-01-29 08:25 UTC, SafariXiu commented
Such a change is ridiculous, but luckily I've built a lot of big machines ahead of time, otherwise I would have gone crazy

2023-01-29 08:27 UTC, SafariXiu commented
I'd like to know if you've actually played UEV+。This change caused quite a stir in the Chinese community. Many of us who are already in UIV, UMV or even UXV think this change is unreasonable

2023-01-29 08:32 UTC, BlueWeabo commented
The change isn't unreasonable. PAs can still have 64 parallels with no problem. (i have no clue why you think the max is 16x). Currently there is a new multiblock system being made, which will be able to take on these new crafting times with no problem and no need for spamming machine. Currently in UMV and crafting stargate with said new changes. haven't upgraded any infra to be able to do so.

2023-01-29 08:39 UTC, cainiaojun commented
There is a concept that called reciprocal countermeasures. If there is a nerf that makes it unacceptable to use Processing Array to make lategame components, there SHOULD BE a machine that enables players to do that. So if there is a new multi in making, please tell the community before pull requests to nerf the old one. Players don't want to blow up to something inexistent.

By the way, is there a machine that is being made can make catalysts which are used in DTPF in a reasonable time? We are bored with hundreds of Industrial Mixers and Nine in Ones.

~~To tell the truth, many players has talked about kicking Colen out of GTNH Developers because he had bad game-understanding before we know about the new multi.~~

2023-01-29 08:42 UTC, BlueWeabo commented
Well another machine which needs a lot less spamming would be the PA, but it gets expensive to use it. We are using the PA with  UEV machines inside (downtiered for every catalyst but exotic) It consumes a lot of power, but you can make more than enough with Dyson Swarm.

2023-01-29 08:42 UTC, wumingzhiren commented
At least the procress time shou not be still like LV, maybe it can be decrease with voltage to 1t.
Now their is already too much waiting time. Just like playing 4h but 3h50min playing other games.
You said there is a new multiblock system, then please show it out.

2023-01-29 08:43 UTC, BlueWeabo commented
There is another PR, which makes it T-2 for recipes

2023-01-29 08:44 UTC, wumingzhiren commented
> There is another PR, which makes it T-2 for recipes
Why not merge it？

2023-01-29 08:47 UTC, wumingzhiren commented
> Currently there is a new multiblock system being made

Unless it it made, this PR shouldn't be merged.

2023-01-29 08:48 UTC, cainiaojun commented
> Well another machine which needs a lot less spamming would be the PA, but it gets expensive to use it. We are using the PA with UEV machines inside (downtiered for every catalyst but exotic) It consumes a lot of power, but you can make more than enough with Dyson Swarm.

Just do it. Expensive is not a problem. Players after UV are more cared about there computer performance and productivity instead of expense. We are welcomed to those machines which could improve productivity substantially no matter how expensive it is. e.g. Component Assline.

Please tell the community much eariler instead of after making players angry, which is more important.

2023-01-29 08:55 UTC, boubou19 commented
> The late game requires exponential amount of late game resources, while this changes make processing material have an almost constant cost.
This change will make PA practically not usable, since processing latest material requires T-1 tier machine, making it impossible to go beyond 16x parallel.

PAs are a hack, there is a consensus in the dev team about removing them sooner or later. You typically use PAs if you hate GT++ machines (your choice but then face the difficulties associated with it) or for extreme parallel processing, which is not possible with recipe of your current tier, so it's not actually an issue.

> This change will force player to make every tier of machine for material processing, making gameplay tedious and redundant.

That's called progression so not a good argument.

> This change will induce more machine spam, and may cause more TPS issue.

This is true if you one tick recipes. Most of the time of a recipe a machine idles. Biggest lag is the first tick processing the inputs for the recipe and the last tick when it generates recipe output. So for recipes of your tier, you cannot really one tick them, so it's not an issue

> To tell the truth, many players has talked about kicking Colen out of GTNH Developers because he had bad game-understanding before we know about the new multi.

lmao. Colen is in relation with several stargate tier players, and they are tweaking the game according to how their base respond to new recipes. It's not random thoughts. As always, when introducing new stuff, there will be successive PR to tweak the numbers. Idk why you guys are going mad about that, you are playing in highly WIP tiers, so that kind of stuff is to be expected, especially if you are sticking with latest dev versions.

2023-01-29 08:57 UTC, SafariXiu commented
> 
If that's true then it's a joke. Do they think they're done with the gate and the rest of the world should be left alone? This severely limits the pace of the entire game

2023-01-29 08:59 UTC, SafariXiu commented
The game is already long enough, what's the point of making it longer

2023-01-29 09:00 UTC, BlueWeabo commented
Ah yes. let's put a stop to developing

2023-01-29 09:00 UTC, boubou19 commented
Not really no, what is endgame now will be less endgame later, as we want to add content up to max tier, so we need to add content with matching recipes to counter power creep. 

> The game is already long enough, what's the point of making it longer

Nice so we stop developping NH and save our time got it 🤦.

I'm locking this.

2023-01-29 09:16 UTC, iouter commented
my opinion: the time spent on make material lines, etc. is meaningful time, and the time spent waiting for machines is meaningless time. just adding invalid time is boring and meaningless