Centrifuge Recipes for U235 - Tweaks
GTNewHorizons/GT5-Unofficial pull request #1708
Opened 2023-01-30 15:39 UTC by Steelux8

See https://github.com/GTNewHorizons/GT5-Unofficial/pull/1670.

I made the PR again, after the GT_MachineRecipeLoader changes. I also changed the small dust chances to normal dust chances by using the naive method (divide chances by 4), but I also doubled the chances from there from Dream's feedback saying that the recipe probably wasn't worth it still. On top of that, discussion with other devs clarified that the minimum Plutonium needed for the Radon loop is actually meant to be 72, not 8.

2023-01-30 15:47 UTC, boubou19 commented
@Steelux8 if you do the recipe of the radon loop in a LCR. Does it take 72 or 64 dusts? because if the bug is still here let's not readd a powerful plutonium dupe.

2023-01-30 15:54 UTC, boubou19 requested changes

2023-01-30 15:54 UTC, boubou19 commented on src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
> +                (int) GT_Values.VP[3]);
Use the recipe enum instead, much more clear to have a `Tier.RECIPE_HV` than a `GT_Values.VP[3]`

2023-01-30 15:54 UTC, boubou19 commented on src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
> +                (int) GT_Values.VP[4]);
Use the recipe enum instead, much more clear to have a `Tier.RECIPE_EV` than a `GT_Values.VP[4]`

2023-01-30 15:55 UTC, BlueWeabo commented on src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
> +                (int) GT_Values.VP[3]);
It's TierEU.RECIPE_HV

2023-01-30 15:57 UTC, boubou19 commented on src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
> +                (int) GT_Values.VP[3]);
forgot Colen updated it

2023-01-30 15:57 UTC, BlueWeabo commented on src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
> +                (int) GT_Values.VP[3]);
Yeah an Colen's PR ain't merged for it lol iirc

2023-01-30 18:50 UTC, Steelux8 commented
> if you do the recipe of the radon loop in a LCR. Does it take 72 or 64 dusts? because if the bug is still here let's not readd a powerful plutonium dupe.

Input and output are both 64.

2023-02-05 16:05 UTC, Steelux8 commented on src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
> +                (int) GT_Values.VP[3]);
It's there now.

2023-02-05 16:05 UTC, Steelux8 commented on src/main/java/gregtech/loaders/postload/recipes/CentrifugeRecipes.java
> +                (int) GT_Values.VP[4]);
It's there now.

2023-02-05 21:32 UTC, boubou19 approved these changes

2023-02-05 21:32 UTC, merged