Make material renderer available for arbitrary item
GTNewHorizons/GT5-Unofficial pull request #1753
Opened 2023-02-18 06:21 UTC by miozune

Apply renderer to combs

2023-02-18 14:25 UTC, miozune commented
I'm not sure if we should keep the name `GT_GeneratedItem_Renderer` now that it accepts any kind of item... But like `GT_CustomItemRenderer` does not make difference with other renderers like `GT_FlaskRenderer`

2023-02-19 09:29 UTC, OneEyeMaker requested changes

2023-02-19 09:29 UTC, OneEyeMaker commented on src/main/java/gregtech/common/render/items/UniversiumRenderer.java
>      public IIcon getTrueIcon(ItemStack stack) {
This method should include render pass as argument.

2023-02-19 09:59 UTC, OneEyeMaker approved these changes

2023-02-19 10:00 UTC, merged

2023-02-19 10:02 UTC, OneEyeMaker commented on src/main/java/gregtech/common/render/items/UniversiumRenderer.java
> +                magicRenderMethod(type, aStack, getTrueIcon(aStack), data);
Render pass also should be included in this call, shouldn't it?

2023-02-19 10:05 UTC, miozune commented on src/main/java/gregtech/common/render/items/UniversiumRenderer.java
> +                magicRenderMethod(type, aStack, getTrueIcon(aStack), data);
Oh you're right. I'm actually working on another PR, will include the fix in it