Convert more recipes to RA2
GTNewHorizons/GT5-Unofficial pull request #1957
Opened 2023-05-06 22:32 UTC by chochem

- MetaTE recipes
- lens recipes
- rotor recipes

still WIP

2023-05-06 22:37 UTC, boubou19 requested changes

2023-05-06 22:37 UTC, boubou19 commented on src/main/java/gregtech/loaders/load/GT_Loader_MetaTileEntities_Recipes.java
> +                .eut(120)
TierEU.RECIPE_MV

2023-05-06 22:37 UTC, boubou19 commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingLens.java
> +                    .eut(30)
TierEU.RECIPE_LV

2023-05-06 22:37 UTC, boubou19 commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingLens.java
> +                        .eut(120)
TierEU.RECIPE_MV

2023-05-06 22:37 UTC, boubou19 commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingLens.java
> +                        .eut(30)
TierEU.RECIPE_LV

2023-05-06 22:40 UTC, boubou19 commented
also you forgot to import `SECONDS` multiple times (see [compilation errors](https://github.com/GTNewHorizons/GT5-Unofficial/actions/runs/4903946223/jobs/8756679365?pr=1957#step:8:667))

2023-05-06 22:44 UTC, chochem commented
yea still wip ;)
those are all fixed though

2023-05-07 14:21 UTC, boubou19 requested changes

2023-05-07 14:21 UTC, boubou19 commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingIngot.java
> +                        .eut(calculateRecipeEU(aMaterial, 8))
1 second 12 ticks would be better here

2023-05-07 14:21 UTC, boubou19 commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingLens.java
> +                    .duration(120 * SECONDS)
2 minutes would be better

2023-05-07 14:21 UTC, boubou19 commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingLens.java
> +                        .duration(60 * SECONDS)
1 minute

2023-05-07 14:21 UTC, boubou19 commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingLens.java
> +                        .duration(120 * SECONDS)
2 minutes

2023-05-07 14:34 UTC, boubou19 approved these changes

2023-05-07 14:34 UTC, merged