fix recipe time and tier to adapt to CBD
GTNewHorizons/GT5-Unofficial pull request #2076
Opened 2023-06-10 22:45 UTC by POPlol333

Fix chemplant enforcing as it makes no sense, and btw no one use nitrobenzene in ZPM

2023-06-10 22:45 UTC, chochem submitted a review, later dismissed
that is the wrong recipe. this is just for kevlar because dreams wants it. nitrobenzene for power is in the chemplant

2023-06-10 22:45 UTC, boubou19 approved these changes

2023-06-10 22:46 UTC, POPlol333 commented
> that is the wrong recipe. this is just for kevlar because dreams wants it. nitrobenzene for power is in the chemplant

This is the "good recipe" as CBD isn't in chemplant and nitrobenzene is his equivalent in renewable line for is no reason for it to be in chemplant only

2023-06-10 22:47 UTC, POPlol333 commented
Not even talking about the "30s" for 5kL

2023-06-10 22:47 UTC, boubou19 commented
@chochem this is so stupid.  It's kevlar that must be changed. This is so stupid, no one is going to bother making a chemplant in HV because benzene.

2023-06-10 22:47 UTC, chochem commented
this is nitrobenzene and meant to be EV not HV

2023-06-10 22:49 UTC, POPlol333 commented
After if you want in ANY case I'm still ok if it's not more lmao

2023-06-11 00:03 UTC, Steelux8 requested changes
Nitrobenzene is a Chemical Plant recipe, not an LCR recipe. The ZPM tier was decided so that there was no possibility of the LCR recipe being used for power, and only for Kevlar purposes. This ZPM placement is not meant to be reverted.

2023-06-11 00:08 UTC, boubou19 commented
> Nitrobenzene is a Chemical Plant recipe, not an LCR recipe. The ZPM tier was decided so that there was no possibility of the LCR recipe being used for power, and only for Kevlar purposes. This ZPM placement is not meant to be reverted.

https://colab.research.google.com/drive/134Mk4NiJzW-Qbb62DC_ZJymMRzL1EeQm?authuser=2#scrollTo=r_IUi480pkEL

TLDR, CBD is weaker than NitroBenzene, so NitroBenzene must be unlocked later, chemplant if it can be avoided, it will be avoided by lot of players for obvious reasons, so to keep a reason to use the chemplant recipe, it must recieve a buff (how much is the question). The fact that nitrobenzene is too strong in comparison to CBD is just a simple change to the fuel value that is beyond the scope of this PR. The fact it can be an issue for kevlar too.

2023-06-11 00:38 UTC, chochem commented
there is a longer discussion with even some numbers in #meta-dev if some dev wants to read or chime in

2023-06-11 01:42 UTC, boubou19 commented
> there is a longer discussion with even some numbers in #meta-dev if some dev wants to read or chime in

i updated the data on the link

2023-06-11 02:52 UTC, chochem requested changes

2023-06-11 02:52 UTC, chochem commented on src/main/java/gregtech/loaders/postload/recipes/ChemicalRecipes.java
> +                .eut(TierEU.RECIPE_EV)
if we follow the logic in the doc this needs to be IV. aka 2x EV hatches.

2023-06-11 07:54 UTC, Dream-Master commented
@chochem ok now ?

2023-06-11 11:10 UTC, merged