Fix the shadow ItemStack bug of multi-InputBus_ME
GTNewHorizons/GT5-Unofficial pull request #2104
Opened 2023-06-29 16:14 UTC by wohaopa

When a machine contains multiple InputBus_ME and they are marked with the same item, the machine will recognize the item as multiple copies. For example, if there is only one iron ingot in the inventory, but two InputBus_ME are marked with iron ingot, the machine will assume that there are two iron ingots, which will lead to a series of bugs related to item duplication. This issue can only be fixed in GT_MetaTileEntity_MultiBlockBase because other InputBus_ME cannot know what is around them. It is not possible to use Set to fix this issue because the items are new objects that are copied.

2023-06-29 18:37 UTC, OneEyeMaker requested changes
Thank you for this bug fix!
Please resolve minor code style issues.

2023-06-29 18:37 UTC, OneEyeMaker commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +import java.util.*;
Please, don't use wildcard imports.

2023-06-29 18:37 UTC, OneEyeMaker commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        if (rInputBusMeList.size() != 0) rList.addAll(rInputBusMeList.values());
```suggestion
        if (!rInputBusMeList.isEmpty()) rList.addAll(rInputBusMeList.values());
```

2023-06-30 00:36 UTC, miozune commented
Actually we have another issue with stocking bus. I think making the hatch actually extract and store items is the way to go.

2023-06-30 00:46 UTC, wohaopa commented
> Actually we have another issue with stocking bus. I think making the hatch actually extract and store items is the way to go.

Yes, but the way it's implemented is that it's so hard to do. Also, ae had an inventory bug: connecting multiple storage buses to the same container would result in multiple items
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/30284813/28ed0552-8a26-474b-97e6-6ce8e24c3d6b)
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/30284813/07f602ef-3734-4870-9197-f6dbc4d437b6)
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/30284813/08fa7ce3-f8e6-43d5-a7e2-71fdda0641dd)

2023-06-30 01:03 UTC, miozune commented
Yes, multiple storage buses is what I meant. The actual issue is that result get from `Actionable.SIMULATE` can be different from `MODULATE`.
FYI GTCEu uses `MODULATE` and stores items / fluids in the hatch, so it's not something unreasonable.

2023-06-30 01:44 UTC, wohaopa commented
> 



> Yes, multiple storage buses is what I meant. The actual issue is that result get from `Actionable.SIMULATE` can be different from `MODULATE`. FYI GTCEu uses `MODULATE` and stores items / fluids in the hatch, so it's not something unreasonable.

In fact, there is no problem with Actionable, but the problem is that cache shadowInventory is used, and the modification of itemstack actually occurs in shadowInventory. When the inventory is insufficient, shadowInventory cannot be correctly updated to the inventory.

2023-06-30 01:55 UTC, miozune commented
I'm not saying `Actionable.SIMULATE` itself is issue, but making assumption that result get from `SIMULATE` is equal to itemstacks get from `MODULATE` is.

2023-06-30 07:47 UTC, OneEyeMaker approved these changes
This change will work as temporary fix. But proper bus rework @miozune suggest is requested.

2023-06-30 08:50 UTC, wohaopa commented
To really fix this issue, I need to rewrite inputBus_ME, and I will do it later. Also, I mean that there is no problem with Actionable.SIMULATE used by InputBus_ME. The problem occurs on the shadow inventory.  The shadow inventory thinks that the result of SIMULATE is the same as that of MODULATE, and the item deduction occurs on the shadow. However, according to the architecture, InputBus_ME cannot determine when it is simulated and when it is extracted. Using extraction all the time has a great burden on the network. Or I can make InputBus_ME in a form similar to the ME interface, which is really extracted to the cache, instead of using the shadow inventory of network inventory.

2023-06-30 09:27 UTC, miozune commented
> Or I can make InputBus_ME in a form similar to the ME interface, which is really extracted to the cache, instead of using the shadow inventory of network inventory.

Yeah this is what I've been thinking of. I'm sorry that my words are poor and couldn't tell you about that

2023-06-30 23:22 UTC, harrynull commented
> Or I can make InputBus_ME in a form similar to the ME interface, which is really extracted to the cache, instead of using the shadow inventory of network inventory.

Curious, with this approach, would the same item not be visible in two different ME input bus at once?

Consider the following scenarios:
1. ME Input Bus is used for load balancing, where one subnet stores all ingredient for processing, and connets to multiple ME input buses for parallel processing. Would only one machine stay active at once?
2. ME Input Bus is used for passively supplying materials in production lines, common materials e.g. carbon, sulfur, might get involved in multiple lines and hence multiple different buses. I think it's important that all of those can have the item visible at the same time.
3. AAL, where the same item gets used in multiple buses.

A easy workaround I guess is to cache only a certain number of items into the bus itself, but this number might be hard to determine because it depends on the parallel of the multi and also the recipe
Another workround maybe is to do kinda two stage recipe check where you use SIMULATE results first for recipe check and then try to "commit" that result before actually starting that craft?

2023-07-01 03:42 UTC, miozune commented
Maybe we can allow configuring max stored amount for each item via GUI

2023-07-03 16:01 UTC, merged