Lcf first muc
GTNewHorizons/GT5-Unofficial pull request #2142
Opened 2023-07-16 18:28 UTC by Steelux8

[See here for a document explaining MUCs in more detail.](https://docs.google.com/document/d/1_Xz9qG1QJXgKxqRqxfafWtdp_XEsUge1Pf7txrVA2EI/edit?usp=sharing)

This is the first implementation of Modular Upgrade Casings (MUCs), a system where special upgrade casings are placed in specific slots of a MuTE multi, but a choice is given between several options per slot, and each option gives a different bonus to the multi. Bonuses are not yet implemented, only some MUCs and their relevant checks.

I refactored what I had previously so that other MuTEs don't use the new implementations. I added a hashmap to keep track of MUCs per type, and then per tier. Each MUC type has 5 tiers, and each of those 5 are a range of GT tiers, as explained in the document above. By saving the exact amount of MUCs of each type, bonuses can be applied by the controller based on said amount.

So far, only Heater and Insulator MuTEs exist, each with their 5 tiers. I tested them in the multi I added, the Layered Coke Battery, with each MUC slot allowing any of the 10 possible MUCs. The hashmap stored the correct amounts from my testing.

2023-07-16 18:36 UTC, BlueWeabo requested changes

2023-07-16 18:36 UTC, BlueWeabo commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +    protected Map<String, Integer[]> mucMap = createMucMap();
IMO, you should use an Enum to get something into/out of the map instead of using a string. Nothing, much, but would look better than a string

2023-07-16 18:36 UTC, BlueWeabo commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        mucMap = createMucMap();
instead of creating a new map it would be better to call mucMap.clear() imo.

2023-07-16 18:36 UTC, BlueWeabo commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        }
Can you put this into a switch case instead?

2023-07-16 18:36 UTC, BlueWeabo commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        mucMap.put(casingType, casingCount);
as you are working with Integer arrays this is unneeded.

2023-07-16 18:41 UTC, minecraft7771 commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +    protected Map<String, Integer[]> mucMap = createMucMap();
This place seems perfect to use the enum `UpgradeCasing`

2023-07-16 18:55 UTC, Steelux8 commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        mucMap = createMucMap();
If I clear the map, I'll also clear the arrays I need to count the casing types. I'd have to create them again.

2023-07-16 18:58 UTC, BlueWeabo commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        mucMap = createMucMap();
```suggestion
        mucMap,forEach((type, casingCount) => for(int i = 0; i < casingCount.lenght; i++) casingCount[i] = 0);
```

2023-07-16 19:13 UTC, Steelux8 commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        mucMap.put(casingType, casingCount);
What is unneeded here, the "put"?

2023-07-16 19:20 UTC, BlueWeabo commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        mucMap.put(casingType, casingCount);
yeah the put

2023-07-16 19:33 UTC, Steelux8 commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        }
Fixed.

2023-07-16 19:34 UTC, Steelux8 commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        mucMap = createMucMap();
IntelliJ suggested the following:

`mucMap.forEach((type, casingCount) -> {
            Arrays.fill(casingCount, 0);
        });`

2023-07-16 19:34 UTC, Steelux8 commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        mucMap.put(casingType, casingCount);
Fixed.

2023-07-16 19:37 UTC, BlueWeabo commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +        mucMap = createMucMap();
That one also works. will do the same

2023-07-16 21:27 UTC, Steelux8 commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +    protected Map<String, Integer[]> mucMap = createMucMap();
Done.

2023-07-23 18:46 UTC, minecraft7771 approved these changes

2023-07-23 18:48 UTC, BlueWeabo approved these changes
This will keep me warm in the winter and cold in the summer yay

2023-07-23 19:07 UTC, merged

2023-07-25 03:28 UTC, r2go-beep commented on src/main/java/gregtech/api/multitileentity/multiblock/base/StackableModularController.java
> +public abstract class StackableModularController<T extends StackableModularController<T>> extends StackableController<T>
Is StackableModularController<T suppose to be StackableModularController<T> ?