Add more API to ParallelHelper and rework OverclockCalculator
GTNewHorizons/GT5-Unofficial pull request #2185
Opened 2023-07-26 12:27 UTC by BlueWeabo

GT_ParallelHelper:
- setting custom item and fluid output calculation
- batchmode now only starts if the duration of the recipe gets under 200 ticks before it being calculator (no more 10 hour recipes AND duration overflows)
- possibility of adding extra reason as to why something failed with CheckRecipeResult
GT_OverclockCalculator:
- Everything uses math now.
- added the tool to use laserOC from AAL with customizable penalty
- added a boolean if one should use amperage for OCing
Overall:
- Cleanup PCB Factory output calculation and make it follow ParallelHelper one (calculating each output per parallel)
- Cleanup Fusion Computer where possible

2023-07-26 14:08 UTC, miozune commented
Since you cleaned up variables in `GT_OverclockCalculator`, how about regrouping them by their functionality, not by variable type?

2023-07-26 18:59 UTC, minecraft7771 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
>                  GT_OverclockCalculator calculator = super.createOverclockCalculator(recipe, helper)
I think for the non-OC branch we can set the getDurationMultiplierFromRoughness() too. Then we could delete the calculateDuration override or?

2023-07-26 18:59 UTC, minecraft7771 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
> +                        ItemStack controllerStack = getControllerSlot();
Can inline the getter.

2023-07-26 18:59 UTC, minecraft7771 commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        GT_OverclockCalculator calc = new GT_OverclockCalculator().setEUt(availableEUt)
Do I see it right that we just discard this after we have the parallels done? Wouldn't it be less wasteful, to not create it here but give the parallel helper our own OC-calc for re-use? Or are there any issues that could cause?

2023-07-26 19:03 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        GT_OverclockCalculator calc = new GT_OverclockCalculator().setEUt(availableEUt)
The calc here is only to see what our duration will be after OCing. We could give the OC calc here, but that would mean we will need to create it before hand thus not being able to give the helper to give parallelDone, or anything relying on the helper to it.

2023-07-26 19:05 UTC, minecraft7771 commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        GT_OverclockCalculator calc = new GT_OverclockCalculator().setEUt(availableEUt)
Likewise though we are missing information here like speed boost from the machine.

2023-07-26 19:06 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        GT_OverclockCalculator calc = new GT_OverclockCalculator().setEUt(availableEUt)
O. true I forgot that one.

2023-07-26 19:08 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_PCBFactory.java
>                  GT_OverclockCalculator calculator = super.createOverclockCalculator(recipe, helper)
should be possible in theory.

2023-07-27 07:31 UTC, miozune requested changes
Some machines don't work at all but here're the things I've noticed so far

2023-07-27 07:31 UTC, miozune commented on src/main/java/gregtech/api/logic/ProcessingLogic.java
> +    protected GT_OverclockCalculator createOverclockCalculator(@Nonnull GT_Recipe recipe) {
return value is `@Nonnull`

2023-07-27 07:31 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +    public GT_OverclockCalculator setEUtDiscount(double aEUtDiscount) {
Actually this is backward-incompatible change. Either keep `float` method or decide to break other deprecated methods too

2023-07-27 07:31 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        calculator.setParallel(currentParallel)
Missing `setDuration`?

2023-07-27 07:31 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +            / (amountOfOverclocks * Math.pow(2, calculatorExtra.getDurationDecreasePerOC()));
`1 << calculatorExtra.getDurationDecreasePerOC()` instead of `Math.pow(2, calculatorExtra.getDurationDecreasePerOC())`?

2023-07-27 07:38 UTC, BlueWeabo commented
All machines don't work :trollface:

2023-07-27 07:43 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        calculator.setParallel(currentParallel)
It should be put in createOverclockcalculator. oversight on my part. (just put it there)

2023-07-27 07:43 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +    public GT_OverclockCalculator setEUtDiscount(double aEUtDiscount) {
Could I then make the internal float instead? I don't remember why I would've made it a double

2023-07-27 07:44 UTC, BlueWeabo commented on src/main/java/gregtech/api/logic/ProcessingLogic.java
> +    protected GT_OverclockCalculator createOverclockCalculator(@Nonnull GT_Recipe recipe) {
fixed

2023-07-27 07:46 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +            recipeVoltage >>= durationDecreasePerOC * ((int) multiTier - (int) recipeTier - overclockCount);
yes. something i forgot to change

2023-07-27 07:53 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        double currentPenalty = eutIncreasePerOC * 2 + laserOCPenalty;
yeah that is correct

2023-07-27 07:54 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +    public GT_OverclockCalculator setEUtDiscount(double aEUtDiscount) {
I don't remember the exact reason, but I made them double in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2096/commits/cb855c288f3874e2be3df8b7b3413f46d6556d59#diff-4eadea65dcd60ccd2ec4df264e8dfb224dd1821cc426a1e4a457e3bbe1f160cd along with `GT_ParallelHelper#mDurationMultiplier`. The latter is needed to prevent noob trophy recipe duration from overflowing due to insufficient precision of float

2023-07-27 07:55 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +    public GT_OverclockCalculator setEUtDiscount(double aEUtDiscount) {
I see. I will just force convert them to float when doing recreating the calculator. it shouldn't be a problem i think

2023-07-27 07:59 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        setOneTickDiscount(calculator.oneTickDiscount);
Any reason i need to also sync overclockCount? as that is an output variable

2023-07-27 08:02 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        setOneTickDiscount(calculator.oneTickDiscount);
Oh you're right

2023-07-27 08:07 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        setOneTickDiscount(calculator.oneTickDiscount);
Also should I just make limitOverclocks only be true is maxOverclocks is different from 0?

2023-07-27 08:10 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +            .min(multiTier - recipeTier, Math.log(duration) / Math.log(Math.pow(2, durationDecreasePerOC)));
Any idea on how to explain it in a good way.
Something like: log10 (5) / log10 (6) is the same as log6 (5)?

2023-07-27 08:11 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        setOneTickDiscount(calculator.oneTickDiscount);
I don't think such logic should be put in this constructor

2023-07-27 08:11 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        setOneTickDiscount(calculator.oneTickDiscount);
so just don't sync that?

2023-07-27 08:11 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        setOneTickDiscount(calculator.oneTickDiscount);
I would've liked to sync it as it will be needed

2023-07-27 08:12 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +            .min(multiTier - recipeTier, Math.log(duration) / Math.log(Math.pow(2, durationDecreasePerOC)));
yeah that sounds good. `Math.log(n)` is `log_e n` though

2023-07-27 08:13 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        setOneTickDiscount(calculator.oneTickDiscount);
no, just sync `limitOverclocks` and `maxOverclocks` without extra check here

2023-07-27 08:14 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        setOneTickDiscount(calculator.oneTickDiscount);
alright

2023-07-27 09:29 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +        duration >>= durationDecreasePerOC * (overclockCount - heatOCs);
`heatOCs` should not exceed `overclockCount`

2023-07-27 13:42 UTC, miozune commented
It's my fault, but I noticed `GT_Utility#roundDownVoltage` actually rounds up voltage :kekw: Can you deprecate it and add `#roundUpVoltage`?

Also since we introduced `amperageOC` feature, how about making `GT_MetaTileEntity_MultiBlockBase#setProcessingLogicPower` to use it?

2023-07-27 13:44 UTC, BlueWeabo commented
Sure I can add those methods. and yeah I will make it use it in a moment. Just need to test why the extra parallels from going under 1 tick aren't being added

2023-07-27 13:48 UTC, BlueWeabo commented
division by 0 not being logged my beloved

2023-07-27 14:06 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +                + heatOverclocks * (1 << calculator.getDurationDecreasePerHeatOC()));
This looks duplicated logic between `GT_OverclockCalculator` and `GT_ParallelHelper`. Ideally only the former should know the logic about overclocking.

2023-07-27 14:07 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +            calculate();
can change to throw exceptions was just following what i had done before for it.

2023-07-27 14:08 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +                + heatOverclocks * (1 << calculator.getDurationDecreasePerHeatOC()));
Will now make a method for this inside the calculator. and just remove methods I added. Should make it look cleaner

2023-07-27 14:44 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +            calculate();
yeah throwing is good

2023-07-28 03:18 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +            * (1 << durationDecreasePerHeatOC * heatOverclocks));
This should be `a / (b * c)`, not `a / b * c`

2023-07-28 03:18 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        logic.setAmperageOC(false);
Hmm, `setAmperageOC` is obsolete because it already sets amperage to 1. What's your idea behind `amperageOC` feature?

2023-07-28 03:23 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +            * (1 << durationDecreasePerHeatOC * heatOverclocks));
Oh nvm I read it wrong, it already is

2023-07-28 06:11 UTC, BlueWeabo commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        logic.setAmperageOC(false);
I need to fix it in the overclock calculator, but in short only use amperage for parallels if possible and not overclocking extra.

2023-07-28 07:39 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        logic.setAmperageOC(false);
I mean, `setAmperageOC(false)` or `setAmperageOC(true)` doesn't matter here because amperage is set to constant 1.
If it's supposed to actually change OC behavior depending on amperage, how about this?
```java
protected void setProcessingLogicPower(ProcessingLogic logic) {
    logic.setAvailableVoltage(getAverageInputVoltage()); // currently doesn't exist in non-long machine
    logic.setAvailableAmperage(getMaxInputAmps()); // currently doesn't exist in non-long machine
    logic.setAmperageOC(mEnergyHatches.size() != 1);
}
```
This also fixes an issue (well not critical but why not fix it if possible) where mixing LV and MV hatches to run MV recipe results in power shortage, because of the machine trying to overclock to 512 EU/t while hatches can provide only 320 EU/t. `ProcessingLogic#findRecipe` needs adjustment to not fail recipe check though.

2023-07-28 07:41 UTC, BlueWeabo commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        logic.setAmperageOC(false);
alright. I shall change it then and integrate the methods which don't exist there to here

2023-07-28 08:02 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        }
I'm not sure, is this correct? Setting recipe voltage after executing calculation sounds... not right? Or even if it's correct, is there any way better than this? It looks too complex to read for me.

2023-07-28 08:04 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        logic.setAmperageOC(false);
`ProcessingLogic#findRecipe` should be
```java
return map.findRecipeWithResult(lastRecipe, false, false, amperageOC ? availableVoltage * availableAmperage : availableVoltage, inputFluids, specialSlotItem, inputItems);
```

2023-07-28 08:07 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        }
Or if it just works and you know what you're doing, I'd leave it untouched :trollface:

2023-07-28 08:56 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        return recipe.isRecipeInputEqual(true, false, fluids, items);
oh oops

2023-07-28 09:18 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        int trueMaxParallel = maxParallel;
changed name and added a comment

2023-07-28 09:31 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        }
Now it should be more correct than before. and there really isn't a better way RN. I would need to do API changes much deeper in the chain than this. And its already frustrating a bit.

2023-07-28 09:35 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java
> +        logic.setAvailableVoltage(GT_Utility.roundUpVoltage(getAverageInputVoltage()));
`roundUpVoltage` here can be removed too

2023-07-28 09:37 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        }
I see. Yeah this PR has become large, let's test it first and then we can improve it in the future

2023-07-28 09:39 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +        }
I already have people testing it. Its being tested on the baller server, GDCloud is testing it and Hiagg wanted to try it out too. Current things that need to really be improved are the recipe input checking. Thorium plasma is mk5, which is why i fixed the fusion nei (unsure if it actually is, but the values were like that.)

2023-07-28 09:52 UTC, miozune approved these changes
I can't fully follow the logic on OC under 1 tick, but we'll see how it'll work well while doing more broad test play.
Getting review from others would be nice, but if not we can just merge and test as usual.

2023-07-28 10:13 UTC, merged