Crafting Input: display pattern output by default
GTNewHorizons/GT5-Unofficial pull request #2186
Opened 2023-07-26 13:40 UTC by harrynull

![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/7413706/5ba7871b-cdcf-4a4c-8ccf-dee6490378a4)

Display the output of the pattern without having to hold shift like ME interface does.

Also fixes the overlay icon.

2023-07-27 05:47 UTC, miozune requested changes

2023-07-27 05:47 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_CraftingInput_ME.java
> +                        // hack to display the output of the pattern
Add method to get itemstack to render on MUI side

2023-07-27 19:04 UTC, harrynull commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_CraftingInput_ME.java
> +                        // hack to display the output of the pattern
https://github.com/GTNewHorizons/ModularUI/pull/50

2023-07-28 01:42 UTC, miozune approved these changes

2023-07-28 08:22 UTC, merged