obliterate RA1
GTNewHorizons/GT5-Unofficial pull request #2206
Opened 2023-08-02 22:21 UTC by boubou19

😎

2023-09-07 08:37 UTC, kuba6000 requested changes

2023-09-07 08:37 UTC, kuba6000 commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +        return true;
Wrong machine (alloy smelter -> ore washer)

2023-09-09 14:53 UTC, chochem commented on src/main/java/gregtech/api/util/GT_RecipeRegistrator.java
> +            .itemOutputs(recipeOutput)
this will spam the the recipe debug as you set recipeOutput = null most of the time

2023-09-22 08:52 UTC, boubou19 commented on src/main/java/gregtech/api/util/GT_RecipeRegistrator.java
> +            .itemOutputs(recipeOutput)
i put a null check now

2023-09-22 08:53 UTC, boubou19 commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +        return true;
fixed

2023-09-22 09:25 UTC, chochem commented on src/main/java/gregtech/api/util/GT_RecipeRegistrator.java
> +        if (recipeOutput != null) {
isnt that just the byproduct?
so there should still be a recipe if its null. just without the '.itemOutputs(recipeOutput)'

2023-09-22 12:19 UTC, boubou19 commented on src/main/java/gregtech/api/util/GT_RecipeRegistrator.java
> +        if (recipeOutput != null) {
i decided to do separate full recipe registration instead of making a temp variable and doing different calls based on the nullity of the recipe output. Should be good now

2023-09-22 14:41 UTC, chochem approved these changes

2023-09-22 15:11 UTC, merged