Fix server crash with RecipeFilter
GTNewHorizons/GT5-Unofficial pull request #2231
Opened 2023-08-15 05:01 UTC by miozune

Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14216

Recipe catalysts and recipe handlers are stored only on client, so we can't just use it on server side. I'm not sure how to iterate over MuTEs, so I just leave it untouched.
This doesn't work well with machines that have multiple recipemaps; It needs some more work but it should be after stable release.

2023-08-15 05:21 UTC, Glease commented
we could make it so that client send over the selected recipe map and selected machine and we store those instead. it will probably not go very well if one machine received some more recipe map than before due to a mod update, but we can always devise a better fix at that moment, where time is not at a premium

2023-08-15 05:53 UTC, miozune commented
"selected recipe map" as in letting player to choose recipemap from list, not from clicking slot with item (or combination of both)? That's what I'm thinking of, but it's considered as feature addition.

2023-08-15 13:44 UTC, Glease commented
@miozune I mean determine the recipe map to use on client side, and send that over (alongside the actual block selected). from a server standpoint yes the player *is* selecting the recipe map, but unless they go packet forging that feature is not really available.

2023-08-15 15:42 UTC, miozune commented
Ah, now I see. I'll work on it tomorrow

2023-08-16 14:45 UTC, Glease requested changes

2023-08-16 14:45 UTC, Glease commented on src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_RecipeFilter.java
> +                NetworkUtils.writeStringSafe(buffer, recipeMap != null ? recipeMap.mUnlocalizedName : null);
We should use mUniqueIdentifier instead. It is ensured to be unique and stable. See save/loadNBTData above.

2023-08-17 01:07 UTC, miozune commented on src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_RecipeFilter.java
> +                NetworkUtils.writeStringSafe(buffer, recipeMap != null ? recipeMap.mUnlocalizedName : null);
I don't think this variable is useful, because
- There's no conflicting `mUnlocalizedName` in the pack.
- We have full control over GT addons that add recipemap.
- Since it only appends a few variables, there's still possibility that conflict happens. It's actually not necessarily unique.

But anyways I made it to use `mUniqueIdentifier` just like other parts.

2023-08-17 01:34 UTC, Glease approved these changes

2023-08-17 02:06 UTC, miozune commented on src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_RecipeFilter.java
> +                NetworkUtils.writeStringSafe(buffer, recipeMap != null ? recipeMap.mUnlocalizedName : null);
I actually loaded up the pack, and both of the list and set of `mUnlocalizedName`s have the same size.
GT++ issue was fixed 2 years ago https://github.com/GTNewHorizons/GTplusplus/pull/32

2023-08-17 04:38 UTC, merged