Adds item and charging info to Locker WAILA panel
GTNewHorizons/GT5-Unofficial pull request #2245
Opened 2023-08-18 22:27 UTC by querns

This is a new feature, and doesn't need to be in 2.4.0 right away if a feature freeze is in place.

This PR adds more information to the WAILA readout for GT Lockers. Includes charge level for each item, if appropriate. 

![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/33518699/4fc4ae41-7073-4d99-81c3-8255d1a27a95)

![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/33518699/14f63071-ea96-483c-9cf6-839eb0195123)

2023-09-05 14:07 UTC, Alastors approved these changes
Beautiful

2023-09-06 03:13 UTC, miozune requested changes
~~Yes I don't trust Alastor's reviews~~

2023-09-06 03:13 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +        if (aStack == null || !isElectricItem(aStack)) {
`isElectricItem` just checks for `IElectricItem`, so it's not needed

2023-09-06 03:13 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +        if (item == null) {
null is also checked by `instanceof`, so it's not needed

2023-09-06 03:13 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +        if (item instanceof GT_MetaBase_Item) {
Is this check needed? I took a brief look at `GT_MetaBase_Item` but it seems to be just passing electric stats to `IElectricItem` methods

2023-09-06 03:13 UTC, miozune commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_Locker.java
> +                    .append(itemStack.getDisplayName())
This hardcodes server-sided translation. All the formats should be done on client side (== `getWailaBody`), and server should send minimal data client needs to fetch.

2023-09-06 03:47 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +        if (aStack == null || !isElectricItem(aStack)) {
nvm, it uses `Integer.MAX_VALUE` to indicate it's not electric item

2023-09-06 12:43 UTC, querns commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +        if (item instanceof GT_MetaBase_Item) {
It's needed, yeah. The abstract class `GT_MetaBaseItem` is extended by `GT_MetaGeneratedTool`, which overrides the method used to pull the electricity information from a different place. While my locker change won't ever actually receive an instance of `GT_MetaGeneratedTool`, a generic method such as this shouldn't be so constrained.

2023-09-06 13:42 UTC, querns commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +        if (item == null) {
This should be cleaner now.

2023-09-06 15:56 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +        if (item instanceof GT_MetaBase_Item) {
Hmm, you're right, `ElectricItemManager` is doing something suspicious...

2023-09-06 16:29 UTC, merged