Display current recipe in GUI
GTNewHorizons/GT5-Unofficial pull request #2252
Opened 2023-08-26 01:22 UTC by harrynull

![2023-08-26_09 21 27](https://github.com/GTNewHorizons/GT5-Unofficial/assets/7413706/ded65010-90be-4821-aecd-1cacb0cb3ead)
![2023-08-26_09 21 36](https://github.com/GTNewHorizons/GT5-Unofficial/assets/7413706/ed12a2c9-6e2e-46c5-b31c-2b721fba30ed)
![2023-08-26_09 21 50](https://github.com/GTNewHorizons/GT5-Unofficial/assets/7413706/1175fbbd-5055-4ea4-bf33-032c37d7a621)

2023-08-26 08:13 UTC, harrynull commented
todo: fix draconic fusion reactor
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.item.ItemStack.func_82833_r()" because "item" is null
    at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.generateCurrentRecipeInfoString(GT_MetaTileEntity_MultiBlockBase.java:2168)
    at com.gtnewhorizons.modularui.common.widget.TextWidget.lambda$dynamicString$0(TextWidget.java:47)
    at com.gtnewhorizons.modularui.common.widget.DynamicTextWidget.updateText(DynamicTextWidget.java:47)
    at com.gtnewhorizons.modularui.common.widget.DynamicTextWidget.getText(DynamicTextWidget.java:40)
    at com.gtnewhorizons.modularui.common.widget.TextWidget.onScreenUpdate(TextWidget.java:80)
    at com.gtnewhorizons.modularui.api.screen.ModularWindow.lambda$update$6(ModularWindow.java:195)
    at com.gtnewhorizons.modularui.api.widget.IWidgetParent.lambda$forEachByLayer$2(IWidgetParent.java:119)
    at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:84)
    at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:71)
    at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:67)
    at com.gtnewhorizons.modularui.api.widget.IWidgetParent.forEachByLayer(IWidgetParent.java:118)
    at com.gtnewhorizons.modularui.api.screen.ModularWindow.update(ModularWindow.java:194)
    at com.gtnewhorizons.modularui.common.internal.wrapper.ModularGui.updateScreen(ModularGui.java:440)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1661)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:973)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5106)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke(Method.java:578)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

2023-08-29 02:53 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +                    Utils::readFluidStack))
Why not
```java
buffer -> {
    try {
        return NetworkUtils.readFluidStack(buffer);
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
}
```
? Same for others

2023-08-29 02:53 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        if (mOutputFluids != null) {
Any reason fluid comes earlier than item?

2023-08-29 02:53 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        StringBuilder ret = new StringBuilder(EnumChatFormatting.WHITE + "In progress ")
nit: "In progress: " makes more sense to me

2023-08-29 02:53 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +                    .append(Math.round((double) fluid.amount / mMaxProgresstime * 20 * 10) / 10)
For early-to-mid-game people, this "amount per sec" can be annoying, as processing time rarely goes under 1 second. Limiting this display would be nice, depending on e.g. whether if processing time goes under 1 sec, parallel is more than 1, or config.

2023-08-30 10:02 UTC, harrynull commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +                    Utils::readFluidStack))
Just wanted to make cleaner code on the caller side as this might potentially get reused.

2023-08-30 10:02 UTC, harrynull commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        if (mOutputFluids != null) {
no. swapped

2023-08-30 10:23 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +                    Utils::readFluidStack))
Then they should be put at MUI

2023-08-30 15:42 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +                    .append("s/ea)");
What does "s/ea" stands for?

2023-08-30 22:10 UTC, harrynull commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +                    .append("s/ea)");
sec/each

2023-08-30 22:26 UTC, Connor-Colenso requested changes

2023-08-30 22:26 UTC, Connor-Colenso commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +            .append(Math.round((double) mProgresstime / mMaxProgresstime * 1000) / 10.0)
formatNumbers around all numbers that the end user can see please <3

2023-09-02 00:43 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +                    .append("s/ea)");
TIL

2023-09-02 06:13 UTC, Connor-Colenso commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
>              .append(String.format("%.2f", (double) mMaxProgresstime / 20))
These two need formatting as well please

2023-09-02 06:18 UTC, harrynull commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
>              .append(String.format("%.2f", (double) mMaxProgresstime / 20))
they are already formatted to two digits decimal strings, I don't think you can call formatnumbers on strings?

2023-09-07 01:05 UTC, Connor-Colenso approved these changes

2023-09-07 02:14 UTC, miozune requested changes
Waiting for https://github.com/GTNewHorizons/ModularUI/pull/51 being merged

2023-09-07 04:52 UTC, Dream-Master commented
> Waiting for [GTNewHorizons/ModularUI#51](https://github.com/GTNewHorizons/ModularUI/pull/51) being merged

It is merged

2023-09-07 04:54 UTC, miozune commented
And this PR should use methods added there instead of inventing own ones

2023-09-08 08:39 UTC, miozune approved these changes

2023-09-08 08:53 UTC, merged