Made and added Hatch_Input_ME
GTNewHorizons/GT5-Unofficial pull request #2264
Opened 2023-09-02 12:09 UTC by this-til

be similar to GT_MetaTileEntity_Hatch_InputBus_ME , but it is fluid version
![Cache_67679f636dd3697b](https://github.com/GTNewHorizons/GT5-Unofficial/assets/83351975/d0b1f047-29cb-4cdd-8292-ecee2762dd43)

2023-09-02 15:09 UTC, miozune requested changes
This has the same issue as stocking bus: `Actionable.SIMULATE` might return more fluids than `Actionable.MODULATE` actually can provide, resulting in dupe of fluids.
The simple solution would be actually storing fluids in the hatch, but it removes "load balancer" functionality. One solution to this would be to allow setting limit to draw from network per each fluid type.
But I guess it will be a hard work for you... You can ask questions on #mod-dev channel on Discord, or wait for one of us fixing stocking bus and adapt changes from there.

2023-09-04 04:04 UTC, harrynull commented
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12269

2023-09-05 06:38 UTC, Dream-Master commented
@this-til can you run spotless

2023-09-05 20:11 UTC, Jonodonozym commented on src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
> +                    "Stocking Input (ME)").getStackForm(1L));
Stocking Input (ME) -> Stocking Input Hatch (ME)

2023-09-10 19:56 UTC, Dream-Master commented
@this-til can you take care your pr and fix the stuff so we can re review it ?  thanks

2023-09-27 13:46 UTC, Pilad commented
> be similar to GT_MetaTileEntity_Hatch_InputBus_ME , but it is fluid version ![Cache_67679f636dd3697b](https://user-images.githubusercontent.com/83351975/265203397-d0b1f047-29cb-4cdd-8292-ecee2762dd43.jpg)
Here are the fixes added. Does your code need to be written in the same way or not? Nothing will break in the operation of Hatch_Input_ME?
https://github.com/GTNewHorizons/GT5-Unofficial/commit/6599b089a7d259ddf0313b10e26e00ab116d3699
https://github.com/GTNewHorizons/GT5-Unofficial/commit/b893dfcaae9f1e2186073606fce1f7b79e3c78bb

2023-09-27 16:15 UTC, FoKuCNiK commented
When will this candy be released?

2023-09-27 16:17 UTC, Dream-Master commented
> When will this candy be released?

Go and fin user @this-til to finished the pr and resolve conflicts

2023-10-02 14:16 UTC, tth05 commented
@Dream-Master Considering OP seems to have gone missing, I'd want to make a new PR for this to finish it up and get it merged. Would that be ok?

2023-10-02 14:20 UTC, Dream-Master commented
> @Dream-Master Considering OP seems to have gone missing, I'd want to make a new PR for this to finish it up and get it merged. Would that be ok?

Sure make a new pr

2023-10-08 06:38 UTC, closed without merging