fixes uninsulated cable not damaging players
GTNewHorizons/GT5-Unofficial pull request #2300
Opened 2023-09-22 11:31 UTC by iamblackornot

- a workaround fix to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14431
- code clean-up of unused variables related to the issue
- portable scanner infodata is cleaned too since some of the data is related to mentioned before "ghost" variables

2023-09-22 11:41 UTC, BlueWeabo commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
> +        final var baseEntity = (BaseMetaPipeEntity) getBaseMetaTileEntity();
no need to use var here, just use BaseMetaPipeEntity.

2023-09-22 11:41 UTC, BlueWeabo commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
> +        final var livingEntity = aEntity instanceof EntityLivingBase ? (EntityLivingBase) aEntity : null;
instead of this do:
```suggestion
        if (!(aEntity instanceof EntityLivingBase livingEntity)) return;
```

2023-09-22 11:41 UTC, BlueWeabo commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
> +        if (livingEntity == null) return;
can remove this if suggesting is implemented

2023-09-22 11:41 UTC, BlueWeabo commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
> -        mTransferredVoltageOK = 0;
I would recommend to not delete variables that are deleted, but mark them as deprecated. That is if you are sure they aren't used anywhere else you can delete them.

2023-09-22 11:41 UTC, BlueWeabo commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
> -            lastWorldTick = aBaseMetaTileEntity.getWorld()
any reason for removing the setting of lastWorldTick?

2023-09-22 11:57 UTC, Pxx500 requested changes

2023-09-22 11:57 UTC, Pxx500 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
> +            "Current Amperage: " + EnumChatFormatting.GREEN
I'm not a native speaker, but I think you should either use "current" or "amperage", and not both at the same time since they mean the same thing, also saying that the amperage is current (at this moment) is implied.

2023-09-22 16:26 UTC, Dream-Master commented
@iamblackornot can you check your pr and run spotless?

2023-09-22 17:33 UTC, iamblackornot commented
i've built the project for every commit i made, right now additionally ran spotless with successful result

2023-09-22 17:59 UTC, Dream-Master commented
this time you need to only run update buildscript @iamblackornot

2023-09-22 18:11 UTC, Dream-Master commented
@iamblackornot thanks but there are two open questions blue ask. Any new here ?

2023-09-22 18:12 UTC, iamblackornot commented
I hope committing updated 'build.gradle' script is what needed. I see it fixes the issue with ic2 maven. Sorry, if i am doing it the wrong way

2023-09-22 18:16 UTC, Dream-Master commented
> I hope committing updated 'build.gradle' script is what needed. I see it fixes the issue with ic2 maven. Sorry, if i am doing it the wrong way

yes it work now. MAybe you can look at the two issue and we can merge this pr

2023-09-22 18:16 UTC, iamblackornot commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
> -            lastWorldTick = aBaseMetaTileEntity.getWorld()
This variable is private and unused except the code above. I've brought it back to prevent any issues

2023-09-22 18:17 UTC, BlueWeabo approved these changes
Thanks for your contribution

2023-09-22 18:18 UTC, iamblackornot commented
My bad. Haven't ever participated in github git work. I guess i should have resolved that two questions. Thanks for your patience

2023-09-22 18:19 UTC, BlueWeabo commented
Its alright. Everyone starts out somewhere.

2023-09-22 18:24 UTC, merged

2023-09-23 09:10 UTC, Pilad commented
> * a workaround fix to [Uninsulated wires don't deal damage GT-New-Horizons-Modpack#14431](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14431)
> 
>     * code clean-up of unused variables related to the issue
> 
>     * portable scanner infodata is cleaned too since some of the data is related to mentioned before "ghost" variables

I compiled the latest greg tech from Gita, you can still stand on the wires.

2023-09-23 09:11 UTC, Dream-Master commented
@iamblackornot any idea?
@Pilad  did you test it in full pack ?

2023-09-23 09:39 UTC, iamblackornot commented
- needs amperage being transfered
- as far as i know high tier wires, which don't have insulation at all, don't shock
 i'll do more tests

2023-09-23 09:41 UTC, Pilad commented
> * needs amperage being transfered
> 
> * as far as i know high tier wires, which don't have insulation at all, don't shock
>   i'll do more tests

I used copper wire and a medium voltage battery buffer. And there was no electric shock.

2023-09-23 09:48 UTC, Pilad commented
Strange, it worked.

2023-09-23 09:50 UTC, Pilad commented
> * needs amperage being transfered
> 
>     * as far as i know high tier wires, which don't have insulation at all, don't shock
>       i'll do more tests

This same mechanic is only written into gregtech, doesn’t it depend on other mods?

2023-09-23 09:54 UTC, iamblackornot commented
There is one more thing. If hold an item that causes drawing a voxel cover grid, it blocks your movement like if it was a whole voxel block

2023-09-23 09:57 UTC, iamblackornot commented
> > * needs amperage being transfered
> >   
> >   * as far as i know high tier wires, which don't have insulation at all, don't shock
> >     i'll do more tests
> 
> This same mechanic is only written into gregtech, doesn’t it depend on other mods?

not sure

2023-09-23 09:57 UTC, Pilad commented
> There is one more thing. If hold an item that causes drawing a voxel cover grid, it blocks your movement like if it was a whole voxel block

With wire cutters or a wrench, damage from the wire/pipe is blocked. This is all clear. I meant dependence, for example, on mixins or feeds or settings in the config.

2023-09-23 09:57 UTC, Pilad commented
> > > * needs amperage being transfered
> > >   
> > >   * as far as i know high tier wires, which don't have insulation at all, don't shock
> > >     i'll do more tests
> > 
> > 
> > This same mechanic is only written into gregtech, doesn’t it depend on other mods?
> 
> not sure

Ok.

2023-09-23 10:22 UTC, Pilad commented
Something was wrong with the gamemod; in the new world, the wires began to cause damage.

2023-09-23 10:32 UTC, iamblackornot commented
good to hear, thanks for testing