Add stocking input hatch
GTNewHorizons/GT5-Unofficial pull request #2322
Opened 2023-10-03 17:52 UTC by tth05

Implementation taken from https://github.com/GTNewHorizons/GT5-Unofficial/pull/2264, rebased on master. I made some small fixes and added stuff like the "additional connections" mode.

[This ](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2264#pullrequestreview-1608322582) comment remains unresolved. In my opinion this should be done in a separate PR where both the hatch and the bus get fixed.

Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12269.

2023-10-03 18:16 UTC, S4mpsa commented
A single-slot, non-autopull stocking hatch tiered at EV-IV would be fine, with maybe 4-slot in IV-LuV.

The moment you introduce autopull to the hatch, however, tiers it to the realm of the Crafting Input Buffer as it completely trivializes most automation, so expect that to be tiered to UIV-UMV, no matter how many slots it has.

Personally I am fully in favor of the non-autopull stocking hatch; It would be nice QoL to replace P2P/Fluid Export buses, and heavily against the autopull, as that trivializes crafting setups - however, the CRIB was added, so having a high-tier autopull stocking hatch would likely be too.

2023-10-03 18:41 UTC, lordIcocain commented
Without auto pull you can just spam stocking hatch until you select every possible liquid. In some cases you dont have much place for input hatch, but anyway.

2023-10-03 20:50 UTC, Pilad commented
> Implementation taken from #2264, rebased on master. I made some small fixes and added stuff like the "additional connections" mode.
> 
> [This ](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2264#pullrequestreview-1608322582) comment remains unresolved. In my opinion this should be done in a separate PR where both the hatch and the bus get fixed.
> 
> Closes [GTNewHorizons/GT-New-Horizons-Modpack#12269](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12269).

Stack size for items? The block works with liquid. I do not understand something.
![изображение](https://github.com/GTNewHorizons/GT5-Unofficial/assets/9840821/f38de55b-5b4c-468a-9bbb-81d426f798df)

2023-10-03 21:12 UTC, tth05 commented
> Stack size for items? The block works with liquid. I do not understand something. ![изображение](https://user-images.githubusercontent.com/9840821/272394709-f38de55b-5b4c-468a-9bbb-81d426f798df.png)

Fixed it. Missed that.

2023-10-04 10:34 UTC, miozune requested changes
I still think we shouldn't add new feature that is known to be exploitable. Stocking bus is left as is because it had been a long time since it was originally added until the bug was found. For stocking hatch, we don't even have it yet, so we should add it in a clean state.

I'll push the stocking bus rework in a few days. You can adapt changes / redo the PR based on that.

2023-10-04 11:48 UTC, Pilad commented
> > Stack size for items? The block works with liquid. I do not understand something. ![изображение](https://user-images.githubusercontent.com/9840821/272394709-f38de55b-5b4c-468a-9bbb-81d426f798df.png)
> 
> Fixed it. Missed that.

Below is the code, line 722. It’s also about objects. Below is more text in NBT about stacks and items. It's not a mistake?
![изображение](https://github.com/GTNewHorizons/GT5-Unofficial/assets/9840821/6f87696b-2de4-43b8-ac88-dfb70b70aa13)
![изображение](https://github.com/GTNewHorizons/GT5-Unofficial/assets/9840821/c1632a25-532e-4b71-94e9-c81d626c1fa4)

2023-10-04 19:51 UTC, Pelotrio commented
> A single-slot, non-autopull stocking hatch tiered at EV-IV would be fine, with maybe 4-slot in IV-LuV.
> 
> The moment you introduce autopull to the hatch, however, tiers it to the realm of the Crafting Input Buffer as it completely trivializes most automation, so expect that to be tiered to UIV-UMV, no matter how many slots it has.
> 
> Personally I am fully in favor of the non-autopull stocking hatch; It would be nice QoL to replace P2P/Fluid Export buses, and heavily against the autopull, as that trivializes crafting setups - however, the CRIB was added, so having a high-tier autopull stocking hatch would likely be too.

@S4mpsa I disagree with gating this UIV-UMV as it certainly does not trivialize setups as much as the Crafting Input Buffer. On the other hand, the standard stocking input bus with autopulling is arguably even stronger and is not gated at all (at least not more than most other AE2 components, obviously). To be fair, the power of autopull was discovered after it was added because it was presumed to be only beneficial for some niche automations. However, gating the same mechanic exclusively for fluids very late-game seems illogical. If you could give some examples where this feature would be significantly more overpowered than some sort of fluid P2P setup, I would agree. But I don't see it. My suggestion would be to probably gate this with a UHV or, at worst, a UEV pump. UHV would be nice because you are likely upgrading your infrastructure for the Amunra gate, and there's no reason you shouldn't have access to it by then. By this point, you've likely undergone maybe 2-3 infrastructure rebuilds, at least for some chem lines, and you've already had to work without it, so there's no reason you shouldn't be able to craft it. Depending on the crafting recipe, some UHV components may be quite expensive for you. Imagine a new player who just reached EV-IV and wants to build a cool setup involving stocking hatches and buses, checking out the recipe for the stocking input bus, which is not gated, just to get jumpscared by a UIV-UMV recipe with the same functionality but for fluids. I agree this feature requires gating, but having an AE2 component that only a tiny minority of players will be able to craft seems unnecessary.

2023-10-12 17:46 UTC, tth05 commented
Now up-to-date with https://github.com/GTNewHorizons/GT5-Unofficial/pull/2326. Once that is merged I'll rebase on master

2023-10-12 23:28 UTC, miaowwwwww commented
not working with EOH, Assline. (only tested this 2 & PA, could be other compatible.) EOH i don't think we need to add support, we need support for assline.

2023-10-12 23:36 UTC, Pelotrio commented
> not working with EOH, Assline. (only tested this 2 & PA, could be other incompatible.) EOH i don't think we need to add support, we need support for assline.

I will do some more testing soon with more multiblocks and let the current ones be fixed

2023-10-13 03:16 UTC, miozune commented
Isn't assline behavior intended because it enforces the order of fluids?

2023-10-13 04:17 UTC, miaowwwwww commented
I think 4 fluids in 4 input hatch ME should be good, right?
(in good order)

2023-10-14 01:35 UTC, Pelotrio commented
> I think 4 fluids in 4 input hatch ME should be good, right? (in good order)

Both Assline and EOH need custom code to support them because it doesnt actually store the fluid itself in the hatch. I figured out what to do and it will be added soon

2023-10-14 05:43 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +                setResultIfFailure.accept(aware.endRecipeProcessing(this));
nit: put curly brackets

2023-10-14 05:43 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +            if (hatch instanceof IRecipeProcessingAwareHatch aware) aware.startRecipeProcessing();
Same here

2023-10-14 05:43 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +                "Configuration data can be copy+pasted using a data stick." });
Description for ME connection behavior is missing

2023-10-14 05:43 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +        AENetworkProxy proxy = getProxy();
I don't think this hatch should allow extracting fluid from outside

2023-10-14 05:43 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +        AENetworkProxy proxy = getProxy();
Same here

2023-10-14 05:43 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +                    // be used either
We have full control over MUI source, so please make changes there instead of using reflection.

2023-10-14 05:43 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +                    FluidStack fluid = fluidTanks[slotIndex].getFluid();
`getContent()` to retrieve fluidstack of this widget

2023-10-14 05:43 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +                    FluidStack fluid = fluidTanks[slotIndex].getFluid();
Same here

2023-10-14 05:43 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +    protected final FluidStack[] storedFluid = new FluidStack[ALL_SLOT_COUNT];
`FluidStackTank` should have many methods enough for manipulating fluid I/O. Why not use it instead of raw FluidStack?

2023-10-14 05:43 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +    protected final FluidStackTank[] fluidTanks = new FluidStackTank[ALL_SLOT_COUNT];
Using the same variable for configuration slots and information slots can be confusing. I suggest splitting into 2 variables. (Yes, stocking bus using `mInventory` is not great)

2023-10-14 12:44 UTC, GDCloudstrike commented
> > I think 4 fluids in 4 input hatch ME should be good, right? (in good order)
> 
> Both Assline and EOH need custom code to support them because it doesnt actually store the fluid itself in the hatch. I figured out what to do and it will be added soon

I would be against adding stocking hatch functionality to the EOH as it would completely trivialize its automation challenge, which is one of its more impactful mechanics (the penalties for not inserting exact fluid amounts are very harsh).

2023-10-14 13:00 UTC, Pelotrio commented
> > > I think 4 fluids in 4 input hatch ME should be good, right? (in good order)
> > 
> > 
> > Both Assline and EOH need custom code to support them because it doesnt actually store the fluid itself in the hatch. I figured out what to do and it will be added soon
> 
> I would be against adding stocking hatch functionality to the EOH as it would completely trivialize its automation challenge, which is one of its more impactful mechanics (the penalties for not inserting exact fluid amounts are very harsh).

@GDCloudstrike It would help filling the internal buffer to start faster as you are limited by input hatch size here. Also the hatch would pull all available fluids so you still have to have the right amount stored in a subnet. That is at least the functionality I would expect maybe with an upper limit so it doesnt completely drain your entire me if you are not careful. I would not expect it to only pull the right amount of fluid every time as this would really trivialize it. Or is there more to it that Im missing?

2023-10-14 13:39 UTC, tth05 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +                setResultIfFailure.accept(aware.endRecipeProcessing(this));
Why is this not included in the spotless config if it's required?

2023-10-14 17:41 UTC, tth05 commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +    protected final FluidStack[] storedFluid = new FluidStack[ALL_SLOT_COUNT];
I decided to keep raw FluidStacks, because the main IO operations are removing or setting the fluids itself. Extraction is performed on the raw stacks as well. Changing this would remove the wrapping code in the GUI, but then require unwrapping in `getStoredFluids`.

2023-10-14 18:07 UTC, GDCloudstrike commented
> @GDCloudstrike It would help filling the internal buffer to start faster as you are limited by input hatch size here. Also the hatch would pull all available fluids so you still have to have the right amount stored in a subnet. That is at least the functionality I would expect maybe with an upper limit so it doesnt completely drain your entire me if you are not careful. I would not expect it to only pull the right amount of fluid every time as this would really trivialize it. Or is there more to it that Im missing?

@Pelotrio 
If it can only pull up to max int at a time and cannot pull exact fluid amounts then it should probably be fine. What definitely should not happen is EOH suction getting even faster as that would exacerbate the 1 ticking issue and break it's frail 'balance' (or what's left of it) even more. 

Another thing I was worried about was that you could just put all the required fluid into a pattern and do a dual interface -> dual interface -> fluid storage -> stocking hatch setup and completely circumvent dummy item cycling, but it appears that interfaces in general cannot handle packet sizes larger than max int, so dummy items will be required regardless of the stocking hatch existing or not.

One more thought I had revolved around the humongous input hatch and how the stocking hatch would affect its use on the EOH and this is the conclusion I arrived at: 
If the stocking hatch truly cannot pull exact amounts then it wouldn't invalidate the usecase of humongous hatches on the EOH, but if it can then it absolutely would.

A bit unrelated to the EOH, but the humongous input hatch situation also made me think about hatch tiering in general, if the stocking hatch can pull 2 billion L of fluid then it would fully invalidate hatch progression above the tier the stocking hatch is unlocked. One could argue that this happened with the stocking bus and items too, but super buses were still a limiting factor because even the largest ones were too small (and the highest tier one was uhv). With fluids we already have properly tiered hatches going all the way to uxv that are sufficiently large for the tiers they are used/craftable in. Maybe it would make sense to have tiered stocking hatches that can pull a different maximum amount of fluid per operation to not just straight up make large hatches useless.

2023-10-15 02:57 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +                setResultIfFailure.accept(aware.endRecipeProcessing(this));
iirc spotless cannot handle it

2023-10-15 05:25 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +    protected final FluidStack[] storedFluid = new FluidStack[ALL_SLOT_COUNT];
ok

2023-10-15 05:27 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +                .controlsAmount(true)
This should be false

2023-10-15 05:27 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +                            tooltip.add(Text.localised("GT5U.machines.stocking_bus.cannot_set_slot"));
This line should be added only when auto-pull mode

2023-10-15 05:27 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +
Also showing the amount of fluid would be good

2023-10-15 14:13 UTC, tth05 commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +                .controlsAmount(true)
I did that to get the amount to render. I'm not sure if there's a proper way?
See https://github.com/GTNewHorizons/ModularUI/blob/master/src/main/java/com/gtnewhorizons/modularui/common/widget/FluidSlotWidget.java#L227

2023-10-15 14:18 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +                .controlsAmount(true)
Ah I see, it's ok

2023-10-15 15:35 UTC, miozune commented on src/main/java/gregtech/common/tileentities/machines/GT_MetaTileEntity_Hatch_Input_ME.java
> +                            tooltip.add(Text.localised("modularui.amount", fluid.amount));
`modularui.fluid.phantom.amount` to make it shown as liter

2023-10-15 23:21 UTC, miaowwwwww commented
just don't add support for EOH, it's getting reworked soooooon anyway. plus, it does makes the humongous hatch useless. by not effecting this balance, I expect the price to be not high, somewhat equivalent to stocking bus.

2023-10-16 01:32 UTC, miozune approved these changes
Thanks for your patience, now we can ship this feature in a good state.

2023-10-16 04:47 UTC, merged