A new approach for block updates in BaseMetaTileEntity
GTNewHorizons/GT5-Unofficial pull request #2342
Opened 2023-10-19 15:19 UTC by iamblackornot

This is my attempt to address the [flickering lag issue](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14625)
More details in the [comment](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14625#issuecomment-1770749144)

TLTR: needs tests on slow hardware

2023-10-20 12:01 UTC, Glease requested changes
beyond the small coding errors and the problem of missed updates, I'm not sure if this is the proper way to do it. for now please at least add a config option so people can disable this feature.

2023-10-20 12:37 UTC, iamblackornot commented on src/main/java/gregtech/api/objects/blockupdate/BlockUpdateHandler.java
> +            it.remove();
What kind of a miss? Like a request to update a block from a chunk, which is on cooldown? It will be stored in UpdateQueue (HashMap<ChunkCoordIntPair, WorldCoord>) till the cooldown ends, then processed

2023-10-20 15:06 UTC, iamblackornot commented on src/main/java/gregtech/api/objects/blockupdate/BlockUpdateHandler.java
> +            it.remove();
Appreciate your comprehensive response. I've decided to stick with a tick counter inside the BlockUpdateHandler

2023-10-20 15:07 UTC, iamblackornot commented on src/main/java/gregtech/api/objects/blockupdate/Cooldown.java
> +        return MinecraftServer.getServer()
Appreciate your comprehensive response. I've decided to stick with a tick counter inside the BlockUpdateHandler

2023-10-20 15:07 UTC, iamblackornot commented on src/main/java/gregtech/api/objects/blockupdate/RandomCooldown.java
> +    private Random random = new Random();
Done

2023-10-20 15:07 UTC, iamblackornot commented on src/main/java/gregtech/api/objects/blockupdate/RandomCooldown.java
> +            throw new InvalidParameterException("min length should be a positive non-zero number");
Done

2023-10-20 15:07 UTC, iamblackornot commented on src/main/java/gregtech/api/objects/blockupdate/BlockUpdateHandler.java
> +    protected class UpdateQueue extends HashMap<ChunkCoordIntPair, WorldCoord> {
Done

2023-10-21 08:40 UTC, Glease approved these changes
Given this now have a config, I'd say it's good enough to be merged.

2023-10-21 08:40 UTC, Glease commented on src/main/java/gregtech/api/objects/blockupdate/BlockUpdateHandler.java
> +            it.remove();
Oh I see.. Yes this won't cause any missed update. sorry for that.

2023-10-21 10:16 UTC, merged