Overloaded utility methods with more specific types
GTNewHorizons/GT5-Unofficial pull request #2357
Opened 2023-11-06 12:11 UTC by ghostflyby

　It’s non-sense passing every ItemStack as Object and check them with `instanceof ItemSack` again.

2023-11-06 13:03 UTC, leagris commented on src/main/java/gregtech/api/util/GT_Utility.java
> +
It is ok to overload with tighter typing, though the logic shall not be duplicated as it is a source of bugs when one need to adjust the logic later on.
The generic object version could call the typed version once it has tetermined that the object is of type `ItemStack`

2023-11-06 13:07 UTC, miozune commented
Please deprecate old ones

2023-11-06 13:08 UTC, leagris commented on src/main/java/gregtech/api/util/GT_Utility.java
> +    }
Possibly here too factorize logic at a single place

2023-11-06 13:17 UTC, leagris requested changes
Please try to factorize code logic to avoid duplicated logic in overloaded functions.

Also check the potential logic bug I commented in vararg ItemStack copy.

2023-11-06 13:24 UTC, miozune commented on src/main/java/gregtech/api/util/GT_Utility.java
> +        for (var tStack : aStacks) if (isStackValid(tStack)) return tStack.copy();
Isn't it intended? Return type is `ItemStack`, not `ItemStack[]`

2023-11-06 13:44 UTC, ghostflyby commented on src/main/java/gregtech/api/util/GT_Utility.java
> +        for (var tStack : aStacks) if (isStackValid(tStack)) return tStack.copy();
The original method was accepting `Object…` and only took the first ItemStack, but it has never been called with more than one object.

2023-11-06 14:48 UTC, ghostflyby commented
> Please deprecate old ones


Deprecating Object versions is causing warnings everywhere as many of the interfaces have been utilizing Objects, is that OK?

2023-11-06 15:05 UTC, leagris commented
> > Please deprecate old ones
> 
> Deprecating Object versions is causing warnings everywhere as many of the interfaces have been utilizing Objects, is that OK?

it is ok, warnings helps address the problem of calls to deprecated versions

2023-11-06 15:06 UTC, miozune commented
I think existing usages will be automatically transitioned to ItemStack version as soon as dep is updated?

2023-11-06 15:09 UTC, leagris commented
> I think existing usages will be automatically transitioned to ItemStack version as soon as dep is updated?

If adding proper javadoc tags, then some IDEs might be able to help automate the transition to the new methods, though it is not entirely automatic and will always require human to check or adjust parameters accordingly.

2023-11-08 00:26 UTC, merged

2023-11-08 11:45 UTC, leagris commented
@ghostflyby If you have some time for it:

Now that you've deprecated those methods, it would be helpful and courteous to fix the deprecated calls at least within the scope of GregTech. This would also serve as an example for other GTNH developers to fix calls in other mods afterward.

2023-11-08 11:57 UTC, ghostflyby commented
I’ll handle that.