fix lag caused by too much parallel
GTNewHorizons/GT5-Unofficial pull request #2358
Opened 2023-11-08 04:57 UTC by HoleFish

2023-11-08 05:00 UTC, BlueWeabo requested changes
The way you have done this will not allow for any recipes to work unless you always give enough items to go for the current parallel. There is a reason the variable in the method is called 'minParallel' and not 'maxParallel'

2023-11-08 05:05 UTC, BlueWeabo requested changes

2023-11-08 05:05 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +        int parallel=Integer.MAX_VALUE;
Instead of going for Integer.MAX_VALUE. you should be accepting the max possible parallels.

2023-11-08 05:05 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +                            currentParallel = Math.min(parallel, providedFluid.amount / recipeFluidCost.amount);
not assigning to correct variable

2023-11-08 05:05 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +                        currentParallel = Math.min(parallel, providedItem.stackSize / recipeItemCost.stackSize);
not assigning to correct variable

2023-11-08 05:05 UTC, BlueWeabo commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +                    if (!inputFound) {
this should prolly also check if you have enough fluid, cus it could've been found, but not had enough. that way an early return can also be done

2023-11-08 05:26 UTC, miozune reviewed
`isRecipeInputEqual` makes good use of `amountMultiplier` so that it won't simply loop over N times, so it should actually contribute to performance

2023-11-08 05:26 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +                SingleRecipeCheck builtCheck = tSingleRecipeCheckBuilder.setAfter(itemInputs, fluidInputs)
SingleRecipeCheck builder works by comparing inputs before and after consumption. This code simply makes it fail since no input has been consumed at this point.

2023-11-08 05:26 UTC, miozune commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +    public int maxParallelCalculatedByInput(FluidStack[] aFluidInputs, ItemStack... aInputs){
Since this method is essentially the same with `isRecipeInputEqual`, code duplication should be reduced here. Make `maxParallelCalculatedByInput` take the same arguments as `isRecipeInputEqual`, and make the latter simply return `parallel > 0`

2023-11-08 05:31 UTC, HoleFish commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +    public int maxParallelCalculatedByInput(FluidStack[] aFluidInputs, ItemStack... aInputs){
actually it should work like SingleRecipeCheck.checkRecipeInput, which needs recipemap so cannot work when SingleRecipeMachine is null

2023-11-10 12:52 UTC, Dream-Master commented
@HoleFish can you run spotless? thanks

2023-11-10 14:39 UTC, miozune commented on src/main/java/gregtech/api/util/GT_ParallelHelper.java
> +                recipe.consumeInput(1,fluidInputs,itemInputs);
Since most of the machines don't have ability to lock recipe, consuming `currentParallel` if recipe is not locked would almost double performance

2023-11-10 14:39 UTC, miozune commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +     **/
nit: Javadoc ends with `*/`

2023-11-10 14:39 UTC, miozune commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +    public double maxParallelCalculatedByInputs(int maxParallel, FluidStack[] aFluidInputs, ItemStack... aInputs) {
Putting mention on being inspired by `SingleRecipeCheck#checkRecipeInputs` would be nice

2023-11-11 06:29 UTC, BlueWeabo reviewed
Logic works and won't break anything.

2023-11-11 06:31 UTC, HoleFish commented
bug exists.Trying to fix.

2023-11-11 21:03 UTC, BlueWeabo approved these changes

2023-11-11 21:06 UTC, Dream-Master commented
@miozune if this pr is ok feel free to merge it. Thanks

2023-11-12 03:02 UTC, miozune approved these changes
Thanks for your contribution, great work!

2023-11-12 03:03 UTC, merged