Add connect/block to line of pipes
GTNewHorizons/GT5-Unofficial pull request #2407
Opened 2023-12-18 23:54 UTC by LewisSaber

With ctrl mode it will only connect to other pipes
![java_W6qUbhzGj6](https://github.com/GTNewHorizons/GT5-Unofficial/assets/39595617/e4716721-67a6-495d-8fd9-b22007289219)
![java_8E4Qwv0Mmc](https://github.com/GTNewHorizons/GT5-Unofficial/assets/39595617/88fbe60a-3f35-499a-9cad-8830f8a32ab0)
It will not disconnect pipes in line if you are doing connect
![java_iXbUFHRZ7x](https://github.com/GTNewHorizons/GT5-Unofficial/assets/39595617/4aee53e7-d353-426d-a50f-35d1180f9541)
It works the same with blocking of pipes

2023-12-19 08:35 UTC, Dream-Master commented
Can the pipe looked . For me it looks like you can disconnect stuff very easy even by accident . Why you against use a wrench?

2023-12-19 09:18 UTC, LewisSaber commented
For this feature to activate you need both wrench and holding ctrl key
Wrench is barely visible on gifs cuz that would increase their size, sorry for misleading

2023-12-19 10:17 UTC, miozune requested changes

2023-12-19 10:17 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +            if (!Keyboard.isKeyDown(Keyboard.KEY_LCONTROL)) {
You can't use `Keyboard` on server, otherwise it causes server to crash whenever wrenching pipes. You somehow need to tell server that player is holding control.

2023-12-19 10:40 UTC, OneEyeMaker requested changes

2023-12-19 10:40 UTC, OneEyeMaker commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +    public void blockPipeOnSide(ForgeDirection side, EntityPlayer entityPlayer, byte tMask) {
Please be consistent with naming: either use `aParameter` for every argument or don't use prefixes (`mask`).

2023-12-19 10:40 UTC, OneEyeMaker commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +                IGregTechTileEntity nextPipeBase = (IGregTechTileEntity) nextPipeBaseTile;
Hello, my dear `ClassCastException`!
`getTileEntityAtSide` returns regular TileEntity, not `IGregTechTileEntity`.

2023-12-27 19:05 UTC, OneEyeMaker approved these changes

2023-12-28 02:18 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +                for (int painted = 0; painted < limit; painted++) {
Maybe use different name?

2023-12-28 02:18 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +                    if (nextPipeBaseTile == null) {
Null is checked by instanceof

2023-12-28 02:18 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +                    if (!(nextPipeBaseTile instanceof IGregTechTileEntity)) {
Pattern matching is useful, `!(nextPipeBaseTile instanceof IGregTechTileEntity nextPipeBase)`

2023-12-28 10:49 UTC, miozune commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +                for (int painted = 0; painted < limit; painted++) {
I mean `painted` is copy-paste from spray can right?
And config name could be misinterpreted as "Max number of pipes that can connect each other", how about `PipeWrenchingChainRange`?

2023-12-28 12:42 UTC, miozune commented
And what about `painted`?

2023-12-28 13:03 UTC, miozune approved these changes

2023-12-28 13:37 UTC, merged