Add Drone Centre
GTNewHorizons/GT5-Unofficial pull request #2412
Opened 2023-12-20 03:19 UTC by RealSilverMoon

See [GTNewHorizons/GT-New-Horizons-Modpack#14972](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14972)
The old PR seems broken so i have to open a new one, sorry!

2023-12-26 07:47 UTC, RealSilverMoon commented
Code work seems done. This machine is fine to review now.

2023-12-29 14:43 UTC, Hikari1nVoid requested changes
Downsides for this multi has been too cruel for everyone.

2023-12-29 14:43 UTC, Hikari1nVoid commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_Hatch_DroneDownLink.java
> +                    // Let's have some "surprise".
Please,no surprise needed here:(

2023-12-29 16:39 UTC, RealSilverMoon commented
Great there are no debuff now. If centre offline it just lost every control function and will not maintain machine actively.
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/31100241/a10ff6f1-3d65-4992-9920-aa35d02a485e)

2024-01-01 06:24 UTC, Hikari1nVoid commented
Not working.
Lmk if I have anything misconfigured.
Test bench:ZETA PDIM_201 with nightly-290.

2024-01-01 11:24 UTC, Hikari1nVoid requested changes
Osmium fluid cells non-stackable.Which prevented me from crafting T2 drones.

2024-01-01 15:25 UTC, RealSilverMoon commented
All confirmed and fixed. Have fun with new year and new drones now~!

2024-01-01 15:54 UTC, Dream-Master commented
Will make new nightly soon

2024-01-14 08:49 UTC, Hikari1nVoid commented
Bug:I can still remote access machines after DC shuts down.

2024-01-24 01:33 UTC, Hikari1nVoid approved these changes
I have no more counterpoint for this.

2024-01-24 09:56 UTC, Dream-Master commented
@GTNewHorizons/developers we need here a code review. Thanks

2024-01-24 17:46 UTC, BlueWeabo reviewed
Overall good job on the multiblock, but there are some stuff to fix and to be explained.

2024-01-24 17:46 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_Hatch_DroneDownLink.java
> +    public Vec3Impl vec3;
Can you explain what this Vec3 is being used for? Maybe add as a comment or rename the variable. Also if possible don't make it public unless absolutely necessary, using a method making it public would be better.

2024-01-24 17:46 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/droneConnection.java
> +public class droneConnection {
PascalCase the class name

2024-01-24 17:46 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_Hatch_DroneDownLink.java
> +        connection.machine.mWrench = connection.machine.mScrewdriver = connection.machine.mSoftHammer = connection.machine.mHardHammer = connection.machine.mCrowbar = connection.machine.mSolderingToo
[nit] I understand the need to be compact, but this really gets confusing to read.

2024-01-24 17:46 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_Hatch_DroneDownLink.java
> +    public boolean tryFindConnection() {
if possible explain how it find the location in a comment, as I am having a hard time understanding how its being done....

[nit] don't make something public if its not needed to be public.

2024-01-24 17:46 UTC, BlueWeabo commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_DroneCentre.java
> +    public Vec3Impl vec3;
what is it? what is it used for?

[nit] no need to be public, unless needed (for all variables, better to have methods for getting said variable instead of calling it directly)

2024-01-25 03:32 UTC, RealSilverMoon commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_Hatch_DroneDownLink.java
> +    public Vec3Impl vec3;
It stored coordinate. The withinDistance() method in Vec3Impl is used to avoid spam code. Renamed to coordinate.

2024-01-25 03:37 UTC, RealSilverMoon commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_DroneCentre.java
> +    public Vec3Impl vec3;
Well it should has a animation on machine but i forgot to draw it... anyway just delect it.

2024-01-25 04:42 UTC, Ethryan commented
This whole Drone Centre thing isn’t really my favorite way of implementing something like this.

A better way in my opinion would be a Wireless Control Station multiblock, perhaps 5x5x5 with the nine blocks in the middle being a mix of (New Block) Wireless Signal Booster and (New Block) Wireless Computational Core. 

With the Signal Booster block increasing the range of the working area, and the Computational Core increasing the maximum number of multis that can be used. In my vision of this you would still need a Wireless Multiblock Connector to connect it to the network.

This is just my opinion on this, but I wanted to put it out there.

2024-01-25 04:52 UTC, RealSilverMoon commented
> This whole Drone Centre thing isn’t really my favorite way of implementing something like this.
> 
> A better way in my opinion would be a Wireless Control Station multiblock, perhaps 5x5x5 with the nine blocks in the middle being a mix of (New Block) Wireless Signal Booster and (New Block) Wireless Computational Core.
> 
> With the Signal Booster block increasing the range of the working area, and the Computational Core increasing the maximum number of multis that can be used. In my vision of this you would still need a Wireless Multiblock Connector to connect it to the network.
> 
> This is just my opinion on this, but I just wanted to put it out there.

Sounds more suitable as a MuTes. And wireless is not enough- the **Drone** Centre emphasize on maintain multiblock, the control function was added later on. Still a good idea when we are ready to switch to mutes, because mutes doesn't has maintenance hatch or such function at all...

2024-01-25 14:18 UTC, Connor-Colenso submitted a review, later dismissed
The textures need to be made into a 16x16 format, these are very out of place and not fitted to minecrafts style.

2024-01-31 13:27 UTC, RealSilverMoon commented
New texture here！ Thanks to the author: Graymare@https://github.com/Graymare

2024-01-31 16:10 UTC, BlueWeabo approved these changes
Thanks for your work. The code looks fine. (Personally not sure on the balance)

2024-01-31 17:15 UTC, merged