More detailed Fusion Reactor recipes NEI info
GTNewHorizons/GT5-Unofficial pull request #2418
Opened 2023-12-21 13:41 UTC by HoleFish

![000](https://github.com/GTNewHorizons/GT5-Unofficial/assets/48403212/80cd4167-07e6-42eb-8481-5546414298d4)
More convenient for players to calculate overclock.

2023-12-21 17:43 UTC, Dream-Master commented
@HoleFish guess the nei gui need to make a big bigger to hold all this info.

2023-12-22 01:53 UTC, miozune commented
I think having two startup tier could be confusing. Doesn't recipe catalyst calculate overclock for you?

2023-12-22 02:28 UTC, HoleFish commented
The old MK confused 'voltage tier' with 'capable tier'. Actually it has nothing to do with 'overclocking tier', which has confused a lot of players.(see discussion [here](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13739))

2023-12-22 04:42 UTC, miozune commented
I think I understand the situation now. Then how about appending `startupTier` to `Start:` property and using `startupTierForOverclock` to show "Higher tier machine than MkX can overclock" (or "This recipe cannot be overclocked") instead? I think that's more intuitive

2023-12-22 04:47 UTC, miozune reviewed
You can use `neiHandlerInfo` for recipemap to increase height of NEI display

2023-12-22 04:47 UTC, miozune commented on src/main/java/gregtech/nei/formatter/FusionSpecialValueFormatter.java
> +        if (startupPower <= 160000000) {
Use underscore to make them more readable: `160_000_000`

2023-12-22 10:45 UTC, HoleFish commented
![001](https://github.com/GTNewHorizons/GT5-Unofficial/assets/48403212/40708e36-ac69-48eb-bdaa-da3a03d12320)
Now NEI displays these (if there's no error in my code)

2023-12-22 13:21 UTC, miozune commented on src/main/java/gregtech/api/objects/overclockdescriber/FusionOverclockDescriber.java
> +    protected final int tier;
This is the exact copy of `OverclockDescriber#tier`, you can use it instead

2023-12-22 13:21 UTC, miozune commented on src/main/java/gregtech/api/objects/overclockdescriber/FusionOverclockDescriber.java
> -        byte tier = GT_Utility.getTier(recipe.mEUt);
Any reason for removing this? e.g. Mk1 cannot handle titanium or oxygen plasma due to their voltage but they'll show up this way

2023-12-22 13:36 UTC, HoleFish commented on src/main/java/gregtech/api/objects/overclockdescriber/FusionOverclockDescriber.java
> -        byte tier = GT_Utility.getTier(recipe.mEUt);
An opposite example is that Compact Fusion MK4 can do Th/Pb/Pu-241 plasma, however they won't show up in MK4 map also due to their voltage. So I decide to show them all.
There may be a better way to deal with this conflict, but I don't quite have any idea.

2023-12-22 13:39 UTC, chochem commented
This looks all wrong. There arent three different tiers for fusion recipes.

2023-12-22 13:41 UTC, miozune commented on src/main/java/gregtech/api/objects/overclockdescriber/FusionOverclockDescriber.java
> -        byte tier = GT_Utility.getTier(recipe.mEUt);
You can set custom OverclockDescriber for compacts in GG code.
Oh also, GT++ sets its own describer `AdvancedFusionOverclockDescriber`, so `if(tier>8)` for `getEUtIncreasePerOC` and `getDurationDecreasePerOC` are not needed if you set them differently for `LargeFusionComputerPP`.

2023-12-23 09:36 UTC, miozune approved these changes

2023-12-23 09:36 UTC, miozune commented
@chochem Did you read the code? There are actually 3 factors to account for when making plan for compact fusions

2023-12-23 09:40 UTC, chochem commented
But the player makes normal fusion first, not compact. This new page is terrible and confusing for players getting to know fusion.

2023-12-23 09:58 UTC, HoleFish commented
The old MK says Rhugnor recipe is MK4, however it can never be overclocked even in Compact MK5. That's what's even more confusing. At least NEI should tell players how it actually works instead of hiding all information about overclocking in the code.

2023-12-23 10:01 UTC, chochem commented
It tells you the needed tier and is correct. Also the numbers to calculate OCS. Nothing is hidden in the code.

2023-12-23 10:18 UTC, chochem requested changes
These changes are incorrect/misleading for normal fusion reactors which is what the page is for. Special info about compacts has to go somewhere else.

2023-12-23 10:19 UTC, Dream-Master commented
I guess compact and normal fusion use the same recipe map? maybe we need to change that ?

2023-12-23 10:30 UTC, HoleFish commented
Rhugnor problem exists in both normals and compacts. You cannot overclock Rhugnor recipe also in normal MK5. It's not sepcial.

2023-12-23 10:41 UTC, chochem commented
sounds more like a bug than a documentation gap

2023-12-26 13:01 UTC, Dream-Master commented
@chochem so what is about this ?

2023-12-26 13:08 UTC, chochem commented
maybe draft for now. we still need some change (code/tooltip/nei/... ?) for compacts.

2024-01-29 18:09 UTC, closed without merging