Make some changes to OC Calculator to add functionality to be used by God Forge
GTNewHorizons/GT5-Unofficial pull request #2508
Opened 2024-02-25 22:36 UTC by BlueWeabo

Allows one to directly put in a double to have an OC like 4.1 of energy increase or 2.1 duration decrease.

This allows a for a bit more customization and upgrades for the future of multiblock

2024-02-25 23:13 UTC, GDCloudstrike approved these changes
Thanks

2024-02-26 02:57 UTC, miozune requested changes
I think we should deprecate old integer methods to reduce confusion. Also I'd guess your editor has _strong_ opinion on max amount of characters per line...

2024-02-26 06:46 UTC, miozune commented on src/main/java/gregtech/api/util/GT_OverclockCalculator.java
> +    @Deprecated
In general adding `@deprecated` javadoc with describing what alternative should be used, would be the right way to apply `@Deprecated` annotation

2024-02-26 07:00 UTC, miozune approved these changes
Thanks for addressing my nitpicks

2024-02-26 07:04 UTC, BlueWeabo commented
Good to have then especially when i had written everything at midnight thinking it was a 10 min job turning into 1 hour :clueless:

2024-02-26 12:30 UTC, merged