Show the reason why the machine shutdown on DC
GTNewHorizons/GT5-Unofficial pull request #2536
Opened 2024-03-13 07:43 UTC by RealSilverMoon

Since we have ShutDownReason now, why not show them on the Drone Center?
![5](https://github.com/GTNewHorizons/GT5-Unofficial/assets/31100241/43229ac7-587d-4b51-8c20-444e51c1a2d3)

2024-03-13 09:00 UTC, HoleFish requested changes

2024-03-13 09:00 UTC, HoleFish commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_DroneCentre.java
> +                        coreMachine != null && coreMachine.shouldDisplayShutDownReason()
`setEnabled(boolean)` will be called only once so that it gets no update when gui is open. Use `setEnabled(Function)`

2024-03-13 09:09 UTC, HoleFish commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_DroneCentre.java
> +                        coreMachine != null && coreMachine.shouldDisplayShutDownReason()
So are many other places such as line 440, 472 and 504

2024-03-13 11:49 UTC, RealSilverMoon commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_DroneCentre.java
> +                        coreMachine != null && coreMachine.shouldDisplayShutDownReason()
`setEnabled(Function)` will be called on **every render tick**. Not sure if this would cause performance issues.

2024-03-13 15:50 UTC, RealSilverMoon commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_DroneCentre.java
> +                        coreMachine != null && coreMachine.shouldDisplayShutDownReason()
OK let's havse a try. Seems it works well!

2024-03-15 06:41 UTC, HoleFish approved these changes

2024-03-15 06:43 UTC, Dream-Master commented
it is a feature but after the shutdown mechanism is in the pack let this go into 2.6.0 as well

2024-03-15 06:43 UTC, merged