Fix AL crash with ME hatches
GTNewHorizons/GT5-Unofficial pull request #2566
Opened 2024-04-11 14:51 UTC by HoleFish

For example:
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/48403212/aca15e3a-87d0-4c78-a2ba-ec55fff819b2)
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/48403212/7cf3e844-de63-46da-97b5-983e70e72bb0)
Result:
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/48403212/b9195d6f-187a-4ee8-ab2e-0871d22e39f1)
This pr tries to fix it.

2024-04-11 20:51 UTC, Laiff requested changes

2024-04-11 20:51 UTC, Laiff commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_AssemblyLine.java
> +                if (item != null) {
This check broke rule of basic AL logic: items should be stored in right slot. Can you add inputs order in ME cache and try to consume it from only one index not from whole map?

2024-04-11 20:51 UTC, Laiff commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_AssemblyLine.java
> +                if (fluid != null) {
Same here

2024-04-12 03:45 UTC, HoleFish commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_AssemblyLine.java
> +                if (fluid != null) {
Fluids have never had such a rule. Their only requirement is to be in seperate hatches.

2024-04-12 04:15 UTC, HoleFish commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_AssemblyLine.java
> +                if (item != null) {
ME cache map has no order and should not have. ME bus just checks the item in the first stocking slot, pulls it from net storage (the map) and consumes it.

2024-04-12 07:25 UTC, Laiff commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_AssemblyLine.java
> +                if (fluid != null) {
It is same rule

2024-04-12 07:26 UTC, Laiff commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_AssemblyLine.java
> +                if (item != null) {
Ok it also can works

2024-04-12 07:43 UTC, HoleFish commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_AssemblyLine.java
> +                if (fluid != null) {
not the rule the old code implied. ok I will fix it if you want

2024-04-13 08:58 UTC, HoleFish commented
Should be careful. Have been suffering from ME input buses/hatches.

2024-04-13 13:48 UTC, Laiff approved these changes

2024-04-13 14:03 UTC, merged