Add plascrete block as an exception
GTNewHorizons/GT5-Unofficial pull request #2591
Opened 2024-05-06 03:20 UTC by RealSilverMoon

Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16127

2024-05-06 09:04 UTC, RealSilverMoon commented
Also add a sort button:
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/31100241/2a330072-19df-47ad-bc2d-5b657b238cdb)
You can sort all machines by name, distance, or if it's shutdown.

2024-05-10 10:13 UTC, NotAPenguin0 requested changes
Overall fine, just a few minor details that should probably be looked at before merging

2024-05-10 10:13 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/DroneConnection.java
> +    public float getDistance() {
Minor nitpick but I would rename this to `getDistanceSquared()` to better indicate what it actually does

2024-05-10 10:13 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_DroneCentre.java
> +            .addInfo("Range is determined by drone tier: T1-128, T2-512, T3-4096")
Is this an intentional buff to the drone centre or just clarifying values?

2024-05-10 10:13 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_DroneCentre.java
> +            case 1 -> 128;
Also see above

2024-05-10 10:13 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_Hatch_DroneDownLink.java
> +                || (block == GregTech_API.sBlockReinforced
Add a comment explaining this check for future reference.

2024-05-10 11:28 UTC, RealSilverMoon commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_DroneCentre.java
> +            .addInfo("Range is determined by drone tier: T1-128, T2-512, T3-4096")
Yes it's a buff. Have seen too many complains about the expensive drones and their narrow range.

2024-05-10 11:28 UTC, RealSilverMoon commented on src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_Hatch_DroneDownLink.java
> +                || (block == GregTech_API.sBlockReinforced
done.

2024-05-10 11:39 UTC, NotAPenguin0 approved these changes

2024-05-10 11:42 UTC, merged