add covers that can hold some items
GTNewHorizons/GT5-Unofficial pull request #2593
Opened 2024-05-11 20:25 UTC by Glease

This cover allows player to store a small amount of item alongside a machine. The intended use case is for steam to EV player to store extruder shapes and alloy smelter shapes inside the machine. The cover GUI system would then allow player to retrieve the items right from the machine GUI. To facilitate this goal and not make this cover some generic diamond chest, the current line up impose a 1 item per stack limit. 

While this demo showcased a 3-slot gui, the submitted PR contains a 3x3 cover instead. The code is structured in a way that the slot count can be tweaked freely without writing any significant code. Multiple cover with different slot count can also be added to game at the same time.

Depends on [this bugfix PR in modular UI](https://github.com/GTNewHorizons/ModularUI/pull/75) to work correctly, but does not require that one to be compiled.

TODO:
- [x] basic implementation
- [ ] find item texture
- [ ] find cover texture (what is displayed when it's placed on a machine)
- [ ] determine the tiering
- [ ] ensure the meta item id isn't used by something else in fullpack

2024-05-11 20:33 UTC, eigenraven commented on src/main/java/gregtech/common/covers/GT_Cover_Chest.java
> +        return new ChestUIFactory(buildContext).createWindow();
Is there a way to force this window to spawn left/right of the main window, so you don't have to drag it around to use it every time?

2024-05-11 20:36 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_Chest.java
> +        return new ChestUIFactory(buildContext).createWindow();
this is on the todo list. from what I gathered it *is* possible to place it at a fixed location on the left. The necessary context containing parent window seems to be missing here, so I cannot place it at `max(0, parentWindow.guiLeft - thisWindow.width)`.

2024-08-04 10:45 UTC, Dream-Master commented
@Glease feel free to set it undraft when its done.

2024-08-13 10:15 UTC, Glease commented
![gui](https://github.com/user-attachments/assets/682827ce-d346-4e66-b7d4-db5ebcbab4f2)
![in world](https://github.com/user-attachments/assets/799b0c5e-afac-4a08-88e2-308123af5a7b)

image credit @ wilybit on discord. 
Unfortunately I'm unable to make the cover icon in gui to switch depending on whether the window is open without substantial refactor

2024-08-14 02:41 UTC, Nxer requested changes
![image](https://github.com/user-attachments/assets/5b2690bd-a117-46f9-87c4-598a34c3caf6)

It will open a wrong UI when shift right click the cover side on machine block.

2024-08-14 02:45 UTC, Nxer commented
And when break the machine block, the items in cover will drop in world, but re-place the machine(with these covers), there still are items in cover's inventory.

2024-08-14 03:01 UTC, YannickMG commented
Only somewhat related: I always wished the crafting table cover held an inventory as that would've made it somewhat useful. As it is it behaves like a vanilla crafting table in that all items you place in it are expelled when you close the UI.

If you think it would make sense to upgrade the crafting table cover to hold an inventory then you might balance this new "chest cover" alongside it.

2024-08-15 02:07 UTC, Nxer commented
![image](https://github.com/user-attachments/assets/c6e6ff27-3d94-452c-b56b-105f3ec51863)
Would it be convenient to add an player inventory UI when opening this UI ?

2024-08-17 16:59 UTC, Nxer approved these changes
Worked well. Good stuff for hand-crafting masters.

2024-08-17 18:43 UTC, merged