Leaves, Breads and Pizzas re texture
GTNewHorizons/GT5-Unofficial pull request #2606
Opened 2024-05-23 18:26 UTC by BlueHero233

To make leaves not identical and some other foodstuffs

2024-05-23 18:26 UTC, boubou19 approved these changes

2024-05-24 01:15 UTC, Ethryan commented
Beautiful!

2024-05-24 08:27 UTC, LazyFleshWasTaken commented
I love you

2024-05-24 09:06 UTC, leagris commented
One issue though,with leaves/beries/fruits items. They are no longer like their block crop counterpart.
Would you edit the block texture for those so the leaves, fruits are same on the item and crop blocks?

2024-05-24 09:26 UTC, leagris requested changes
Could you please try to also texture the corresponding blocks crop textures so they match their item counterpart?

Example with Indigo:

Indigo leaves item
Deleted ![old](https://raw.githubusercontent.com/GTNewHorizons/GT5-Unofficial/79d72d365441583801a649c23928b1a01fd2341b/src/main/resources/assets/gregtech/textures/items/gt.metaitem.02/502.png)
Added ![new](https://raw.githubusercontent.com/GTNewHorizons/GT5-Unofficial/3ccacc49c68d6f807ae353f2778849f64cc3bb33/src/main/resources/assets/gregtech/textures/items/gt.metaitem.02/502.png)
no longer look like the block crop texture ![](https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/resources/assets/ic2/textures/blocks/crop/blockCrop.Indigo.4.png?raw=true)

Same issue with multiple leaves/fruit items

2024-05-24 09:26 UTC, leagris commented on src/main/resources/assets/gregtech/textures/items/gt.metaitem.02/502.png
Indigo leaves item
Deleted ![old](https://raw.githubusercontent.com/GTNewHorizons/GT5-Unofficial/79d72d365441583801a649c23928b1a01fd2341b/src/main/resources/assets/gregtech/textures/items/gt.metaitem.02/502.png)
Added ![new](https://raw.githubusercontent.com/GTNewHorizons/GT5-Unofficial/3ccacc49c68d6f807ae353f2778849f64cc3bb33/src/main/resources/assets/gregtech/textures/items/gt.metaitem.02/502.png)
no longer look like the block crop texture ![](https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/resources/assets/ic2/textures/blocks/crop/blockCrop.Indigo.4.png?raw=true)

Same issue with multiple leaves/fruit items

2024-05-24 23:27 UTC, BlueHero233 commented on src/main/resources/assets/gregtech/textures/items/gt.metaitem.02/502.png
Added stages 4 and 3 for all modified crops

2024-05-24 23:32 UTC, BlueHero233 commented
> One issue though,with leaves/beries/fruits items. They are no longer like their block crop counterpart. Would you edit the block texture for those so the leaves, fruits are same on the item and crop blocks?

Done

2024-05-26 10:41 UTC, leagris approved these changes
Ok good. Thank you @BlueHero233 for all those nice civilized textures

2024-05-26 12:49 UTC, merged