Beamline
GTNewHorizons/GT5-Unofficial pull request #2619
Opened 2024-05-25 14:58 UTC by eigenraven

Port of https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/31

2024-05-27 19:30 UTC, Elisis commented
Technically ready for testing so I'm going to remove the Draft status

2024-05-27 19:31 UTC, chochem commented
can you add some overview/description/etc in that case?

2024-05-27 20:04 UTC, Elisis commented
### General
Adds a particle physics system that supports a number of particle types and four new multiblocks for the production and use of said particles.
Technically, functions in a similar way to the TecTech quantum computer, with data packets representing particle beams transmitted through Beamline Pipes. 
Each particle beam has four properties:
- Particle type: Determines what recipes can be done using the beam. For example, for photolithography, only photon-bearing beams are able to be used in recipes. 
- Energy: Energy of the particles, must be within a certain range for each recipe
- Focus: How precise the beam is, must be above some threshold set by each recipe. Tends to decrease the more multiblocks the beam runs through.
- Amount/Rate: A representation of the number of particles being transmitted through the beam in some unit time. Determines recipe length.

### Multiblocks
- Source Chamber: Chief producer of particles, the start of the line. Output particle energy scales with EU to an extent determined by each recipe, with other properties similarly defined by the recipe. For example, the current tungsten rod recipes has moderate EU energy scaling with a high output particle focus (98), a maximum energy value of 1000keV and an amount of 20. 
- LINAC: Linear Accelerator, requires EU and coolant to accelerate charged particles to energies determined by the (variable) length of the multi. An increase in length also results in a decrease in focus, as well as an increase in coolant consumption, meaning that players are meant to balance aspects of the machine to suit the situation. Output energy can also be increased by increasing input EU. Focus can also be improved by decreasing the temperature of the coolant. Currently the four supported coolants are LO2, LN2, IC2 coolant, and Super Coolant, in order of efficacy. Has no recipemap.
- Synchrotron: Only produces photons from charged particles. Similar to the LINAC, changes in input EU and coolant affect output focus and energy. Also possesses antenna casings, currently two-tiered, which dramatically affects energy-EU scaling. Has no recipemap.
- Target Chamber: Currently only used for photolithography, intended to be the endpoint for most lines. Recipes for this can include a target item, and optionally a focus item, a photolithographic mask in the case of wafer production. This effectively boils down to hitting the target with particles from the input. Doesn't scale whatsoever with input EU, barring a minimum requirement. Can define an acceptable input particle energy range, minimum focus, and amount. This amount value is used to calculate the length of the recipe, depending on the rate value of the input beamline.

2024-05-27 20:05 UTC, Elisis commented
Might have to revise it, it's currently 4am so not sure if it's too legible 😅

2024-05-27 20:22 UTC, Elisis commented
Source Chamber:
![2024-05-28_04 18 58](https://github.com/GTNewHorizons/GT5-Unofficial/assets/28530295/b10f7451-0414-45cf-855f-9616c1f84664)
![2024-05-28_04 19 02](https://github.com/GTNewHorizons/GT5-Unofficial/assets/28530295/87ed1f2b-7ebc-4fe8-b939-ad6391a39676)
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/28530295/c5daceb2-3e41-4bf8-977f-4ad4fd6d22f1)

LINAC:
![2024-05-28_04 19 19](https://github.com/GTNewHorizons/GT5-Unofficial/assets/28530295/97168f35-6ee0-4ab7-a6ca-3c69c6a6c843)
![2024-05-28_04 19 37](https://github.com/GTNewHorizons/GT5-Unofficial/assets/28530295/5e0a89f8-1ecc-4a10-9277-bafad8339321)

Synchrotron:
![2024-05-28_04 19 48](https://github.com/GTNewHorizons/GT5-Unofficial/assets/28530295/ff96f980-dfbc-4e03-bb7d-47d7951b8cfd)
![2024-05-28_04 19 57](https://github.com/GTNewHorizons/GT5-Unofficial/assets/28530295/4e95e0dc-810b-4d75-bdbe-d9722f16dbdf)

Target Chamber:
![2024-05-28_04 20 06](https://github.com/GTNewHorizons/GT5-Unofficial/assets/28530295/c3569dfe-a23f-471e-b551-16629620d636)
![2024-05-28_04 20 09](https://github.com/GTNewHorizons/GT5-Unofficial/assets/28530295/ba5da1e5-8005-4da6-96e3-b423a38b2239)
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/28530295/a5b34d48-22a8-4d59-b491-993dbb68e296)

2024-05-30 05:25 UTC, Elisis commented
> You said the target chamber does not scale with EU whatsoever. How do you speed it up to make sure it can reach endgame level speeds?

You increase the Amount of particles in the beam used as input. Current it takes 10s per recipe per integer multiple of Recipe Amount over Beam Amount, but that can be changed pretty easily. Even if the current Source Chamber items don't produce enough, more exotic ones with larger Amount outputs can be added as well. I've got it so that large batches of wafers can be produced using higher tier wafers, and I can probably make it so that the Amount specified doesn't scale linearly with the number of output wafers

2024-05-30 22:03 UTC, NotAPenguin0 reviewed
Is it intentional that the controllers and hatches don't use the casing textures?

2024-05-30 23:26 UTC, Elisis commented
> Is it intentional that the controllers and hatches don't use the casing textures?

Mainly was just a pain to add custom blockicons. Plus the blocks that neighboured the hatches differed between multis so GT casings seemed to fit

2024-06-01 15:13 UTC, NotAPenguin0 requested changes
Balancing and some minor nitpicks aside, the code looks mostly good to me. What I would like to see done to get this merged:

- A proper comparison of EU/t, speed, resource usage and amount of machines of the beamline versus traditional laser engraver setups (LPF, PA), in early tiers (ZPM, UV) and for lategame setups (UMV+).
- Perhaps a nightly build so Zeta/beta testers can do some QA testing and find possible bugs
- The hatches and controllers that are next to regular casings really should use the casing textures in my opinion.

2024-06-01 15:13 UTC, NotAPenguin0 commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/Synchrotron.java
> +        FluidStack primaryFluid = fluidList.get(0);
Same comment about coolant as with the LINAC. Does this not allow players to put in any fluid even if it's not in the coolant map?

2024-06-01 15:13 UTC, NotAPenguin0 commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/Synchrotron.java
> +        int fluidConsumed = 32_000; // Amount of fluid consumed per operation, maybe increase with EU/t
Since this value is documented in the tooltip, would be nice to extract it into a static so it can be balanced without having to change it in multiple locations.

2024-06-01 15:13 UTC, NotAPenguin0 commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/Synchrotron.java
> +            || (!primaryFluid.isFluidEqual(FluidRegistry.getFluidStack("ic2coolant", 1)) && primaryFluid.getFluid()
This logic already exists somewhere else, perhaps move it into a helper function to avoid duplicate code?

2024-06-01 15:13 UTC, NotAPenguin0 commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/Synchrotron.java
> +        if (Objects.isNull(fluidOutput)) return false;
If the input fluid was not in the coolant map, it gets consumed but you get nothing back and the recipe fails. I think it would be more user-friendly if the multi just reported an error saying no valid coolant was found.

2024-06-01 15:13 UTC, NotAPenguin0 commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/Synchrotron.java
> +    private BeamInformation getInputInformation() {
Already addressed this function in another file, but since it is exactly the same logic it can maybe be extracted into a helper function somehow?

2024-06-01 15:13 UTC, NotAPenguin0 commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/TargetChamber.java
> +        this.mMaxProgresstime = Math.round((tRecipe.amount / inputRate * 10 * 20)); // 10 seconds per integer multiple
```suggestion
        this.mMaxProgresstime = Math.round((tRecipe.amount / inputRate * 10 * SECONDS)); // 10 seconds per integer multiple
```

2024-06-01 15:13 UTC, NotAPenguin0 commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/TargetChamber.java
> +    private BeamInformation getInputInformation() {
See previous comments on Synchotron and LINAC.

2024-06-01 15:13 UTC, NotAPenguin0 commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/recipe/beamline/BeamlineRecipeLoader.java
> +
Random suggestion, maybe add some advanced coolants like spacetime that give a bonus?

2024-06-01 15:13 UTC, NotAPenguin0 commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/recipe/beamline/BeamlineRecipeLoader.java
> +            new ItemStack[] { Materials.Uranium.getDustTiny(1) },
Tiny dusts are a bit annoying to work with, would it be possible to change it to a full dust and generate 9x output in 9x more time?

2024-06-01 17:53 UTC, Elisis commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/LINAC.java
> +        FluidStack primFluid = tFluidInputs.get(0);
Well there's no real reason to use a stocking hatch with both valid and invalid coolants imo, so this shouldn't break much

2024-06-01 17:56 UTC, Elisis commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/LINAC.java
> +        for (TileHatchInputBeamline in : this.mInputBeamline) { // Easy way to find the desired input. Efficient? No.
This kinda works as a template for newer multis that do have multiple input beamline hatches, so I left it

2024-06-01 17:58 UTC, Elisis commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/LINAC.java
> +        length += 8;
All the math's done with the internal length variable, but the players only really see the actual length ingame

2024-06-01 17:59 UTC, Elisis commented on src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
> +import static gregtech.api.enums.MetaTileEntityIDs.*;
I think this was a holdover from an older commit? This definitely isn't intentional

2024-06-01 18:03 UTC, Elisis commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/SourceChamber.java
> +    // TODO: Variable recipe duration
More of a reminder than a TODO tbh, can probably just remove it

2024-06-01 18:10 UTC, NotAPenguin0 commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/LINAC.java
> +        for (TileHatchInputBeamline in : this.mInputBeamline) { // Easy way to find the desired input. Efficient? No.
That makes sense yeah. Nothing wrong with keeping it then.

2024-06-01 18:11 UTC, Elisis commented
> A proper comparison of EU/t, speed, resource usage and amount of machines of the beamline versus traditional laser engraver setups (LPF, PA), in early tiers (ZPM, UV) and for lategame setups (UMV+).

I've got an Excel sheet of some data I've collected for the lower end setups, but comparisons to traditional recipes I'm not so sure about, honestly might be better to leave to nightly players to mess around with?

2024-06-01 18:13 UTC, NotAPenguin0 commented
I can see if I can find some time in the next days to try to make a large scale setup viable for endgame bases to see if it can compete with laser engraver PAs/8x UXV LPFs.

2024-06-09 08:58 UTC, Elisis commented
TODO:
- [ ] Neutrons in LINAC error
- [ ] Incorrect particles in synchrotron error
- [ ] Iron-Quartz Plate recipe -> Shaped

2024-06-09 10:04 UTC, NotAPenguin0 commented
If the Iron-Quartz plate recipe is used a lot, I'd make sure it has an assembler recipe too if you haven't already.

2024-06-09 10:30 UTC, Miisi commented
Lanthanum Hexaboride has no small dust -> dust recipe, rendering the dust from this recipe useless (also maybe a better recipe for rods?)
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/46682682/75e3f3f1-e466-43e1-826a-2e3cb215fbbd)


Lanthanum Hexaboride and Mu-metal seem to be instantly processed (1 tick) into parts, probably not intended
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/46682682/b6de2fd3-a804-4b03-83a7-1241aacb6045)
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/46682682/7d6adedf-375e-450e-9b72-65b8c14c041e)

2024-06-09 14:49 UTC, Elisis commented on src/main/java/com/elisis/gtnhlanth/util/Util.java
> +    public static List<Pos2d> getGridPositions(int totalCount, int xOrigin, int yOrigin, int xDirMaxCount,
This also alters the distance between slots, whereas the GT version doesn't, so I don't think I can just remove it

2024-06-16 11:23 UTC, Elisis commented
Woo blank spotless apply commit

2024-07-18 22:53 UTC, Elisis commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/Synchrotron.java
> +        if (Objects.isNull(fluidOutput)) return false;
I mean this is mainly personal preference, that it tries to use the wrong coolant and subsequently fails

2024-07-18 22:59 UTC, Elisis commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/Synchrotron.java
> +    private BeamInformation getInputInformation() {
Wouldn't really be neat tbh, I'd need to add the hatch list as an argument which isn't great

2024-07-18 23:29 UTC, Elisis commented on src/main/java/com/elisis/gtnhlanth/common/tileentity/recipe/beamline/BeamlineRecipeLoader.java
> +
Going to see how well these work in practice first

2024-07-20 14:22 UTC, NotAPenguin0 approved these changes
I like the ideas and mechanics a lot. Code looks fine to me now, assuming everything works. If @Elisis agrees it's ready, I think it would be good to start adding this to nightly releases so we can hopefully get some better numbers for balancing in real bases. 

My only concern is that it might not scale enough for endgame/stargate, but that's something we can only see by actually testing it in such bases, and we can always adjust numbers later.

2024-07-20 14:35 UTC, Dream-Master commented
DreamMasterXXL — 07/18/2024 5:09 PM
Hi. Are beamline now ready to merge ?
Elisis — 07/18/2024 5:10 PM
I'd say so
Haven't received any negative feedback about it lately
DreamMasterXXL — 07/18/2024 5:11 PM
Kk

2024-07-20 14:35 UTC, merged

2024-08-02 04:07 UTC, Reflex18 commented
Just a minor nitpix after checking out the beamline on the nightly.

I noticed there is a recipe using a cell in it within a blast furnance.

![image](https://github.com/user-attachments/assets/e983a263-8c4c-47a5-9e14-c984ba3b6168)


I would rather not have to use cell chem in the later parts of the game.

Since i think there is a limitation within the EBF for fluids the alloy blast furnace could be used instead, however this is just a suggestion.

![image](https://github.com/user-attachments/assets/5026171e-1bae-496f-be65-d7ea5f91b9d6)

This is an example recipe using a fluid, and item input to get a fluid/item output.

2024-08-02 22:45 UTC, Elisis commented
Not the biggest fan of using the ABS, as it's not really alloying here. I could probably make a Silane-Nitrogen Plasma mix material and just use that in the EBF though

2024-08-11 05:49 UTC, koiNoCirculation commented
![04a817a1c62d779db1001c9f7da97b9e](https://github.com/user-attachments/assets/0b99ba3e-0bf6-4c58-b44c-047bf62f1730)
Mobs spawnes in side.

2024-08-11 22:43 UTC, Elisis commented
No clue why that's happening, I literally set the casings to not allow mob spawns :concern: