add 3rd recipe for platinum concentrate precipitation
GTNewHorizons/GT5-Unofficial pull request #2622
Opened 2024-05-26 11:45 UTC by Glease

this keeps the same total eu per operation as the old 9x recipe, but with a much more sensible EU/t and duration combination

See more around this message: https://discord.com/channels/181078474394566657/939305179524792340/1244192255619633222

2024-05-26 12:06 UTC, Dream-Master commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/GT_Enhancement/PlatinumSludgeOverHaul.java
> +import static gregtech.api.recipe.RecipeMaps.*;
I thought star imports are not allowed by spotless ? Or I am wrong ?

2024-05-26 13:09 UTC, chochem requested changes
this is just bloat unless I am missing something. why didnt you just change the existing recipe?

2024-05-26 13:11 UTC, NotAPenguin0 commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/GT_Enhancement/PlatinumSludgeOverHaul.java
> +            .itemInputs(GT_Utility.getIntegratedCircuit(2))
Why keep the old recipe at all? In my opinion this just causes unnecessary confusion. I'd just change the EU/t and duration of the original recipe instead. If this causes an issue for someone's setup they have done something cursed like sharing an energy hatch on 2 LCRs running the same recipe (?)

2024-05-26 13:11 UTC, NotAPenguin0 commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/GT_Enhancement/PlatinumSludgeOverHaul.java
> +            .itemInputs(GT_Utility.getIntegratedCircuit(2))
ah chochem already said this while I was typing.

2024-05-26 15:22 UTC, Glease commented on src/main/java/com/github/bartimaeusnek/bartworks/system/material/GT_Enhancement/PlatinumSludgeOverHaul.java
> +import static gregtech.api.recipe.RecipeMaps.*;
static star import are allowed for a lot of reasons.

2024-05-26 15:24 UTC, Glease commented
@chochem changing the old recipe will break 2 energy hatch, each powered by 1 generator setups. the cost of not breaking these setup are extremely low so I prefer to not break them

2024-05-26 16:03 UTC, Glease commented
I have hide the old 9x recipe in NEI. This should not cause any confusion now. Existing setups will work normally.

2024-05-26 16:10 UTC, chochem commented
thats a pretty weird setup to worry about breaking.
Boubou said earlier this can be cleaned up to just one recipe

2024-05-27 08:38 UTC, Glease commented
I still hold my pooints: if it's rather hard to provide a migration, I'd just tell the player to fix it yourselves. This is definitely not the case here.

2024-05-27 08:40 UTC, Glease commented
and on the "weird setup" part, that's what I'm using, so I do worry about it.

2024-05-27 09:12 UTC, Dream-Master commented
i am ok with this change but we need to not forget to remove the 240 eu/t recipe next update

2024-05-27 09:12 UTC, chochem commented
hmm, well that is a bit of an impass. I am happy to let boubou (or dream I guess) decide this.

however, please dont hide recipes. I rather you add another 3 extra recipes than obfuscating them

2024-05-27 09:15 UTC, Dream-Master commented
where is the code that hide the recipe?

2024-05-27 09:15 UTC, chochem commented
> where is the code that hide the recipe?

https://github.com/GTNewHorizons/GT5-Unofficial/pull/2622/commits/8d4d909258f0a6e45db2ce4507aeb32ba0ee6ec9

2024-05-27 09:16 UTC, Dream-Master commented
ah ok. yea maybe unhide it otherwise we forget to remove it later @Glease

2024-05-27 12:51 UTC, AbdielKavash commented
I would also prefer changing the recipe power and time, rather than changing the circuit number. Changing the former breaks existing setups which do not provide the LCR a full amp of power. While extant, as mentioned, I would wager a guess that these are rare. Changing the circuit breaks *all* existing setups. (Whether you break them in 2.7 or 2.8, at some point *every* player who has a platline will have to adjust.)

We talked about this on Discord, and my opinion in a bigger picture would be to save breaking changes to such critical recipes for a more comprehensive chemistry overhaul, especially when the gain from this specific change is just consistency with numbers. (Amount of inputs/outputs is unchanged.)

2024-05-27 17:58 UTC, merged