Revert "Fix water bottle fluid exploit"
GTNewHorizons/GT5-Unofficial pull request #2629
Opened 2024-05-29 09:11 UTC by HoleFish

Reverts GTNewHorizons/GT5-Unofficial#2494
Can confirm this is the cause of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16399.
Need further fix for the exploit.

2024-05-29 09:52 UTC, chochem commented
this seems like a AE2FC problem. dont see any issue here

2024-05-29 09:59 UTC, chochem requested changes
yea looking at the log, this is clearly a bug in AE2FC and should be fixed there

2024-05-29 10:00 UTC, HoleFish commented
Remove fluid container registration of water bottle or what. I dont know. This reminds us the amount of fluid in a container should not be 0

2024-05-29 10:32 UTC, chochem commented
should be fixed now

2024-05-30 07:51 UTC, chochem commented
[16399](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16399) is already fixed.

This PR just breaks stuff and makes the interactions all inconsistent.

2024-05-30 07:52 UTC, HoleFish commented
Ive found another crash related to this. I'm making ticket.
The one who is breaking stuff is you.

2024-05-30 07:54 UTC, chochem commented
this is 10 years old, I wasnt working on gt back then.

boubou might not care about fixing a water exploit. but purposefully making one is a different story I would guess.

2024-05-30 07:58 UTC, HoleFish commented
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16420

2024-05-30 08:10 UTC, chochem commented
I appreciate that you are trying to find very fringe interactions (that nobody tried in 10 years) to make the pack more robust. But the fix should still be in binnies.

2024-05-30 08:16 UTC, HoleFish commented
I only see GT messed things up, waiting for other mods to clean up its mess

2024-05-30 08:32 UTC, chochem commented
we use 0 amounts even more for itemstacks than fluidstacks. Both have their use cases.

2024-05-30 09:32 UTC, boubou19 commented
fixing the 0 sized fluidstack in GT is just yet another part of ductape, anything crashing against 0 sized fluidstack should be fixed. With this PR, you just prevent one way of passing problematic fluid stacks to genetics. If you do a fluid stack size check in genetics, you definitely fixed the issue.

Also, with this you'll break all the occurences of the pack assuming this being a 0 sized fluidstack, creating more trouble for us in a more or less future.

The fix should go in Genetics.

2024-05-30 09:32 UTC, closed without merging