Add Steam Multi
GTNewHorizons/GT5-Unofficial pull request #2631
Opened 2024-06-01 06:26 UTC by evgengoldwar

Steam Centrifuge

![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/69961523/1c0534ad-0227-4329-89fb-2400affd22b4)

![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/69961523/3d1939cd-a1ec-40d9-92b3-557d786050a8)

![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/69961523/6f4e1bdf-2d74-4de0-90eb-239c6d182e36)

Steam Washer

![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/69961523/639f79f6-d522-46af-afea-5a84e11f20f6)

![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/69961523/0e289f0c-99e3-4298-b4b6-543944f59ba8)

![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/69961523/02648373-7212-417f-9fc1-665f19472ea8)

The new steam multi works similarly to the steam compressor and steam macerator

2024-06-01 09:16 UTC, Reflex18 commented
These mutliblocks look amazing and much better then the GT ++ counterparts.

2024-06-01 09:24 UTC, Alastors commented
I’d say reject the steam centrifuge, it just doesn’t fit into the balance IMO, though the washer is dope as hell

2024-06-01 09:29 UTC, evgengoldwar commented
> I’d say reject the steam centrifuge, it just doesn’t fit into the balance IMO, though the washer is dope as hell

Centrifuge does not make higher mv tier recipes, we can say it is used only for ore processing

2024-06-01 09:43 UTC, chochem reviewed
did you test the behaviour of the steam hatch and how much power it can provide? as the recipes in these multis take more power than the existing ones like macerator.
As I recall the hatch is somewhat limited on that front

2024-06-01 09:43 UTC, evgengoldwar commented
> did you test the behaviour of the steam hatch and how much power it can provide? as the recipes in these multis take more power than the existing ones like macerator. As I recall the hatch is somewhat limited on that front

Yes everything has been tested

2024-06-01 09:44 UTC, chochem commented
so how much is it?

2024-06-01 09:46 UTC, evgengoldwar commented
> so how much is it?

Centrifuge will not make recipes above mv tier, washer will not make recipes above lv tier

2024-06-01 09:51 UTC, chochem commented
why would it be different?

2024-06-01 09:53 UTC, chochem commented
also it does not really relate to my question as number of parallels would affects this

2024-06-01 09:53 UTC, evgengoldwar commented
> why would it be different?

Everything works correctly as it should be

2024-06-01 09:54 UTC, chochem commented
I guess I am not going to get a straight answer.

2024-06-01 09:58 UTC, evgengoldwar commented
> I guess I am not going to get a straight answer.

Do you mean how many parallels does each have?

2024-06-01 10:00 UTC, evgengoldwar commented
> > I guess I am not going to get a straight answer.
> 
> Do you mean how many parallels does each have?

If about them, then a couple is enough to provide the required number of parallels

2024-06-01 10:01 UTC, Quarri6343 commented
> Centrifuge will not make recipes above mv tier
Why MV?

2024-06-01 10:02 UTC, chochem commented
> 
> Do you mean how many parallels does each have?

did not ask anything like that as the answer is max 8. I am asking about the steam hatch.

The wiki says the steam hatch is limited to 40L/t. This would be a major limitation for your multis if true. so checking in the code/the game what the limit is, is critical for this PR.

2024-06-01 10:06 UTC, Quarri6343 commented
In the most simplest term:
How much EU can steam hatch provide?

> > Do you mean how many parallels does each have?
> 
> did not ask anything like that as the answer is max 8. I am asking about the steam hatch.
> 
> The wiki says the steam hatch is limited to 40L/t. This would be a major limitation for your multis if true. so checking in the code/the game what the limit is, is critical for this PR.

2024-06-01 10:12 UTC, evgengoldwar commented
> > Do you mean how many parallels does each have?
> 
> did not ask anything like that as the answer is max 8. I am asking about the steam hatch.
> 
> The wiki says the steam hatch is limited to 40L/t. This would be a major limitation for your multis if true. so checking in the code/the game what the limit is, is critical for this PR.

Sorry, I didn’t immediately understand the essence of the question. 320 L/t couple consumes centrifuge with mv recipe and has 2 parallels. Washer consumes 171 L/t steam with lv recipe and has 8 parallels

2024-06-01 10:14 UTC, Dream-Master commented
> I’d say reject the steam centrifuge, it just doesn’t fit into the balance IMO, though the washer is dope as hell

No i ask for it and i want it for ages. Sure it affect balance but it can be adjust to fit better.

2024-06-01 10:14 UTC, chochem commented
ok thats good. so the wiki is wrong on this. (It might have been correct pre-gpl)

2024-06-01 10:24 UTC, NotAPenguin0 reviewed
I have mixed feelings about the machine being made out of steel instead of bronze. I feel like bronze machines and hulls fit the steam age much better, similarly to the steam macerator. With the current version costing this much steel, I'm not sure if it will be worth making for steam or LV players.

On the other hand, making it out of bronze might be considered "too cheap".

2024-06-01 10:29 UTC, Dream-Master commented
> I have mixed feelings about the machine being made out of steel instead of bronze. I feel like bronze machines and hulls fit the steam age much better, similarly to the steam macerator. With the current version costing this much steel, I'm not sure if it will be worth making for steam or LV players.
> 
> On the other hand, making it out of bronze might be considered "too cheap".

Washer and centrifuges are not bronze machines (single block) so I ask for steel not make it to cheap but available at late steam age .

2024-06-01 10:35 UTC, NotAPenguin0 submitted a review, later dismissed

2024-06-01 10:35 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamCentrifuge.java
> +                .addElement('C', ofBlock(getCasingBlock2(), getCasingMeta2()))
Nit: I would inline these calls to `getCasingBlock` and `getCasingMeta` and add a comment explaining what block they are.

2024-06-01 10:35 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamCentrifuge.java
> +            .addInfo("Centrifuged up to " + getMaxParallelRecipes() + " things at a time")
```suggestion
            .addInfo("Centrifuges up to " + getMaxParallelRecipes() + " things at a time")
```
Typo. Alternatively use standard wording like `Processes N recipes in parallel`.

2024-06-01 10:35 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamCentrifuge.java
> +            .addCasingInfoMin(mCasingName, 50, false)
This min casing amount is hardcoded in `checkMachine` as well, extract this into a static variable.

2024-06-01 10:35 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamWasher.java
Same general comments as on the centrifuge:
- Extract min casing amount into a variable
- Perhaps do not use `getCasingBlock` and `getCasingMeta`

2024-06-01 10:35 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSteamMultis.java
> +            new GregtechMetaTileEntity_SteamWasher(31082, "gtpp.multimachine.steam.washer", "Steam Washer")
Why are 31079 and 31081 skipped?

2024-06-01 10:49 UTC, evgengoldwar commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamCentrifuge.java
> +                .addElement('C', ofBlock(getCasingBlock2(), getCasingMeta2()))
For steel framebox? To those calls that exist, I’ll add what kind of blocks they are

2024-06-01 10:55 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamCentrifuge.java
> +                .addElement('C', ofBlock(getCasingBlock2(), getCasingMeta2()))
Not for the frame box, that one is fine. I refer specifically to simply writing `ofBlock(sBlockCasings2, 0)` instead of the method call. The idea is that
- These calls are only used in one place, so having a function isn't *that* beneficial.
- If I wanted to see what value is passed there (for debugging or documentation purposes for example), I have to do another physical jump in the code to go have a look, which is somewhat unnecessary here.

2024-06-01 10:55 UTC, evgengoldwar commented on src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSteamMultis.java
> +            new GregtechMetaTileEntity_SteamWasher(31082, "gtpp.multimachine.steam.washer", "Steam Washer")
If you use 31079 the game crashes

2024-06-01 10:56 UTC, evgengoldwar commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamCentrifuge.java
> +                .addElement('C', ofBlock(getCasingBlock2(), getCasingMeta2()))
Got it, I'll change it now

2024-06-01 10:56 UTC, Dream-Master commented on src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSteamMultis.java
> +            new GregtechMetaTileEntity_SteamWasher(31082, "gtpp.multimachine.steam.washer", "Steam Washer")
maybe occupied by another machine?

2024-06-01 11:00 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSteamMultis.java
> +            new GregtechMetaTileEntity_SteamWasher(31082, "gtpp.multimachine.steam.washer", "Steam Washer")
> If you use 31079 the game crashes
Oh, the joys of GT++ code. Sounds fine then, maybe add a comment explaining for someone looking at this in the future.

2024-06-01 11:03 UTC, evgengoldwar commented on src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSteamMultis.java
> +            new GregtechMetaTileEntity_SteamWasher(31082, "gtpp.multimachine.steam.washer", "Steam Washer")
Write that id 31079 and 31081 are occupied by another machine?

2024-06-01 11:13 UTC, evgengoldwar commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamWasher.java
Fixed

2024-06-01 11:34 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSteamMultis.java
> +            new GregtechMetaTileEntity_SteamWasher(31082, "gtpp.multimachine.steam.washer", "Steam Washer")
Yeah something like that.

2024-06-01 11:40 UTC, evgengoldwar commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamCentrifuge.java
> +            .addCasingInfoMin(mCasingName, 50, false)
Fixed

2024-06-01 13:14 UTC, tommy307507 commented
> > I have mixed feelings about the machine being made out of steel instead of bronze. I feel like bronze machines and hulls fit the steam age much better, similarly to the steam macerator. With the current version costing this much steel, I'm not sure if it will be worth making for steam or LV players.
> > On the other hand, making it out of bronze might be considered "too cheap".
> 
> Washer and centrifuges are not bronze machines (single block) so I ask for steel not make it to cheap but available at late steam age .

Maybe use a steel-plated bronze version instead of full on steel casings, the whole thing takes ~400-500 steel ingots in mv, and at steam it would take 2x ingots for plates and rods crafted by hand. So as a player, this multi belongs to the post-ebf and mv extruder, as I can make everything efficiently, and at a reasonable amount of steel for the ability to do recipes a bit faster than a few single block. I agree completely that the multis should not be at early steam and should not be made completely out of bronze , but we may have a different opinion on  what is late steam age by the steel cost. 
As steam hatch and other existing steam multies requires the assembler, I think the recipes for the controller could be nudged a bit towards post assembler / ebf, where you can use plate bender to get steel plates and assembler to craft the "steel plated bronze bricks" , such that players in early mv could get some use out of the centrifuge for , say redstone centrifuging, which this would be great to have.

2024-06-01 13:20 UTC, Dream-Master commented
> > > I have mixed feelings about the machine being made out of steel instead of bronze. I feel like bronze machines and hulls fit the steam age much better, similarly to the steam macerator. With the current version costing this much steel, I'm not sure if it will be worth making for steam or LV players.
> > > On the other hand, making it out of bronze might be considered "too cheap".
> > 
> > 
> > Washer and centrifuges are not bronze machines (single block) so I ask for steel not make it to cheap but available at late steam age .
> 
> Maybe use a steel-plated bronze version instead of full on steel casings, the whole thing takes ~400-500 steel ingots in mv, and at steam it would take 2x ingots for plates and rods crafted by hand. So as a player, this multi belongs to the post-ebf and mv extruder, as I can make everything efficiently, and at a reasonable amount of steel for the ability to do recipes a bit faster than a few single block. I agree completely that the multis should not be at early steam and should not be made completely out of bronze , but we may have a different opinion on what is late steam age by the steel cost. I think the recipes for the controller could be nudged a bit towards post assembler / ebf, where you can use plate bender to get steel plates and assembler to craft the "steel plated bronze bricks" , such that players in early mv could get some use out of the centrifuge for , say redstone centrifuging, which this would be great to have.

if you build 8 washer and 8 Centrifuges in LV you need much more materials. No new blocks are needed. Just do the 4bbfs in bronze age and you have tons of Steel. I had 30 stacks of steel in early lv and 60 when i hit mv.

2024-06-01 13:22 UTC, Nxer commented
I have a question, with the same cost, can we get higher profit by making a single-block machine than a multi-block machine?🤔

2024-06-01 13:28 UTC, tommy307507 commented
> > > > I have mixed feelings about the machine being made out of steel instead of bronze. I feel like bronze machines and hulls fit the steam age much better, similarly to the steam macerator. With the current version costing this much steel, I'm not sure if it will be worth making for steam or LV players.
> > > > On the other hand, making it out of bronze might be considered "too cheap".
> > > 
> > > 
> > > Washer and centrifuges are not bronze machines (single block) so I ask for steel not make it to cheap but available at late steam age .
> > 
> > 
> > Maybe use a steel-plated bronze version instead of full on steel casings, the whole thing takes ~400-500 steel ingots in mv, and at steam it would take 2x ingots for plates and rods crafted by hand. So as a player, this multi belongs to the post-ebf and mv extruder, as I can make everything efficiently, and at a reasonable amount of steel for the ability to do recipes a bit faster than a few single block. I agree completely that the multis should not be at early steam and should not be made completely out of bronze , but we may have a different opinion on what is late steam age by the steel cost. I think the recipes for the controller could be nudged a bit towards post assembler / ebf, where you can use plate bender to get steel plates and assembler to craft the "steel plated bronze bricks" , such that players in early mv could get some use out of the centrifuge for , say redstone centrifuging, which this would be great to have.
> 
> if you build 8 washer and 8 Centrifuges in LV you need much more materials. No new blocks are needed. Just do the 4bbfs in bronze age and you have tons of Steel. I had 30 stacks of steel in early lv and 60 when i hit mv.

I do build about 20 lv machines for my redstone centrifuging + washing machine, but that is in late mv/early hv where I can pump out 10 stacks in a few mins using 4ebf. I agree that you can hang around and get tons of steel, but an average player / new player would look at the price and decide maybe its not worth it at the intended late steam tier (as the intended tier affects the speed and balance of the recipes), if you set it as a late steam tier and balance around it , I am afraid it wont get much use at such tier, and be replaced by better singleblocks (one MV machine would beat 2 lv singleblock)

2024-06-01 13:37 UTC, Dream-Master commented
sure we can look for how much a machine should cost. Maybe we need to make the amount better than 8 per recipe or we need to check which steel blocks are cheaper to use. But no new casings are needed lets look what we have else to combine steel and bronze maybe

2024-06-01 13:45 UTC, Connor-Colenso commented
> if you build 8 washer and 8 Centrifuges in LV you need much more materials. No new blocks are needed. Just do the 4bbfs in bronze age and you have tons of Steel. I had 30 stacks of steel in early lv and 60 when i hit mv.

Most people do not have 4 BBFs nor afk enough to get 30 stacks of steel. 240s/steel ingot using a BBF, so 60s/ingot means 60s* 30*64 (30 stacks of 64 steel) = 32 hours of solid 4xBBF running . 

400-500 steel is excessive and all that will happen is that virtually no one will use it because no one really needs massive centrifuge parallel in low tiers, because most ore byproducts do not make it worth it. Lets make it more a more reasonable cost.

2024-06-01 13:50 UTC, Dream-Master commented
pr is wip and can be adjust

2024-06-01 14:02 UTC, tommy307507 commented
> sure we can look for how much a machine should cost. Maybe we need to make the amount better than 8 per recipe or we need to check which steel blocks are cheaper to use. But no new casings are needed lets look what we have else to combine steel and bronze maybe
The steel cost at **steam** from top to bottom of the centrifuge would be :
650+48+42+208+112 = 1060, 16.5625 stacks
the most costly component is the casing , then the gear casing , then the pipe casing,
maybe we can replace some of them with bronze to reduce the steel cost? because bronze plated bricks are much cheaper with assembler and lv tech.

Meanwhile, the steel cost at **steam** / lv for the single block gen + a centrifuge is:
35 for centrigue, 57 for a combustion (most expensive) with steam tech (so in full lv tech would be a bit cheaper)
(credits to ppl in the chinese qq for calculating this)

The player could make nearly 12 set of the single blocks in steam and run it with combustion gen. And this would be a nice estimate for the upper limit of cost of the single block gen. It would be nice to do such estimation, because I do like the idea of a steam multi for the centrifuge and would like to actually use it in my setup too...

2024-06-01 14:07 UTC, Nxer commented
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/43300390/9c853c7e-cc37-4a23-ace7-2063c05aab31)

A choice

2024-06-01 14:10 UTC, Dream-Master commented
Or two tiers. 8x with bronze and 16x with steel.

2024-06-01 14:10 UTC, evgengoldwar commented
> > sure we can look for how much a machine should cost. Maybe we need to make the amount better than 8 per recipe or we need to check which steel blocks are cheaper to use. But no new casings are needed lets look what we have else to combine steel and bronze maybe
> 
> The steel cost at **steam** from top to bottom of the centrifuge would be : 650+48+42+208+112 = 1060, 16.5625 stacks the most costly component is the casing , then the gear casing , then the pipe casing, maybe we can replace some of them with bronze to reduce the steel cost? because bronze plated bricks are much cheaper with assembler and lv tech.
> 
> Meanwhile, the steel cost at **steam** / lv for the single block gen + a centrifuge is: 35 for centrigue, 57 for a combustion (most expensive) with steam tech (so in full lv tech would be a bit cheaper) (credits to ppl in the chinese qq for calculating this)
> 
> The player could make nearly 12 set of the single blocks in steam and run it with combustion gen. And this would be a nice estimate for the upper limit of cost of the single block gen. It would be nice to do such estimation, because I do like the idea of a steam multi for the centrifuge and would like to actually use it in my setup too...

Still, I’ll probably make tier 2 bronze and steel for each steam multi

2024-06-01 14:21 UTC, tommy307507 commented
> Or two tiers. 8x with bronze and 16x with steel.

As the washer would be quite limited, maybe add a chemical washer ability on the tier 2, similar to that of the gt++ version? Would make it more useful at the steel version.

2024-06-01 14:52 UTC, chochem commented on src/main/java/gtPlusPlus/xmod/gregtech/registration/gregtech/GregtechSteamMultis.java
> +            new GregtechMetaTileEntity_SteamWasher(31082, "gtpp.multimachine.steam.washer", "Steam Washer")
31079 is the adv heat exchanger clearly

2024-06-01 16:44 UTC, Dream-Master commented
> > Or two tiers. 8x with bronze and 16x with steel.
> 
> As the washer would be quite limited, maybe add a chemical washer ability on the tier 2, similar to that of the gt++ version? Would make it more useful at the steel version.

i want some washer for ore processing not for anything else.

2024-06-06 04:04 UTC, Nxer commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamCentrifuge.java
> +    public static int getTierCasing4(Block block, int meta) {
```suggestion
    public static int getTierCasingPipe(Block block, int meta) {
```

Better to use meaningful names instead of numbers. Others too.

2024-06-06 04:38 UTC, Nxer requested changes
I guess all tiered block should be same tier at same time. Anyway the method `checkMachine` is logically confusing. Maybe you confused the logical operators `&&` and `||`. And `return` is the end of method you may need to check your logic design expression correct.

Try to use meaningful names instead of numember.

Write more comments to describe what your code is doing. Especially if you are not sure whether it is correct.

Finally, be sure to test the effect in the game.

2024-06-06 20:21 UTC, Nxer approved these changes
Looks like there's no problem.

2024-06-07 03:40 UTC, Dream-Master approved these changes
Let’s test it on zeta and see if balance is ok or need to be changed.

2024-06-07 03:41 UTC, merged