add mold check for solidifier hatch
GTNewHorizons/GT5-Unofficial pull request #2679
Opened 2024-06-22 19:06 UTC by Quetz4l

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16405

2024-06-29 15:40 UTC, OneEyeMaker requested changes

2024-06-29 15:40 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_Solidifier.java
> +    static final Item[] solidifierMolds = { ItemList.Shape_Mold_Bottle.get(1)
Store ItemStacks instead of items, cause many molds (if not most of ones) share *the same* (meta-generated) item.
And use `GT_Utility.areStacksEqual(stack1, stack2, true)` to compare.

2024-06-29 15:40 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_Solidifier.java
> +        return false;
Should we call `super.isItemValidForSlot(...)` if index doesn't match?

2024-06-30 12:37 UTC, Quetz4l commented on src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_Solidifier.java
> +        return false;
Other slots don't use the isItemValidForSlot(...) method, but ok,  I'll add it

2024-06-30 13:49 UTC, OneEyeMaker approved these changes

2024-06-30 13:50 UTC, merged