Added Water Pump
GTNewHorizons/GT5-Unofficial pull request #2694
Opened 2024-06-29 12:04 UTC by evgengoldwar

Water Pump : 
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/69961523/776c9e32-7dbc-4237-b291-4dd2dfb78c94)
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/69961523/f909e76d-c1ea-4920-9b21-f17cfb1a373c)

Tier 1 :
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/69961523/f5c35700-5051-43d4-800c-bd0e25b9e587)

Tier 2 :
![image](https://github.com/GTNewHorizons/GT5-Unofficial/assets/69961523/80f98d85-99e7-40cd-a99b-0e424ee08777)

2024-06-29 12:13 UTC, chochem commented
did you discuss this with the dev team at all? please dont make big changes like this to early without any prior discussion.

here some obvious starting question:
why?
how much does it make? (tooltip is very unclear)
how much fuel/what type of fuel does it take?

2024-06-29 12:21 UTC, evgengoldwar commented
> did you discuss this with the dev team at all? please dont make big changes like this to early without any prior discussion.
> 
> here some obvious starting question: why? how much does it make? (tooltip is very unclear) how much fuel/what type of fuel does it take?

Dream asked to add to the existing Steam Washer as it requires a lot of water. 
The water extraction formula is written in the tooltip. Humidity and Tiers are written in the wailla on the controller. 
It requires nothing to run.

2024-06-29 12:25 UTC, chochem commented
This is not a steam washer.
As I said the tooltip is totally unclear. (no time frame! 40% humidity is 40 or 0.4?)
A pump that runs on nothing is nonsense. We already have a water pump and it uses fuel.

2024-06-29 12:34 UTC, Reflex18 commented
Is this a replacement to the Stirling dynamo and an upgrade to the railcraft water tanks?

2024-06-29 12:35 UTC, evgengoldwar commented
> This is not a steam washer. As I said the tooltip is totally unclear. (no time frame! 40% humidity is 40 or 0.4?) A pump that runs on nothing is nonsense. We already have a water pump and it uses fuel.

40% = 40 As already said in wailla the humidity of the biome is deduced

2024-06-29 12:36 UTC, Dream-Master commented
The new washer need tons of water so a pump is a nice idea and needed. About blance when can discuss.

2024-06-29 12:36 UTC, evgengoldwar commented
> to add to those questions: why would humidity affect a water pump?

It's a mix of Railcraft Water tank and Pump from Impact.

2024-06-29 12:36 UTC, chochem commented
> Is this a replacement to the Stirling dynamo and an upgrade to the railcraft water tanks?

replacing the stirling pump with something nicer looking (at roughly the same mechanics) could be a cool thing yea. that is not what this is sadly.

2024-06-29 12:38 UTC, chochem commented
> > This is not a steam washer. As I said the tooltip is totally unclear. (no time frame! 40% humidity is 40 or 0.4?) A pump that runs on nothing is nonsense. We already have a water pump and it uses fuel.
> 
> 40% = 40 As already said in wailla the humidity of the biome is deduced

you are not saying anything if you dont say the time frame. for th railcraft tanks its 8 ticks. but for all I know you mean per second or per tick instead.

2024-06-29 12:39 UTC, chochem commented
> The new washer need tons of water so a pump is a nice idea and needed. About blance when can discuss.

we have a pump already dream

2024-06-29 12:39 UTC, evgengoldwar commented
> > > This is not a steam washer. As I said the tooltip is totally unclear. (no time frame! 40% humidity is 40 or 0.4?) A pump that runs on nothing is nonsense. We already have a water pump and it uses fuel.
> > 
> > 
> > 40% = 40 As already said in wailla the humidity of the biome is deduced
> 
> you are not saying anything if you dont say the time frame. for th railcraft tanks its 8 ticks. but for all I know you mean per second or per tick instead.

per second

2024-06-29 12:52 UTC, chochem requested changes
thanks for answering some questions. Though these should discussion should really happen in advance and not on the PR.

**I propose we close this PR.**

We already have a water pump which is better (excepty for looks). Specifically:
- a water pump based on humidity makes no sense.
- a water pump without power/fuel of any kind makes no sense.
- adding some bronze to a water tank to make it produce (literally) 200x as much makes no sense.

If the reason for this was the new steam washer, there is a much simpler solution. Reduce the water consumption. It acts as a simple washer only right? Meaning no byprodructs. You can simple wash 3 stacks of material with 1000L water in a cauldron, so low water usage for simple washing has precedent in the game.

Regarding water pumps, I could see us using a multiblock structure like this as a replacement for the existing (stirling) water pump but with its existing mechanics (based on fuel not humidity), just to make it look nicer. Outside of looks the existing water pump seems fine.

2024-06-29 13:47 UTC, Dream-Master commented
The steam washer has byproducts. Its not a simple washer.
The stirling Water pump from bartworks was a duct tape solution and never a very good way to generate water.
reduce the amount of water make the single block washer completly useless and break balance.
About how this pump have to generate/pump water we can discuss.

2024-06-29 14:29 UTC, dahgul333 commented
> thanks for answering some questions. Though these discussion should really happen in advance and not on the PR.
> 
> **I propose we close this PR.**
> 
> We already have a water pump which is better (excepty for looks). Specifically:
> 
>     * a water pump based on humidity makes no sense.
> 
>     * a water pump without power/fuel of any kind makes no sense.
> 
>     * adding some bronze to a water tank to make it produce (literally) 200x as much makes no sense.
> 
> 
> If the reason for this was the new steam washer, there is a much simpler solution. Reduce the water consumption. It acts as a simple washer only, right? Meaning no byprodructs. You can simple wash 3 stacks of material with 1000L water in a cauldron, so low water usage for simple washing has precedent in the game.
> 
> Regarding water pumps, I could see us using a multiblock structure like this as a replacement for the existing (stirling) water pump but with its existing mechanics (based on fuel not humidity), just to make it look nicer. Outside of looks the existing water pump seems fine.

1) We alredy have humidiry based water source - Water Tank (If you want a near-realistic justification, the groundwater depends on humidity+-.
2)instead of fuel, we pay with the cost of the structure
3)I don't see any point in being greedy for water.

2024-06-29 14:34 UTC, Dream-Master commented
This pump use steam which need coal  to work. About the pump rate and other balacing stuff we can discuss here or in Discord.

2024-06-29 15:15 UTC, chochem commented
> The steam washer has byproducts. Its not a simple washer. The stirling Water pump from bartworks was a duct tape solution and never a very good way to generate water. reduce the amount of water make the single block washer completly useless and break balance. About how this pump have to generate/pump water we can discuss.

why does it have byproducts? the steam macerator does not.

2024-06-29 15:16 UTC, chochem commented
> This pump use steam which need coal to work. About the pump rate and other balacing stuff we can discuss here or in Discord.

no. they say it uses nothing.

2024-06-29 22:43 UTC, ah-OOG-ah commented
> > The steam washer has byproducts. Its not a simple washer. The stirling Water pump from bartworks was a duct tape solution and never a very good way to generate water. reduce the amount of water make the single block washer completly useless and break balance. About how this pump have to generate/pump water we can discuss.
> 
> why does it have byproducts? the steam macerator does not.

Probably because unlike the macerator, there is an LV washer that gives byproducts. It's just slower and more expensive to run.

2024-06-29 23:27 UTC, Dream-Master commented
Pump need to used Steam so it need to be changed. About Byproducts. Lv macerator has no byproducts same as multi. Lv washer has byproducts same as the new multi

2024-07-16 18:24 UTC, chochem commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamWaterPump.java
> +                EnumChatFormatting.AQUA + "Generation water: " + EnumChatFormatting.WHITE + ": (Humidity * 50) * Tier" + EnumChatFormatting.RESET)
these values still need a timeframe

2024-07-16 18:35 UTC, chochem commented
Steam based is a good approach. Apparently that was Dreams idea from the start, so that is great.
And at least not depending on skycheck but only humidity improves things a lot on that front for sure.

Outside of improving the tooltip, I guess a big discussion point left is balance. If I understand correctly this now produces 5000L/s water for 400L/s running cost. Well with the production scaled down proportionally at less than 100 humidity and doubled with steel tier though the steam consumption remains the same. (please correct me if wrong)
For comparison the passive railcraft water tank makes 25L/s water at 100 humidity and the coal/charcoal/similar based existing water pump makes 150L/s (I dont remember the fuel consumption rate).
So right now even just the bronze tier is like 200 water tanks (but with steam consumption!) or like 33 water pumps (and probably more efficient. That is a lot, and way more than you need in steam age, even with the washer. (and its highly unlikely you will run the washer a lot with max parallels anyway)

2024-07-18 09:01 UTC, NotAPenguin0 requested changes
There are a few minor code quality nitpicks I'd like to see addressed. Some of these aren't necessary, but would improve maintainability a little and make it easier for others unfamiliar with the implementation to change this in the future.

There's also a few other things like trying to automatically determine the tier of the multi instead of having to set it with a screwdriver, but overall well done on the multi.

As for balancing, I think in it's current state it's mostly fine. Spamming the RC water siding tanks in Steam/Early LV is not very interesting in my opinion, so having a pump multiblock that's a bit stronger does make some sense. It would also increase the viability of the large boilers in LV/MV a bit, which I'm all for.

2024-07-18 14:01 UTC, Dream-Master commented on src/main/java/gtPlusPlus/core/handler/COMPAT_HANDLER.java
> +import gtPlusPlus.xmod.gregtech.registration.gregtech.GregtechWaterPump;
i guess because they are all steam multies they belongs in gt++

2024-07-18 14:49 UTC, evgengoldwar commented on src/main/java/gregtech/common/blocks/GT_Cyclotron_Coils.java
> +        return 208 + aMeta;
What do I need to document I don't quite understand?

2024-07-18 15:22 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/blocks/GT_Cyclotron_Coils.java
> +        return 208 + aMeta;
Can keep it like this

2024-07-18 15:37 UTC, NotAPenguin0 approved these changes

2024-07-18 15:37 UTC, NotAPenguin0 commented
No more comments from me

2024-07-18 15:38 UTC, Dream-Master commented
if the values need to be changed we can do another pr

2024-07-18 15:38 UTC, merged