Mute work
GTNewHorizons/GT5-Unofficial pull request #2714
Opened 2024-07-09 01:28 UTC by mitchej123

2024-07-09 02:05 UTC, Caedis commented
The rename refactor doesnt really belong imo

2024-07-09 02:07 UTC, mitchej123 commented
> The rename refactor doesnt really belong imo

It was too annoying....  Plus you can just look at the last 3 commits :P

2024-07-10 01:10 UTC, mitchej123 commented
Ran it in the latest nightly, logged into a world, no crashes/warnings.

2024-07-10 03:42 UTC, Caedis requested changes
Minor stuff, mainly commented out code

2024-07-10 03:42 UTC, Caedis commented on src/main/java/gregtech/api/multitileentity/MultiTileEntityBlock.java
> +        // spotless:off
Remove commented out code

2024-07-10 03:42 UTC, Caedis commented on src/main/java/gregtech/api/multitileentity/MultiTileEntityBlock.java
> +        // return StatCollector.translateToLocal(registry.getInternalName() + ".name");
Remove

2024-07-10 03:42 UTC, Caedis commented on src/main/java/gregtech/api/multitileentity/MultiTileEntityBlock.java
> +        // return registry.getInternalName();
Remove

2024-07-10 03:42 UTC, Caedis commented on src/main/java/gregtech/api/multitileentity/MultiTileEntityRegistry.java
> -        //
Remove

2024-07-10 03:42 UTC, Caedis commented on src/main/java/gregtech/api/multitileentity/interfaces/IMultiTileEntity.java
> +    // }
Will this be used later?

2024-07-10 03:46 UTC, mitchej123 commented on src/main/java/gregtech/api/multitileentity/interfaces/IMultiTileEntity.java
> +    // }
I think it might, that's why its still here

2024-07-10 03:47 UTC, mitchej123 commented on src/main/java/gregtech/api/multitileentity/MultiTileEntityBlock.java
> +        // spotless:off
Anything that specifically is commented out, and has a spotless:off/on combo is because I think it might be relevant in the (near) future.  I'll remove as soon as I don't think it is.

2024-07-10 04:09 UTC, mitchej123 commented on src/main/java/gregtech/api/multitileentity/MultiTileEntityRegistry.java
> -        //
Wait I'm confused, this is already removed.

2024-07-10 04:10 UTC, mitchej123 commented
Addressed

2024-07-10 04:23 UTC, Caedis approved these changes

2024-07-10 04:38 UTC, merged