Add a Multiblock Electromagnetic Separator
GTNewHorizons/GT5-Unofficial pull request #2726
Opened 2024-07-15 14:06 UTC by FourIsTheNumber

This PR adds the Magnetic Flux Exhibitor, an IV-tiered multiblock that can act as an Electromagnetic Separator as well as an Electromagnetic Polarizer (I can easily remove that functionality if not desired, or I have some other thoughts about gating it to a different set of electromagnets). This is part of the effort to deprecate PA, as EM Separator has no multiblock equivalent. Since the deprecation of LPF is also a long-term goal, I thought it might be appropriate for this multi to act as a Polarizer.

The MFE has a simple mechanic for tiering in the form of Electromagnets - tiered upgrades that you can insert into an Electromagnet Housing in order to give it bonuses. The first of these is craftable at IV (one is required for the multi to function) and there is one every following tier up to UHV.

This PR is currently a draft for two reasons:
-The structure is WIP, and there are some additional textures I would like to change
-I am not confident in the balance of the electromagnets and the recipes I have given them and would love some feedback!

![image](https://github.com/user-attachments/assets/fe2787f3-a794-4a44-ba1a-fd462d2321b8)

WIP Structure (The frame boxes are Magnetic Neodymium and Magnetic Samarium):
![image](https://github.com/user-attachments/assets/a632eeb4-ecf4-45b6-bac8-20333db8c4ea)
![image](https://github.com/user-attachments/assets/9ec665f5-dc41-401b-b3b1-f25c510d6610)

Electromagnets:
![image](https://github.com/user-attachments/assets/235db04b-2121-44eb-852b-99e63456a7b2)
![image](https://github.com/user-attachments/assets/d0443597-8627-4a72-a6e0-228ba1c52908)
![image](https://github.com/user-attachments/assets/c0df300b-4a38-413d-8dd1-a1a130cbdd89)
![image](https://github.com/user-attachments/assets/52d90416-d418-418d-b2d8-4c52c090ccb3)
![image](https://github.com/user-attachments/assets/66c16c52-1529-4a28-960a-1defa03e754b)

These numbers are of course approximate and I expect some of them will need to be changed! The Tengam Electromagnet in particular I expect will be controversial as it allows use of exotic hatches, so let me pre-emptively defend it:

The tengam magnet is designed around the current use of PA, specifically for Tengam processing. A PA with 64 UMV separators (down-tiered) effectively has 256 parallels, and it can use a TT 64A hatch to get full access to all of those parallels at UMV. I see players currently building 10+ PAs just for Tengam, and I do not want to increase spam by forcing players to make 30 of this multi once PA is removed. Due to this, I would like to keep the multi as strong as a few PAs would be, since it has a larger footprint and is a dedicated multiblock. I am not attached to the specific speed/eu/parallel numbers as long as it is ultimately within the ballpark of 2-3 PAs. 

I also understand that giving a multi access to laser hatches allows players to lazily pump in lots of power - if this is a problem, I propose just allowing use of multi-amp hatches and not laser. As said before, if players are not able to give this multi 64A UMV to utilize all of its parallels, I will have increased spam by an insane amount.

If all of this still sounds problematic, I can add a sixth tier of electromagnet to further gate these powers to ~UMV.

EDIT: I have disallowed laser. 1 Multi-amp hatch only! Also, turned down the numbers on the speed bonuses of all electromagnets.

Recipes:

Magnetic Flux Exhibitor controller, based on GT++ controller recipes:
![image](https://github.com/user-attachments/assets/75e91783-7c1f-4ba7-9122-e315d37d4c93)
1x Advanced Electromagnetic Separator IV
2x Conveyor Module (IV)
2x IV Circuit
4x Tungstensteel Plate

MagTech Casing (Also has the standard wrench + hammer shaped recipe):
![image](https://github.com/user-attachments/assets/9cc8091b-a7a4-4c95-89ac-3a56a0aefeca)
1x Titanium Frame Box
6x Tungstensteel Plate

Electromagnet Housing (I would switch iron bars to tungstensteel bars once these recipes are in coremod):
![image](https://github.com/user-attachments/assets/c68ca11a-cd66-48f0-9c65-5d1b6f664320)
1x Input Bus (IV)
4x Tungstensteel Bars
4x Polystyrene Sheet

Iron Electromagnet:
![image](https://github.com/user-attachments/assets/cceb41b8-4a3d-4c4a-b2dd-5745cceea84d)
8x Magnetic Iron Ring
8x Insane Voltage Coil
16x Superconductor IV Wire (2x)
1152L Molten Cobalt (8 Ingots)

Steel Electromagnet (All assembling line scans are the prior electromagnet):
![image](https://github.com/user-attachments/assets/9c2f674c-7bc4-4e8c-88ef-d1fa1ecf0ecc)
32x Nickel-Zinc Ferrite Plate
16x Magnetic Steel Ring
16x Ludicrous Voltage Coil
32x Superconductor LuV Wire (2x)
2x Field Generator (LuV)
8000L IC2 Coolant
2304L Molten Cobalt (16 Ingots)
2304L Molten Vanadium-Gallium (16 Ingots)

Neodymium Electromagnet:
![image](https://github.com/user-attachments/assets/f9a67588-1f9a-4e95-8ebe-aa24e8a8f899)
32x Nickel-Zinc Ferrite Plate
16x Magnetic Neodymium Ring
16x ZPM Voltage Coil
32x Superconductor ZPM Wire (4x)
2x Field Generator (ZPM)
16000L IC2 Coolant
4608L Molten Cobalt (32 Ingots)
2304L Molten Osmiridium (16 Ingots)

Samarium Electromagnet:
![image](https://github.com/user-attachments/assets/77b40e89-2def-4d63-9a47-397c881a17f2)
32x Double Neutronium Plate
32x Magnetic Samarium Ring
32x Ultimate Voltage Coil
64x Superconductor UV Wire (4x)
2x Field Generator (UV)
32000L IC2 Coolant
6912L Molten Cobalt (48 Ingots)
2304L Molten Fluxed Electrum (16 Ingots)

Tengam Electromagnet:
![image](https://github.com/user-attachments/assets/8831a71d-812d-4367-a311-85d00f3f47f5)
32x Double Cosmic Neutronium Plate
32x Attuned Tengam Ring
32x Highly Ultimate Voltage Coil
64x Superconductor UHV Wire (8x)
2x Field Generator (UHV)
64000L IC2 Coolant
9216L Molten Cobalt (64 Ingots)
2304L Molten Naquadria (16 Ingots)

**Texturework done by Bapy (@bapy_ on discord)**

2024-07-16 07:23 UTC, FourIsTheNumber commented
Quick update: Nerfed the electromagnet speed bonuses significantly and also disabled use of laser hatches with Tengam Electromagnet (Multi-amp still allowed)

2024-07-18 09:27 UTC, NotAPenguin0 requested changes
A couple minor things, but this looks mostly good. I personally think the balance is in a good place as it is now. At anything before the highest tier it's in line with the other GT++ multiblocks, and using the Tengam electromagnet makes it able to compete with PAs easily without being too overpowered.

Great job :)

2024-07-18 09:27 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +                    .shouldReject(t -> !t.mMagHatches.isEmpty())
If any additional mag hatch after the first should be rejected, it might be easier to get rid of the array entirely and just store a single `GT_MetaTileEntity_MagHatch`.

2024-07-18 09:27 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +    final String authorBaps = EnumChatFormatting.GOLD + "Ba" + EnumChatFormatting.LIGHT_PURPLE + "ps";
Might as well move Baps to the main author list

2024-07-18 09:27 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +        if (mCasingAmount < 64) return false;
Maybe extract this `64` into a `MIN_CASINGS` variable, considering it's also written out in the tooltip?

2024-07-18 09:27 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +            if (mExoticEnergyHatches.get(0)
The previous check for connection type is no longer necessary, since laser hatches are 256A minimum.

2024-07-18 09:27 UTC, NotAPenguin0 commented on src/main/java/gregtech/loaders/load/GT_Loader_MetaTileEntities_Recipes.java
> +        GT_ModHandler.addCraftingRecipe(
Personally I'd like to see all recipes in NHCoreMod, but I do understand that all other multis do not respect this and that it's annoying to have to open 2 PR.

2024-07-18 09:27 UTC, NotAPenguin0 commented on src/main/java/gregtech/loaders/postload/recipes/AssemblerRecipes.java
> +        GT_Values.RA.stdBuilder()
Same as above, would be nice to have in coremod instead.

2024-07-18 11:41 UTC, FourIsTheNumber commented on src/main/java/gregtech/loaders/load/GT_Loader_MetaTileEntities_Recipes.java
> +        GT_ModHandler.addCraftingRecipe(
Everything is in a coremod pr now, removed all recipes from gt5u

2024-07-18 12:30 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +            if (mExoticEnergyHatches.get(0)
👍

2024-07-18 12:30 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +        if (mCasingAmount < 64) return false;
👍

2024-07-18 12:30 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +    final String authorBaps = EnumChatFormatting.GOLD + "Ba" + EnumChatFormatting.LIGHT_PURPLE + "ps";
I gave Baps an author tag in the main list but I'm still not using it here - the author tags come with "Author: " prepended, so I have to manually use a different tag to get the "Author: author & author" formatting correct

2024-07-18 12:31 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java
> +                    + "100% Speed/n "
Made a tooltip builder method in MagnetTiers. Much cleaner!

2024-07-18 12:39 UTC, NotAPenguin0 approved these changes

2024-07-18 12:39 UTC, NotAPenguin0 commented
Looks all good to me, unmark as draft when you're ready to get it merged I suppose

2024-07-18 12:49 UTC, Dream-Master commented
@FourIsTheNumber

2024-07-18 13:37 UTC, Dream-Master commented
Oh I merged the core mod pr already

2024-07-18 13:52 UTC, FourIsTheNumber commented
> Oh I merged the core mod pr already

You can merge this now if you want, it's fully functional, but I might want to change the structure definition before 2.7 is out.

2024-07-18 13:58 UTC, merged