Mode switch button
GTNewHorizons/GT5-Unofficial pull request #2730
Opened 2024-07-18 07:53 UTC by FourIsTheNumber

This pr adds a GUI button to multi-machines and a handful of methods in MultiBlockBase that can be used to add more. No more screwdriver! I have tested these in my own world to make sure that it does not break bases - multis should migrate to the new system seamlessly.

Examples:
![image](https://github.com/user-attachments/assets/4aa6a8f9-7c96-48a4-8f40-9777042ffa09)
![image](https://github.com/user-attachments/assets/9fb77740-5efe-4446-891f-9c4fd54b3148)
![image](https://github.com/user-attachments/assets/e9a717c9-4da3-489f-b734-48e2f378c269)
![image](https://github.com/user-attachments/assets/dac642a4-ff7e-446e-99f8-830010f6f9ec)
![image](https://github.com/user-attachments/assets/386d838d-9495-46ed-b206-cf5c387bb654)

Technical details/changes: 
All of these machines previously used their own internal variable to track mode (sometimes integer, sometimes boolean). I have replaced all of these with an integer inherited from MultiBlockBase called machineMode, so I have made minor changes to these multis:
-Amazon Warehouse
-Large Processing Factory
-Industrial Material Press
-Ore Washing Plant
-Cutting Factory

In order to implement multi-machine behavior in the future, override the following methods:
supportsMachineModeSwitch() { return true; } - Will cause the button to appear
setMachineModeIcons() - Called when the GUI is built, use this to add (in order) a list of icon overlays
nextMachineMode() - Gets the next number in the mode sequence. By default this just alternates between 0-1. Override if you have more modes or want some other behavior.

2024-07-18 15:55 UTC, OneEyeMaker requested changes
Great job!
Few changes are needed to make it fully compatible with old saves.

And I have an idea, which you can *optionally* implement.
Right now an integer representation of machine mode can confuse. For example, what does mode 2 stand for? *IDK*. I should read whole class to find it out.

What about declaring `IMachineMode` interface with `id` and `name` (`texture`?) getters. Then create nested enums implementing this interface for every multi-mode machine. 
```
// pseudo-code!
// Define enum for all machine modes:
static enum MachineMode implements IMachineMode {
    WashPlant(0, "WashPlant"),
    SimpleWasher(1, "SimpleWasher"),
    ChemBath(2, "ChemBath");

//  ...
    public IMachineMode next() { /* ... */ }
}

// And use like this:
nbt.setInteger("machineMode", this.mode.id());
// or
if (this.mode == MachineMode.ChemPlant) { /* ... */ }
// or
for (IMachineMode mode : MachineMode.values()) {
    machineModeIcons.add(mode.texture());
}
```

2024-07-18 15:55 UTC, OneEyeMaker commented on src/main/java/gregtech/api/interfaces/modularui/ControllerWithOptionalFeatures.java
> +    int nextMachineMode();
* Please add documentation for each new method to avoid confusion. For example, right now it's unclear whether the `nextMachineMode` method should *change* the mode to the next one, or *just return* it.
* Add a (dummy) implementation for these methods (for backward compatibility).

2024-07-18 15:55 UTC, OneEyeMaker commented on src/main/java/gregtech/api/interfaces/modularui/ControllerWithOptionalFeatures.java
> +            button.addTooltip(StatCollector.translateToLocal(BUTTON_FORBIDDEN_TOOLTIP));
IMHO, the better solution would be not to add a button to the UI if mode switching is not supported.

2024-07-18 15:55 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialWashPlant.java
> +        return machineMode == 0 ? RecipeMaps.oreWasherRecipes
nitpick: You can use modern `switch` syntax in such cases for better readability.

2024-07-18 20:56 UTC, FourIsTheNumber commented on src/main/java/gregtech/api/interfaces/modularui/ControllerWithOptionalFeatures.java
> +            button.addTooltip(StatCollector.translateToLocal(BUTTON_FORBIDDEN_TOOLTIP));
Oops, this is leftover. It already doesn't render the button on the UI, this code is redundant. Removed

2024-07-19 03:01 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +        machineMode = aNBT.getInteger("machineMode");
Before, I used the original nbt tags for most of the machines, but for clarity I have switched to this. I left it out of canner and EMS because those multis were merged today, not much fear of breaking stuff - but I can just put it in if that's preferred.

2024-07-19 03:07 UTC, FourIsTheNumber commented
> Great job! Few changes are needed to make it fully compatible with old saves.
> 
> And I have an idea, which you can _optionally_ implement. Right now an integer representation of machine mode can confuse. For example, what does mode 2 stand for? _IDK_. I should read whole class to find it out.
> 
> What about declaring `IMachineMode` interface with `id` and `name` (`texture`?) getters. Then create nested enums implementing this interface for every multi-mode machine.
> 
> ```
> // pseudo-code!
> // Define enum for all machine modes:
> static enum MachineMode implements IMachineMode {
>     WashPlant(0, "WashPlant"),
>     SimpleWasher(1, "SimpleWasher"),
>     ChemBath(2, "ChemBath");
> 
> //  ...
>     public IMachineMode next() { /* ... */ }
> }
> 
> // And use like this:
> nbt.setInteger("machineMode", this.mode.id());
> // or
> if (this.mode == MachineMode.ChemPlant) { /* ... */ }
> // or
> for (IMachineMode mode : MachineMode.values()) {
>     machineModeIcons.add(mode.texture());
> }
> ```

I have attempted to do this, but I think my implementation is pretty rough. The more things I fixed, the more issues it caused, etc. This version should be working, but I'm not really happy with it and it added a LOT of boilerplate. Maybe it's not as bad as I think - but feel free to tell me I have to revert this, haha.

All other issues should be addressed.

2024-07-19 04:57 UTC, OneEyeMaker requested changes
Please keep working on backwards compatibility with existing save files. It would be very annoying if some machines in your base *silently* changed mode after the update.

And feel free to revert to integer implementation and constants if you think it's a more clear approach. That's what code reviews are for - to find best solution.

2024-07-19 04:57 UTC, OneEyeMaker commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +        super.loadNBTData(aNBT);
Don't forget about compatibility with existing saves. It would be annoying to reconfigure all machines *manually* after update.
Please, make sure that algorithm below is applied for all multi-mode machines.
```suggestion
        // Firstly, always try to read old tag to properly load existing saves.
        if (aNBT.hasKey("polarizerMode")) {
            machineMode = aNBT.getBoolean("polarizerMode") ? MachineMode.Polarizer :  MachineMode.Separator;
        }
        // Secondly, set mode to default one if previous step failed (and mode is still null).
        if (machineMode == null) {
            machineMode = MachineMode.Polarizer;
        }
        // Lastly, override mode from new tag. if such exists. That's already properly handled in base class, so just call:
        super.loadNBTData(aNBT);
```

2024-07-19 13:51 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +        super.loadNBTData(aNBT);
The machines I did not include this for were the MFE and TurboCan, which I had merged yesterday, so there is no real risk of anyone ever having built them - added it anyways, though. I guess there is no cost to doing this since loadNBT runs so rarely

2024-07-19 14:16 UTC, FourIsTheNumber commented
Tested this latest version in my base again and it reverted all the machines, which it didn't do originally. Workin on it

2024-07-19 15:11 UTC, FourIsTheNumber commented
Running the super for loadNBT before the migration fixes it. Prevents the migration from being overwritten.
Again, tested on a copy of my world and it seems to work properly:
-Old tags migrated
-Changes save after leave/rejoin

2024-07-19 15:57 UTC, OneEyeMaker requested changes
Your current implementation ignores new tag if old one is present.

2024-07-19 15:57 UTC, OneEyeMaker commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        }
Migration with `super.loadNBTData` won't work in your case, because this condition is wrong.
What happens with migration *before* `super.loadNBT` and current condition:
1) Migration properly loads machine mode from old tag.
2) This condition checks if multi-mode is supported (`true`).
3) This call overwrites machine mode from tag that *doesn't yet exist* and returns 0.

Whether machine supports multi-mode should only be checked on save. On load, you only need to check if tag exists:
```suggestion
        if (aNBT.hasKey("machineMode")) {
            machineMode = aNBT.getInteger("machineMode");
        }
```
And the whole logic will be:
1) Machine checks old tag and migrates to new system.
2) Machine calls `super.loadNBTData`.
3) if there's no `machineMode` tag (i. e., either it's old save or machine doesn't support multiple modes) then old (migrated) value is used. If `machineMode` tag is present then new tag is used.

2024-07-19 15:57 UTC, OneEyeMaker commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +        super.loadNBTData(aNBT);
Read the message above and make `super` call the last one.

2024-07-19 15:57 UTC, OneEyeMaker commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +    private final int MACHINEMODE_POLARIZER = 1;
Please mark these constants as `static'.

2024-07-19 16:11 UTC, FourIsTheNumber commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java
> +        }
Why is it wrong to ignore the new tag if there's an old tag? Since we no longer save the old tag, doesn't that mean it will (on first load) set to the new tag, and on all subsequent loads the old tag will not exist? I made these changes but I'm definitely a bit in over my head

2024-07-19 16:19 UTC, OneEyeMaker approved these changes
Great job! 👍 🚀 

P. S. I apologize for such a large number of requests on my part. But we have to keep backwards compatibility (so as not to annoy players by rebuilding their bases).

2024-07-19 16:27 UTC, merged

2024-07-19 16:33 UTC, FourIsTheNumber commented
> Great job! 👍 🚀
> 
> P. S. I apologize for such a large number of requests on my part. But we have to keep backwards compatibility (so as not to annoy players by rebuilding their bases).

No problem at all - I was trying to keep it compatible, just not being very successful. Thank you for reviewing!