Update multi-machines to display running mode in GUI
GTNewHorizons/GT5-Unofficial pull request #2755
Opened 2024-07-23 20:13 UTC by FourIsTheNumber

This is an extension of the mode switch button as it was not clear which mode the machine was in after changing modes with the gui button.

Now, the machine mode is always displayed at the top of multi-machine GUIs like this:
![image](https://github.com/user-attachments/assets/2bd512a9-0c60-487a-8495-26da9cae2e43)
![image](https://github.com/user-attachments/assets/eb2852b4-90c5-4eb9-9e47-818e78186993)
It updates immediately when the button is clicked.

2024-07-23 22:53 UTC, OneEyeMaker commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_IndustrialElectromagneticSeparator.java
> +        PlayerUtils.messagePlayer(aPlayer, "Now running in " + getMachineModeName() + " Mode.");
nitpicks:
* Since these methods now do (almost) the same thing, all the messaging logic can be moved to the parent class.
* Also, it would be nice to localize the string `Now running in %s Mode.`. Otherwise players will see this text in two languages (which will be confusing).

2024-07-24 00:00 UTC, FourIsTheNumber commented
These changes have made me realize I was overriding the normal screwdriver use for supporting single recipe locking. The only two multi-machines that support single recipe locking are the two new ones I added, but you cannot configure them via any tool currently. I'm not sure if this is a big enough issue to warrant fixing, but figured I should note it.

2024-07-24 08:09 UTC, OneEyeMaker requested changes
Sorry, my bad. I didn't notice that this change messes up with other logic. Please, revert methods handling screwdriver clicking and I'll approve this PR.

2024-07-24 16:23 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/misc/GMTE_AmazonPackager.java
> -        mLastRecipe = null;
Please also restore additional logic that some machines perform (such as resetting the last recipe).

2024-07-24 16:32 UTC, FourIsTheNumber commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/misc/GMTE_AmazonPackager.java
> -        mLastRecipe = null;
> Please also restore additional logic that some machines perform (such as resetting the last recipe).
This is redundant since it is already set to null in the base class used by gt++ machines
https://github.com/GTNewHorizons/GT5-Unofficial/blob/44350e2eca48bea0ae954a4e64352c526e2af14f/src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GregtechMeta_MultiBlockBase.java#L857-L863

2024-07-24 17:28 UTC, OneEyeMaker approved these changes

2024-07-25 01:14 UTC, merged