EOH fix & change
GTNewHorizons/GT5-Unofficial pull request #2792
Opened 2024-07-29 19:46 UTC by HoleFish

Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16279 (not tested)
Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16585
Change astral array EU formula again. (slight simplify)
Ability to insert planet block by rightclicking the controller with planet block in hand.
Limit astral array amount up to 10000.

2024-07-30 20:38 UTC, Persus1 commented
the changed power formula for astral arrays looks like a bit to overpowered or am i missing something?

With maxed eoh:
- T0 planets need around 100,5% of the previous power required
- T5 planets need around 97,64% of the previous power required
- T9+ planets need around 79,62% of the previous power required

while the earlier planets work just fine T9+ planets get a massive power reduction of over 20% which seems like a pretty noticeable buff.
(example of a 1024 parallel eoh)
![image](https://github.com/user-attachments/assets/e291c374-e4b7-466f-ba2f-5e4c249fcefa)

2024-07-31 16:57 UTC, HoleFish commented
oh that's a tooltip mistake

2024-08-02 15:09 UTC, GDCloudstrike requested changes
Thanks for the tierskip fix and adding the planet block functionality, that's a really nice qol change. 
About the astral array limit, what is the reason for implementing such a limit? I'm not against it existing (as you wont ever reach 10k astral arrays anyways), it's just a surprising change to see. 
A small nit regarding the limit number, if you want to keep it around the 10k range, I'd suggest changing it to 8637 instead of the flat 10k, as that is the closest 'step' in astral array amounts that grants more parallel, else you'd just have up to 1363 astral arrays sitting there doing nothing.

2024-08-02 15:09 UTC, GDCloudstrike commented on src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java
> +                "The maximum amount of Astral Array is " + formatNumbers(ASTRAL_ARRAY_LIMIT)
nit: "The maximum amount of stored Astral Arrays is " would be better here

2024-08-02 18:32 UTC, HoleFish commented
> what is the reason for implementing such a limit?

Ive seen some crazy players trying inserting infinite astral arrays which caused parallel overflow :trollface:

2024-08-02 23:08 UTC, GDCloudstrike approved these changes

2024-08-03 00:39 UTC, merged