Cryofreezer buff
GTNewHorizons/GT5-Unofficial pull request #2795
Opened 2024-07-30 04:59 UTC by Volence

In relation to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16521, just did all the requested buffs/matched with the volcanus stats and figured we could fine tune it from here.

2024-07-31 10:25 UTC, Steelux8 requested changes
The Volcanus is known to be very powerful, to the point of being overpowered, so there's no good reason to buff the Cryofreezer with the objective of having it match stats that the Volcanus currently has.

2024-07-31 16:11 UTC, HoleFish submitted a review, later dismissed

2024-07-31 16:11 UTC, HoleFish commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialVacuumFreezer.java
> +                                    .outOfFluid(Objects.requireNonNull(FluidUtils.getFluidStack("cryotheum", 10))));
you didnt actually change cyro consumption. you just changed the tips

2024-07-31 16:53 UTC, GirixK commented
> The Volcanus is known to be very powerful, to the point of being overpowered, so there's no good reason to buff the Cryofreezer with the objective of having it match stats that the Volcanus currently has.
> 
> The downtiering to IV and the reduction in Cryotheum consumption are probably a good starting point, until the balance of the multis is thoroughly calculated.

It's by no means thorough, but here's some current numbers:

- The Cryogenic Freezer currently works twice as fast, can do 4 parallels, and gets no discount on power usage
  - It requires an LuV tiered ABS, and even if this was changed, the current recipe costs an arm, a leg, a second arm, a second leg, and a liver (Computer cube, LuV circuit, a very long smelting time, accompanied by the slow freezing times)

- The Mega Vacuum Freezer gets no speed benefits, no power discounts, but has 256 parallels
  - This multi is by no means cheap, requiring 3 stacks of EV circuits and 9 stacks of HV pumps just for the controller, but the casings are borderline free at the point where you may need to consider upgrading your cooling beyond just a quad VF

In it's current state, the cryogenic freezer is borderline unusable due to the existence of the MVF
One of the main reasons the volcanus is prevalent over the MEBF is due to it's high efficiency and low coil cost

Gathering 800+ TPV coils or HSS-G coils is not cheap, especially when you know you'll have to replace them soon, so most would prefer to stick to the relatively cheaper volcanus and only swap to MEBF later on, when the coil upgrades don't come in as-quick succession

2024-07-31 17:33 UTC, Pxx500 commented
I'd say the volcanus is not overpowered, it's just pretty good at smelting ingots at the tier you are using (normal EBF gets better at low tier items due to perfect OCs from coil heat tiers). I'd say it's a pretty good niche for volcanus to fill and cryofreezer definitely deserves a buff.

2024-07-31 20:33 UTC, Volence commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialVacuumFreezer.java
> +                                    .outOfFluid(Objects.requireNonNull(FluidUtils.getFluidStack("cryotheum", 10))));
Oops that's embarrassing, changed it to 5 per 10 ticks instead of 10, thanks!

2024-07-31 21:08 UTC, chochem commented
just doing 2 buffs (tiering and cryo) for now and seeing where it goes sounds good to me

2024-07-31 21:23 UTC, Volence commented
To be honest I think having to deal with cryotheum and how easily available the mega is would make me lean towards mega still, but I'm ok changing to whatever the consensus is

2024-07-31 21:33 UTC, Steelux8 commented
The mega will eventually have to be dealt with, perhaps with mutes. One of the arguments towards buffing the Cryofreezer here is how cheap the mega is, which should not be a factor in the comparison to the EBF's variants, but the mega freezer is just a cube of nothing, so this happens.

2024-07-31 21:44 UTC, Volence commented
I think the comparisons happen just because the machines go hand in hand, they both have a normal, gt++ variant, and mega variant, and if you're able to just skip one for a slightly higher cost machine which is stronger and easier to maintain, it makes sense to look at all 3 from both sides. 

Why is it the volcanus used much more on the EBF side of things and not just skipped over to the mega EBF whereas the freezer side of things has this balance issue where the cryogenic is mostly just skipped?

2024-07-31 22:41 UTC, Steelux8 commented
> Why is it the volcanus used much more on the EBF side of things and not just skipped over to the mega EBF whereas the freezer side of things has this balance issue where the cryogenic is mostly just skipped?

Because the EBF, as a machine, is both expensive in materials and in EU/time costs, whereas the Vacuum Freezer is not. The Volcanus's bonuses are massive, making it very strong and arguably overpowered, so it is becomes nearly a requirement, whereas, otherwise, the EBF and its mega lag behind the Freezer and its mega in terms of speed.

2024-07-31 22:48 UTC, Volence commented
Yeah that question was more of a rhetorical to provoke the idea of why they're often compared to each other in terms of balance and why I think they should be in terms of a game design/balance perspective at least (with how they're currently balanced and function)

2024-08-01 02:18 UTC, GirixK commented
> so it becomes nearly a requirement

The processing demands grow, and so should your processing power. Do you really think you can expect players to keep setting up new sets of Quad-EBFs all the way until a MEBF?
One Quad-Volcanus has the smelting capacity of ~70 EBFs, or ~18 quad EBFs for lower tier materials, and only a bit over 2 quad EBFs for higher tier materials

You can take this as either "The Volcanus is overpowered", or as a "The smelting demand at that [IV] point of the game is too high for the EBF to handle, and the Volcanus just meets your demands for two tiers, at which point the MEBF may be a saving grace"...

...until you need to start smelting cosmic neutronium--have you seen the setups people have for cosmic neutronium? Arrays of 8x8 Volcani(?), purpose built to do nothing but smelt (cosmic) neutronium for potentially weeks

(for context, the fastest gate-achieving run by far is Cell 2, which used a setup like this for about a week, except they had two arrays of 64, one for Nt and one for SpNt, and a MEBF or two to help out)

Sure, the Volcanus may be overpowered in a vacuum (ha..!), I mean I just told you, it's almost 18 EBFs per, how could it not be overpowered?
But nerfing the Volcanus even as so little as to halve it's parallels, or decrease it's bonus speed, could lead to unintended consequences that potentially increase smelting time by--as previously mentioned--non-stop _weeks_ later down the line

I don't think it's a good idea to consider nerfing such a prevalent multi without considering everything it affects
Cosmic Neutronium smelting is just an example of one thing it affects, and in this case, the MEBF is just so inefficient comparatively

Here's a quote from someone who has a lot more experience than I do
> the eu usage is really important for volc...[it] means that cooking cosmic in volc gets full parallels without a 2/4 overclock and still saves on top of mebf
bc of discounts

How about some numbers?

### Volcanus Xenon/EFlux coil:
UV: 32.5s/ea, 442,368 EU/t
UHV: 16.2s/ea, 884,736 EU/t
2x UHV: 8.1s/ea, 3,538,944 EU/t

UV: 14,376,960 EU per ingot
UHV: 14,332,723.2 EU per ingot
2x UHV: 28,665,446.4 EU per ingot

### MEBF Xenon/EFlux coil:
UV: 53.55s/ea, 491,520 EU/t
UHV: s/ea, 2,088,960 EU/t
2x UHV: 3.15s/ea, 8,355,840 EU/t

UV: 26,320,896 EU per ingot
UHV: 26,320,896 EU per ingot
2x UHV: 26,320,896 EU per ingot
>volcanus is far more efficient until UEV where it falls out because mebf can continue to parallel, which outweighs the bonuses of volcanus once it hits max parallel
so running an array of volcani for cosmic at 2x uv hatch or 1x uhv hatch is just much more efficient than mebf

>mebf continues with that efficiency for i think 2 more overclocks and then it falls off into 2/4 overclocks and starts becoming even less efficient
at uev its at 68 parallels
yeah at uiv it would hit 256
and then beyond that it would start doing 2/4 overclocks and be less efficient

I hope these numbers can put into perspective as to why people prefer to use Volcani(??) over a MEBF
To sterilize the numbers a bit:
- At UV, the Volcanus is ~40% faster, and uses 10% less EU, this is as expected.
- At UHV, the MEBF is ~22% faster, but consumes 236% EU/t, 183% EU more per ingot
- At UEV (2x UHV), the MEBF finally beats out the Volcanus by ~61% faster smelting, and finally using ~8% less power per ingot
Unfortunately, you do not run twenty MEBFs at UIV, you run one at a unit that I like referring to as "Biggest laser hatch that won't cause my entire base to powerfail", name pending

It's much more economical to spam volcani(???) than to either make 20 MEBFs, or to just shove all your power into one

It's not as big of a task as the deprecation of PA, but nerfing it would definitely reveal how load-bearing the Volcanus is, and I feel like it's in your best interest to instead focus on addressing why people rely on it so much, an example I've been mentioning so much that I can give is comically long Neutronium and Cosmic Neutronium smelting times, I feel like that's something that should be addressed first, before touching the volcanus

In my eyes it's shameful that an IV-tiered multiblock remains not just relevant, but basically mandatory all the way up until the end of UEV, especially when a Mega side-grade exists

## cool (get it?) segue ooioe
> the EBF and its mega lag behind the Freezer and its mega in terms of speed.

This may be true for earlier tiers, but one thing the EBFs have over Vacs is that they scale, and they can scale _hard_, resulting in the overall ratio of MEBF to MVF being around 1:2 by the end

Say, are you aware the MVF is getting a Tier 2, don't know the details but it should tell you just how much you overrate the MVF, it's not as good as you think it is, and cyro does not, and can not ever compete, as long as the MVF is where it is, and how it is, It's not like you can nerf the MVF, it's already really bad, and you can't just move it to a later point in progression, not without making other massive changes and tweaks to the EBF & Cooling balance



I understand this is meant to be more of an earlier-game balance discussion, but you seem somewhat fixated on the Volcanus being overpowered, rather than the cryo being severely underpowered, so I feel the need to bring up later-game play for comparison and to contextualize how balancing the volcanus around IV-LuV absolutely nukes UHV->UIV progression, and how imperative coming up with an alternative solution is, be it lowering The Neutroniums' smelting times, or something more creative

Sorry for turning this into a volc/mebf math discussion, but it just felt fitting, if you wish to continue this elsewhere I'd gladly join a new issue or talk on discord

2024-08-01 16:54 UTC, Steelux8 commented
I was focused on earlier game progression, yes, and I am very aware of why the demand for EBFs and their alternatives is so high. I'm willing to bet the Volcanus was made this powerful because of the extreme demand for ingots that take 300s, 400s or longer to cook each, but that in itself was a poor balance decision because it is the demand that is too high and should be lowered, it's not the supply that should be raised to meet the demand.

I already suggested which buffs the Cryofreezer should get that I would be okay with.

2024-08-01 21:09 UTC, Volence commented
Updated to remove the buffs to parallel, eu usage, and speed. Also made cryo freezer and pyro ebf take 10L per second instead of 5 per half second, and got rid of the grace period of no fluids (about a second before it would shut down). As requested by Pxx500 https://discord.com/channels/181078474394566657/401118216228831252/1268625872248901642

2024-08-01 22:40 UTC, Pxx500 commented
I'd say all the buffs are warranted, except down tiering to IV, that means: Speed, EU, Parallels and cryo usage

2024-08-03 17:41 UTC, chochem approved these changes
Looking good. If it turns out to be weak and useless still in the future, we can always come back and buff it more.

2024-08-03 17:47 UTC, Pxx500 approved these changes
As chochem said, we can start with these changes

2024-08-04 02:07 UTC, merged