Make frame boxes no longer TileEntities
GTNewHorizons/GT5-Unofficial pull request #2799
Opened 2024-07-30 17:55 UTC by NotAPenguin0

This PR makes frame boxes regular blocks instead of TileEntities. They still accept covers like before, by spawning a TileEntity the moment they are right clicked with a cover. The majority of frame boxes in real bases won't need these of course, so this should improve lag significantly. Some notes:

- The TileEntity version of the frame box item still exists, but is hidden in NEI, no longer craftable and no longer used in recipes. This is a pretty big breaking change, since players will need to update all their AE patterns dealing with frames. If anyone knows a way around this, please let me know.
- There's currently an issue where frame boxes seem to forget they have covers attached on world load. The tileentity still exists, because I can right click the frame with a crowbar and the cover comes off, or I can add a new cover and the old ones show up as well. Might just be a rendering issue, but if anyone knows how to fix this I'd be grateful.
- On drop, frame boxes no longer keep all their cover settings, but instead simply drop the cover items they had attached to them. I think this is a fine tradeoff honestly.
- I couldn't get the correct breaking tool and harvest level to work, so someone please look over that.
- Existing frameboxes will need to be converted to the block version, @Connor-Colenso has told me to do this using postea, so I'll try that in a different PR over there I think? Or is this code that should go in GT as well?

2024-08-07 06:21 UTC, Dream-Master commented
draft until the structure check work

2024-08-11 10:52 UTC, OneEyeMaker commented on src/main/java/gregtech/api/util/GT_StructureUtility.java
> +                    return aFrameMaterial == material;
I think this change should be backward compatible (to prevent sudden breakage of existing multiblocks).

2024-08-11 10:59 UTC, NotAPenguin0 commented on src/main/java/gregtech/api/util/GT_StructureUtility.java
> +                    return aFrameMaterial == material;
I plan on writing a transformer using https://github.com/gtNewHorizons/postea that turns all in world TE frameboxes into their new block versions, which should solve this

2024-08-15 19:46 UTC, NotAPenguin0 commented
Aside from one rendering issue where covers are not rendered after reloading the world until the framebox is modified in some way, this should be ready now.

2024-08-15 20:02 UTC, NotAPenguin0 commented
Seems like I need to fix a crash somewhere first

2024-08-20 15:29 UTC, NotAPenguin0 commented
The difference is that as far as I know, ores always need that attached TileEntity to function properly, and I don't know enough about their behaviour to change that. The reason this whole thing can be removed from frame boxes is because they only need their TileEntity in rare cases and not by default, when they need this TE it's still spawned even with this PR.

2024-08-20 15:32 UTC, mitchej123 commented
> Hi! can you make ores be also regular block? because ores are also tile entities, i know it might be useless question/proposal, but it makes impossible to use cofh world or condensedores to make custom oregen with Gregtech

This doesn't belong here on an unrelated PR.

It needs a separate issue/PR, and might already have one.

2024-08-20 15:40 UTC, NotAPenguin0 commented
Yeah if anything it should go in a different PR

2024-08-20 15:54 UTC, mitchej123 commented
> but i can make issue, in case someone interested in remaking ores to be regular blocks

Check that there isn't one already.  Colen has wanted to do it and postea was implemented for that reason.  I know it hasn't yet been pushed forward on the implementation side.

2024-08-22 12:03 UTC, NotAPenguin0 commented
This also modifies the tesla tower code slightly, for two reasons:
- It used a custom implementation of `StructureUtility.ofFrame()`, making it unable to form with the new frame boxes. Simply switching to `ofFrame()` works.
- It crashed the machine on shutdown because of a missing null check so I just added that fix in here.

2024-08-23 17:38 UTC, OneEyeMaker requested changes
Looks good overall. Just needs a code cleanup.

2024-08-23 17:38 UTC, OneEyeMaker commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +        if (frameEntity == null) return false;
This line is not necessary since `instanceof` check below will do the trick.

2024-08-23 17:38 UTC, OneEyeMaker commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +            ((IGregTechTileEntity) tTileEntity).onEntityCollidedWithBlock(aWorld, aX, aY, aZ, collider);
```suggestion
        if (tTileEntity instanceof IGregTechTileEntity gtTE
            && gtTE.getMetaTileEntity() != null) {
            gtTE.onEntityCollidedWithBlock(aWorld, aX, aY, aZ, collider);
```

2024-08-23 17:38 UTC, OneEyeMaker commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +            ((IGregTechTileEntity) tTileEntity).onEntityCollidedWithBlock(aWorld, aX, aY, aZ, collider);
Same for other methods.

2024-08-23 17:38 UTC, OneEyeMaker commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +        if (tTileEntity != null) {
Null-check is not necessary.

2024-08-23 17:38 UTC, OneEyeMaker commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +        // It's probably fine, who makes facades out of frame boxes anyway.
IIRC, `getRenderColor(int meta)` is responsive for that. Try override this method and retrieve color from material.

2024-08-23 17:38 UTC, OneEyeMaker commented on src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
> +                || (GregTech_API.sGeneratedMaterials[meta] == Materials.Wood)) {
```suggestion
            if ((material != null && (material.mTypes & 0x2) != 0)
                || material == Materials.Wood) {
```

2024-08-23 17:38 UTC, OneEyeMaker commented on src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
> +                || (GregTech_API.sGeneratedMaterials[meta] == Materials.Wood)) {
And keep using this local variable below.

2024-08-23 20:27 UTC, OneEyeMaker commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +        super(Material.glass);
Please, change material of block. Otherwise BW will mark this block as HV glass.

2024-08-23 20:46 UTC, OneEyeMaker commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +        super(Material.glass);
Original material was `GT_Material_Machines`.

2024-08-23 20:53 UTC, OneEyeMaker commented
There are 2 minor visual inconsistencies:
* Because new frames use a different `ItemBlock` class, the original tooltip is missing (`MetaPipeEntity_Frames::getDescription`).
* Frames without a TileEntity don't display a grid when hovering over the block with a tool or cover.

2024-08-23 21:38 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +        return aMeta % 4;
I wasn't sure what to do for this, I think I copied the implementation from some other block, but I agree `aMeta % 4` probably doesn't make much sense, since `aMeta` is just the material index. Maybe there's a way to get a harvest level from the material, but if not I'd probably just make this a single fixed harvest level.

2024-08-23 21:58 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +        // It's probably fine, who makes facades out of frame boxes anyway.
I've tried implementing this, but it still doesn't seem to work very well and leaves them all white.

```java
    @Override
    public int getRenderColor(int meta) {
        Materials material = getMaterial(meta);
        short[] rgba = material.mRGBa;
        return (rgba[0] << 24) + (rgba[1] << 16) + (rgba[2] << 8) + rgba[3];
    }
```

I'm not 100% sure this implementation is correct, though if it ends up not working I think it's somewhat fine since these cover items are always hidden in NEI and I can't imagine anyone using them. Would be nice to get it fixed either way though, so if you can spot what's wrong here please let me know.

2024-08-23 22:12 UTC, NotAPenguin0 commented
![image](https://github.com/user-attachments/assets/5e4dae02-c892-4e52-a4cd-dbb0cbcefd32)
I've added the description and removed the glass material. Also, the wrench is now properly required to break a frame box, but the harvest level does still need work. 

I'm not sure what to do about displaying the grid really, I agree it's a bit of a weird inconsistency so it would be nice to have, but I'm not sure how without digging more into the arcana that is GT rendering code.

2024-08-23 23:38 UTC, Ethryan commented
Psst @NotAPenguin0 
https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/common/GT_Client.java#L309
Got something for you.

2024-08-24 04:45 UTC, OneEyeMaker commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +        return aMeta % 4;
AFAIK `Material::mToolQuality` describes the mining level of a *tool*, not the block made from the material. I think keeping it as it is now would be fine because one is equivalent to the old value.

2024-08-24 05:03 UTC, OneEyeMaker requested changes

2024-08-24 05:44 UTC, Caedis commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +            && !((BaseMetaTileEntity) tTileEntity).playerOwnsThis(aPlayer, true) ? -1.0F
instanceof casts is probably a better name to describe what you are wanting.

2024-08-24 06:22 UTC, OneEyeMaker commented
![2024-08-24_09 17 06](https://github.com/user-attachments/assets/4779e4c1-2798-4d76-9259-3c9ffdc921d0)

Add this method to `GT_Item_Frames`:
```java
    @Override
    public int getColorFromItemStack(ItemStack aStack, int aPass) {
        int meta = aStack.getItemDamage();
        Materials material = ((GT_Block_FrameBox) this.block()).getMaterial(meta);
        return (material.mRGBa[0] << 16) | (material.mRGBa[1] << 8) | material.mRGBa[2];
    }
```

Method `getRenderColor` can be safely removed from `GT_Block_FrameBox`.
Also, what about making `getMaterial` method static (to prevent such ugly casts)?

2024-08-24 09:04 UTC, NotAPenguin0 commented
![image](https://github.com/user-attachments/assets/31e37b39-0382-4d45-aa85-5c398bbfb299)
Much better, thanks @Ethryan

2024-08-24 10:36 UTC, OneEyeMaker commented on src/main/java/gregtech/common/GT_Client.java
> +        if (aTileEntity == null && aBlock instanceof GT_Block_FrameBox) {
I suggest adding a grid when hovering over the block with the wrench. Just add this condition to the `if` expression above.

2024-08-24 10:38 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/GT_Client.java
> +        if (aTileEntity == null && aBlock instanceof GT_Block_FrameBox) {
I thought about this, but since you can't really rotate the block frame boxes I'm not sure if this makes a lot of sense to do

2024-08-24 10:42 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/GT_Client.java
> +        if (aTileEntity == null && aBlock instanceof GT_Block_FrameBox) {
![image](https://github.com/user-attachments/assets/36b4dfae-404b-4439-a215-e40661af2ce3)
Adding it was easy though and I guess it doesn't hurt to have

2024-08-24 10:44 UTC, OneEyeMaker commented on src/main/java/gregtech/common/blocks/GT_Item_Frames.java
> +        aList.add(GT_LanguageManager.getTranslation("gt.blockframes." + aStack.getItemDamage() + ".tooltip"));
Why do you replace description when I suggest to just extend it? ;) IMHO it would be nice to have both lines (chemical element localized with key `gt.blockframes.<meta>.tooltip` and info about covers - `gt.blockmachines.gt_frame.desc.format`).

Anyway I leave this up to you.

2024-08-24 10:44 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/blocks/GT_Item_Frames.java
> +        aList.add(GT_LanguageManager.getTranslation("gt.blockframes." + aStack.getItemDamage() + ".tooltip"));
Oh yeah it could totally have both actually, I forgot I can add multiple lines

2024-08-24 10:49 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/blocks/GT_Item_Frames.java
> +        aList.add(GT_LanguageManager.getTranslation("gt.blockframes." + aStack.getItemDamage() + ".tooltip"));
![image](https://github.com/user-attachments/assets/196a758b-0ce4-4ab3-833d-274d4299bc0c)
That's better

2024-08-24 10:57 UTC, OneEyeMaker commented on src/main/java/gregtech/common/GT_Client.java
> +        if (aTileEntity == null && aBlock instanceof GT_Block_FrameBox) {
This grid should tell players that the wrench is the correct tool to *break* the block. Also, the grid should be present on regular blocks for compatibility with blocks with TileEntity. 
Grid is always displayed on TileEntity (regardless of the existence of covers). So it should be on a regular block too.

2024-08-24 11:00 UTC, OneEyeMaker approved these changes
Great job!

2024-08-24 12:26 UTC, NotAPenguin0 commented
Adding one more fix to make breaking and placing frame boxes cause structure updates like regular casing blocks do

2024-08-24 13:09 UTC, OneEyeMaker commented on src/main/java/gregtech/common/blocks/GT_Block_FrameBox.java
> +        GregTech_API.causeMachineUpdate(aWorld, aX, aY, aZ);
Should be called before `onBlockDestroyed` (according to `GT_Block_Machines`)

2024-08-24 13:12 UTC, merged