Fixed minor bugs with Steam Washer
GTNewHorizons/GT5-Unofficial pull request #2839
Opened 2024-08-06 17:31 UTC by evgengoldwar

Added mode change to the controller's gui

Added the ability for Steam Washer to fill water. Like Washer

2024-08-07 02:12 UTC, Nxer requested changes
Better to choose a timing to confirm the water block has been set, instead check water block in every recipe checking.

2024-08-07 02:12 UTC, Nxer commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamWasher.java
> +        }
```
        if (frontFacing == ForgeDirection.WEST) {
            xOffset -= 1;
            if (curFlip.isHorizontallyFlipped()) {
                zOffset -= 6;
            } else zOffset += 4;
        } else if (frontFacing == ForgeDirection.EAST) {
            xOffset -= 1;
            if (curFlip.isHorizontallyFlipped()) {
                zOffset += 4;
            } else zOffset -= 6;
        } else if (frontFacing == ForgeDirection.NORTH) {
            zOffset -= 1;
            if (curFlip.isHorizontallyFlipped()) {
                xOffset += 4;
            } else xOffset -= 6;
        } else if (frontFacing == ForgeDirection.SOUTH) {
            zOffset -= 1;
            if (curFlip.isHorizontallyFlipped()) {
                xOffset -= 6;
            } else xOffset += 4;
        }
```
Use `else if` to separate `frontFacing` like using `switch`

2024-08-07 13:35 UTC, evgengoldwar commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamWasher.java
> +        }
Fixed

2024-08-07 23:59 UTC, Nxer commented
![image](https://github.com/user-attachments/assets/87a85773-7070-4387-90a0-8685a3003a07)
Something wrong in structure definition.

2024-08-08 11:19 UTC, Nxer approved these changes
No problem overall.

2024-08-08 11:22 UTC, merged