Compressor Multiblock
GTNewHorizons/GT5-Unofficial pull request #2861
Opened 2024-08-10 13:05 UTC by FourIsTheNumber

Given two authors were just unknowingly working on similar multis, putting this up as a draft pr now. It's nearing completion but needs tuning.

This pr adds a tiered compressor multi to replace the LPF. Collaboration between me and @OlliedeLeeuw! 

Structure/casings/numbers WIP:

![image](https://github.com/user-attachments/assets/a7320bde-8cb3-4688-952f-bd7f3c64da32)
Tier 1: Just a compressor multi with TBD bonuses. Tiered around EV/IV.
Tier 2 (Hot Isostatic Pressing): Adding heating/cooling vents to the structure enables a heating cycle mechanic where the compressor goes through heating/cooling stages. Normal recipes gain bonuses during the heating phase. Additional recipes may require the HIP unit and these recipes will fail if executed during the wrong stage. Heat can be read via a sensor hatch. This upgrade is tiered around ZPM.

![image](https://github.com/user-attachments/assets/4e155ecc-6da8-4d25-a319-dde5f3f9d57a)
Tier 3 (Neutronium Compressor): The structure is entirely transformed. Now allows for the creation of Avaritia singularities and is intended to _fully deprecate_ Avaritia's singleblock Neutronium Compressor. It is therefore available at the same tier: UHV.

![image](https://github.com/user-attachments/assets/a89a9b55-95c5-49b9-a5f0-651fe5c00daf)
Tier 4 (Semi-Stable Black Hole Containment): The structure is again transformed into a black hole containment field. This allows for improved singularity recipes (such as the recipes which are currently in EIC for Eternal and Iron - along with upcoming recipes for Diamond, Copper, Cryptic, Spaghettic used in god forge). This structure adds a new mechanic - black hole stability. A catalyst must be inserted to open the black hole, at which point its stability will begin to decay to zero, with the following effects:

If the black hole is off, recipes which require black hole stability will not start.
If the black hole is off, recipes which don’t require black hole stability will run normally
If the black hole is on but unstable, recipes which require black hole stability will be voided constantly as they enter the machine.
If the black hole is on but unstable, recipes which do not require black hole stability will not be voided, but slowed down.
If the black hole is on and stable, recipes which do not require black hole stability will be sped up.

Stability loss can be slowed down significantly by running any recipes in the compressor. Stability loss can be entirely halted by inserting spacetime, but this costs an exponentially increasing amount of spacetime to maintain. To reset the stability to 100%, the player must insert a different catalyst which closes the black hole before opening another. 

This upgrade is tiered to UIV.

2024-08-10 13:05 UTC, OlliedeLeeuw commented
its still WIP but feedback is appreciated

2024-08-27 21:52 UTC, FourIsTheNumber commented
Closing pr for the freeze

2024-08-29 08:57 UTC, NotAPenguin0 requested changes
Nice work, juts a few minor nitpicks. Death to the LPF!

2024-08-29 08:57 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/compressor/GT_MetaTileEntity_BlackHoleCompressor.java
> +                if (recipe.mSpecialValue > 0) {
Should probably be checked using recipe metadata instead of special value.

2024-08-29 08:57 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/compressor/GT_MetaTileEntity_HIPCompressor.java
> +                    + "0"
Nit: All other parallel wording in the pack implies that the total parallel is `N * tier`, but with 0 that would become 0 recipes processed. There might be some better wording for this, but I can't come up with anything immediately so maybe this is fine to keep as it is.

2024-08-29 08:57 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/compressor/GT_MetaTileEntity_HIPCompressor.java
> +    void onCasingAdded() {
```suggestion
    private void onCasingAdded() {
```

2024-08-29 08:57 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/compressor/GT_MetaTileEntity_HIPCompressor.java
> +                if (recipe.mSpecialValue > 0) doingHIP = true;
Same thing as with the black hole compressor, might be nicer if this uses recipe metadata (as far as I know we're trying to deprecate `specialValue` as much as possible).

2024-08-29 08:57 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/compressor/GT_MetaTileEntity_HIPCompressor.java
> +        if (aMetaTileEntity instanceof GT_MetaTileEntity_HeatSensor) {
Use modern `instanceof` cast thing.

```suggestion
        if (aMetaTileEntity instanceof GT_MetaTileEntity_HeatSensor sensor) {
```

2024-08-29 08:57 UTC, NotAPenguin0 commented on src/main/java/gregtech/common/tileentities/machines/multi/compressor/GT_MetaTileEntity_NeutroniumCompressor.java
> +    void onCasingAdded() {
```suggestion
    private void onCasingAdded() {
```

2024-08-29 13:40 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/compressor/GT_MetaTileEntity_HIPCompressor.java
> +                    + "0"
Just changed it to 1 per tier, the overheat penalty is already enormous as is

2024-08-29 14:21 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/compressor/GT_MetaTileEntity_BlackHoleCompressor.java
> +                if (recipe.mSpecialValue > 0) {
Changed everything to the metadata formatter, no idea if I did it right

2024-08-29 15:15 UTC, NotAPenguin0 approved these changes

2024-08-29 15:15 UTC, merged