New Multi Autoclave
GTNewHorizons/GT5-Unofficial pull request #2863
Opened 2024-08-11 00:54 UTC by Volence

Started working on the new multi autoclave, as part of the process of building out singular machines for the Processing Factory. This is still a work in progress but being made as a draft app to make others more aware of it being worked on.

The basic shape so far:

![image](https://github.com/user-attachments/assets/fee92472-81d9-45df-aaff-629b4a2975ca)

Glass isn't planned on being tiered. At the top we have heating coils:

![image](https://github.com/user-attachments/assets/2a72334e-cb64-4a7b-b4f4-2bd9043e2173)

The internals are made of 2 rows of Pipe Casings (to transfer any fluids evenly), and 1 row of Item Pipe Casings for the solids in the center. They are surrounded by PTFE frame boxes (this seems to be very commonly used within autoclaves), the rest of the space is empty to allow the steam to move around to control temperature properly and push any actual air out (eg supersaturation):

![image](https://github.com/user-attachments/assets/4adba168-4fd5-4f9d-a046-158a5966f80c)

This is based loosely on images from large scale autoclaves, and just reading various data online:

![image](https://github.com/user-attachments/assets/de29802a-34a5-4d69-9f5f-b1af67c0df02)
![image](https://github.com/user-attachments/assets/7c276779-6a13-418d-adda-ac1eb6ec2385)
![image](https://github.com/user-attachments/assets/303399e7-b7c6-4e15-9e0c-7123dd60a80c)

I plan on allowing the 3 items to allow different bonuses (pipe casings, item pipe casings, and heating coils), haven't decided the numbers or specific bonuses on those yet though. I would also like to give a foggy appearance within the machine itself while it runs (but honestly I may need some help with this part).

2024-08-17 06:41 UTC, Volence commented
Just updated a bunch of the code, should all be working fine. Got new textures for the blocks thanks to juan_elcazador:

![image](https://github.com/user-attachments/assets/688ff0e1-8574-4084-9d46-54de6f5990ef)
![image](https://github.com/user-attachments/assets/87e038fc-1fdf-47b8-98a5-39463a988cb9)

2024-08-19 01:34 UTC, Zenovis commented
Anyone else think this multi is a little too big?

2024-08-19 01:35 UTC, FourIsTheNumber requested changes

2024-08-19 01:35 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +        // if (mCasingAmount < 8) return false;
```suggestion
       if (mCasingAmount < x) return false;
```
Need to enable a minimum casing here as well as adjust the tooltip

2024-08-19 01:35 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +    GT_MetaTileEntity_EnhancedMultiBlockBase<GT_MetaTileEntity_MultiAutoclave> implements ISurvivalConstructable {
```suggestion
    GT_MetaTileEntity_ExtendedPowerMultiBlockBase<GT_MetaTileEntity_MultiAutoclave> implements ISurvivalConstructable {
```
Use extended power base class, just ensures compatibility with high-tier energy hatches

2024-08-19 01:35 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +                    Pair.of(GregTech_API.sBlockCasings11, 7)),
It would be nice to add some kind of ofItemPipe() call so that these do not have to all be manually defined here (same for Fluid Pipe), especially for other multis. You can also then add a getter for pipe tier that is defined in structureutility instead of being manually defined in the base class for each multi. This is basically necessary if any item pipes are ever to be added in the future.

2024-08-19 01:35 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +            .addInfo("Each pipe casing (bronze, steel, titanium, tungstensteel)")
Just clarity nitpick - I know they are just called "pipe casing" but this feels a little unclear with the above line talking about item pipe casings, even with the clarification. I would consider renaming item pipe casings entirely to something like "Duct Casing" or some other similar word to avoid confusion (also, I just don't love "Item Pipe Casing" as a name personally)

2024-08-19 01:35 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +        getBaseMetaTileEntity().sendBlockEvent(GregTechTileClientEvents.CHANGE_CUSTOM_DATA, getUpdateData());
Why call this here? I believe the multis that use this are using it to adjust hatch texture to match the tiered casing, but I could be mistaken

2024-08-19 01:35 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +        currenttip.add("Heating Coil Level: " + EnumChatFormatting.WHITE + tag.getInteger("coilTier"));
Big fan of giving this kind of information in WAILA - maybe also provide the bonus each piece is giving? I like to see numbers :)

2024-08-19 01:35 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +                euModifier = (float) 1 / (fluidPipeTier);
This is a _huge_ eu reduction modifier especially for the first tiers. I would drastically change this equation, 25% eu cost is a much larger bonus than any other multi and it's available so early

2024-08-19 01:35 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +                speedBoost = 1F / (Math.min(1, (getCoilTier() + 1) / 2));
```suggestion
                speedBoost = 1F / (Math.max(1, (getCoilTier() + 1) / 2));
```
Am i misunderstanding or should this be max? Otherwise if you have a coil, say, tier 3, the speed boost is 1 / Math.min(1, 2), which is just 1.

Also I think this could use a different formula - this is your current scaling
![image](https://github.com/user-attachments/assets/4dceb7be-ef43-4c34-850a-75224b16e45a)
It very quickly approaches 500% speed, which is far too fast

2024-08-19 02:51 UTC, EnderProyects commented
> Anyone else think this multi is a little too big?

I think is good to have diferent sizes for multis

2024-08-19 02:52 UTC, Alastors commented
> Anyone else think this multi is a little too big? 

I'm chill with it, it's a penalty of nice looking multis

2024-08-25 03:19 UTC, Volence commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +        // if (mCasingAmount < 8) return false;
Adjusted, now needs minimum of 128 of the blocks

2024-08-25 03:19 UTC, Volence commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +    GT_MetaTileEntity_EnhancedMultiBlockBase<GT_MetaTileEntity_MultiAutoclave> implements ISurvivalConstructable {
Fixed this

2024-08-25 03:20 UTC, Volence commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +                    Pair.of(GregTech_API.sBlockCasings11, 7)),
Discussed this, going to come with a future update where pipe tiers are rebalanced a bit

2024-08-25 03:20 UTC, Volence commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +            .addInfo("Each pipe casing (bronze, steel, titanium, tungstensteel)")
Same as above

2024-08-25 03:20 UTC, Volence commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +        getBaseMetaTileEntity().sendBlockEvent(GregTechTileClientEvents.CHANGE_CUSTOM_DATA, getUpdateData());
Removed

2024-08-25 03:20 UTC, Volence commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +        currenttip.add("Heating Coil Level: " + EnumChatFormatting.WHITE + tag.getInteger("coilTier"));
Added those in

2024-08-25 03:21 UTC, Volence commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +                euModifier = (float) 1 / (fluidPipeTier);
Adjusted

2024-08-25 03:21 UTC, Volence commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +                speedBoost = 1F / (Math.min(1, (getCoilTier() + 1) / 2));
Adjusted

2024-08-25 03:47 UTC, FourIsTheNumber approved these changes

2024-08-25 03:47 UTC, FourIsTheNumber commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiAutoclave.java
> +            .addCasingInfoMin("Pressure Containment Casings", 1, false)
```suggestion
            .addCasingInfoMin("Pressure Containment Casings", 128, false)      
```
Put minimum here

2024-08-25 03:48 UTC, FourIsTheNumber commented
Looks good, nice work!

2024-08-25 03:48 UTC, Volence commented
Just finished all the review items, everything should be good to move forward

2024-08-25 08:42 UTC, BlueHero233 commented
think you forgot to run spotless mate

2024-08-25 11:50 UTC, merged