Single-block Steam Boiler item handling improvements
GTNewHorizons/GT5-Unofficial pull request #2871
Opened 2024-08-12 01:30 UTC by YannickMG

### Reason for change
Shift-clicking item stacks into boilers annoyingly always places them in the fluid container slot, which is almost never the intended behavior, as the only input you cannot automate early on is fuel items. This PR makes sure shift clicking item stacks into a boiler always a sensible outcome.

### Affected machines
- Small Coal Boiler
- High Pressure Coal Boiler
- High Pressure Lava Boiler
- Simple Solar Boiler
- High pressure Solar Boiler
- Advanced Boiler[LV]
- Advanced Boiler[MV]
- Advanced Boiler[HV]

### General changes
- Clicking slots, shift-clicking item stacks and item pipes can no longer place items in stacks where they do not belong.
  - Specifically: fuel slots only accept items the boiler will consume for fuel and fluid container input slots will only accept containers which the boiler will drain. (Water for all, and also lava for **High Pressure Lava Boiler**)
  - As a result, you can no longer place any items in output slots.
- Item pipes can no longer pull items from input slots.

### Machine specific changes
 - Solar Boilers still had 2 unusable stacks which were made unusable 2 years ago with intent to remove them at a later time. Now should be safe to remove them entirely, so this was done.

### Balance considerations
- None, as long as you don't consider annoying UI and item pipe interactions part of a hidden automation challenge.

### Backwards incompatible API changes
- `GT_MetaTileEntity_Boiler::createFuelSlot`'s return type was changed from `SlotWidget` to `Widget` which could in theory break overrides of that method which depend on `SlotWidget` specific functionality in the return value of `super()`, but a code search makes me confident that there is no such instance of this in the codebase that wasn't corrected as part of this PR.

## Media
![before](https://github.com/user-attachments/assets/3bdbbc68-e619-4230-b470-af9440f80132)
*Before*

![shift-click-works](https://github.com/user-attachments/assets/ab8d1f7e-33e2-458b-952f-9adc37ddc385)
*After*

![solar-boiler-old-slots](https://github.com/user-attachments/assets/a2ccebcb-23a9-4db6-ba03-0d97e4921958)
*These unusable slots are gone*

![image](https://github.com/user-attachments/assets/9bdf57b5-0df5-4cb5-90c7-883955929468)
*Pipes can't create this mess anymore*

2024-08-12 06:36 UTC, OneEyeMaker requested changes
Looks good overall.
I advise you not to stop there and suggest to improve readability and remove repeated code. I marked some examples of problematic/hardly readable code.

2024-08-12 06:36 UTC, OneEyeMaker commented on src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Bronze.java
> +            (Block.getBlockFromItem(fuelStack.getItem()) != null && // check if the block exists
I understand intent to combine whole logic in one expression. But I suggest to split this expression and cache some values for better readability (and maybe performance).
These values are:
* `Block.getBlockFromItem(...)` and
* `block.getUnlocalizedName().toLowerCase()`

2024-08-12 06:36 UTC, OneEyeMaker commented on src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Bronze.java
> +            == 0 ? GT_OreDictUnificator.get(OrePrefixes.dustTiny, (GT_Utility.isPartOfMaterials(stack, Materials.Lignite) || GT_Utility.isPartOfMaterials(stack, Materials.Coal)) ? Materials.DarkAsh :
I suggest caching the results of `GT_Utility.isPartOfMaterials(...)` method. This will make this method much more readable.
```suggestion
        boolean isCoal = GT_Utility.isPartOfMaterials(stack, Materials.Coal);
        boolean isCharcoal = GT_Utility.isPartOfMaterials(stack, Materials.Charcoal);
        boolean isLignite = GT_Utility.isPartOfMaterials(stack, Materials.Lignite);
        return XSTR.XSTR_INSTANCE.nextInt(isCoal || isCharcoal ? 3 : isLignite ? 8 : 2) == 0
             ? GT_OreDictUnificator.get(OrePrefixes.dustTiny, (isCoal || isLignite) ? Materials.DarkAsh : Materials.Ash, 1L)
              : null;
```

2024-08-13 23:41 UTC, YannickMG commented
I tried but had trouble refactoring by simply deduplicating and naming code, as it became clear the existing code didn't really follow a completely consistent logic and had a lot of special cases.

Instead I rewrote the combustion outcome code to be easier to read and reason about while still producing roughly similar outcomes, in this case ashes.

Namely, the chances of obtaining dust on burning anything other than a block are now as follows:
- Coal (1600) : 3, so 33% (Same as before)
- Charcoal (1600) : 3, so 33% (Same as before)
- Lignite (1200) : 4, so 25% (Was 12.5%)
- Sugar Charcoal (400) : 6, so 16.6% (Was 50%)

A block still guarantees a large dust, and only coal and lignite produce dark ashes. (Fixed an inconsistency where compressed charcoal would give dark ashes)

2024-08-14 04:08 UTC, OneEyeMaker approved these changes
I didn't expect *such* overhaul... But anyway code now looks much clearer. 
Thank you for good job!

2024-08-14 04:34 UTC, merged