Steam Multi change
GTNewHorizons/GT5-Unofficial pull request #2959
Opened 2024-08-24 18:56 UTC by evgengoldwar

Added craft for Forge Hammer

Renamed Steam Controller ID

Added Dark Steel Block For Steel tier

2024-08-24 19:43 UTC, OneEyeMaker commented
Why did you choose ***dark steel*** as the material for the next level of this multi? It makes no sense to me because all other steam machines use bronze and regular steel. Also, dark steel will be available at late MV (AFAIR), and at that point I'd prefer Advanced Mixer instead of this *steam-powered* monstrosity. This decision breaks whole progression (from my point of view).

2024-08-24 19:45 UTC, chochem commented
dark steel is just EBF I think in terms of gating. but really this whole thing was about all steam multis having MV recipes as I recall. though mixer MV recipes is pretty massive as you get diesel.

2024-08-24 20:03 UTC, OneEyeMaker requested changes
I can accept dark steel as gating measure.
But probably there should be more elegant way to achieve the same.

2024-08-24 20:03 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/steam/GregtechMetaTileEntity_SteamMixer.java
> +            } else simpleBlockTiers.put(Blocks.iron_block, 2);
Please, use unificator instead of hardcoding blocks. And add next tier only if block exists.
```suggestion
            ItemStack blockDarkSteel = GT_OreDictUnificator.get(OrePrefixes.block, Materials.DarkSteel, 1L);
            if (blockDarkSteel != null) {
                simpleBlockTiers.put(blockDarkSteel);
            }
```

2024-08-24 20:40 UTC, OneEyeMaker approved these changes

2024-08-24 21:20 UTC, NotAPenguin0 commented
> dark steel is just EBF I think in terms of gating. but really this whole thing was about all steam multis having MV recipes as I recall. though mixer MV recipes is pretty massive as you get diesel.

I think the mixer should blacklist fluids entirely, so just no input hatches in its structure.

2024-08-24 21:20 UTC, chochem commented
> > dark steel is just EBF I think in terms of gating. but really this whole thing was about all steam multis having MV recipes as I recall. though mixer MV recipes is pretty massive as you get diesel.
> 
> I think the mixer should blacklist fluids entirely, so just no input hatches in its structure.

diesel is cell. no fluids involved

2024-08-24 21:33 UTC, NotAPenguin0 commented
> > > dark steel is just EBF I think in terms of gating. but really this whole thing was about all steam multis having MV recipes as I recall. though mixer MV recipes is pretty massive as you get diesel.
> > 
> > 
> > I think the mixer should blacklist fluids entirely, so just no input hatches in its structure.
> 
> diesel is cell. no fluids involved

The steam mixer uses the `mixerNoCell` recipemap, so that recipe shouldn't be possible I think even with cells in an input bus

2024-08-24 22:47 UTC, PlayfulPiano commented
My personal recommendation/suggestion, after some discussions in the discord with @NotAPenguin0 , is to have the following recipe locks for Tier 1/2 Steam Multis:

Tier 1: IMO the recipe should use the HP singleblock machine types, but that would also mean the addition of singleblock variants for the mixer/centrifuge/washer/pump. Alternatively, these multis could require a different post-Steel / Rubber resource requirement, as to keep Tier 1s obtainable in roughly mid-late steam. Generally though, since these multis are the tier 1 variant and we already have 2 tier 1 multis in existence (squasher & grinder), both placed in mid-late steam, I believe that any new tier 1 steam multi should also be made accessible in roughly the same progression point.

Tier 2: The controllers should require Polyethylene & should be made in the LV Assembler. Polyethylene isn't obtainable immediately entering LV, meaning you will have to make some kind of oil based ethylene line (regular, seed, or fish). And the LV Assembler adds a good cost requirement in advance to have access to the multis. I don't agree with using Dark Steel as it is specifically post EBF (since the mixer is purely solid items and not liquids it cannot do a good chunk of good MV mixer recipes for what's it worth), and progression wise Dark Steel would mean having access to the cheaper Steel methods through the EBF. If we want to preserve the at-access expense of the higher tier multis, I would argue that it should be placed when Steel is still more difficult to obtain. Also, after thinking about it more, I don't agree that the recipe for any Tier 2 controller should include circuits at any capacity, for more thematic reasons.

2024-08-25 02:52 UTC, PlayfulPiano commented
One other thing I forgot to mention, now that I took a look at the tooltips for the new multis. I don't agree with 16x parallel for tier 2s. 

Assuming we keep the same bonuses for tier 1 multis as per the change done in https://github.com/GTNewHorizons/GTplusplus/pull/875 (aka 66.6% steam usage & 25% faster recipe duration for roughly 2x efficiency vs. a bronze singleblock), 16x parallel would mean the steam usage would roughly match with 2x efficiency vs. a bronze singleblock, or roughly close to a 2:1 L:EU/t conversion (akin to steam to EU generators at 100% efficiency). Problem here is that when you're doing an MV tier recipe, at 16A parallel, that requires a whopping 51080L/s throughput. You would literally need *Large Dark Steel Pipes* to get past that throughput requirement, & steam hatches currently only support 64000L buffer.

Instead of doubling the parallel for tier 2 multis, my recommendation would be to keep it at 8x parallel but improve the speed/L usage following one of the two following paths.

* Note: I did make a modification for the Tier 1 steam usage & recipe duration multipliers from 1.33 L:EU & 1.5x Duration to 1.25 L:EU & 1.6x Duration. This would lead to an exact 2x efficiency ratio without any issues for rounding at max parallel, but lower parallel quantities could still experience rounding inefficiencies, which imo makes logical sense here. Also, all values at 1x parallel assume rounding up decimals at the L/t point of calculation.
* Examples shown are based on macerating Crushed Iron Ore, which is a 2EU/t 20s recipe at 800EU total baseline.
* Assumption is that there would not be any standard overclock for LV recipes for Tier 2 multis (2x speed 4x cost).
* "Faster" and "Steam Usage" are relative to a Bronze Singleblock steam machine unless otherwise specified.

Option 1: Pure Efficiency Upgrade
Tier 1: 1.25:1 L:EU/t Cost (62.5% steam use), 1.6x Recipe Duration (25% faster) (2x Efficient vs Singleblocks)
16EU/t | 20L/t (400L/s) Cost, 32s, 10240EU | 12800L total (8x)
2EU/t | 3L/t (60L/s) Cost, 32s, 1280EU | 1920L total (1x)

Tier 2: 1.125:1 L:EU/t Cost (56.25% steam use), 1.25x Recipe Duration (60% faster vs Bronze, 20% slower vs Steel) (~2.8x Efficient vs Singleblocks)
16EU/t | 18L/t (360L/s) Cost, 25s, 8000EU | 9000L total (8x)
2EU/t | 3L/t (60L/s) Cost, 25s, 1000EU | 1500L total (1x)


Option 2: Mirroring High Pressure/Steel Logic
Tier 1: 1.25:1 L:EU/t Cost (62.5% steam use), 1.6x Recipe Duration (25% faster) (2x Efficient vs Singleblocks)
16EU/t | 20L/t (400L/s) Cost, 32s, 10240EU | 12800L total (8x)
2EU/t | 3L/t (60L/s) Cost, 32s, 1280EU | 1920L total (1x)

Tier 2: 2.5:2 L:EU/t Cost (62.5% steam use), 0.8x Recipe Duration (150% faster vs Bronze, 25% faster vs Steel) (2x Efficient vs Singleblocks)
32EU/t | 40L/t (800L/s) Cost, 16s, 10240EU | 12800L total (8x)
4EU/t | 5L/t (100L/s) Cost, 16s, 1280EU | 1600L total (1x)

Option 1 is the best for having an actual upgrade with regards to efficiency (i.e. less total steam required). It also has the lowest max EU -> L/s conversion when considering MV recipes (the max being 21600L/s at an 8A MV recipe). The slight drawback here is that Tier 2's actual ratios in terms of the current tooltip (steam use rate & % faster) is a lot less conventional, but this could always get changed to "uses X% less steam" instead. This still won't be more efficient than EU machines of course, which would otherwise require a 4x Efficiency rate to properly match.

Option 2 matches the best with, well, the actual Bronze -> Steel upgrade mechanic for singleblocks (2x speed but 2x cost vs. Bronze meaning 4L:2EU/t at 1x speed). It would also have the second highest max EU -> L/s conversion when considering MV recipes (the max being 48000L/s at an 8A MV recipe, only beaten out by the current proposal which has a max of 51080L/s at a 16A MV recipe). Therefore, like the current proposal of 16x parallel, max parallel usage would need significant throughput infrastructure, and it would in actuality be more expensive L/s wise compared to the current proposal at a per parallel basis. On the other hand, this would have the fastest processing speed across all 3 of the options I mentioned, being outright faster than the baseline recipe if you used an at tier singleblock machine (with the exception of LV OCs).


Anyways, hope this information here can either be considered for the steam multi changes or at least get used as a reference in the future.

2024-08-25 11:18 UTC, chochem commented
> Assuming we keep the same bonuses for tier 1 multis as per the change done in https://github.com/GTNewHorizons/GTplusplus/pull/875 (aka 66.6% steam usage & 25% faster recipe duration)

current ones are 33.3% faster as you can see in the PR you linked

2024-08-25 14:51 UTC, PlayfulPiano commented
> > Assuming we keep the same bonuses for tier 1 multis as per the change done in https://github.com/GTNewHorizons/GTplusplus/pull/875 (aka 66.6% steam usage & 25% faster recipe duration)
> 
> current ones are 33.3% faster as you can see in the PR you linked

Whoops sorry long post so I misplaced a number, thanks / fixed

2024-08-25 20:13 UTC, merged