Fix of Overflow Covert
GTNewHorizons/GT5-Unofficial pull request #3040
Opened 2024-09-04 01:07 UTC by Elkatra2

# Description Comming Soon Pls Don't Merge 

- [ ] TODO
- [ ] TODO
- [ ] TODO
...
- [ ] TODO

# Related Issues
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9561

2024-09-05 08:12 UTC, Elkatra2 commented
I just realized I done one thing wrong..., I used while loop for reducing  amount of fluid, when instead it was done every time when the cover activate, like if we set the valve to do voiding every seconds it my to do that every second reducing by `mTransferRate` time to fix ...

2024-09-05 18:27 UTC, Elkatra2 commented
find a few problems ...

2024-09-11 04:57 UTC, Dream-Master commented
If someone approve this I will add it to 2.7.0

2024-09-12 15:37 UTC, OneEyeMaker requested changes

2024-09-12 15:37 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +            fluid.amount -= Math.min(fluid.amount - data.voidingRate, data.voidingRate);
Current logic *dupes* fluid if voiding rate is greater than overflow point. It also doesn't stop voiding when reaches overflow point. 
```suggestion
            fluid.amount = Math.min(fluid.amount - data.voidingRate, data.overflowPoint);
```

2024-09-12 15:37 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +        if (data.overflowPoint == 0) return data;
You shouldn't prevent this cover from performing action when overflow point is set to zero. Its totally valid case - to void tank completely. Instead you should prevent any actions if voiding rate is 0. 
```suggestion
        if (data.voidingRate == 0) return data;
```

2024-09-12 15:37 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +        }
It's preferable to manipulate fluids using the `IFluidHandler` interface instead of juggling the *internal* `FluidStack`s directly. But if you can't find a better solution - this will do for now.

2024-09-12 15:37 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                .setSize(width, height)))
Please limit the voiding rate. The voiding rate should not be greater than the overflow value - it doesn't seem logical and leads to dupes.

2024-09-12 17:42 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                .setSize(width, height)))
> Please limit the voiding rate. The voiding rate should not be greater than the overflow value - it doesn't seem logical and leads to dupes.

I can reduce like they was before up to maxOverflowPoint / 10

2024-09-12 17:47 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +        }
> It's preferable to manipulate fluids using the `IFluidHandler` interface instead of juggling the _internal_ `FluidStack`s directly. But if you can't find a better solution - this will do for now.

The problem with IFluidHandler is I don't know what I should void, like before my changes it voided the first given storage, and not other if they are, it's caused the issue when in singleblock machine like chemical reactor it's void the input fluid instead of  output, but I can add also a condition for other tiles with `IFluidHandler` interface and void everything they has to a certain limit

2024-09-12 17:51 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +        if (data.overflowPoint == 0) return data;
I didn't think about that, thanks for the advice, I'll think through the logic better in the future if I change/add anything else

2024-09-12 17:51 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +        if (data.overflowPoint == 0) return data;
> You shouldn't prevent this cover from performing action when overflow point is set to zero. Its totally valid case - to void tank completely. Instead you should prevent any actions if voiding rate is 0.

I didn't think about that, thanks for the advice, I'll think through the logic better in the future if I change/add anything else

2024-09-12 17:54 UTC, Elkatra2 commented on src/main/java/gregtech/api/util/GTLanguageManager.java
> +        addStringLocalization("Interaction_DESCRIPTION_Index_322.1", "Voiding rate: ");
> Please add units to these 2 labels, otherwise it's unclear.

Sorry, I can't understand, what do you mean by units (due to my skill issue and maybe English), it should be for `"Overflow point: "` 322.0 ?

2024-09-12 17:59 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +            fluid.amount -= Math.min(fluid.amount - data.voidingRate, data.voidingRate);
> Current logic _dupes_ fluid if voiding rate is greater than overflow point. It also doesn't stop voiding when reaches overflow point.

The voiding rate can't be higher than `maxOverflowPoint` by the logic I written in widget or it's happens ?

2024-09-12 18:07 UTC, Elkatra2 commented on src/main/java/gregtech/api/util/GTLanguageManager.java
> +        addStringLocalization("Interaction_DESCRIPTION_Index_322.5", "Block fluid Output: ");
Forgot when done copypasting

2024-09-12 18:15 UTC, Elkatra2 commented
Maybe I should also clean a little bit positions coordinates due to a lot of +/- sings

2024-09-12 19:04 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +            fluid.amount -= Math.min(fluid.amount - data.voidingRate, data.voidingRate);
> Current logic _dupes_ fluid if voiding rate is greater than overflow point. It also doesn't stop voiding when reaches overflow point.
 
During refactoring I done a mess... as usual

2024-09-12 19:05 UTC, Elkatra2 commented
@OneEyeMaker thx for the review, I hope it help me to be more attentive and write better code

2024-09-12 20:34 UTC, OneEyeMaker commented on src/main/java/gregtech/api/util/GTLanguageManager.java
> +        addStringLocalization("Interaction_DESCRIPTION_Index_322.1", "Voiding rate: ");
By units I mean liters/buckets. Right now it's unclear what units this value is in. Tooltips should look like "Overflow Point (L):" and "Voiding Rate (L/update):".

2024-09-12 20:55 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +            fluid.amount -= Math.min(fluid.amount - data.voidingRate, data.voidingRate);
1) It's totally possible to set ***current*** voiding rate larger than overflow value (while you're speaking about maximum limit):
![image](https://github.com/user-attachments/assets/144527c3-a7d6-4d45-b0e6-6557262ef0a4)
2) I made mistake in my code sample. Of course there should be `max` function.
3) Your logic causes dupe:
* Given: amount is 2 000, voiding rate is 10 000 and overflow value is 1 000.
* `amount > overflowValue` - true.
* `Math.min(amount - voidingRate, amount)` = `Math.min(2000 - 10000, 2000)` = -8000.
* `amount -= Math.min(...)`: `amount -= -8000`. *Oops,  8 000 L of liquid is duped*.

So please use suggested code (with coreection: `max` instead of `min`).

2024-09-12 20:58 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +        }
Let's keep current logic *for now*, until we can find better solution.

2024-09-12 21:01 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                .setSize(width, height)))
The problem is not bound to `maxOverflowPoint`. The problem is that voiding rate can exceed ***current*** overflow value. And that isn't logical and leads to bugs/dupes.

2024-09-12 21:28 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +            fluid.amount -= Math.min(fluid.amount - data.voidingRate, data.voidingRate);
1) It's totally possible to set ***current*** voiding rate higher than overflow point.
![image](https://github.com/user-attachments/assets/15ee1cb4-45b0-4509-bf6b-b08679cd7fff)
2) I made a typo in suggested code. Of course there should be `max` instead of `min`.
3) How your current logic duplicates fluids:
* Given container with 1000 L of liquid, cover is set like shown on screen.
* Adding any amount of liquid causes condition `amount > overflowValue` to be true (1000 + 1 > 1000).
* `Math.min(amount - voidingRate, voidingRate)` = `Math.min(1001 - 10000, 10000)` = -8999
* `amount -= Math.min(...)` = `amount -= -8999`. *Oops, over 8000 L of liquid is duped!*

So please use suggested code (with exception: `max` instead of `min`).

2024-09-12 21:52 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +            fluid.amount -= Math.min(fluid.amount - data.voidingRate, data.voidingRate);
I have a lot of thing to learn :face_with_head_bandage:

2024-09-12 22:05 UTC, Elkatra2 commented on src/main/java/gregtech/api/util/GTLanguageManager.java
> +        addStringLocalization("Interaction_DESCRIPTION_Index_322.1", "Voiding rate: ");
Ok!

2024-09-12 22:07 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                .setSize(width, height)))
I'll try to figure out how to solve this, if not I will just remove the input for `voidingRate`

2024-09-12 22:50 UTC, Elkatra2 commented on src/main/java/gregtech/api/util/GTLanguageManager.java
> +        addStringLocalization("Interaction_DESCRIPTION_Index_322.1", "Voiding rate: ");
Done in commit https://github.com/GTNewHorizons/GT5-Unofficial/pull/3040/commits/3c1274c905452cea324eb5e411f1e99ead798933

2024-09-12 22:50 UTC, Elkatra2 commented on src/main/java/gregtech/api/util/GTLanguageManager.java
> +        addStringLocalization("Interaction_DESCRIPTION_Index_322.5", "Block fluid Output: ");
Done in commit https://github.com/GTNewHorizons/GT5-Unofficial/pull/3040/commits/3c1274c905452cea324eb5e411f1e99ead798933

2024-09-12 22:51 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +            fluid.amount -= Math.min(fluid.amount - data.voidingRate, data.voidingRate);
Done in commit https://github.com/GTNewHorizons/GT5-Unofficial/pull/3040/commits/3c1274c905452cea324eb5e411f1e99ead798933

2024-09-12 22:51 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +        if (data.overflowPoint == 0) return data;
Done in commit https://github.com/GTNewHorizons/GT5-Unofficial/pull/3040/commits/3c1274c905452cea324eb5e411f1e99ead798933

2024-09-12 22:52 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                .setSize(width, height)))
![image](https://github.com/user-attachments/assets/18e50ebc-3cd3-4cbd-b935-415bf387ab3c)
 
Now when updating the value it will assign to `overflowPoint` if it's pass the limit (I tested)
Done in commit https://github.com/GTNewHorizons/GT5-Unofficial/pull/3040/commits/3c1274c905452cea324eb5e411f1e99ead798933

2024-09-12 22:52 UTC, Elkatra2 commented
I need to change coordinates for text and inputs of `overflowPoint` and `voidingRate`, because the text is changed ...

2024-09-13 14:56 UTC, OneEyeMaker approved these changes
There're tiny thing to change or improve, but overall this feature is *ready* for testing.

2024-09-13 16:53 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +        return new OverflowValveData(0, 0, false, false);
![image](https://github.com/user-attachments/assets/c6c39221-c992-4300-9749-025ba59453fd)

Before may changes `Overflow Valve` used only `overflowPoint` as `aCoverData` value, and I think it's could be logic to set the legacy data like this right ?

Done in commit https://github.com/GTNewHorizons/GT5-Unofficial/pull/3040/commits/f38c6b3aacf20170a47ce5a7463e8db7058ede10

2024-09-13 17:51 UTC, Elkatra2 commented on src/main/java/gregtech/api/util/GTLanguageManager.java
> +        addStringLocalization("Interaction_DESCRIPTION_Index_322.0", "Overflow point (L):");
![image](https://github.com/user-attachments/assets/7d75b90d-59ab-4cb9-b303-c6bfc0a58f7c)

If I understand, I should add here ?

2024-09-13 20:59 UTC, Elkatra2 commented on src/main/java/gregtech/api/util/GTLanguageManager.java
> +        addStringLocalization("Interaction_DESCRIPTION_Index_322.0", "Overflow point (L):");
Can you see please https://github.com/GTNewHorizons/GT5-Unofficial/pull/3040/commits/11a8fe708c1bbf8f5efa1a09a533cb09a54b3f72

2024-09-13 21:12 UTC, Elkatra2 commented
@miozune thx for the review, can you please see if it's okay ? It's the first time I do something with `en_US.lang` and language translations

2024-09-13 23:06 UTC, merged