Add higher tiered fluid regulators
GTNewHorizons/GT5-Unofficial pull request #3061
Opened 2024-09-05 04:49 UTC by kstvr32

With changes from @Glease (GTNewHorizons/GT5-Unofficial#890), fluid regulators are no longer limited to storing their data in a single `int`. This makes it easy to add higher tiered fluid regulators to match the pumps.

This can be particularly useful for XL steam turbines in later tiers.

### Adds `Fluid Regulator (UHV)` and `Fluid Regulator (UEV)`

2024-09-05 08:29 UTC, OneEyeMaker commented on src/main/java/gregtech/api/enums/ItemList.java
> +    FluidRegulator_UEV,
Why don't you add all tiers (up to and including MAX)? At least for the sake of consistency with other components. Or is there some limitation or balance concern?

2024-09-05 10:35 UTC, kstvr32 commented on src/main/java/gregtech/api/enums/ItemList.java
> +    FluidRegulator_UEV,
Pumps pants UEV are just crafting components. They can’t be used as covers. 

I could add all of the regulators, leave them uncraftable and unusable.

2024-09-05 14:09 UTC, kstvr32 commented on src/main/java/gregtech/api/enums/ItemList.java
> +    FluidRegulator_UEV,
Thinking about it more, we could add even higher tiered pumps and regulators due to the change with how data is stored. Not sure if there are balance concerns.

2024-09-06 06:48 UTC, OneEyeMaker commented on src/main/java/gregtech/api/enums/ItemList.java
> +    FluidRegulator_UEV,
I think there should be regulators past UEV, at least as crafting components. If there are no balance concerns, then both pump and regulator covers can be registered for those tiers.

2024-09-07 09:56 UTC, chochem requested changes
this pr appears to be broken and crashes the nightly https://discord.com/channels/181078474394566657/603348502637969419/1281823994806276187

please test your changes next time

2024-09-07 09:59 UTC, chochem commented on src/main/java/gregtech/common/items/IDMetaItem01.java
> +    FluidRegulator_UEV(767);
yea those indices are definetly out of bounds

2024-09-07 11:26 UTC, kstvr32 commented on src/main/java/gregtech/common/items/IDMetaItem01.java
> +    FluidRegulator_UEV(767);
Can I move this to metaitem 2/3?

2024-09-07 11:35 UTC, kstvr32 commented
> this pr appears to be broken and crashes the nightly https://discord.com/channels/181078474394566657/603348502637969419/1281823994806276187
> 
> please test your changes next time

This ran fine on my local. I can check again this afternoon. 

I thought there was enough room given that the signed short can be 32,767 giving 767 non-generated items.

2024-09-07 11:38 UTC, chochem commented
> This ran fine on my local.

pretty sure thats impossible

2024-09-07 11:41 UTC, boubou19 commented
it's possible it worked in dev env, but not fullpack

2024-09-07 11:42 UTC, chochem commented
> it's possible it worked in dev env, but not fullpack

it wouldnt crash but the items still wouldnt be there

2024-09-07 11:47 UTC, kstvr32 commented
Sorry about that, I’ll fix this and implement @OneEyeMaker suggested changes. 

Do you have an recommendations on a free set of IDs I can move this to?

2024-09-07 13:15 UTC, Dream-Master commented
@kstvr32 please finish the pr add the missing tiers and test your pr first. After this you can undraft it and ask for a re review.

2024-09-07 21:20 UTC, kstvr32 commented on src/main/java/gregtech/common/items/IDMetaItem01.java
> +    FluidRegulator_UEV(767);
Moving to a free range near the beginning of item 1.

2024-09-07 22:33 UTC, kstvr32 commented
Fixed PR. Implemented UHV and UEV fluid regulators correctly.

Still need texture for UMV, UXV, and MAX.

@OneEyeMaker should I add recipes for UIV, UMV, UXV, and MAX if they are not used as covers and not as crafting components (yet)?

2024-09-08 05:51 UTC, Dream-Master commented
Sure add textures and recipes @kstvr32

2024-09-09 16:47 UTC, kstvr32 commented
Added textures and recipes, re-opening PR.

2024-09-09 16:48 UTC, kstvr32 commented on src/main/java/gregtech/api/enums/ItemList.java
> +    FluidRegulator_UEV,
Added fluid regulators all the way to MAX tier.

2024-09-10 10:34 UTC, boubou19 approved these changes

2024-09-10 12:02 UTC, merged