Godforge finale
GTNewHorizons/GT5-Unofficial pull request #3080
Opened 2024-09-06 01:27 UTC by GDCloudstrike

Hopefully final godforge PR. 

https://github.com/user-attachments/assets/aaae1efb-b74b-4419-93d5-cdb52bbabf8a

Doc: https://docs.google.com/document/d/1Lpt73uBFvdEvF_Wx0dfHodfxW4zCSyxlcRwd9XUhH-A/edit?usp=sharing

2024-09-06 14:46 UTC, Connor-Colenso commented on src/main/resources/assets/tectech/lang/en_US.lang
>  gt.blockmachines.multimachine.FOG.upgradeinfotext=Uprades are the heart and soul of the Godforge, they unlock most of its functionality and processing power. The upgrade tree can be accessed via its
Upgrades*

2024-09-06 14:48 UTC, Caedis commented
Make sure you reenable the multi outside of dev envs

2024-09-11 05:05 UTC, Dream-Master commented
@GDCloudstrike what is the status of this pr?

2024-09-12 01:00 UTC, GDCloudstrike commented
> @GDCloudstrike what is the status of this pr?

Should be mergeable by the weekend

2024-09-15 15:19 UTC, NotAPenguin0 requested changes
Almost good to go

2024-09-15 15:19 UTC, NotAPenguin0 commented on src/main/java/tectech/loader/recipe/Godforge.java
> +            ItemStack[] solids_t1_1step = { Materials.Lead.getDust(1), Materials.Plutonium241.getDust(1),
Naquadria plasma has disappeared

2024-09-15 15:19 UTC, NotAPenguin0 commented on src/main/java/tectech/loader/recipe/Godforge.java
> +                .specialValue(recipe.mSpecialValue);
Unless coil heat is irrelevant for the molten module, this should probably also copy over the `COIL_HEAT` metadata tag.

2024-09-15 17:31 UTC, NotAPenguin0 approved these changes

2024-09-15 17:38 UTC, merged