Add Antimatter Power Generation
GTNewHorizons/GT5-Unofficial pull request #3117
Opened 2024-09-08 12:58 UTC by S4mpsa

Adds a new endgame power option, **Semi-Stamble Antimatter**, for UIV, UMV and UXV power generation. Intended to tackle the reliance on Dysons in UIV and providing an alternative to EOH power generation (while still keeping EOHs the best power generation option overall).

Antimatter power consists of two new multiblocks, the Semi-Stable Antimatter Stabilization Sequencer (Antimatter Forge), and the Shielded Lagrangian Annihilation Matrix (Antimatter Generator).

### Antimatter Forge

![image](https://github.com/user-attachments/assets/56e3930c-cf30-41a1-b3c6-ecf4b64c834e)

![image](https://github.com/user-attachments/assets/e3203fa2-b337-4dbc-9ddd-52c66e79866e)

The Forge is used to convert Protomatter, a new fluid, into Antimatter. The forge has an unique automation challenge based on balancing the antimatter amount in 16 hatches, and optimizing the amount of antimatter with energy. The production of Antimatter can be upgraded with different fluids to make it scale to UMV and UXV, while introducing logistical complexity to sustaining Antimatter power.

The balancing math for Antimatter is quite complex, see the Sheet here: 
[AntimatterMath.xlsx](https://github.com/user-attachments/files/16922254/AntimatterMath.xlsx)

TL;DR
2.77T in UIV, 23.2T in UMV, 310T in UXV of net EU/t in Antimatter.
After running through generator:
3.84T in UIV, 40,8T in UMV, 800T in UXV

To reach these numbers, a large amount of tiered materials need to be supplied to the Forge and the Generator.
The energy values do not account for the energy lost for the creation of the booster fluids, and on average the player will have to spend 10-30% of the energy produced just to sustain the antimatter production.

### Antimatter Generator

![image](https://github.com/user-attachments/assets/c4e4aa00-0fa8-43fa-9a38-1de6214cde51)

![image](https://github.com/user-attachments/assets/9be41b6f-3ecb-48e0-94f6-2ca287266c25)

The generator converts Antimatter and Matter directly into EU. It can process infinite EU per operation, but is capped by the amount of source hatches. Varying Matter can be used to increase the EU of Antimatter in an exponential fashion, providing an incentive for the player to annihilate as much Antimatter as they can in a single cycle, without saturating the energy hatches.

Also supports wireless mode in UMV, but still respects the hatches.

This PR contains the base mechanics of Antimatter with fully functional machines, but is lacking recipes for protomatter and the machines themselves. Some rendering and texture work is still missing, but the multis should be in a state where they can be already tested.

2024-09-08 14:02 UTC, NotAPenguin0 commented on src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
> +        info[4] = "Probably makes: " + EnumChatFormatting.RED
nit: I think this is usually worded as `Probably generates...` in other generators.

```suggestion
        info[4] = "Probably generates: " + EnumChatFormatting.RED
```

2024-09-08 14:09 UTC, S4mpsa commented on src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
> +        info[4] = "Probably makes: " + EnumChatFormatting.RED
Need to redo this function entirely anyways, generator works in bursts instead of continously.

2024-09-08 14:28 UTC, S4mpsa commented
There's still some polish required (Scanner info and GUI). Shouldn't merge into main pack before I do those, but everything should work mechanics wise for testing in nightlies.

2024-09-11 19:59 UTC, Dream-Master commented
@S4mpsa any news here? Want to merge this soon. Will focus on beta version this weekend

2024-09-11 20:55 UTC, NotAPenguin0 requested changes

2024-09-11 20:55 UTC, NotAPenguin0 commented on src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
> +            long euCapacity = 0;
This can probably be computed once on structure check in `checkMachine` and then be cached

2024-09-11 20:55 UTC, NotAPenguin0 commented on src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
> +        nbt = (nbt == null) ? new NBTTagCompound() : nbt;
If the passed in `nbt` is `null` then saving to this new instance won't do anything anyway, so it being null wouldn't make much sense. I'm pretty sure this is never `null`, so that should probably be removed.

2024-09-11 20:55 UTC, NotAPenguin0 commented on src/main/java/goodgenerator/blocks/tileEntity/AntimatterGenerator.java
> +        nbt = (nbt == null) ? new NBTTagCompound() : nbt;
I don't think this can ever be null, but if it is you should just `return` instead of loading from an empty NBT tag

2024-09-11 20:55 UTC, NotAPenguin0 commented on src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
> +                return 0;
:caught:

2024-09-11 20:55 UTC, NotAPenguin0 commented on src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
> +                return (12 << 7) + 9;
Probably better to look these up from the block class instead of hardcoding

2024-09-11 20:55 UTC, NotAPenguin0 commented on src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
> +            for (int tier = 1; tier <= magneticUpgrades.length; tier++) {
This logic can definitely be abstracted into a function instead of copy pasting it 4 times

2024-09-11 20:55 UTC, NotAPenguin0 commented on src/main/java/goodgenerator/blocks/tileEntity/AntimatterForge.java
> +    public static final int M = 1_000_000;
This should probably be renamed to not conflict/be confused with `GTValues.M`

2024-09-12 11:32 UTC, NotAPenguin0 approved these changes

2024-09-12 12:03 UTC, merged