A simple cache for the furnace recipes, to avoid linear iteration
GTNewHorizons/GT5-Unofficial pull request #312
Opened 2020-09-07 21:38 UTC by repo-alt

(Should help with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6416)

2020-09-08 20:54 UTC, Glease commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +    private static HashMap<GT_ItemStack, ItemStack> smeltingRecipeCache = new LinkedHashMap<>();
Maybe use guava Cache instead? I feel like an unbounded cache will not be *that* helpful and can cause its own problems.

2020-09-08 21:01 UTC, repo-alt commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +    private static HashMap<GT_ItemStack, ItemStack> smeltingRecipeCache = new LinkedHashMap<>();
Any hash map will be better than vanilla array, regardless of the size. Guava has it's own hash map implementation?

2020-09-08 23:35 UTC, Glease commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +    private static HashMap<GT_ItemStack, ItemStack> smeltingRecipeCache = new LinkedHashMap<>();
See [this page](https://github.com/google/guava/wiki/CachesExplained). The thing I want most is size constraint.

2020-09-09 05:15 UTC, repo-alt commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +    private static HashMap<GT_ItemStack, ItemStack> smeltingRecipeCache = new LinkedHashMap<>();
Wow, that's a good stuff. I wish they allowed overriding comparison operator too

2020-09-09 05:45 UTC, draknyte1 requested changes
Rename smeltingRecipeCache to sSmeltingRecipeCache.

2020-09-09 11:31 UTC, merged

2020-09-09 11:31 UTC, Dream-Master commented
AlkalusToday at 1:31 PM
Looks fine.

2020-09-09 11:33 UTC, draknyte1 commented
You merged it before I could actually leave the approved review. 
2fast4me

2020-09-09 12:49 UTC, Dream-Master commented
@draknyte1 sorry. So should i revert it ?

2020-09-09 12:55 UTC, draknyte1 commented
No no no. All is good. 👍