Fix for sense block digging (now only leaves)
GTNewHorizons/GT5-Unofficial pull request #314
Opened 2020-09-10 16:04 UTC by 4gname

2020-09-10 16:18 UTC, draknyte1 requested changes
I’d check if the block is leaves by ore dictionary, not just vanilla.

2020-09-10 16:27 UTC, 4gname commented
Why hasn't anyone done it for so many years?

2020-09-10 16:38 UTC, repo-alt commented
I remember somebody fixing this stuff, (or at least talking that he will)

2020-09-10 16:48 UTC, draknyte1 commented
> Why hasn't anyone done it for so many years?

Probably because nobody uses the item.

2020-09-11 06:46 UTC, bartimaeusnek commented
I don't quite get the usefulness of this pr...

2020-09-11 09:15 UTC, draknyte1 commented
> I don't quite get the usefulness of this pr...

A sense can currently be used to mine anything, Totally not intended.

2020-09-12 11:31 UTC, bartimaeusnek commented
> 
> 
> > I don't quite get the usefulness of this pr...
> 
> A sense can currently be used to mine anything, Totally not intended.

It can be used to mine everything that doesnt need any tools, thats correct, i literally changed that a while ago.

2020-09-12 14:07 UTC, 4gname commented
> It can be used to mine everything that doesnt need any tools, thats correct, i literally changed that a while ago.

No, you didn't fix this problem

2020-09-12 20:04 UTC, Prometheus0000 commented
This could be easily checked by going ingame and trying it out if anyone wants to. I thought it was for harvesting crops, but that seems like a worse use than getting rid of leaves anyway.

2020-09-15 19:38 UTC, 4gname commented
> I’d check if the block is leaves by ore dictionary, not just vanilla.

I will correct the commit later, add instanceof?

2020-09-16 05:51 UTC, 4gname commented on src/main/java/gregtech/common/tools/GT_Tool_Sense.java
> +                        if (!(gBlock instanceof BlockLeaves)) {
I don't know how to check oredict for a block from the world

2020-09-17 07:29 UTC, Dream-Master commented
@draknyte1 can this be merged ?

2020-09-17 09:58 UTC, bartimaeusnek commented
1. The change need to be applied to ``isMinableBlock`` not ``convertBlockDrops``
2. I don't see the point in restricting this to leaves and plants only.

2020-09-17 10:27 UTC, repo-alt commented
Because digging dirt with a scythe makes so much sense...

2020-09-17 10:30 UTC, 4gname commented
> 1. The change need to be applied to `isMinableBlock` not `convertBlockDrops`
> 2. I don't see the point in restricting this to leaves and plants only.

isMinableBlock this is only for breaking the block, and cutting out along the radius is already convertBlockDrops

2020-09-17 10:42 UTC, bartimaeusnek commented
> 
> 
> Because digging dirt with a scythe makes so much sense...

So does punching trees, or picking up sand/gravel/dirt with your hands.

2020-09-17 10:57 UTC, 4gname commented
> > Because digging dirt with a scythe makes so much sense...
> 
> So does punching trees, or picking up sand/gravel/dirt with your hands.

no, you do not dig around the radius with your hands

2020-09-17 11:14 UTC, Prometheus0000 commented
Does it really make sense for a scythe to dig dirt in a 5x5 area? Or chop wood? Plus we have specialized tools for those things.

2020-09-17 11:36 UTC, bartimaeusnek commented
> Does it really make sense for a scythe to dig dirt in a 5x5 area? Or chop wood? Plus we have specialized tools for those things.

yupp, which have a speed boost, that the scythe does not provide.

2020-09-18 04:17 UTC, Cleista commented
I like not dismantling my entire base when trying to harvest crops with a Sense. 

- [Try to harvest crops](https://cdn.discordapp.com/attachments/181078474394566657/728317113197920417/unknown.png)
- [Accidentally dismantle base instead](https://cdn.discordapp.com/attachments/181078474394566657/728317188267835401/unknown.png)

This is **not expected to occur** and I doubt people not named bart will genuinely disagree with me on this claim, considering other users have raised issues like [#5956](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5956) specifically regarding this nonsensical behavior of the Sense tool that prevents it from being used for _the one task it's designed to do_: crop and leaf harvesting.

2020-09-18 05:14 UTC, 4gname commented
> I like not dismantling my entire base when trying to harvest crops with a Sense.
> 
> * [Try to harvest crops](https://cdn.discordapp.com/attachments/181078474394566657/728317113197920417/unknown.png)
> * [Accidentally dismantle base instead](https://cdn.discordapp.com/attachments/181078474394566657/728317188267835401/unknown.png)
> 
> This is **not expected to occur** and I doubt people not named bart will genuinely disagree with me on this claim, considering other users have raised issues like [#5956](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5956) specifically regarding this nonsensical behavior of the Sense tool that prevents it from being used for _the one task it's designed to do_: crop and leaf harvesting.

I explain this by the fact that Bart never played gregtech, but only codes it

2020-09-18 05:36 UTC, Dream-Master commented
I reopen it. Feel free to discuss further.

2020-09-19 14:39 UTC, repo-alt commented on src/main/java/gregtech/common/tools/GT_Tool_Sense.java
> +                        if (!(gBlock instanceof BlockLeaves)) {
There is literally Block.isLeaves function

2020-09-19 14:41 UTC, repo-alt commented on src/main/java/gregtech/common/tools/GT_Tool_Sense.java
> +                        if (!(gBlock instanceof BlockLeaves)) {
isFoliage is probably also worth checking.

2020-09-19 15:06 UTC, bartimaeusnek commented
> > I like not dismantling my entire base when trying to harvest crops with a Sense.
> > 
> > * [Try to harvest crops](https://cdn.discordapp.com/attachments/181078474394566657/728317113197920417/unknown.png)
> > * [Accidentally dismantle base instead](https://cdn.discordapp.com/attachments/181078474394566657/728317188267835401/unknown.png)
> > 
> > This is **not expected to occur** and I doubt people not named bart will genuinely disagree with me on this claim, considering other users have raised issues like [#5956](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5956) specifically regarding this nonsensical behavior of the Sense tool that prevents it from being used for _the one task it's designed to do_: crop and leaf harvesting.
> 
> I explain this by the fact that Bart never played gregtech, but only codes it

Just having an UV Base on Delta doesn't count, right?

No, it doesn't make SENSE to impair your ability to harvest shit you can w/o any tool.

2020-10-02 06:48 UTC, closed without merging