Fix of new Overflow Valve
GTNewHorizons/GT5-Unofficial pull request #3186
Opened 2024-09-14 16:47 UTC by Elkatra2

### Related merged issue :
https://github.com/GTNewHorizons/GT5-Unofficial/pull/3040

### 1. GUI Fix
#### Before
![image](https://github.com/user-attachments/assets/09121be1-76e8-40f4-a127-b19c98151cab)

#### After (can be changed !), and example of default state for LV
![image](https://github.com/user-attachments/assets/0f9fcd1c-caca-47af-97ce-fa3a2e1a9faa)

### 2. Fixing logic

1. Now it's no possible, to set `overflowPoint` lower than `voidingRate` when changing values in GUI.
2. When the Overflow Valve is loading from old save (before changes), it will set the `voidingRate` to `maxOverflowPoint / 10`, to prevent from ruining infrastructure, but with new rules in 1 it will be no more possible

### 3. Other bugs to solve

The `Block Fluid Output` button don't work for `MTEBasicTank` if the `Fluid Auto-Output` button is pushed

2024-09-15 18:20 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                coverData.voidingRate = Math.min(state.intValue(), coverData.voidingRate);
If you're planning to add logic for limiting voiding rate, please do it everywhere. Right now it's possible to change overflow point below voiding rate with right-click or screwdriver.

2024-09-15 18:29 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                coverData.voidingRate = Math.min(state.intValue(), coverData.voidingRate);
Alternatively you can make voiding rate unrestricted (by removing these `min` calls). This will allow to void fluids as fast as possible and removes need to handle special case with 0 overflow point.

2024-09-16 00:18 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                coverData.voidingRate = Math.min(state.intValue(), coverData.voidingRate);
Tottaly forgot about screwdriver :fail:

2024-09-16 00:43 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                coverData.voidingRate = Math.min(state.intValue(), coverData.voidingRate);
> Alternatively you can make voiding rate unrestricted (by removing these `min` calls). This will allow to void fluids as fast as possible and removes need to handle special case with 0 overflow point.

With the current logic, it's like they are not possible cases when the fluid is duping, because `fluid.amount = max(fluid.amount - voidingRate, overflowPoint) >= 0` so maybe I can just remove every restrict for  `voidingRate` like before from `0` to `maxOverflowPoint` and change the condition when the voiding is not possible with `overflowPoint == 0` (new button to On/Off the cover ? On/Off by redstone ?), or just add again (without forgetting I hope) restricts to `voidingRate` where `overflowPoint` is changing the data, but maybe if we let `voidingRate` to be chosen from `0` to `maxOverflowPoint` like `overflowPoint` it's can be in theory somewhere useful.

2024-09-16 09:18 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                coverData.voidingRate = Math.min(state.intValue(), coverData.voidingRate);
No need in additional buttons, redstone interaction or crafting recipes. This feature is no longer in the stage of inventing new mechanics - it is in the stage of fixing bugs. All you need to do is to choose: should voiding rate be restricted or not. And then either add `Math.min` *everywhere* overflow value changes or remove it *everywhere*.

2024-09-16 18:08 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +                                coverData.voidingRate = Math.min(state.intValue(), coverData.voidingRate);
@OneEyeMaker I hope this time they are not issue

2024-09-17 11:38 UTC, OneEyeMaker requested changes

2024-09-17 11:38 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/items/MetaGeneratedGregtechItems.java
> +                "Cover Overflow Valve (LV)",
No need in word "Cover" in localized name. Conveyors, fluid pumps and other covers don't have one, so this component shouldn't too.

2024-09-17 11:38 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +        if (data.overflowPoint == 0) return data;
If you have decided to prevent the cover from working when the overflow value is set to zero then you also should disable it when voiding rate equals 0. Since with zero voiding rate this cover will void nothing anyway.
```suggestion
        if (data.overflowPoint == 0 || data.voidingRate == 0) return data;
```

2024-09-18 07:45 UTC, Elkatra2 commented on src/main/java/gtPlusPlus/xmod/gregtech/common/covers/CoverOverflowValve.java
> +        if (data.overflowPoint == 0) return data;
@OneEyeMaker I hope it's finally done

2024-09-18 08:58 UTC, OneEyeMaker approved these changes

2024-09-18 09:00 UTC, merged