Update BaseMetaTileEntity.java
GTNewHorizons/GT5-Unofficial pull request #320
Opened 2020-10-01 19:08 UTC by kaziu687

Fixes problem that may cause explosion on Thermos servers with load-chunks-on-request: false and it's raining/thundering.

When machine stays at the edge of loaded chunk (where siblings is not loaded) worldObj.getPrecipitationHeight will return -1 (cuz chunk wont be loaded on request). Machine will explode even if there is a roof.

2020-10-01 20:05 UTC, Glease requested changes

2020-10-01 20:05 UTC, Glease commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +                                            || (getCoverIDAtSide((byte) 2) == 0 && worldObj.getPrecipitationHeight(xCoord, zCoord - 1) - 1 < yCoord && worldObj.getPrecipitationHeight(xCoord, zCoord -
`worldObj.getPrecipitationHeight()` is not something as trivial as `Hashmap::get`. Better not invoke it twice, especially when the bulk of TEs will not be residing on the edge of the chunk.

2020-10-01 23:27 UTC, Glease approved these changes
Looking good. Still can't believe thermos is that aggressive in the sense of optimization. It would make sense to add a comment for future reference, but one can always trace back to this commit & PR via git blame and understand the background. I think either doing it or not doing it is acceptable. I'll leave it upon you to decide that.

2020-10-02 04:39 UTC, merged

2020-10-02 07:47 UTC, kaziu687 commented
By default Thermos has load-chunk-on-request feature enabled so problem didn't occurs. At server with ~200 active users by day loading on request will result with huge and constant tps drop (near everything work like an chunkloader).