Remove some GT tools
GTNewHorizons/GT5-Unofficial pull request #3203
Opened 2024-09-15 23:55 UTC by Connor-Colenso

Removes all GT pickaxes, shovels, hoes, axes and swords. Adds a new flint tool for each, that is a separate item. Each current item will be converted into a flint equivalent tool. Both axes and swords will retain their fire aspect enchant and new crafted tools will also retain this. Tested postea transforms and all seems to work fine. Will need some QB adjustments but nothing major. Main progression should be unchanged. I believe this is a good step to untangling the GT hell that is every item sharing an ID.

Removed the GT sense, with no replacement, just because this tool is rather pointless. The head was used in one recipe, and I just replaced it with a plate of the same material, no substantial change in balance.

This should hopefully help speed up pack load (very) marginally as it will likely result in a reduction of 100s of random unused recipes for tons of useless GT tools with random materials.

2024-09-16 00:12 UTC, boubou19 requested changes

2024-09-16 00:12 UTC, boubou19 commented on src/main/java/gregtech/common/items/MetaGeneratedItem02.java
>              OrePrefixes.toolHeadPlow,
use `___placeholder___` instead of removing the prefixes, otherwise you shift all the meta ids

2024-09-16 00:23 UTC, boubou19 commented
Sense should be added back but as a single item, its AOE cleaning ability is nice. (or we add AOE to mattocks)

2024-09-16 08:05 UTC, LazyFleshWasTaken commented
Can we at least keep gt pick in? For some people that don't want to use tinker's for some time at the beginning they can do flint pick -> small iron/banded iron/magnetite/whatever ore -> ingots -> hammer -> gt pick -> full ores.

Or, if the gt tools are removed, can the vanilla ones be re-enabled with a matching recipe to not remove the alternative progression?

2024-09-16 08:23 UTC, boubou19 commented
> Can we at least keep gt pick in? For some people that don't want to use tinker's for some time at the beginning they can do flint pick -> small iron/banded iron/magnetite/whatever ore -> ingots -> hammer -> gt pick -> full ores.
> 
> Or, if the gt tools are removed, can the vanilla ones be re-enabled with a matching recipe to not remove the alternative progression?

We want to improve early game by removing bloat. GT pickaxes are just some pickaxes. We want to properly integrate and balance tinker construct stuff in the progression. Part of this effort is to remove the absurd amount of materials in tinker so we can properly balance the tools, part of this effort is to remove GT tools, so the progression is simplier. Tinker tools are objectively more interesting than GT pickaxes, and we have a huge interest to remove them, as it removes the tools, but also the pickaxe heads, and the recipes associated to them, resulting in a faster booting time, and less code to migrate for the future material rework.

The alternative progression path is an oversight, so aside maybe special behavior tools such as amethyst which has pickaxe, they won't be added back.

2024-09-16 08:26 UTC, LazyFleshWasTaken commented
> > Can we at least keep gt pick in? For some people that don't want to use tinker's for some time at the beginning they can do flint pick -> small iron/banded iron/magnetite/whatever ore -> ingots -> hammer -> gt pick -> full ores.
> > Or, if the gt tools are removed, can the vanilla ones be re-enabled with a matching recipe to not remove the alternative progression?
> 
> We want to improve early game by removing bloat. GT pickaxes are just some pickaxes. We want to properly integrate and balance tinker construct stuff in the progression. Part of this effort is to remove the absurd amount of materials in tinker so we can properly balance the tools, part of this effort is to remove GT tools, so the progression is simplier. Tinker tools are objectively more interesting than GT pickaxes, and we have a huge interest to remove them, as it removes the tools, but also the pickaxe heads, and the recipes associated to them, resulting in a faster booting time, and less code to migrate for the future material rework.
> 
> The alternative progression path is an oversight, so aside maybe special behavior tools such as amethyst which has pickaxe, they won't be added back.

I see. Nevermind then. 
Also, it'd still technically be possible, you'd just have to use iron hammer instead of iron pickaxe, but it would also return crushed ores intead.

2024-12-11 15:53 UTC, YannickMG commented
> Sense should be added back but as a single item, its AOE cleaning ability is nice. (or we add AOE to mattocks)

I thought the  same but it turns out Biome O' Plenty scythes already have a very large AOE clearing, and TiCo Scythes have 3x3 clearing. Maybe the TiCo scythe's clearing range could be upgraded to make it worth crafting.

2024-12-11 19:55 UTC, ALongStringOfNumbers commented
> > Sense should be added back but as a single item, its AOE cleaning ability is nice. (or we add AOE to mattocks)
> 
> I thought the same but it turns out Biome O' Plenty scythes already have a very large AOE clearing, and TiCo Scythes have 3x3 clearing. Maybe the TiCo scythe's clearing range could be upgraded to make it worth crafting.

On 1.12, we let the Sense have AOE Right Click to Harvest behavior for fully grown crops, which could be a compelling reason to keep the sense if this behavior was added.

2024-12-12 19:34 UTC, RecursivePineapple approved these changes
Looks good. Boubou's change request looks like it's stale, so unless anyone has anything else to add I think this is ready to be merged.

2024-12-12 19:40 UTC, chochem commented
goes together with https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1101.
but its missing a quest pr for sure.

2024-12-12 20:25 UTC, merged

2024-12-14 00:27 UTC, Pilad commented
The scythe is needed for the perches with IC2. Maybe we should return them?

2024-12-22 08:04 UTC, Impos913 commented
The sense is an important tool for crops. It needs to be added back

2025-02-27 04:18 UTC, spacebuilder2020 commented
So, I hate to necro an old PR, but one thing that just occurred to me is why are we removing them from the mod entirely instead of making it a config option that the pack disables.  How does this account for any user that does not have the pack but instead is using the updated gtnh forks?

For example, if a user does not use tinkers, they still need a tool option.

2025-02-27 04:27 UTC, FourIsTheNumber commented
> So, I hate to necro an old PR, but one thing that just occurred to me is why are we removing them from the mod entirely instead of making it a config option that the pack disables. How does this account for any user that does not have the pack but instead is using the updated gtnh forks?
> 
> For example, if a user does not use tinkers, they still need a tool option.

GTNH's GT5U is completely unsupported and dysfunctional outside of this specific modpack. Many things do not even have recipes in the mod.

2025-02-27 05:02 UTC, spacebuilder2020 commented
> > So, I hate to necro an old PR, but one thing that just occurred to me is why are we removing them from the mod entirely instead of making it a config option that the pack disables. How does this account for any user that does not have the pack but instead is using the updated gtnh forks?
> > For example, if a user does not use tinkers, they still need a tool option.
> 
> GTNH's GT5U is completely unsupported and dysfunctional outside of this specific modpack. Many things do not even have recipes in the mod.

I wasn't actually aware of that.  For example, nothing in the readme says that other mods are unsupported and I know people in the past have used GTNH forks because they were more up to date and had bug fixes.  Personally, as a modder myself, I am strongly against not providing config options but I understand your reasoning for doing so.

2025-02-27 05:11 UTC, FourIsTheNumber commented
> I wasn't actually aware of that. For example, nothing in the readme says that other mods are unsupported and I know people in the past have used GTNH forks because they were more up to date and had bug fixes. Personally, as a modder myself, I am strongly against not providing config options but I understand your reasoning for doing so.

Many of GTNH's forks are indeed supported for use outside GTNH - we have a spreadsheet of supported mods. This GT5U is extremely tangled in GTNH-specific mechanics and coremods, so it remains unsupported - I'd agree about adding configs, but there is really no point in a pack-exclusive mod. These tools eat up item ids and code maintaining for no purpose in the pack.

2025-02-27 05:25 UTC, spacebuilder2020 commented
> Many of GTNH's forks are indeed supported for use outside GTNH - we have a spreadsheet of supported mods. This GT5U is extremely tangled in GTNH-specific mechanics and coremods, so it remains unsupported - I'd agree about adding configs, but there is really no point in a pack-exclusive mod. These tools eat up item ids and code maintaining for no purpose in the pack.

yea, that is a fair point but even to the point of configs, it is very possible to have configs that enable or disable items completely.  Thus, if the config is false, the items would never get registered and thus would not eat up the item ids.  (not that item ids are that limited anymore due to the use of neid.)  (And of course, since gt tools are meta items, they only use a small amount of ids to begin with) 

Also, I understand your point about no need for configs if it is pack specific but I disagree cause a users who consumes the pack should have the ability to customize and enable or disable features.  

Though, I also agree that other than a few edge cases (ordo, etc), there is very little reason to keep the GT tools and by removing them it allows you to clean things up at the expense of the users who may have these tools and will loose them on update.  I will miss the special abilities that gt tools had, such as fire aspect on flint, silk touch on ordo / nether star, etc.

2025-03-01 03:12 UTC, spacebuilder2020 commented
Well, another thing I noticed is the removal of the universal spade...  Going to miss that too, was using it on my run so I could keep a saw in my toolbox and have it also work as a crowbar