Godforge encore
GTNewHorizons/GT5-Unofficial pull request #3213
Opened 2024-09-17 03:58 UTC by serenibyss

There's always at least one more PR than anticipated for a new feature

2024-09-17 04:40 UTC, serenibyss commented on src/main/java/tectech/loader/recipe/Godforge.java
> +        exoticModuleMagmatterItemMap.put(MaterialsUEVplus.SixPhasedCopper.getDustTiny(1), 100000);
I added these to the Magmatter exotic pool, since all other exotic plasmas were represented here previously. @GDCloudstrike let me know if you'd like for this to be reverted

2024-09-17 15:00 UTC, GDCloudstrike commented on src/main/java/tectech/loader/recipe/Godforge.java
> +        exoticModuleMagmatterItemMap.put(MaterialsUEVplus.SixPhasedCopper.getDustTiny(1), 100000);
sounds good, it can stay

2024-10-03 21:55 UTC, NotAPenguin0 requested changes
Looks good, just one thing I'm not sure about

2024-10-03 21:55 UTC, NotAPenguin0 commented on src/main/java/tectech/thing/metaTileEntity/multi/godforge_modules/MTESmeltingModule.java
> +                    .setMachineHeat(Math.max(recipe.mSpecialValue, getHeatForOC()))
Should probably also check `COIL_HEAT` metadata (also in the line above)

2024-10-03 22:06 UTC, NotAPenguin0 approved these changes

2024-10-03 22:14 UTC, merged