Add the matter manipulator
GTNewHorizons/GT5-Unofficial pull request #3222
Opened 2024-09-18 04:46 UTC by RecursivePineapple

This adds the matter manipulator, which is meant to be a survival-usable version of world edit. The goal of this tool isn't to replace world edit completely, rather its goal is to help with building large or repetitive structures without cheating.

I'd appreciate any feedback since I want this process to be as smooth as possible. I wanted to avoid complex GUIs, so everything is done via context actions or by selecting an option in the right click radial menu. I also didn't want to add unique keybinds, which is the main reason for the odd placing controls (shift + right click the air to place blocks, this will be talked about more later).

Currently, the tool only supports a basic geometry mode and dismantling, but in the future it will have the capability to copy/paste regions of blocks (including machinery) or cut/paste a region of blocks to move it. I will also add a brush mode once I figure out a good way to implement it. The copy/paste mode will be able to set colours, add and configure covers, orient machines, connect pipes, install AE upgrades, configure AE machines, and likely more. This system will be modular, so it'll be trivial to extend once I get it working completely.

The tool can be connected to an ME network by placing it in a security terminal, and has the same requirements as all other wireless terminals (the network must have a nearby access point and it must be powered). If the tool is unconnected, it will pull items from or place items into the player's inventory. When dismantling a tank, any stored fluids will also be placed in fluid cells within the player's inventory. The ME network has a higher priority than the player's inventory, so blocks will be pulled from the inventory first and placed in the ME network first. If the player's inventory is full, the blocks will be dropped on the ground. Excess fluids will be voided.

The tool requires a variable amount of EU per operation. The EU cost is per-block and is increased quadratically depending on the distance, so blocks farther from the player take increasing amounts of energy to place. Removing blocks also requires EU. If the placed or removed block is a tile entity, the EU required is multiplied by 16. The tool's voltage is ZPM and it holds a billion EU. I will likely increase its storage or decrease its consumption, because building large shapes frequently empties it completely.

The tool can also be used to dismantle large, complex machines. It will remove items from an inventory, remove fluids from tanks, and remove covers from any gregtech machines (or anything that implements ICoverable). It will also reset a machine's strong redstone output to allow them to stack. Some inventories (such as AE upgrade slots) aren't IInventories, and do not get emptied properly. Note that this could be used to mine meteors or ore veins, although by the time the player unlocks the tool (late ZPM) it shouldn't cause balance problems.

To place blocks, the tool must be first spawned in (a recipe will be added to the coremod later).

Second, the player must select the shape by right clicking the item (without hovering over a block) to open the configuration radial menu. Please let me know if I'm missing any important shapes - I know I've missed planes, but I haven't decided how I'm going to add those to the menu yet since they require three points. I will likely just add another point that only shows up when places are selected.

![2024-09-18_00 02 15](https://github.com/user-attachments/assets/9ccf32e6-7167-41cc-a55e-2b5a618ba661)

They can then select "Set Shape" followed by whatever shape they want (I'll use cube as an example).

![2024-09-18_00 02 18](https://github.com/user-attachments/assets/52302427-67fd-4b24-9065-e9fd626c7287)

Fourth, the player must select the two corners by right clicking on two blocks. Shift right clicking a block will select the block's position, otherwise the position will be offset based on the side clicked. 

![2024-09-18_00 03 10](https://github.com/user-attachments/assets/cfe18728-008c-4760-a9d4-236edc64a88c)

Fifth, the player must select which blocks they want to place by opening the menu, then selecting "Select Blocks" followed by one of the options in the menu. Alternatively, the player can use the middle mouse button to set the active block (similar to creative mode). The tool can also be used to remove regions of blocks by clearing the selected block. This will "place" air, although it is mainly useful for clearing out underground rooms or dismantling machines.

To actually place the blocks, the player must hold shift + right click for a short amount of time. There is a 10 tick wind up before anything is placed to make sure the player actually wants to place the blocks. Every 10 ticks afterwards, another set of blocks will be placed. The tool will only place one type of block per interval, but it can place or remove up to 256 blocks every interval.

There are also various ways to select the target coordinates. While the primary way is to right click, they can also be moved interactively, which updates the hologram preview.

https://github.com/user-attachments/assets/64d40301-7f09-4151-a5d2-5a4d11caee8c

The player can move one coordinate at a time, or both, which maintains the coordinates' relative positions but allows the player to make adjustments without having to set both several times.

https://github.com/user-attachments/assets/95f01a13-6759-4458-9ff0-810159423793

By default, right clicking will interleave coordinate A and coordinate B, but it's also possible to only set A or B in case that's useful (I haven't found a purpose, but I also don't have a reason to not add it).

2024-09-18 08:43 UTC, Divran commented
Before any dev comes in and dislikes this PR I would just like to point out that this is basically schematica except actually good, and usable. Schematica is already in the pack, but it's just so shit that it's practically useless because it can't paste half the things you want it to, and the other half are pasted with the wrong orientations. The reason we use worldedit to copy/paste shit is specifically because schematica is garbage, but this tool would allow us to uninstall worldedit (or at least stop using it in case we need it for actual real admin purposes). Once this tool is finished, schematica could honestly just be deleted from the pack.

@RecursivePineapple If this is not merged for some weird reason, you should release it separately. I will 100% install and use it and no doubt so will many others

> When dismantling a tank, any stored fluids will also be placed in fluid cells within the player's inventory. The ME network has a higher priority than the player's inventory, so blocks will be pulled from the inventory first and placed in the ME network first. If the player's inventory is full, the blocks will be dropped on the ground. Excess fluids will be voided.

in this case I also hope it places fluids into ae fluid storage first, before attempting to put them in the player's inventory

> I will likely increase its storage or decrease its consumption, because building large shapes frequently empties it completely.

another solution would be to allow it to be charged at any speed via gt wireless chargers (of any tier). which it may already be able to do. so if you don't have enough power to place things, just make more wireless chargers

2024-09-18 09:09 UTC, Divran commented
> looks good overall, but why putting effort into making it specially in GT rather than working on fixing schematica? I'm not opposed to this stuff, it looks very cool, but i'm curious. Fixing schematica would have allowed us to release it for the whole scene just not for NH. It kind of feel like a duplicate feature, so if this makes it in the pack i guess we will ditch schematica.

I don't see a reason why this wouldn't work outside gtnh. the gtnh specific features most likely simply wouldn't be used in that case. could even have a simple check during launch to see if gregtech is installed and if it isn't, it could switch to using RF power instead, for example.

2024-09-18 09:13 UTC, boubou19 commented
We don't support our GT5U outside of NH.

2024-09-18 15:28 UTC, RecursivePineapple commented
@Divran 
> in this case I also hope it places fluids into ae fluid storage first, before attempting to put them in the player's inventory
Yes, that's what it does. It only places stuff in the player's inventory if it can't place it in their AE system. Looks like I forgot to mention that.

> another solution would be to allow it to be charged at any speed via gt wireless chargers
Wireless chargers work well with it, but it's somewhat slow even with fast charging enabled. I think I'll probably just make the distance curve less harsh (^1.25 or something), because that's what consumes most of the power. Chargers push power, so I can't do much on my end to increase the transfer speed.

@boubou19 
> why putting effort into making it specially in GT rather than working on fixing schematica
I'm just not a fan of schematica. It works, but it's quite tedious to use since you have to wait for block dependencies to finish and you have to move around the whole structure several times to build it. I figured there was a good reason for those behaviours so the thought didn't even cross my mind to improve it.
The BlockAnalyzer class is completely isolated, so once I get that code working it can be integrated into schematica if someone wants to (and fairly trivially, since its interface is only a few methods and its result will be serializable).

2024-09-18 20:23 UTC, RecursivePineapple commented
New AE dismantling:

https://github.com/user-attachments/assets/1cec06a6-0c3d-44db-8435-1ea3d3c48336

2024-09-18 21:17 UTC, Divran commented
> Wireless chargers work well with it, but it's somewhat slow even with fast charging enabled. I think I'll probably just make the distance curve less harsh (^1.25 or something), because that's what consumes most of the power. Chargers push power, so I can't do much on my end to increase the transfer speed.

yeah but did you check if having a shitload of wireless chargers at once makes it charge faster? or can only one wireless charger connect at a time?

2024-09-19 20:00 UTC, ddelconte commented
I really like this idea. In fact, I was looking for something like this as an alternative to schematica the other day to no avail. Well done and I look forward to this getting merged.

My only concern is that waiting until ZPM for this is a little too excessive, considering that schematica is available at all times. Perhaps add different tiers of the item but with restricted abilities (smaller volumes that it could work with, etc.) that can be obtained much earlier, perhaps even in LV/MV.

2024-09-19 21:39 UTC, Divran commented
> My only concern is that waiting until ZPM for this is a little too excessive, considering that schematica is available at all times. Perhaps add different tiers of the item but with restricted abilities (smaller volumes that it could work with, etc.) that can be obtained much earlier, perhaps even in LV/MV.

I think zpm should be ok since you don't really need any sort of machine spam before that. I wouldn't want to put it much later than that though. That said, I also definitely wouldn't be against having it earlier

2024-09-19 21:43 UTC, YannickMG commented
Depending on what people want it for, you could consider unlocking specific functionality across several tiers.

For instance the very first model available might only be able to manipulate decoration blocks and not machines, and could gradually gain support for tile entities, inventories, liquid tanks and machine/AE2 configuration.

2024-09-19 21:58 UTC, ddelconte commented
> I think zpm should be ok since you don't really need any sort of machine spam before that. I wouldn't want to put it much later than that though. That said, I also definitely wouldn't be against having it earlier

Ay, but it does more than just machine spam. It's essentially an all in one build tool and when unlocked in LV could serve as a far superior alternative to the builder's wand, which is our only option at that point. If RecursivePineapple is into the idea of splitting it into tiers, then what Yannick suggested is probably closer to the most reasonable approach.

2024-09-19 22:29 UTC, RecursivePineapple commented
> Well done and I look forward to this getting merged.

@ddelconte Thanks!

> you could consider unlocking specific functionality across several tiers.

I can see about making a T1 version that can only place basic blocks with a somewhat limited range (needs titanium), a T2 that can place tile entities, connect to AE, and disassemble with a larger range (needs osmium) and a T3 with everything unlocked (needs naq alloy).

> when unlocked in LV could serve as a far superior alternative to the builder's wand, which is our only option at that point

If the T1 version is too late, I can make a T0 that requires an equal trade focus or a builders wand (or any other magic teleporter around LV/MV, maybe just enderpearls or something). It'd still be powered by EU and largely function the same, but it would be limited to a radius of 32 blocks with a buffer of ~1mil EU along with the T1 restrictions. To prevent it from becoming junk it can be used in an cheaper alternative T1 recipe. Each tier would require the previous tier as an ingredient, but T1 would have two recipes (one with the T0 and one without).

I want the series of items to be teleporter themed, so the 'first' one should include some sort of non-magical teleporter in the recipe. I don't mind the T0 not having a teleporter, but it shouldn't be the 'first' one, it should be more of a barely-working prototype lore-wise.

2024-09-19 23:40 UTC, ddelconte commented
> I can see about making a T1 version that can only place basic blocks with a somewhat limited range (needs titanium), a T2 that can place tile entities, connect to AE, and disassemble with a larger range (needs osmium) and a T3 with everything unlocked (needs naq alloy).

> If the T1 version is too late, I can make a T0 that requires an equal trade focus or a builders wand (or any other magic teleporter around LV/MV, maybe just enderpearls or something). It'd still be powered by EU and largely function the same, but it would be limited to a radius of 32 blocks with a buffer of ~1mil EU along with the T1 restrictions. To prevent it from becoming junk it can be used in an cheaper alternative T1 recipe. Each tier would require the previous tier as an ingredient, but T1 would have two recipes (one with the T0 and one without).

I think this is an excellent approach. A good T0/LV recipe could include sensors, emitters, steel plates, a small lithium battery, a builder's wand, and an enderman head (why not?).

2024-09-19 23:52 UTC, ddelconte commented
I think this is an excellent approach. A good T0/LV recipe could include sensors, emitters, steel plates, a small lithium battery, a builder's wand, and an enderman head (why not?). All instances of teleportation tech in the gregverse (at least, before the end game) rely on ender/nether technology to function (field generators, etc.), so I don't think you'd be violating the lore by incorporating them. Obviously, though, you'd want to make the recipe involved and not something they can just throw together quickly.

2024-09-20 01:33 UTC, YannickMG commented
I'd suggest having the thing run on ender pearls somehow just to justify having an enderman stuck in a smeltery, but that might not be the right incentive.

2024-09-25 08:20 UTC, Divran commented
random idea: add a feature to allow this tool to request the missing blocks from ae before pasting

2024-10-04 02:40 UTC, RecursivePineapple commented
@Divran I really like that idea. It'll need some sort of base station to request the items properly (so that I can put all of them in one crafting request), but I already planned on adding something similar.

2024-10-04 20:15 UTC, Divran commented
> @Divran I really like that idea. It'll need some sort of base station to request the items properly (so that I can put all of them in one crafting request), but I already planned on adding something similar.

it doesnt even really need to be one request. ctrl+clicking ingame right now will request one item at a time and that works fine. you can yoink the existing code for now and improve it later if you really want to merge it into one request

2024-10-11 11:51 UTC, Divran commented
random idea that will probably be broken op and therefore not included. steal recursive blueprints from factorio. add a machine that can do everything your radial menu can, including requesting missing blocks, and allow it to paste itself. nothing can possibly go wrong with this, ever

2024-10-11 12:09 UTC, Divran commented
random other idea: ability to replace all copies of selected block with another block. useful when upgrading mebf coils or borosilicate glass tiers. or especially dtpf coils since the wand swap upgrade thingy isn't able to replace blocks that aren't visible, and the dtpf has several coils which are not visible so they don't get replaced

2024-10-15 02:49 UTC, RecursivePineapple commented
@Divran 

> add a machine that can do everything your radial menu can, including requesting missing blocks, and allow it to paste itself

That's a bit excessive IMO. Honestly, I don't even know what you'd use this for. I've been using the manipulator for real building and you don't even need to automate it. I was going to add arraying to the copy mode, but it's not even necessary because you can just make a row then copy it for each column.

> ability to replace all copies of selected block with another block

I'll have to think about it some more. I want to add something similar to the equal trade focus, but I'm not sure what the best way to go about it is. It'd have to be functionally similar to the focus (ie right click -> blocks swapped without any other actions) but that could very easily lead to too many blocks getting changed.

2024-10-15 11:46 UTC, Divran commented
> That's a bit excessive IMO. Honestly, I don't even know what you'd use this for. I've been using the manipulator for real building and you don't even need to automate it. I was going to add arraying to the copy mode, but it's not even necessary because you can just make a row then copy it for each column.

yeah it was a joke suggestion

2024-11-08 11:15 UTC, chochem requested changes
why is this adding a metaitem4? that seems very unnecessary.

why are the recipes not starting in zpm like the pr description says? this is very much high tier technology.

2024-11-09 15:18 UTC, Divran commented
As I've said before, I'd be fine with it being gated to zpm but personally I don't believe it should be higher than that. 

Also, another idea for you @RecursivePineapple if you want to do as chochem asks but you don't want to completely delete the recipes you made to allow unlocking earlier, how about you hide those recipes behind a config? That way, if the server owner wants it to be unlockable earlier than zpm, they can enable that in a config and your work on the recipe doesn't go to waste. (also we probably would enable that setting haha)

2024-12-22 04:01 UTC, serenibyss commented on src/main/java/gregtech/api/interfaces/tileentity/IRedstoneEmitter.java
> +    default void setRedstoneOutputStrength(ForgeDirection side, boolean isStrong) {}
Does anything end up using this `isStrong` field? I only see this functioning as strong signal in this PR

2024-12-22 16:12 UTC, RecursivePineapple commented on src/main/java/gregtech/api/enums/OrePrefixes.java
> +    public static ImmutableList<Pair<OrePrefixes, String>> detectPrefix(ItemStack stack) {
It depends on the situation, but the alternative is to loop through every OrePrefix and do a string startsWith on every oredict name. I'm using it in the manipulator mod to detect non-gt ores (since they wouldn't have an ItemData). I just added a basic LRU cache on top of the likely slow loop.

I've needed this in several different features so I figured I should add it here instead of leaving it in the manipulator mod.

2024-12-22 16:23 UTC, RecursivePineapple commented on src/main/java/gregtech/api/metatileentity/implementations/MTEFluid.java
> +public class MTEFluid extends MetaPipeEntity implements IMetaTileEntityPipe {
It can, I only had a problem with fluid pipes since the other pipes had an interface already. I don't need it anymore because I switched to checking for IConnectable. Let me know if you want me to remove it entirely.

2024-12-22 16:46 UTC, RecursivePineapple commented on src/main/java/gregtech/api/interfaces/tileentity/IRedstoneEmitter.java
> +    default void setRedstoneOutputStrength(ForgeDirection side, boolean isStrong) {}
Thanks for catching that

2024-12-22 20:17 UTC, serenibyss commented on src/main/java/gregtech/api/metatileentity/implementations/MTEFluid.java
> +public class MTEFluid extends MetaPipeEntity implements IMetaTileEntityPipe {
If its not needed I would rather reduce the scope of the PR and remove it

2024-12-22 22:51 UTC, YannickMG commented on src/main/java/gregtech/api/enums/OrePrefixes.java
> +    public static ImmutableList<Pair<OrePrefixes, String>> detectPrefix(ItemStack stack) {
I imagine the return type should be `List` instead of `ImmutableList`?

Coincidentally I just wrote some code to do something similar except I only wanted to keep the suffixes (the material name) instead of the prefixes, and I didn't bother to cache them for my use case.

2024-12-22 23:47 UTC, RecursivePineapple commented on src/main/java/gregtech/api/enums/OrePrefixes.java
> +    public static ImmutableList<Pair<OrePrefixes, String>> detectPrefix(ItemStack stack) {
I'd prefer to keep it `ImmutableList` since you aren't supposed to modify it due to the cache. If someone wants to upcast it to `List` or copy it they still can.

2024-12-27 03:41 UTC, serenibyss approved these changes

2024-12-27 05:51 UTC, merged

2024-12-30 00:41 UTC, DCNick3 commented
Since this PR was merged, will pulling a prerelease jar from this repo work with the mod? Or is there still something in the [GT Fork](https://github.com/RecursivePineapple/GT5-Unofficial/releases) that is not upstreamed?

2024-12-30 00:47 UTC, RecursivePineapple commented
@DCNick3 there was a merge problem, but it was fixed by this PR: https://github.com/GTNewHorizons/GT5-Unofficial/pull/3725. The latest nightly might work, but I haven't tested it so I'm not sure if it includes the ID PR. If you haven't built a quantum uplink then you can use any nightly after the compat PR was merged.