GT++ Code Sanitize
GTNewHorizons/GT5-Unofficial pull request #3235
Opened 2024-09-20 16:01 UTC by BlueHero233

Did some code cleanup before i change any textures and their references, this time i tested it on nightly 651

2024-09-20 16:19 UTC, Dream-Master commented
@BlueHero233 can you add some ingame screens with the new textures here?
it seems the build crash 
```Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.ExceptionInInitializerError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:[16](https://github.com/GTNewHorizons/GT5-Unofficial/actions/runs/10962510441/job/30441924065?pr=3235#step:15:17)3)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.startServer(DedicatedServer.java:213)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:445)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)
Caused by: java.lang.ExceptionInInitializerError
	at gtPlusPlus.xmod.gregtech.registration.gregtech.GregtechLargeTurbinesAndHeatExchanger.run1(GregtechLargeTurbinesAndHeatExchanger.java:52)
	at gtPlusPlus.xmod.gregtech.registration.gregtech.GregtechLargeTurbinesAndHeatExchanger.run(GregtechLargeTurbinesAndHeatExchanger.java:25)
	at gtPlusPlus.core.handler.CompatHandler.registerGregtechMachines(CompatHandler.java:[17](https://github.com/GTNewHorizons/GT5-Unofficial/actions/runs/10962510441/job/30441924065?pr=3235#step:15:18)7)
	at gtPlusPlus.xmod.gregtech.HandlerGT.init(HandlerGT.java:54)
	at gtPlusPlus.core.handler.CompatIntermodStaging.init(CompatIntermodStaging.java:30)
	at gtPlusPlus.core.common.CommonProxy.init(CommonProxy.java:99)
	at gtPlusPlus.GTplusplus.init(GTplusplus.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:[19](https://github.com/GTNewHorizons/GT5-Unofficial/actions/runs/10962510441/job/30441924065?pr=3235#step:15:20)0)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:3[22](https://github.com/GTNewHorizons/GT5-Unofficial/actions/runs/10962510441/job/30441924065?pr=3235#step:15:23))
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 5 more
Caused by: java.lang.IllegalArgumentException
	at com.gtnewhorizon.structurelib.structure.StructureUtility.ofBlock(StructureUtility.java:1[25](https://github.com/GTNewHorizons/GT5-Unofficial/actions/runs/10962510441/job/30441924065?pr=3235#step:15:26)2)
	at com.gtnewhorizon.structurelib.structure.StructureUtility.ofBlock(StructureUtility.java:1379)
	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.multi.processing.advanced.MTEAdvHeatExchanger.<clinit>(MTEAdvHeatExchanger.java:63)
	... 38 more```

2024-09-20 20:40 UTC, NotAPenguin0 requested changes
As a side note, what's up with the changed textures for QFT casings?

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/base/BasicTileBlockWithTooltip.java
> -        /**
This is a javadoc comment, the extra star shouldn't really be removed.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/base/BlockBaseOre.java
> -    public boolean canCreatureSpawn(final EnumCreatureType type, final IBlockAccess world, final int x, final int y,
I don't really think this should be removed, even if the superclass implementation is the same, it's somewhat convenient to be explicit about spawnable blocks and it's not really in the way.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/general/BlockHellFire.java
> +        return (Math.max(newChance, oldChance));
Remove excess parentheses

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/general/BlockHellFire.java
> +        } catch (Throwable ignored) {}
This probably should log the error instead of ignoring it.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/general/BlockLightGlass.java
> -    private final int a = 255;
I understand this field is only used in one method and can therefore technically be inlined into the method as suggested by IntelliJ, but logically it doesn't make much sense to separate this from the `r, g` and `b` variables.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockCircuitProgrammer.java
> +        return 4;
I kind of prefer the member variable here

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockCircuitProgrammer.java
> +            } catch (final Throwable ignored) {}
Log the error instead of ignoring it.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockCircuitProgrammer.java
> -    public boolean canCreatureSpawn(final EnumCreatureType type, final IBlockAccess world, final int x, final int y,
Same comment as earlier, I would just keep this.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockDecayablesChest.java
> +        return 5;
Same as above, I prefer the member variable.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockFishTrap.java
> +        return 0;
Again member variable is a bit cleaner I think.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockFlaskSetter.java
> +        return 8;
Use the member variable.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockFlaskSetter.java
> +            } catch (final Throwable ignored) {}
Log the error

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockFlaskSetter.java
> +                if ((te instanceof TileEntityVolumetricFlaskSetter)) {
Remove excess parenthesis pair.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockCircuitProgrammer.java
> +                if ((te instanceof TileEntityCircuitProgrammer)) {
Remove excess parenthesis pair.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockFlaskSetter.java
> -    public boolean canCreatureSpawn(final EnumCreatureType type, final IBlockAccess world, final int x, final int y,
As already mentioned i think keeping this is fine

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockPestKiller.java
> +        return 6;
Member variable is a bit better. Maybe extract all the magic values into an enum somewhere?

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockPestKiller.java
> +        if ((te instanceof TileEntityPestKiller)) {
Remove excess parenthesis pair.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockProjectTable.java
> +        return 3;
Member variable or enum

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/item/base/itemblock/ItemBlockGtBlock.java
> +        assert block instanceof BlockBaseModular;
This seems like a bad idea. This assert can be triggered easily (there is even code handling a different case of `block instanceof BlockBaseOre` right above. You cannot guarantee that `block instanceof BlockBaseModular` at this point and should not assert this unless it is an error, in which case you should probably add a graceful check and error handling instead of a debug assert.

2024-09-20 20:40 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/item/base/itemblock/ItemBlockGtBlock.java
> +            } catch (Throwable ignored) {}
Log the error properly instead of catching any `Throwable`

2024-09-20 20:47 UTC, BlueHero233 commented on src/main/java/gtPlusPlus/core/block/base/BasicTileBlockWithTooltip.java
> -        /**
moved comment to top of method to avoid "dangling"

2024-09-20 20:51 UTC, BlueHero233 commented on src/main/java/gtPlusPlus/core/block/base/BlockBaseOre.java
> -    public boolean canCreatureSpawn(final EnumCreatureType type, final IBlockAccess world, final int x, final int y,
reverted

2024-09-20 21:18 UTC, BlueHero233 commented on src/main/java/gtPlusPlus/core/block/general/BlockLightGlass.java
> -    private final int a = 255;
reverted, cant argue with your logic

2024-09-20 21:18 UTC, BlueHero233 commented on src/main/java/gtPlusPlus/core/block/general/BlockHellFire.java
> +        return (Math.max(newChance, oldChance));
done

2024-09-20 23:38 UTC, BlueHero233 commented
> As a side note, what's up with the changed textures for QFT casings?

No changes, just moved them all to a "qft" folder

2024-09-22 15:55 UTC, NotAPenguin0 requested changes

2024-09-22 15:55 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/base/BasicTileBlockWithTooltip.java
> +    // Init on the Client side only, to prevent Field initialisers existing in the Server side bytecode.
Why was this comment moved from the line above `mSidedTextureArray`?

2024-09-22 15:55 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/base/BasicTileBlockWithTooltip.java
> +    /**
Why was this comment moved from the line it belongs to?

2024-09-22 15:55 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/general/BlockHellFire.java
> +        if ((ret == null)) {
Remove excess parenthesis pair

2024-09-22 15:55 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/machine/BlockFishTrap.java
> +        if ((te instanceof TileEntityFishTrap)) {
Remove excess parenthesis pair

2024-09-22 19:58 UTC, BlueHero233 commented on src/main/java/gtPlusPlus/core/block/base/BasicTileBlockWithTooltip.java
> +    // Init on the Client side only, to prevent Field initialisers existing in the Server side bytecode.
Comment explains why its client side only, seems fitting to be moved up

2024-09-22 20:03 UTC, BlueHero233 commented on src/main/java/gtPlusPlus/core/block/base/BasicTileBlockWithTooltip.java
> +    /**
Javadoc comments need to be written before the method to avoid dangling comment, if you want to keep it before ArrayList<CubicObject<String>> it should be a block comment

2024-09-23 08:58 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/base/BasicTileBlockWithTooltip.java
> +    // Init on the Client side only, to prevent Field initialisers existing in the Server side bytecode.
It explains why that specific line is put into a client-side only initializer function.

2024-09-23 08:59 UTC, NotAPenguin0 commented on src/main/java/gtPlusPlus/core/block/base/BasicTileBlockWithTooltip.java
> +    /**
Then it should be a block comment yes

2024-09-23 19:51 UTC, NotAPenguin0 approved these changes

2024-09-23 20:00 UTC, merged