Digital chest void overflow
GTNewHorizons/GT5-Unofficial pull request #324
Opened 2020-10-12 19:02 UTC by botn365

allow the voiding of overflow on super/quantum chests

2020-10-12 19:06 UTC, Prometheus0000 commented
I think it would be better if the ' Use screwdrive to enable void items on over flow"' was on a separate line, it's kinda long.

Also, it should be 'Use a screwdriver to enable voiding items on overflow'

2020-10-12 19:12 UTC, repo-alt approved these changes
Code-wise looks good.

2020-10-12 19:29 UTC, botn365 commented
tried doing it on a seprate line but nothing worked

2020-10-12 19:37 UTC, Prometheus0000 commented
It looks like you literally have to put it on a new line https://github.com/GTNewHorizons/GT5-Unofficial/blob/3ff33adbffd26a70cdcce3162da14c48ed60c668/src/main/java/gregtech/common/tileentities/generators/GT_MetaTileEntity_DieselGenerator.java#L26-L31

2020-10-12 19:59 UTC, draknyte1 commented
Or just override getDescription().

2020-10-12 20:14 UTC, bartimaeusnek requested changes

2020-10-12 20:14 UTC, bartimaeusnek commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalChestBase.java
> +                        if (mode != appeng.api.config.Actionable.SIMULATE)
this should be in a `@Optional(modid="appliedenergistics2")` annotated, seperate method.

2020-10-12 20:14 UTC, bartimaeusnek commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalChestBase.java
> +    }}
newline

2020-10-12 20:14 UTC, bartimaeusnek commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalChestBase.java
>                  if (count > getMaxItemCount()) {
invert + add `|| mVoidOverflow`
```
 if (count <= getMaxItemCount() || mVoidOverflow ) {
   mInventory[0] = null;
} else {
    mInventory[0].stackSize = (count - getMaxItemCount());
    count = getMaxItemCount();
}
```

2020-10-12 20:25 UTC, repo-alt commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalChestBase.java
>                  if (count > getMaxItemCount()) {
eh, no? What if the mode is not voiding and only half the stack fits

2020-10-12 20:30 UTC, bartimaeusnek commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalChestBase.java
>                  if (count > getMaxItemCount()) {
@repo-alt it literally behaves like that currently,

```
if (count > getMaxItemCount()) {
}else /*if(count <= getMaxItemCount()*/{
mInventory[0] = null;
}
```

2020-10-12 20:34 UTC, botn365 commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalChestBase.java
>                  if (count > getMaxItemCount()) {
@bartimaeusnek your proposed code will void access if there is space
mine will not if voiding is off

2020-10-12 22:11 UTC, Dream-Master commented
@bartimaeusnek ok now?

2020-10-12 22:28 UTC, bartimaeusnek commented
> @bartimaeusnek ok now?

No. 2/3 comments are still unresolved.

2020-10-12 22:30 UTC, botn365 commented
no idea what you want on the ae part of it
and i dont see what the problem is whit the second one

2020-10-12 22:44 UTC, bartimaeusnek commented
The issue is that you created a duplicate else branch for no apparent reason, needlessly increasing code length and complexity

2020-10-12 22:59 UTC, botn365 commented
if your talking about 
`if (mVoidOverflow)
   mInventory[0] = null;
else
  mInventory[0].stackSize = (count - getMaxItemCount());
`
it is to make sure that if overflow is not on it wont delete to many items
that whole functions is
checks if there is a item and it hase place to store items or overflow is on and the item is equal
the second check is
checks if overflow is on and deletes the whole check if it is not it will make sure it wont delete to many items if it is almost full

2020-10-13 00:41 UTC, Glease requested changes

2020-10-13 00:41 UTC, Glease commented on src/main/java/gregtech/common/tileentities/storage/GT_MetaTileEntity_DigitalChestBase.java
> +        GT_Utility.sendChatToPlayer(aPlayer, StatCollector.translateToLocal("GT5U.machines.voidoveflow") +" "+mVoidOverflow);
This makes it hard to translate to other languages. In another language it will be a mix of _Void Overflow_ in native language and _true_ or _false_ in English. Preferably use something like 
```java
StatCollector.translateToLocal(mVoidOverflow ? "GT5U.machines.voidoveflow.enabled" : "GT5U.machines.voidoveflow.disabled")
```
or simply 
```java
StatCollector.translateToLocal("GT5U.machines.voidoveflow." + mVoidOverflow)
```

Imagine you see "Void Excess истиной" (according to wikipedia истиной means true) in chatbox.

2020-10-13 15:32 UTC, Glease approved these changes

2020-10-13 17:06 UTC, merged