Fixed Laser pipe every 32 tick connection update
GTNewHorizons/GT5-Unofficial pull request #3259
Opened 2024-09-22 23:02 UTC by dagger8243

Before laser pipes were a major lag source cause every 32 ticks they would cause a connection check, now its just on coloring pipe, on block break and on server start

2024-09-22 23:09 UTC, FourIsTheNumber commented
If this fix works it should be applied to data pipes as well 🥺

2024-09-22 23:10 UTC, dagger8243 commented
uh sure, let me check how hard it would be to do same over there

2024-09-23 19:14 UTC, Dream-Master commented
@dagger8243 please run spotless

2024-09-24 21:29 UTC, OneEyeMaker commented
This update logic should be also called on neighbor block update (when you extend your network), shouldn't it?

2024-09-25 12:24 UTC, Dream-Master commented
@dagger8243

2024-09-29 21:47 UTC, Lyfts requested changes

2024-09-29 21:47 UTC, Lyfts commented on src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
> +            if (t instanceof IGregTechTileEntity a) {
Please use some reasonable variable names

2024-09-29 21:47 UTC, Lyfts commented on src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
> +                byte tColor = ((IConnectsToDataPipe) tTileEntity).getColorization();
Using pattern variable for this would make it more readable

2024-09-29 21:47 UTC, Lyfts commented on src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
> +            if (t instanceof IGregTechTileEntity a) {
Variable names again

2024-09-29 21:47 UTC, Lyfts commented on src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeEnergy.java
> +                System.out.println("passed");
Debug logging should be removed

2024-09-29 21:49 UTC, dagger8243 commented on src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
> +            if (t instanceof IGregTechTileEntity a) {
what u think would be best ?

2024-09-29 21:50 UTC, Lyfts commented on src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
> +            if (t instanceof IGregTechTileEntity a) {
Anything that's more descriptive than `t`, `a` and `b`

2024-09-29 21:54 UTC, dagger8243 commented on src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
> +                byte tColor = ((IConnectsToDataPipe) tTileEntity).getColorization();
this code is from before this PR i just moved it to that method, im try to clean it up tho

2024-09-29 23:07 UTC, dagger8243 commented on src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeEnergy.java
> +                System.out.println("passed");
done

2024-09-29 23:07 UTC, dagger8243 commented on src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
> +            if (t instanceof IGregTechTileEntity a) {
there

2024-09-29 23:08 UTC, dagger8243 commented on src/main/java/tectech/thing/metaTileEntity/pipe/MTEPipeData.java
> +                byte tColor = ((IConnectsToDataPipe) tTileEntity).getColorization();
dont think i missed any (?)

2024-09-29 23:37 UTC, TheEpicGamer274 approved these changes
Looks fine to me

2024-09-30 00:22 UTC, dagger8243 commented
> This update logic should be also called on neighbor block update (when you extend your network), shouldn't it?

ye, its doing that, also making sure it doesnt cascade creating lag spikes

2024-09-30 13:02 UTC, Lyfts submitted a review, later dismissed
It's not updating correctly if you place and paint a hatch after the pipe has been painted
![gt_hatch](https://github.com/user-attachments/assets/0eddc338-4422-4f6b-b514-bc18280941e0)
And it will stay connected if you break the hatch
![gt_hatch2](https://github.com/user-attachments/assets/3ea2d732-611a-413c-8671-a47d01960994)

2024-09-30 13:25 UTC, Dream-Master commented
@dagger8243

2024-10-02 00:24 UTC, TheEpicGamer274 approved these changes

2024-10-02 04:42 UTC, Dream-Master commented
@Lyfts pr ok now ?

2024-10-02 07:41 UTC, dagger8243 commented
no i gotta fix the server sided animation system cause packets a massive source of lag apparently

2024-10-02 19:55 UTC, Dream-Master commented
@dagger8243 any news? need this pr more work ?

2024-10-03 02:55 UTC, dagger8243 commented
everything is working, boubou lyft and i discussed the packet thing and decided it aint as major of a concern as i thought, if its needed i can make another pr dealing with it

2024-10-03 06:09 UTC, merged