Hot Swapping Cables & Wires
GTNewHorizons/GT5-Unofficial pull request #3336
Opened 2024-10-06 05:28 UTC by dagger8243

Video below describes it best:

https://github.com/user-attachments/assets/32ed9148-ba1a-49b2-85ba-13bff2f1cc78

### To do:
- Figure out that error that pops up
- Possibly a tool for mass hot swapping

2024-10-11 15:29 UTC, NotAPenguin0 requested changes

2024-10-11 15:29 UTC, NotAPenguin0 commented on src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
> +            world.setBlock(x, y, z, Blocks.air);
Do you really need to swap the entire block? You already are setting the MTE at this position, and the blocks for the different cables should be exactly the same (possibly meta is different, but you can just change the meta value).

2024-10-11 15:29 UTC, dagger8243 commented on src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
> +            world.setBlock(x, y, z, Blocks.air);
if i dont then it functions as one cable and looks like another

2024-10-11 16:28 UTC, NotAPenguin0 commented on src/main/java/gregtech/api/metatileentity/implementations/MTECable.java
> +            world.setBlock(x, y, z, Blocks.air);
That means you're not sending an update to the renderer most likely, forcing a block update is just a roundabout way of doing so and not really ideal.

2024-12-14 19:24 UTC, serenibyss commented
@dagger8243 any update on this?

2025-01-08 06:59 UTC, Dream-Master commented
@dagger8243 any updates

2025-01-19 17:52 UTC, serenibyss commented
Superseded by #3826

2025-01-19 17:52 UTC, closed without merging