Remove tremendous and useless RAM allocation from GT++ algae pond recipes
GTNewHorizons/GT5-Unofficial pull request #3338
Opened 2024-10-07 09:32 UTC by Alexdoru

This marvelous piece of code allocates `2 * 15` lists each of size `500` that stores `GTRecipe` with each having an array with all different outputs. It's doing a cache of recipes for all tiers and inputs possible instead of just computing it when the machine is used. It is also creating a `WeightedCollection` of size 100 when generating each recipe (so 15 000 times) and the purpose of that map is just to emulate a mathematical function that does the following : 

```
        final float randFloat = random.nextFloat();
        if (randFloat < 0.96237624) return = 1f;
        else if (randFloat < 0.9912871) return = 2f;
        else return 3f;
```

I don't understand the mental process that one has to go through to create such code but hey now it's gone.

2024-10-07 10:31 UTC, Alexdoru commented
Why the freeze tag, this is a "bug fix", there is only one entry point to all the code I changed and it's here : https://github.com/GTNewHorizons/GT5-Unofficial/blob/09b022f4e15c0ccf2e0f415e98887bb473d31c0f/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java#L340

So it's easy to test

And the 2 classes deleted are used nowhere else in the pack, I checked

2024-10-08 05:32 UTC, Alexdoru commented
Note for the reviewer : I made a small piece of code to understand what the Weighted collection did and translate it to the method below : https://gist.github.com/Alexdoru/2aadd54e8601649be8ae757b74666786

2024-10-09 14:46 UTC, OneEyeMaker requested changes

2024-10-09 14:46 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
> +        return aOutputs;
What about calling `toArray` instead of looping through?

2024-10-09 14:46 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
> +                }
Result of `compostForTier` can be calculated and cached before the loop. And `aItemInputs` argument represents slots, doesn't it? If so, then I suggest changing the logic of this method to sum stack sizes to allow detection of compost divided into multiple stacks/slots.

2024-10-09 15:11 UTC, Alexdoru commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
> +        return aOutputs;
it was the original code xd

2024-10-09 15:15 UTC, OneEyeMaker commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
> +    private static final Random random = new XSTR();
Does it really necessary to have *yet another* `Random` instance? Because this class already uses `MathUtils.rand***` methods.

2024-10-09 15:17 UTC, Alexdoru commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
> +    private static final Random random = new XSTR();
it doesn't, is there a random instance in GT that was use everywhere ?

2024-10-09 15:19 UTC, Alexdoru commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/algae/MTEAlgaePondBase.java
> +    private static final Random random = new XSTR();
I found GTPPCore.RANDOM

2024-10-09 15:47 UTC, OneEyeMaker approved these changes

2024-10-09 16:11 UTC, merged