Single block miner optimization
GTNewHorizons/GT5-Unofficial pull request #344
Opened 2020-11-13 15:04 UTC by repo-alt

2020-11-13 15:28 UTC, bartimaeusnek commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +                    ItemData association = GT_OreDictUnificator.getAssociation(new ItemStack(block, 1, blockMeta));
I'd prefer having an actual ore dict check here. something like 
```
if (OreDictionary.getOres("ore").stream().any(x -> GT_Utility.areStacksEqual(new ItemStack(block, 1, blockMeta), x))
     oreBlockPositions.add(new ChunkPosition(x, drillY, z));
```

2020-11-13 16:02 UTC, repo-alt commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +                    ItemData association = GT_OreDictUnificator.getAssociation(new ItemStack(block, 1, blockMeta));
GT_OreDictUnificator.getAssociation is way cheaper. Anyway, the purpose of this PR is not a logic change, but optimization, so that this check would not be done N^2 times instead of N times. (You are definitely free to submit logic improvement in a separate PR)

2020-11-13 16:15 UTC, Glease requested changes

2020-11-13 16:15 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +    private final ArrayList<ChunkPosition> oreBlockPositions = new ArrayList<>();
This list should be repopulated upon radius change and also on first tick (in case of e.g. server restart).

2020-11-13 16:16 UTC, repo-alt commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +    private final ArrayList<ChunkPosition> oreBlockPositions = new ArrayList<>();
right, good catch

2020-11-14 02:58 UTC, Glease approved these changes

2020-11-14 05:54 UTC, merged