double patterns cribs
GTNewHorizons/GT5-Unofficial pull request #3461
Opened 2024-11-08 15:42 UTC by lordIcocain

![image](https://github.com/user-attachments/assets/d472fb32-686f-47fc-bc69-b080cb25efd1)

close:

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16933

2024-11-11 11:07 UTC, serenibyss reviewed
This feature is great, though the placement of the button is not ideal, I think this could be improved

2024-11-11 12:18 UTC, Alexdoru requested changes

2024-11-11 12:18 UTC, Alexdoru commented on src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
> +    public void doublePatterns(int val) {
isn't there a method in AE2 that doubles the patterns ? Can you use that directly instead of re-inventing the wheel ?

2024-11-11 12:32 UTC, lordIcocain commented on src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
> +    public void doublePatterns(int val) {
i cant.

2024-11-11 12:33 UTC, lordIcocain commented
@serenibyss I have no idea. Can you mark better placement?

![image](https://github.com/user-attachments/assets/ddaf297e-98a6-494f-98e5-88ccc0310830)

2024-11-11 15:47 UTC, FireWarrior2 commented
Add 9 extra pattern slots and there will be place))

2024-11-23 15:54 UTC, Alexdoru commented
just place it outside like the buttons in the ae2 interfaces and so on 
![image](https://github.com/user-attachments/assets/9b710fff-c557-40b7-bf34-d70247705d80)

2024-11-23 16:26 UTC, lordIcocain commented
> just place it outside like the buttons in the ae2 interfaces and so on
Done.

2024-11-27 11:02 UTC, Alexdoru submitted a review, later dismissed

2024-11-27 11:02 UTC, Alexdoru commented on src/main/java/gregtech/common/tileentities/machines/MTEHatchCraftingInputME.java
> +            for (int i = 0; i < patterns.getSizeInventory(); i++) {
you should do the same thing as the other algorithm : first loop on all the patterns to see if it is possible to multiply all of them, and then do it in another loop

2024-11-27 15:30 UTC, FireWarrior2 commented
Will crafting input bus (no fluids) also have this button?

2024-11-27 19:20 UTC, lordIcocain commented
> Will crafting input bus (no fluids) also have this button?

Yes

2024-12-21 18:30 UTC, serenibyss commented
This button location collides with covers:
![image](https://github.com/user-attachments/assets/27376401-9718-4cdd-8df5-0d6aaef27076)

2024-12-21 18:43 UTC, lordIcocain commented
![image](https://github.com/user-attachments/assets/a5025dab-de8c-4578-a3dd-89b515491f11)

2024-12-21 18:45 UTC, serenibyss approved these changes

2024-12-21 18:49 UTC, merged