Added Waila info for ME output hatches/busses
GTNewHorizons/GT5-Unofficial pull request #3467
Opened 2024-11-08 22:05 UTC by RecursivePineapple

I copied the code from the data scanner and modified it a bit to make it HUD-friendly. The data scanner output is still useful because it doesn't crop the number of stacks shown, while this crops it to 10 stacks at most.

![2024-11-08_17 01 16](https://github.com/user-attachments/assets/200a2bbe-25c9-4967-8427-c8cea33990c7)
![2024-11-07_21 52 24](https://github.com/user-attachments/assets/565ba0c7-3733-4387-8998-771ebb09424f)

2024-11-12 13:06 UTC, OneEyeMaker commented on src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
> +        } else {
It would be very nice to *not* throw all this information at player immediately: only when player requests it.
Look at alveary from Forestry: one displays info about bee (large block of data) only when shift key is pressed (https://github.com/GTNewHorizons/WAILAPlugins/blob/master/src/main/java/tterrag/wailaplugins/plugins/PluginForestry.java#L252).
I suggest implementing similar approach.

2024-11-16 19:10 UTC, RecursivePineapple commented on src/main/java/gregtech/common/tileentities/machines/MTEHatchOutputBusME.java
> +        } else {
Sorry for not getting back to you sooner, life came up and I wasn't able to spend any time developing.
Here's the requested changes.

![2024-11-16_14 05 47](https://github.com/user-attachments/assets/da303a81-aab7-4cd4-bd87-6914722a9a68)
![2024-11-16_14 05 48](https://github.com/user-attachments/assets/29259bca-46fb-45eb-863c-6a45f4661ff3)
![2024-11-16_14 05 52](https://github.com/user-attachments/assets/cb9db65b-3307-4f9b-9b36-79fcff0dfaa5)
![2024-11-16_14 05 54](https://github.com/user-attachments/assets/519c63cd-4fb8-48b1-acb2-3df04ed76a8e)

2024-11-17 03:20 UTC, Connor-Colenso requested changes
Nice work, can we get some formatting on some of the smaller numbers? I notice you compact 100,000,000 to 100M, but e.g. 1500 stays the same, when it should be 1,500. Which is out of lockstep with how most of GT handles number formatting otherwise.

2024-11-17 05:17 UTC, RecursivePineapple commented
@Connor-Colenso The tooltip uses the AE number formatter, so I can't change the specifics of its format. Would it be better to change it to the GT number formatter?

2024-11-19 17:31 UTC, Glease approved these changes
It appears we are already using AE's number formatter for ME Crafting Input already, so there is no reason to really focus on this aspect in this PR. Any desire to tweak it can be instead satisfied in its own PR.

2024-11-19 18:14 UTC, Connor-Colenso commented
> It appears we are already using AE's number formatter for ME Crafting Input already, so there is no reason to really focus on this aspect in this PR. Any desire to tweak it can be instead satisfied in its own PR.

I get where you are coming from but the standard is to use the GT5u number formatter, it's used in just over 700 places across our GT5u repo. Using one other exception to further break this standard isn't ideal imo, and takes no effort to just change it to the correct format.

2024-11-19 18:45 UTC, Connor-Colenso approved these changes
Thanks, much better.

2024-11-19 18:49 UTC, merged