Custom iconset for bedrockium
GTNewHorizons/GT5-Unofficial pull request #3471
Opened 2024-11-09 21:49 UTC by FourIsTheNumber

I've always hated that bedrockium is turned into a flat black gt material - this adds a textured iconset that I did manual touchups on.

![image](https://github.com/user-attachments/assets/ef5c5183-fe1e-40b2-afdf-0e082b53d312)
![image](https://github.com/user-attachments/assets/212617ca-fc38-4952-aff1-5d11000f67b8)

2024-11-09 21:51 UTC, Alexdoru requested changes

2024-11-09 21:51 UTC, Alexdoru commented on src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
> +                System.out.println("blahblah");
remove debug comments

2024-11-09 21:51 UTC, FourIsTheNumber commented on src/main/java/gregtech/loaders/preload/LoaderGTBlockFluid.java
> +                System.out.println("blahblah");
oops, lol.

2024-11-11 01:58 UTC, Alexdoru approved these changes

2024-11-11 05:59 UTC, merged