Re-balance GT Assembler recipes for Muffler Upgrades
GTNewHorizons/GT5-Unofficial pull request #3498
Opened 2024-11-14 22:52 UTC by HFPTetraUro

Currently, Muffler Upgrades have 6 recipe variants which are a combination of one of 3 plates and one of 2 dusts, but they all give the same result despite some variants being more expensive. The table below shows the previous recipes and the changes made, the balancing has been done based on how hard to get each material is.

| Plate Material | Dust Material | Original Output | Original Duration    | New Output | New  Duration        |
| -------------- | ------------- | --------------- | -------------------- | ---------- | -------------------- |
| Aluminium      | Plastic       | 1               | 1 minute, 20 seconds | 4          | 1 minute, 20 seconds |
| Aluminium      | Wood          | 1               | 1 minute, 20 seconds | 2          | 1 minute             |
| Wrought Iron   | Plastic       | 1               | 1 minute, 20 seconds | 2          | 1 minute, 20 seconds |
| Wrought Iron   | Wood          | 1               | 1 minute, 20 seconds | 1          | 1 minute             |
| Iron           | Plastic       | 1               | 1 minute, 20 seconds | 1          | 1 minute             |
| Iron           | Wood          | 1               | 1 minute, 20 seconds | 1          | 1 minute, 20 seconds |

2024-11-14 23:20 UTC, Alexdoru commented
Pesronally I would of deleted all the recipes and kept the less expensive one only. This is not an item that you need in large quantities, there is no reason to have different recipes that increasingly become better.

2024-11-14 23:28 UTC, HFPTetraUro commented
I agree with you that there are too many variants, but I do think the lowest cost recipe takes too long to make early game, and you would want dozens of it if you make setups with many machines, so I think there should be at least another variant which is faster/better yield. I just used the existing useless more expensive recipe variants for that.

2024-11-15 00:25 UTC, Alexdoru commented
> I agree with you that there are too many variants, but I do think the lowest cost recipe takes too long to make early game, and you would want dozens of it if you make setups with many machines, so I think there should be at least another variant which is faster/better yield. I just used the existing useless more expensive recipe variants for that.

You're right the recipe takes too long, what about you keep only this one and make it 5 sec 30eu/t ?
![image](https://github.com/user-attachments/assets/3bd53e2d-2891-429a-b397-1c57f1e3a6cb)

2024-11-15 01:06 UTC, HFPTetraUro commented
> > I agree with you that there are too many variants, but I do think the lowest cost recipe takes too long to make early game, and you would want dozens of it if you make setups with many machines, so I think there should be at least another variant which is faster/better yield. I just used the existing useless more expensive recipe variants for that.
> 
> You're right the recipe takes too long, what about you keep only this one and make it 5 sec 30eu/t ? ![image](https://private-user-images.githubusercontent.com/57050655/386411361-3bd53e2d-2891-429a-b397-1c57f1e3a6cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzMwMzAsIm5iZiI6MTczMTYzMjczMCwicGF0aCI6Ii81NzA1MDY1NS8zODY0MTEzNjEtM2JkNTNlMmQtMjg5MS00MjlhLWIzOTctMWM1N2YxZTNhNmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAxMDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2M2M2MGIyMThhZjRmNGYzMDgwYWJhY2ZlZjE1MTUwYTE1NzI0OTllNGIyNzVmOWYxODk3YWM2YWFkN2Y5MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BJ4ij92C-4H8rl7i-SZ2_70tmvhOs4vSCBdw0wZYGSc)

That sounds fair. I'll commit tomorrow and run spotless too

2024-11-15 16:29 UTC, Ethryan approved these changes
LGTM

2024-11-15 16:45 UTC, chochem requested changes
the changes are fully at odds with the pr description and title

2024-11-15 16:50 UTC, Ethryan commented
> the changes are fully at odds with the pr description and title

Maybe, but its the result of the discussion in here, and the title and description can always be changed.

2024-11-15 16:51 UTC, chochem commented
yea I am saying they should be changed when the PR does something entirely different.

2024-11-15 16:58 UTC, Ethryan commented
@HFPTetraUro , Please update the Title and Description to match the effects of this pull request.

2024-11-15 17:11 UTC, Alexdoru commented
I edited the pr title and text

2024-11-15 17:17 UTC, merged