Beamline fixes 4
GTNewHorizons/GT5-Unofficial pull request #3504
Opened 2024-11-16 06:38 UTC by Elisis

# Additions
- Adds hot super coolant fluid for Synchrotron and LINAC coolant output, can be cooled back to regular super coolant in VF
- Add Prepared Masks for CPU, NCPU, PIC, HPIC. CR mask-to-mask recipes are replaced with mask-to-prepared mask, and prepared mask-to-mask engraver recipes are added. E.g. CPU-(CR)->PrCPU-(PLE)->NCPU.
- Adds beamline recipes for crystal chips, along with associated masks.
- 

# Balancing
- Reduces UHPIC minimum TC energy to 190eV.
- Adds subticking to TC.
- TC recipe time save per increase in wafer tier improved by ~20%
- Synchrotron allowed to use laser/multiamp energy hatches.

# Fixes
- Fixes LINAC energy handling, now takes full amperage with two energy hatches.
- Fixes TC IOOB exception caused by empty focus input bus.
- Makes NPIC max energy sane.
- Increases LINAC coolant usage, now equal to length kL/s.
- Fixes OBOE with focus durability vs. max uses.
- Fixes equal amount values across different wafer tiers in TC recipes.
- Fixes tricoder NPEing on all multis that don't yet have beamline input hatches.

# QoL
- Adds max number of uses of foci to their tooltips.
- Casing and item textures updated (Credit goes to BlueHero233)

2024-11-16 11:07 UTC, Dream-Master commented
@boubou19 if it contain more fixes than changes I would add it to 2.7 . Thoughts ?

2024-11-17 14:11 UTC, FireWarrior2 commented
@Elisis this one also will be nice if fixed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17710

2024-11-17 16:57 UTC, Ruling-0 commented
> @boubou19 if it contain more fixes than changes I would add it to 2.7 . Thoughts ?

This really should get in - these are some pretty important fixes and balance changes.

2024-11-17 22:20 UTC, Elisis commented
> @Elisis this one also will be nice if fixed [GTNewHorizons/GT-New-Horizons-Modpack#17710](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17710)

Ah, that was the IOOB I mentioned

2024-11-23 22:32 UTC, Ethryan requested changes
Should the debug code still be there?, Might want to remove it if this is to be merged.

It also contains a few new items, but that's fine if its for balancing stuff imo.

PS: I just did a quick glance of this, and did no further testing.

2024-11-23 22:32 UTC, Ethryan commented on src/main/java/gtnhlanth/common/tileentity/MTESynchrotron.java
> +
Here

2024-11-23 22:32 UTC, Ethryan commented on src/main/java/gtnhlanth/common/tileentity/recipe/beamline/BeamlineRecipeLoader.java
> +         * BeamlineRecipeAdder2.instance.addTargetChamberRecipe( // TODO Test recipe for subticking
And Here

2024-11-23 22:52 UTC, Ethryan approved these changes
Looks good imo.

2024-11-23 23:14 UTC, merged