Replace old 32x/64x/png/gradiented circuitry textures with better 16x ones
GTNewHorizons/GT5-Unofficial pull request #3509
Opened 2024-11-17 16:50 UTC by bluhbipo

Mainframes suck. among other things
they're ugly
i have made them better
**BEFORE**
![image](https://github.com/user-attachments/assets/3e1e7ba1-dc45-4733-882d-38b74e99a960)
**AFTER**
![image](https://github.com/user-attachments/assets/68c2dda5-e491-4801-9cb2-bfc395400d16)
*note, the photonically enriched wafer is animated correctly, this screencap is just of a bad frame

all pngs and 32x nonsense has been boomed and replaced with beautiful _functionally identical_ 16x textures

the mainframe is of particular importance that its shape was mimiced as well as possible, since people often dislike change and mainframes are a core aspect of the game. the design we came up with was workshopped over several hours through the intellectual contributions of several texture dev and main dev people.

here is what the new optical mainframe looks like fully animated:

![opticalmainframe](https://github.com/user-attachments/assets/0246e85b-996a-48e2-9d0a-614c45eea63c)

i do not have the resources to figure out how the hell to screen record. majority of the circuits are still animated ala the previous change by the wonderful terra, but i did not animate textures that i did not believe i could faithfully represent in 256 pixels. this is a job for someone who isnt me

t3 circuits, the computers remain non 16x. why? because they fit in the art style and are too iconic to change. i grappled with perhaps extending the texture of the workstation to all other tiers because i like how it looks, but again, i do not want to poke the hornets nest of "old thing good, new thing bad"

the wafer texture was again workshopped over days via the intellectual contributions of many devs both of texture and code alike. the cut wafer texture sucks but its whatever at least it is not a 64x monstrosity

the earlygame circuit components have been made to look not stupid and png, and later on, glass tubes for all your wetware board needs no longer look ugly as all hell.

this modpack is worthy of the polish that a modern minecraft modpack deserves, and as such, the coloring and shading on the old circuit textures that arent mainframes have been updated in line with a modern understanding of pixel art color theory. wetwares appear more pink because it looks like flesh and we all thought that was cute.

**THIS PR IS UNTESTED I LITERALLY JUST SWAPPED IMAGES AND DELETED MCMETA FILES SO IT SHOULD WORK BUT I WILL TEST IT AT SOME POINT OR SOMEONE ELSE WILL AND THEN EVENTUALLY THIS MESSAGE GOES AWAY HMMM YES YES.**

credit to our resident epic artist bluehero for the gallium arsenide crystal textures.

2024-11-20 17:20 UTC, GDCloudstrike approved these changes
After going through multiple feedback cycles, I think this turned out great

2024-11-20 18:17 UTC, Dream-Master requested changes
We not add this in 2.7.0
Some changes i not agree with. I will give a detailed feedback later

2024-11-20 18:29 UTC, wlhlm commented
Larger than 16px textures are a pet peeve of mine. Thank you for making the base textures more consistent. ❤️

2024-11-20 21:07 UTC, AbdielKavash commented
Could you post a picture of the glass tube/vacuum tube in a machine UI? One of my pet peeves is that the old texture blends into the machine slot background so well as to appear nearly invisible. I remember several people getting their circuit recipes wrong because they didn't even realize that a vacuum tube is needed from the NEI recipe. It would be nice to have this corrected as well.

2024-11-20 21:45 UTC, Dream-Master commented
Not get me wrong I appreciate the work get 16x16 icons for all this items but some items need a bit more work and some changes . As I said I will add a more detailed feedback but not today .

2025-01-09 13:45 UTC, Dream-Master commented
@bluhbipo i just testing this ingame to give a better feedback and it is included in the gt pre tags so thers can test as well.
When i done i let you know if and what need to be changed.

2025-01-09 14:07 UTC, bluhbipo commented
thanks @Dream-Master !

2025-01-10 17:05 UTC, Dream-Master commented
@bluhbipo 
boards are fine
about the circuits why do you change the color from the red one and the green one(Wetware processor quantum processor)
the dots on the wafers/bouls looks now a bit strange since thy are biger because of the 16x16. Can you reduce the color intensity a bit?
samds and asmds are ok
capacitor, transitor  need shadow back. now it looks very flat
Glass tube and vacuum tube looks very similar need a bit different looking otherwise you cant see which item you have
Bio Mainframe has no animation(before you see bubbles)
cosmic Mainframe seems to unchanged and have a 32x32 texture ?
Gallium Arsenic Crystal looks very crappy with 16x16 not sure how it can be improved

2025-01-11 06:18 UTC, bluhbipo commented
@Dream-Master i'll try to work on those, thank you!
the nano/quantum colors were changed to be less bad on the eyes, as they were both very close to rgb yellow and rgb green which is not very good looking. wetware became more pink because it looks like meat which i can change back if you do not like that. mainframes that do not yet exist in game were not textured but i can give them textures to keep up appearences in nei

2025-01-11 07:46 UTC, Dream-Master commented
> @Dream-Master i'll try to work on those, thank you! the nano/quantum colors were changed to be less bad on the eyes, as they were both very close to rgb yellow and rgb green which is not very good looking. wetware became more pink because it looks like meat which i can change back if you do not like that. mainframes that do not yet exist in game were not textured but i can give them textures to keep up appearences in nei

sure i know they close to rgb max color but the new color not looks so nice. i would change it back to orginal value. I like the old color give them more indentification.
oh didnt check it not exist

2025-01-12 13:19 UTC, bluhbipo commented
some of the circuit changes did not make it into this nightly because i forgot that the images are in multiple folders but only one is drawn from in the final texture! effects transitor, capacitor, and vacuum tube

2025-01-12 13:26 UTC, Dream-Master commented
> some of the circuit changes did not make it into this nightly because i forgot that the images are in multiple folders but only one is drawn from in the final texture! effects transitor, capacitor, and vacuum tube

can you update it and i can test it local?

2025-01-12 14:45 UTC, bluhbipo commented
@Dream-Master should work now
vac tube legs i made much darker so they hopefully are more visible, and the circuit parts were shaded

2025-01-15 10:34 UTC, Dream-Master commented
sorry i am on it just delayed by a few real life issues i need to do first

2025-01-25 13:38 UTC, Dream-Master commented
sorry for the long delay i will check this this weekend for sure @bluhbipo

2025-01-25 15:23 UTC, Dream-Master commented
why this one have different colors and not use a gray scale for all circuits and only the inner color differs?
![image](https://github.com/user-attachments/assets/53eac0b7-aa05-4bc7-b1f1-f581f90d0761)
![image](https://github.com/user-attachments/assets/cfc38157-4739-4167-b901-74768e7a701c)
![image](https://github.com/user-attachments/assets/3f2a4ca3-c065-40ab-b8c8-7c562216ec28)
orginal texture keep the color like:
![image](https://github.com/user-attachments/assets/b242e4f6-2cd6-46dc-9dcd-3532744eb6c4)
![image](https://github.com/user-attachments/assets/26f264bf-cedf-4eeb-be44-5debee9f0f78)

2025-01-25 15:32 UTC, Dream-Master commented
Wafers looks now ok
transistor and capacitor looks better now not sure the shadow can be added in some way
Only Diode and Risitor look very flat. Need to compare to old texture
Tubes are ok now
Bio Mainframe still has no animation
Gallium arsenide crystals looks now ok

2025-01-28 10:33 UTC, Dream-Master commented
@bluhbipo the Bio Mainframe has animation now. What about the gray scale of this circuits? I see no change since last time.

2025-02-02 22:45 UTC, Dream-Master approved these changes

2025-02-02 22:45 UTC, merged