isRecipeInputEqual optimization
GTNewHorizons/GT5-Unofficial pull request #351
Opened 2020-11-23 06:30 UTC by Uristqwerty

Significantly reduces the amount of work GT does when checking whether new
recipes are duplicates, and probably other places as well. Saves noticeable
time during startup. However, the implementation here is kinda poor, and
there are still savings to be made. So this commit is more about sharing a
prototype with others than seriously intended to be merged as-is.

2020-11-23 20:57 UTC, Uristqwerty commented
Rewrote the optimization to be less shitty, cutting out the remaining redundant `GT_OreDictUnificator.getAssociation`, and bypassing the copies that `.get` made since the return value was only being used for comparison.

2020-11-24 11:57 UTC, bartimaeusnek requested changes

2020-11-24 11:57 UTC, bartimaeusnek commented on src/main/java/gregtech/api/util/GT_OreDictUnificator.java
> +    public static ItemStack get_nocopy(boolean aUseBlackList, ItemStack aStack) {
I'd like to have this private. These is no reason this should be exposed.

2020-11-24 11:57 UTC, bartimaeusnek commented on src/main/java/gregtech/api/util/GT_Recipe.java
> +            ItemStack unified_tStack = GT_OreDictUnificator.get_nocopy(true, tStack);
this could be inlined with an overloaded ``isInputStackEqual`` in GT_OreDictUnificator.java

2020-11-24 12:27 UTC, Uristqwerty commented on src/main/java/gregtech/api/util/GT_OreDictUnificator.java
> +    public static ItemStack get_nocopy(boolean aUseBlackList, ItemStack aStack) {
Not sure how best to do that.

* `sName2StackMap`'s private, so the whole function can't be put in GT_Recipe without exposing something else.
 * The whole `for (ItemStack aStack : aInputs) {` loop body could be moved from GT_Recipe to GT_OreDictUnificator, if that doesn't bring its own problems.
 * Re-unifying tStack in each comparison would lose some of the performance gains when aInputs.length > 1 (how often does that happen? Maybe it doesn't make much of a difference).
 * Or maybe mInputs could be (or is already!) unified on recipe creation, so that can be skipped completely to both solve that issue and win even more performance.
 * It could at least be made package-private, if nothing else.

2020-11-24 12:33 UTC, bartimaeusnek commented on src/main/java/gregtech/api/util/GT_OreDictUnificator.java
> +    public static ItemStack get_nocopy(boolean aUseBlackList, ItemStack aStack) {
package-private seems reasonable

2020-11-25 17:07 UTC, Dream-Master commented
@Uristqwerty any news here?

2020-11-26 09:29 UTC, merged