Enhance Wireless Detectors with toggle-able sided redstone manipulation
GTNewHorizons/GT5-Unofficial pull request #3617
Opened 2024-12-08 20:00 UTC by Sanduhr32

The follow up as requested in PR #3595 by @OneEyeMaker
Still related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18177

I've tested the GUI changes so they look like previous commits, but with this extra row of button & text.
Also includes localization following the example @serenibyss provided me on discord.

I'ld like your opinion whether i should create a custom background for this new button,
as i'ld like to use the emitter or transmission component for the wireless only mode
and one that's half mentioned gt metaitem & half redstone dust for the "hybrid" mode.

2024-12-14 19:34 UTC, serenibyss commented
@OneEyeMaker are you able to take a look at this when you get a chance?

2024-12-19 15:04 UTC, OneEyeMaker requested changes

2024-12-19 15:04 UTC, OneEyeMaker commented on src/main/java/gregtech/common/covers/redstone/CoverWirelessDoesWorkDetector.java
> +            physical = tag.getBoolean("physical");
Please, update field only if tag is present. Otherwise field value can be set to `false` (when tag doesn't have `"physical"` key) while it's default value is `true`.

2024-12-19 16:25 UTC, Sanduhr32 commented on src/main/java/gregtech/common/covers/redstone/CoverWirelessDoesWorkDetector.java
> +            physical = tag.getBoolean("physical");
```java
    public boolean getBoolean(String key)
    {
        return this.getByte(key) != 0;
    }
    public byte getByte(String key)
    {
        try
        {
    return !this.tagMap.containsKey(key) ? 0 :
```
default is false.

2024-12-19 16:41 UTC, Sanduhr32 commented on src/main/java/gregtech/common/covers/redstone/CoverWirelessDoesWorkDetector.java
> +            physical = tag.getBoolean("physical");
i added the explicit false regardless, i probably should TODO it, so this check eventually gets removed:tm:

2024-12-20 10:09 UTC, Sanduhr32 commented
Due to personal reasons, I am unavailable until next year.
Frohe Weihnachten & Guten Rutsch!

2024-12-20 10:15 UTC, OneEyeMaker commented on src/main/java/gregtech/common/covers/redstone/CoverWirelessDoesWorkDetector.java
> +            physical = tag.getBoolean("physical");
Before last commits and with ones too logic is partially broken. What happens when you load existing save:
* Constructor sets `physical` to `true`.
* Reading from NBT resets this value to `false` (with last commit and without one), because `NBTTagCompound.getBoolean` returns `false` by default.

But I'm suggesting that default value *of field* should stay `true` if tag doesn't exist. Just remove `else` clauses in your last commit and NBT reading will function properly (field will initialize in constructor to `true` and will be untouched in NBT reading process).

2025-01-03 03:28 UTC, Sanduhr32 commented on src/main/java/gregtech/common/covers/redstone/CoverWirelessDoesWorkDetector.java
> +            physical = tag.getBoolean("physical");
I think, if the behavior on a missing tag is set to true by default for old covers, it might break redstone logic, when the cover faces into a redstone sensitive component. I strongly would want to avoid that.
However i agree, that the else clause & possibly the entire if could be removed once the NBT migration is done, aka each modified cover has the mandatory nbt tags.

2025-01-05 11:36 UTC, OneEyeMaker approved these changes

2025-01-05 11:40 UTC, merged