Factory pipe system
GTNewHorizons/GT5-Unofficial pull request #3621
Opened 2024-12-09 06:13 UTC by RecursivePineapple

The system is mostly stable, but it needs a bit more testing. This is meant to be used for complex laser-like pipes that form a network, but in practice it can be used with any mechanic that can be represented as a graph. Factory networks are completely minecraft-agnostic, so they can be used with anything.

There is an example test implementation (see TestFactoryNetwork et al) that has everything a base network should do.

There are also two base classes that remove most of the useless boilerplate for factory hatches and factory pipes. It is highly recommended to subclass these if possible.

A typical factory pipe system would subclass StandardFactoryGrid and StandardFactoryNetwork. It is highly recommended (but not necessary) to make the grid a static singleton. A grid tracks all networks & elements and generally only handles graph/network topology updates. A network is a logical group of factory elements. If your pipe system needs to do anything special, the network is the best place to do it. A factory element represents a real machine in the world and can be a pipe, hatch, multi, or anything else. When a machine is placed in the world, it should immediately add itself to the grid, even if it's not connected to anything. The grid will automatically join two adjacent machines together. Factory elements don't have a superclass, they all implement a shared interface (see TestFactoryElement).

All three types refer to each other recursively via generics. The grid & network subclasses should refer to the others, and the element interface should refer to the grid and the network. The element interface shouldn't have any generics that refer to the pipe system - they should all be pre-specified.

2024-12-21 21:21 UTC, FourIsTheNumber commented
I'll note I'm using this system on the [Artificial Organisms branch](https://github.com/GTNewHorizons/GT5-Unofficial/tree/artificialorganisms) and it's working great

2025-01-13 15:13 UTC, FourIsTheNumber requested changes

2025-01-13 15:13 UTC, FourIsTheNumber commented on src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
> +    TestFactoryPipe(15478),
The test elements should probably not be merged, just pointless items. Good example of the system but hopefully future migrations/ao pipes will also serve as good examples

2025-01-13 22:44 UTC, RecursivePineapple commented on src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
> +    TestFactoryPipe(15478),
They're more for testing an ideal and simple network than anything. It acting as an example is a bonus. Do you think it'd be better to hide the items in prod?

2025-01-14 06:41 UTC, serenibyss commented on src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
> +    TestFactoryPipe(15478),
I would only register the items in dev environment if possible

2025-01-14 06:44 UTC, serenibyss commented on src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
> +    TestFactoryPipe(15478),
See: `Launch.blackboard.get("fml.deobfuscatedEnvironment")`

2025-01-14 09:20 UTC, RecursivePineapple commented on src/main/java/gregtech/api/enums/MetaTileEntityIDs.java
> +    TestFactoryPipe(15478),
Alright, it should be good now

2025-01-14 17:17 UTC, FourIsTheNumber approved these changes
Since I've tested it pretty thoroughly and looked over code again, I think this is good to merge

2025-01-14 17:47 UTC, merged