Boldarnator GPL&Buff
GTNewHorizons/GT5-Unofficial pull request #3668
Opened 2024-12-18 19:01 UTC by HoleFish

- Under GPL, Boldarnator gets subtick
- Boldarnator parallel is removed, instead it gains perfect overclocks
- Boldarnator will get programmed circuit from input bus now

2024-12-18 21:02 UTC, serenibyss commented
Note: whichever merges first between this and #3305 will need to make sure to set `.allowCircuitOnly(true)` on the multi rock breaker recipe map

2024-12-18 22:01 UTC, serenibyss commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialRockBreaker.java
> +            .addInfo("Perform perfect overclocks")
Why change the stats, out of curiosity?

2024-12-21 20:02 UTC, serenibyss approved these changes
Code changes look good, I will leave it open for now for anyone else to comment on the balance change (I think the buff is warranted personally)

2024-12-21 21:00 UTC, chochem commented
regarding balance, the multi was certainly always good as is. I certainly didnt have any issues when I used. The problem is more that other buffs to the pack outscaled it.

2024-12-21 21:29 UTC, serenibyss requested changes
@HoleFish Sorry for the conflicting back to back reviews, but after discussing some more we decided that the buff should be a bit more of a compromise than perfect OC

2024-12-21 21:29 UTC, serenibyss commented on src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/MTEIndustrialRockBreaker.java
> +            .addInfo("Perform perfect overclocks")
Discussed around a bit, we think it would be better to leave the stats how they were and let subtick-OC be a compromise buff rather than buffing with perfect OC

2024-12-26 01:50 UTC, serenibyss approved these changes

2024-12-26 01:56 UTC, merged