Change for loops to int from byte becuase of what leagris said
GTNewHorizons/GT5-Unofficial pull request #379
Opened 2020-12-22 23:09 UTC by Prometheus0000

There should be no functional change. Only a insignificant speedup. See https://discord.com/channels/181078474394566657/603348502637969419/786764836591239188

Not all could be changed since sometimes it messes up since it's relying on them being a byte.
For example in IMetaTileEntityItemPipe if I change it I get this:
![image](https://user-images.githubusercontent.com/8517039/102941153-f95ba400-447f-11eb-8a7c-12027db2b3f1.png)
I could change those to ints as well, but I'm not sure if there would be any functional change if I did? Maybe someone could tell me if that's ok? I tested this change ingame and it didn't explode, but I don't know what else to check besides that it runs, if anything.

I also changed the i = (byte) (i + 1) to i++.

2020-12-22 23:50 UTC, bartimaeusnek requested changes

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/common/render/GT_Renderer_Block.java
> +        for (byte i = 0; i < 6; i++) {
this is still a byte

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/common/render/GT_Renderer_Block.java
> +        for (byte i = 0; i < 6; i++) {
this is still a byte

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/util/GT_Utility.java
> +                    if (tTanks != null) for (int i = 0; i < tTanks.length; i++) {
add a newline after the if ( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/util/GT_OreDictUnificator.java
> +        if (Items.feather.getDamage(aStack) == W) for (int i = 0; i < 16; i++)
add a newline after the if ( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +            for (int i = 0; i < 4; i++) if (isInputDisabledAtSide(sRestrictionArray[aSide][i])) tMask |= 1 << i;
add a newline after the for ( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
> +        if (aVoltage > 0) for (int j = 0; j < 6 && aAmperage > rUsedAmperes; j++, i=(byte)((i+1)%6) )
add a newline after the if ( ) please, the cast to byte isnt nessecary now.

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +        for (int i = 0; i < 6; i++) mCoverBehaviors[i] = GregTech_API.getCoverBehavior(mCoverSides[i]);
add a newline after the for( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +        for (int i = 0; i < 6; i++) mCoverBehaviors[i] = GregTech_API.getCoverBehavior(mCoverSides[i]);
add a newline after the for( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +        for (int i = 0; i < 6; i++) mCoverBehaviors[i] = GregTech_API.getCoverBehavior(mCoverSides[i]);
add a newline after the for( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +            for (int i = 0; i < 6; i++) mCoverBehaviors[i] = GregTech_API.getCoverBehavior(mCoverSides[i]);
add a newline after the for( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
> +        for (int i = 0; i < 6; i++) mCoverBehaviors[i] = GregTech_API.getCoverBehavior(mCoverSides[i]);
add a newline after the for( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
> +        for (int i = 0; i < 6; i++) mCoverBehaviors[i] = GregTech_API.getCoverBehavior(mCoverSides[i]);
add a newline after the for( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/GregTech_API.java
> +        for (int i = 0; i < aMeta.length && i < 16; i++) if (aMeta[i]) rMeta |= B[i];
add a newline after the for( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicMachine.java
> +            if (aTextures[i] != null) for (int c = -1; c < 16; c++) {
add a newline after the if( ) please

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Bronze.java
> +            for (byte i = 1; (this.mSteam != null) && (i < 6); i++) {
this is still a byte

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Lava.java
> +            for (byte i = 1; (this.mSteam != null) && (i < 6); i++) {
this is still a byte

2020-12-22 23:50 UTC, bartimaeusnek commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeTurbine.java
> +            for (byte i = 2; i < 6; i++) {
this is still a byte

2020-12-22 23:53 UTC, draknyte1 requested changes
Honestly, half of, if not all of these changes don’t optimise anything. We’re not boxing nor using billions of smaller types, doubtful it makes any difference at all in 2020 even on a potato, provided its 64 bit. It is also wholly JVM dependant. 

https://stackoverflow.com/questions/27122610/why-does-the-java-api-use-int-instead-of-short-or-byte

https://stackoverflow.com/questions/14531235/in-java-is-it-more-efficient-to-use-byte-or-short-instead-of-int-and-float-inst

2020-12-23 00:13 UTC, Prometheus0000 commented on src/main/java/gregtech/common/render/GT_Renderer_Block.java
> +        for (byte i = 0; i < 6; i++) {
Like I said above, if I change this (and the others I didn't change in for loops), it complains at me because something else needs it to be a byte. In this case it's ```getCoverIDAtSide``` which is declared as ```int getCoverIDAtSide(byte aSide);``` in ICoverable. Also, as I said above I don't know if changing these would have a functional change, so I didn't change them.

2020-12-23 00:26 UTC, Prometheus0000 commented
Isn't MC JVM dependent though? It runs on java, right? And why complain when I already did it?

2020-12-23 01:37 UTC, leagris commented
You need to convert the loop index to int really to int not just a byte i++, so it does not do back and forth conversions from byte to int and back from int to byte for the incrementation arithmetic.
Then for `getCoverIDAtSide` or other methods requesting byte argument you have two options:
1. Cast your int to a byte when passing the argument
2. Change the `getCoverIDAtSide` method to accept int argument and add the old method signature with byte argument as a `@Deprecated` wrapper for compatibility with existing unmaintained code.

2020-12-23 02:01 UTC, Prometheus0000 commented
> You need to convert the loop index to int really to int not just a byte i++, so it does not do back and forth conversions from byte to int and back from int to byte for the incrementation arithmetic.

loop index? Do you mean the for loops? I don't know anything about indexes. Isn't the whole point of this to prevent the back and forth already? Did I miss something? Where exactly?

> Then for getCoverIDAtSide or other methods requesting byte argument you have two options:
   1  Cast your int to a byte when passing the argument
   2 Change the getCoverIDAtSide method to accept int argument and add the old method signature with byte argument as a @Deprecated wrapper for compatibility with existing unmaintained code.

1 How do I do this? ```getCoverBehaviorAtSide(i)``` to ```getCoverBehaviorAtSide(i(byte))``` or ```getCoverBehaviorAtSide(i=(byte))``` don't work as part of
![image](https://user-images.githubusercontent.com/8517039/102950446-aa6e3880-4498-11eb-9086-74a30c1bbfa0.png)

2  Is this the right way to do it?
![image](https://user-images.githubusercontent.com/8517039/102950278-4ba8bf00-4498-11eb-8764-373046bff062.png)


Also, I'd like to do whichever is better, but I'm not the person who'd be able to decide that. The latter sounds like it would be better since it's not converting anymore though.

2020-12-23 02:22 UTC, richardhendricks commented
Do we have concrete evidence spending time here to attempt to optimize this will actually matter? As someone with 20+ years of firmware experience in tight constrained architectures, the #1 thing I've learned is that you must have data before you optimize. How often is this code called? How long does it actually take to execute? And how does it operate in a small environment vs a large server?

A better path to improving tick times might be to change from scanning the whole pipe/wire every tick (I assume that's what this code is) to only doing that occasionally and storing the results in a list. Or to only do it when a change occurs and store the endpoints of the network.

2020-12-23 02:26 UTC, mitchej123 commented
> Do we have concrete evidence spending time here to attempt to optimize this will actually matter? As someone with 20+ years of firmware experience in tight constrained architectures, the #1 thing I've learned is that you must have data before you optimize. How often is this code called? How long does it actually take to execute? And how does it operate in a small environment vs a large server?
> 
> A better path to improving tick times might be to change from scanning the whole pipe/wire every tick (I assume that's what this code is) to only doing that occasionally and storing the results in a list. Or to only do it when a change occurs and store the endpoints of the network.

I don't disagree on the optimization piece, but I'm also happy not looking at the (byte) stuff anymore; he's already done the work.  It's no worse than it is now, so happy to get it merged once it looks good.


As for the pipes/wires -- Long distance pipelines are getting close to finished which only iterate when finding the target or broken/placed. There will be fluid, item, and EU versions.   The fix for the normal wires would be to backport the graph network (tesseract api) from GTI and rescan on change, similar to the long distance pipelines.

2020-12-23 08:37 UTC, draknyte1 commented
> Isn't MC JVM dependent though? It runs on java, right? And why complain when I already did it?

The difference between HotSpot, OpenJ9, Zing, Etc make a difference.  It’s not a complaint, it’s just a pointless optimisation. It’s time spent to gain 0.06ns or less per instance effected, at best. Depending on cpu and JVM, may not benefit at all.

2020-12-23 08:47 UTC, bartimaeusnek commented
> You need to convert the loop index to int really to int not just a byte i++, so it does not do back and forth conversions from byte to int and back from int to byte for the incrementation arithmetic.
> Then for `getCoverIDAtSide` or other methods requesting byte argument you have two options:
> 1. Cast your int to a byte when passing the argument
> 2. Change the `getCoverIDAtSide` method to accept int argument and add the old method signature with byte argument as a `@Deprecated` wrapper for compatibility with existing unmaintained code.

You don't need to tag them as deprecated or create a second one, since byte -> int won't break anything. It'll get automatically converted, as long no reflection of asm is involved.

2020-12-23 09:16 UTC, leagris commented
> > Isn't MC JVM dependent though? It runs on java, right? And why complain when I already did it?
> 
> The difference between HotSpot, OpenJ9, Zing, Etc make a difference. It’s not a complaint, it’s just a pointless optimisation. It’s time spent to gain 0.06ns or less per instance effected, at best. Depending on cpu and JVM, may not benefit at all.

Just have a look at https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-2.html#jvms-2.11.1, the Table **2.11.1-A. Type support in the Java Virtual Machine instruction set**, clearly shows the Java Virtual Machine's low level instructions set has no support for arithmetic operations on 8-bit byte or 16-bit word, but the minimal size native integer type is 32-bit int.

What it means, regardless of the JVM brand and implementation, is that performing arithmetic on byte size values requires that these values be processed in this order:
1. Promote to an integer with an OR to pad extra bits to fill a 32-bit int out of the source    
  Example: `0xFE | 0x00000000` → `0x000000FE` 
2. Execute the arithmetic instructions on the temporary int value  
  Example: `0x000000FE + 0x00000004` → `0x00000102`
3. Demote shrink (recast) the resulting int into a byte, with masking-out of the extraneous bits
  Example: `0x00000102 ^ 0x000000FF` → `0x00000002` to byte `0x02`

2020-12-23 13:20 UTC, leagris requested changes
Same changes requested as @bartimaeusnek
+ some more misses
+ do not mix <kbd>space</kbd> and <kbd>tab</kbd> indentation because it makes the code change diff less readable and may break indentation display depending on used tab size.

2020-12-23 13:20 UTC, leagris commented on src/main/java/gregtech/common/render/GT_Renderer_Block.java
> +        for (byte i = 0; i < 6; i++) {
Then use:
```java
tIsCovered[i] = (aTileEntity.getCoverIDAtSide((byte)i) != 0);
```
It still creates a downcast from int to byte, but you still save the upcast+downcast caused by incrementing a byte counter

2020-12-23 13:20 UTC, leagris commented on src/main/java/gregtech/api/util/GT_OreDictUnificator.java
> +        		setItemData(GT_Utility.copyAmountAndMetaData(1, i, aStack), new ItemData(aPrefix, aMaterial, aBlackListed));
Mix of <kbd>space</kbd> and <kbd>tab</kbd> indentation.

2020-12-23 13:20 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicMachine.java
> +            	}
Mix of <kbd>space</kbd> and <kbd>tab</kbd> indentation.

2020-12-23 13:20 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
> +        		}
The mix of <kbd>space</kbd> and <kbd>tab</kbd> indentation change makes the actual code changes less visible.

2020-12-23 16:10 UTC, leagris commented
Still lot of places with byte loop to fix:
```sh
fgrep -crF 'for (byte' src |awk -F: '{n+=$2}END{print n}'
```
→ 33 places with `for (byte`

```sh
fgrep -rlF 'for (byte' src
```
All the files still containing `for (byte` stuffs:
```none
src/main/java/gregtech/api/util/GT_CircuitryBehavior.java
src/main/java/gregtech/api/interfaces/tileentity/IEnergyConnected.java
src/main/java/gregtech/api/interfaces/tileentity/IExperimentalEnergyTileEntity.java
src/main/java/gregtech/api/interfaces/metatileentity/IMetaTileEntityItemPipe.java
src/main/java/gregtech/api/metatileentity/BaseMetaPipeEntity.java
src/main/java/gregtech/api/metatileentity/MetaPipeEntity.java
src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicMachine.java
src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicGenerator.java
src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Transformer.java
src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
src/main/java/gregtech/api/metatileentity/BaseMetaTileEntityUE.java
src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
src/main/java/gregtech/common/GT_Client.java
src/main/java/gregtech/common/render/GT_Renderer_Block.java
src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeTurbine.java
src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Teleporter.java
src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Lava.java
src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Bronze.java
src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler.java
```

2020-12-23 18:14 UTC, Prometheus0000 commented
> Do we have concrete evidence spending time here to attempt to optimize this will actually matter?

I heard use byte in for loops is bad, and decided to fix it. This is the maximum amount of effort I spent thinking about whether it's worth it or not.

> Still lot of places with byte loop to fix:
 
I also found them with eclipse's ctrl-h search. And as I've said multiple times now I didn't change them because it broke things when I did. I figured we would split the PR into 2 parts, but if that's not what people want that's fine. 

> You don't need to tag them as deprecated or create a second one, since byte -> int won't break anything. It'll get automatically converted, as long no reflection of asm is involved.

Do other people agree? Should I work on the remaining bytes then?

2020-12-23 18:18 UTC, Prometheus0000 commented on src/main/java/gregtech/api/util/GT_OreDictUnificator.java
> +        		setItemData(GT_Utility.copyAmountAndMetaData(1, i, aStack), new ItemData(aPrefix, aMaterial, aBlackListed));
Where? It's all tabs in code?

2020-12-23 18:29 UTC, Prometheus0000 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Cable.java
> +        		}
I think this is an eclipse problem. Or a settings problem. I delete 
![image](https://user-images.githubusercontent.com/8517039/103026465-003af300-4522-11eb-9a03-afc1f939f45d.png)
Then hit enter, which puts it to the right indentation, but when I check the tab/spaces, it has a bunch of spaces created for some reason left of the indentation instead of tabs. Any idea what formatting setting to change? It looks good to me?
![image](https://user-images.githubusercontent.com/8517039/103026836-ba325f00-4522-11eb-94d7-a6678f6ebf7c.png)

2020-12-23 18:35 UTC, draknyte1 commented
> > You need to convert the loop index to int really to int not just a byte i++, so it does not do back and forth conversions from byte to int and back from int to byte for the incrementation arithmetic.
> > Then for `getCoverIDAtSide` or other methods requesting byte argument you have two options:
> > 
> > 1. Cast your int to a byte when passing the argument
> > 2. Change the `getCoverIDAtSide` method to accept int argument and add the old method signature with byte argument as a `@Deprecated` wrapper for compatibility with existing unmaintained code.
> 
> You don't need to tag them as deprecated or create a second one, since byte -> int won't break anything. It'll get automatically converted, as long no reflection of asm is involved.

Well, no.. not if they’re in classes that get extended. 🤦🏻‍♀️ That would invalidate the method signature and extending classes would be borked.

2020-12-23 21:06 UTC, leagris commented
go with simple byte casting argument or this refactor is going to cascade to much larger scopes than can be tested in a reasonable amount of time. Also this alters classes and methods I am working on right-now and I just stopped until this PR is merged to not have complex merge conflicts to deal with. So, please fix the missing byte to int loops in requested changes and downcast to byte when calling methods that require byte argument.

2020-12-23 21:58 UTC, leagris requested changes
Downcasting mutiple times the same value at different place, is unfortunately killing the saved upcasting from the loop counter. Pretty sure it has an even worse impact.
Could you please cache the downcasted value each loop like:
```java
                     for (int i = 0, j = 0; i < 6; i++) { 
                         byte tSide = (byte)i;
....

                            if (aBaseMetaTileEntity.getCoverBehaviorAtSide(tSide).letsItemsIn(tSide, aBaseMetaTileEntity.getCoverIDAtSide(tSide), aBaseMetaTileEntity.getCoverDataAtSide(tSide), -2, aBaseMetaTileEntity)) {
                                IGregTechTileEntity tItemPipe = aBaseMetaTileEntity.getIGregTechTileEntityAtSide(tSide);
                                IGregTechTileEntity tItemPipe = aBaseMetaTileEntity.getIGregTechTileEntityAtSide(tSide);
```
So that there will be only one single downcast from int to byte at each iteration.

2020-12-23 22:04 UTC, Prometheus0000 commented
I thought that might be the case.

2020-12-23 22:25 UTC, Prometheus0000 commented
Is doing it like this correct?
![image](https://user-images.githubusercontent.com/8517039/103040810-a1d23c80-4542-11eb-9a7f-37c5156e564a.png)
I removed j from the for loop since it didn't seem to be used, and declared it below, is there a reason not to?

Also, should I change the lines that still use i to use ii even if it doesn't complain at me? I probably should, right?

2020-12-23 23:21 UTC, leagris commented
> Is doing it like this correct?
> ![image](https://user-images.githubusercontent.com/8517039/103040810-a1d23c80-4542-11eb-9a7f-37c5156e564a.png)
> I removed j from the for loop since it didn't seem to be used, and declared it below, is there a reason not to?
> 
> Also, should I change the lines that still use i to use ii even if it doesn't complain at me? I probably should, right?

Yes and this:
```java
byte j = (byte) (ForgeDirection.OPPOSITES(i));
```
May more efficiently replace:
```java
byte j = GT_Utility.getOppositeSide(i);
```
which calls:
```java
    public static byte getOppositeSide(int aSide) {
        return (byte) ForgeDirection.getOrientation(aSide).getOpposite().ordinal();
    }
```
then calls:
```java
    public static ForgeDirection getOrientation(int id)
    {
        if (id >= 0 && id < VALID_DIRECTIONS.length)
        {
            return VALID_DIRECTIONS[id];
        }
        return UNKNOWN;
    }
```
and then call:
```java
    public ForgeDirection getOpposite()
    {
        return getOrientation(OPPOSITES[ordinal()]);
    }
```
and then another `ordinal()` of the `ForgeDirection` enum.

This is incredible how much fossilised cruft from Forge 1.4.7 or even ModLoader is still there.

2020-12-24 04:21 UTC, Prometheus0000 commented
I checked if it did anything different ingame but I didn't notice anything.

2020-12-24 13:27 UTC, leagris requested changes
Going in the right direction even if I bother you with some more changes.
Thank you for your patience and contribution.

2020-12-24 13:27 UTC, leagris commented on src/main/java/gregtech/api/interfaces/tileentity/IEnergyConnected.java
> +                        ForgeDirection tDirection = ForgeDirection.getOrientation(ii).getOpposite();
Remember this has been already computed line 66 above into variable `j`:
```java
byte j = (byte) (ForgeDirection.OPPOSITES[ii]);
```

2020-12-24 13:27 UTC, leagris commented on src/main/java/gregtech/api/interfaces/tileentity/IEnergyConnected.java
>                              while (aAmperage > rUsedAmperes && ((IEnergySink) tTileEntity).getDemandedEnergy() > 0 && ((IEnergySink) tTileEntity).injectEnergy(ForgeDirection.getOrientation(j), aVolta
Can replace:
```java
ForgeDirection.getOrientation(j)
```
By:
```java
ForgeDirection.VALID_DIRECTIONS[j]
```

2020-12-24 13:27 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +                        		byte ii = (byte)i;
two leftover tab indentations

2020-12-24 13:27 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +                        			}
leftover tab indentations

2020-12-24 13:27 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +                            	byte ii = (byte)i;
leftover tab indentation

2020-12-24 13:27 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +                                	boolean temp = isEnergyInputSide(ii);
leftover tab indentations

2020-12-24 13:27 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/MetaPipeEntity.java
> +        	byte baSide = (byte)aSide;
leftover tab indentation

2020-12-24 13:27 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicGenerator.java
> +        	byte ii = (byte)i;
leftover tab indentation

2020-12-24 19:40 UTC, leagris submitted a review, later dismissed

2020-12-24 19:51 UTC, Dream-Master commented
@bartimaeusnek @draknyte1 can we merge this now ?

2020-12-24 20:04 UTC, leagris commented
> @bartimaeusnek @draknyte1 can we merge this now ?

Some files still need change because the optimization was backward.

Lets take a breath on Weihnachten. Maybe this PR should all be abandoned because it already spreads too far into multiple code areas, will have minimal impact but require huge work to test it has not unforeseen side-effect or even impair performance because code optimization is a complex topic.

We could keep this as a reference material. I think it has valid points.

I'd prefer if we can keep such optimization refactors clean-ups for when we work on a small set of classes already fixing bugs or adding features.

2020-12-25 18:57 UTC, closed without merging