Cleanup and speedup
GTNewHorizons/GT5-Unofficial pull request #393
Opened 2021-01-03 04:52 UTC by mitchej123

Apologies in advance for the size.  I did split up some of the comment removals into a separate commit!

* Remove a bunch of old, commented out shit

* Cleanup & Speedup
1) Remove mAddGTRecipesToIC2Machines (stolen from @Glease)
2) Batch (most) recipe map removals and additions (significant speedup)
3) Modernize old java constructs --> java8 (in the files touched)

2021-01-03 04:58 UTC, mitchej123 commented
It's not as scary as it looks.  Here are the places to pay attention to:

GT_ModHandler.java = This is where most of the actual logic chances take place
* removeRecipeDelayed * removeRecipeByOutputDelayed- Delay a recipe removal
* bulkRemoveByRecipe * bulkRemoveRecipeByOutput - Speedup here, do one giant removeIf, instead of a bunch of smaller ones

GT_Utility.java = some IC2 speedups here
* bulkRemoveSimpleIC2MachineRecipe - Speedup here, bulk removal


Everything Else:
* Add in GT_ModHandler.RecipeBits.BUFFERED
* Use removeRecipe**Delayed

2021-01-03 05:07 UTC, mitchej123 commented
@Dream-Master Please ensure validation that the recipe maps are correct after these changes.  I did my best to spot check changes, but can't guarantee I hit everything.

2021-01-03 06:06 UTC, Glease commented
It's too much for him alone to handle. Probably just check logic changes, merge it and test it on zeta.

2021-01-05 06:19 UTC, Glease requested changes
I looked at the logic and it mostly looks good. IMO verification of changes in `ProcessingXXX` can only be done via playtesting due to its sheer scale.

I'm requesting changes as some place can use a bit of parallelism but that can be done in a later patch if it is proven to be too time consuming.

2021-01-05 06:19 UTC, Glease commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +                for (char c : s.toString().toCharArray()) {
Preferably use `charAt()` + `length()` instead of creating an copy.

2021-01-05 06:19 UTC, Glease commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +                for (char chr : shape.toString().toCharArray()) {
Preferably use `charAt()` + `length()` instead of creating an copy.

2021-01-05 06:19 UTC, Glease commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +        tList.removeIf(tRecipe -> {
This looks like a good candidate for some parallelism. Thoughts?

2021-01-05 06:19 UTC, Glease commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +    public static boolean bulkRemoveRecipeByOutput(List<ItemStack> toRemove) {
Same here. Look like a good candidate for parallelism.

2021-01-05 06:19 UTC, Glease commented on src/main/java/gregtech/api/util/GT_OreDictUnificator.java
> +                        List<ItemStack> list = sUnificationTable.computeIfAbsent(tGTStack1, k -> new ArrayList<>());
nitpicking: replace with ArrayList::new instead of a lambda

2021-01-05 06:31 UTC, mitchej123 commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +                for (char chr : shape.toString().toCharArray()) tData[++x] = tItemDataMap.get(chr);
whoops didn't notice this.  Intellij's cleanup, not sure why this is better.

2021-01-05 07:00 UTC, mitchej123 commented
> I looked at the logic and it mostly looks good. IMO verification of changes in `ProcessingXXX` can only be done via playtesting due to its sheer scale.

Actually I recalled that we have this mod - https://github.com/GTNewHorizons/RecEx which dumps recipes to a json file.  I could run that before the changes, and after, and then throw together a script to compare/validate the outputs.

2021-01-06 02:45 UTC, mitchej123 commented on src/main/java/gregtech/api/util/GT_ModHandler.java
> +                for (char chr : shape.toString().toCharArray()) tData[++x] = tItemDataMap.get(chr);
oh I see, this was a String before, I made it into a string builder; this makes sense again

2021-01-06 03:32 UTC, mitchej123 commented on src/main/java/gregtech/api/util/GT_OreDictUnificator.java
> +                        List<ItemStack> list = sUnificationTable.computeIfAbsent(tGTStack1, k -> new ArrayList<>());
It doesn't like that

2021-01-06 03:57 UTC, Glease approved these changes

2021-01-07 16:01 UTC, merged