Fix multiblock machine tooltip error
GTNewHorizons/GT5-Unofficial pull request #410
Opened 2021-01-17 11:37 UTC by albus12138

Fix multiblock machine tooltip can't display correctly after pressed LSHIFT when UseThisFileAsLanguageFile=true.

These screenshots are captured after this patch.

UseThisFileAsLanguageFile=false
![2021-01-17 19-25-25 的屏幕截图](https://user-images.githubusercontent.com/9742081/104839099-05f5df80-58fa-11eb-973e-a9b50c3681f0.png)

UseThisFileAsLanguageFile=false & Pressed LSHIFT
![2021-01-17 19-25-51 的屏幕截图](https://user-images.githubusercontent.com/9742081/104839116-1f972700-58fa-11eb-9b2b-3f24ae182f72.png)

UseThisFileAsLanguageFile=true
![2021-01-17 19-24-39 的屏幕截图](https://user-images.githubusercontent.com/9742081/104839127-2e7dd980-58fa-11eb-9b6c-ac08287898cb.png)

UseThisFileAsLanguageFile=true & Pressed LSHIFT
![2021-01-17 19-24-56 的屏幕截图](https://user-images.githubusercontent.com/9742081/104839132-38074180-58fa-11eb-8357-11141296b3ab.png)

Code Comments:

- Use "isDisplaySecondaryDescription" to tell "addInfomation" whether LSHIFT is pressed or not.
- Add "Secondary" prefix for tooltip lines in structure parts.
- When a key not found in LANGMAP, try to find it in "Gregtech.lang".

Thanks @JimJokes for finding the cause of the error.

2021-01-17 12:09 UTC, repo-alt reviewed
This adds a method to the public interface w/o default implementation. Won't it break any usage outside of GT?

2021-01-17 12:25 UTC, Glease requested changes

2021-01-17 12:25 UTC, Glease commented on src/main/java/gregtech/api/interfaces/IDescribable.java
> +    boolean isDisplaySecondaryDescription();
This method must have a default method. The default implementation can be as trivial as `return false` but it needs one to prevent GT++ from complaining. The method javadoc should also clearly state that this method should only be called on client side.

2021-01-17 12:25 UTC, Glease commented on src/main/java/gregtech/api/metatileentity/MetaPipeEntity.java
> +    public boolean isDisplaySecondaryDescription() {
The method javadoc should clearly state that this method should only be called on client side.

2021-01-17 12:25 UTC, Glease commented on src/main/java/gregtech/api/metatileentity/MetaTileEntity.java
> +    public boolean isDisplaySecondaryDescription() {
The method javadoc should clearly state that this method should only be called on client side.

2021-01-17 12:25 UTC, Glease commented on src/main/java/gregtech/api/util/GT_LanguageManager.java
> +        	if (!LANGMAP.containsKey(aKey)) {
Formatting is awkward. Please fix this to keep it in line with surrounding code.

2021-01-17 15:42 UTC, Prometheus0000 commented
How is this different from  #404?

2021-01-18 01:19 UTC, albus12138 commented
Sorry for my mistake in the last commit, it is not necessary to add method in IDescribable. It has been removed.

@Glease I'm not sure what formatting I should use. Can you explain it more clearly? Thank you :)

@Prometheus0000 Only one. #404 uses empty lines to bypass GT_LanguageManager's cache. #410 is trying to fix the cache problem.

2021-01-18 11:31 UTC, Glease commented
Upon closer look it seems you are mixing space and tabs even on the same line. The surrounding code use 4 spaces only. If you are still confused, try reading the diff on github instead of your local IDE.

2021-01-18 14:05 UTC, albus12138 commented
Oh, yes. I didn't notice this. I think IDEA should handle this. : (

2021-01-18 14:44 UTC, Glease approved these changes

2021-01-18 15:13 UTC, merged