Refactor World Events
GTNewHorizons/GT5-Unofficial pull request #462
Opened 2021-03-10 17:37 UTC by bartimaeusnek

World events have way to many parameters, so the code gets unreadable, this commit fixes that behavior.

2021-03-10 17:46 UTC, mitchej123 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +                events.setPosition(
Why not have it accept multiple positions and one spawnParticles call then?

2021-03-10 17:49 UTC, bartimaeusnek commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +                events.setPosition(
Doesn't seem nessecary tbh, since this wrapper was done to simplify vanilla code only, i could do that tho

2021-03-10 19:48 UTC, Glease requested changes
Either explicitly ignore *all* argument error (type errors, nulls) by using `if(!check()) return;`, raise some kind of exception by `if (!check()) throw new FooException()`, or do no argument check and let JVM or minecraft code catch them. Mixing all of three in this same class doesn't sound good.

2021-03-10 19:48 UTC, Glease commented on src/main/java/gregtech/api/util/PositionedWorldEvent.java
> +        world.playRecord((String) thing, (int) position.xCoord, (int) position.yCoord, (int) position.zCoord);
Please add javadoc to mention the behavior of rounding down number.

2021-03-10 19:48 UTC, Glease commented on src/main/java/gregtech/api/util/PositionedWorldEvent.java
> +        return world.extinguishFire((EntityPlayer) thing, (int) position.xCoord, (int) position.yCoord, (int) position.zCoord, side);
Please add javadoc to mention the behavior of rounding down number.

2021-03-10 19:48 UTC, Glease commented on src/main/java/gregtech/api/util/PositionedWorldEvent.java
> +        if (position == null || !(thing instanceof String) || world == null)
I'd like it to throw IllegalArgumentException (or some more appropriate exception class that you can think of) if any of these checks fail. It signifies an error in someone's code. Silently ignoring is just sweeping bugs under the rug. Same for below methods.

2021-03-10 19:48 UTC, Glease commented on src/main/java/gregtech/api/util/PositionedWorldEvent.java
> +        if (position == null || world == null)
Missing instanceof check.

2021-03-10 19:48 UTC, Glease commented on src/main/java/gregtech/api/util/PositionedWorldEvent.java
> +        if (position == null || world == null)
Missing instanceof check.

2021-03-10 19:48 UTC, Glease commented on src/main/java/gregtech/api/util/PositionedWorldEvent.java
> +        if (!(thing instanceof String)) {
Missing null check on world.

2021-03-10 19:48 UTC, Glease commented on src/main/java/gregtech/api/util/PositionedWorldEvent.java
> +        if (!(thing instanceof String)) {
Missing null check on world.

2021-03-11 07:10 UTC, Glease approved these changes

2021-03-11 09:16 UTC, Dream-Master commented
@mitchej123 @Skiftcha can we merge this ?

2021-03-11 10:13 UTC, Skiftcha reviewed
i dont see what this commit makes better and do not like it
PositionedWorldEvent is overcomplicated
parameters number is not such a big problem
now to call actual playSound or spawnParticle or whatever you should go to PositionedWorldEvent and figure out what setters are actually needed for call to be successful
reusing PositionedWorldEvent for multiple calls may lead to errors because it remembers state from prevoius calls when manually reusing it or using times().

2021-03-11 10:13 UTC, Skiftcha commented on src/main/java/gregtech/api/util/PositionedWorldEvent.java
> +            action.accept(this, i);
implicitly reusing same object with mutable fields in different iterations does not sound like a good idea

2021-03-11 10:46 UTC, bartimaeusnek commented
> now to call actual playSound or spawnParticle or whatever you should go to PositionedWorldEvent and figure out what setters are actually needed for call to be successful

I can add Javadoc. Also the function was not changed, it just uses a builder-esque pattern now.

> parameters number is not such a big problem

As Robert C. Martin has written in it's book "Clean Code: A Handbook of Agile Software Craftsmanship", any function with more than 3 Parameters is not acceptable.

> i dont see what this commit makes better and do not like it
> PositionedWorldEvent is overcomplicated

How would you wrap these events, to keep the parameters and line length to a reasonable amount? 

> reusing PositionedWorldEvent for multiple calls may lead to errors because it remembers state from prevoius calls when manually reusing it or using times().

Well, thats the point. As i stated previously, *how would you do it differently?*

2021-03-11 11:11 UTC, Skiftcha commented
just create WorldEventsHelper and wrap (x,y,z) to Vec3 as one parameter instead of 3
like
```
    public static void spawnParticle(World world, String particleName, Vec3 position, Vec3 motion) {
        world.spawnParticle(particleName, position.xCoord, position.yCoord, position.zCoord, motion.xCoord, motion.yCoord, motion.zCoord);
    }
```
this
1) reduce parameter number
2) adds normal naming instead of
```
double p_72869_2_, double p_72869_4_, double p_72869_6_, double p_72869_8_, double p_72869_10_, double p_72869_12_
```
3) you see all needed parameters in one place

2021-03-11 11:28 UTC, bartimaeusnek commented
> just create WorldEventsHelper and wrap (x,y,z) to Vec3 as one parameter instead of 3
> like
> ```
>     public static void spawnParticle(World world, String particleName, Vec3 position, Vec3 motion) {
>         world.spawnParticle(particleName, position.xCoord, position.yCoord, position.zCoord, motion.xCoord, motion.yCoord, motion.zCoord);
>     }
> ```
> this
> 1) reduce parameter number
> 2) adds normal naming instead of
> ```
> double p_72869_2_, double p_72869_4_, double p_72869_6_, double p_72869_8_, double p_72869_10_, double p_72869_12_
> ```
> 3) you see all needed parameters in one place

I thought about doing that, but decided against it, since it still doesn't really shorten or tidying up the actual code that uses it. Instead of passing 3 doubles, you now pass the constructor which takes 3 doubles in the actual funktion, which still takes too many arguments. Actually gaining nothing, if the programmer isn't willing to create the Vec3 beforehand.

Personally I prefer the current functional-builder-esque approach, @mitchej123, @leagris and me have created here, lea suggested subclassing this, to further abstract it, and i think that might be the right choice, if someone is willing to put the effort into it, instead of having a generic class for all world related events, subclasses would make sense.

2021-03-11 18:12 UTC, leagris requested changes

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/util/WorldSpawnedEventBuilder.java
> +    private static abstract class StringIdentifierPositionedWorldSpawnedEventBuilder extends PositionedWorldSpawnedEventBuilder implements IStringIdentifierWorldSpawnedEvent {
Modifiers should be declared in the correct order.
```java
private abstract static class
```
The Java Language Specification recommends listing modifiers in the following order:
1. Annotations
2. public
3. protected
4. private
5. abstract
6. static
7. final
8. transient
9. volatile
10. synchronized
11. native
12. strictfp

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/util/WorldSpawnedEventBuilder.java
> +    private static abstract class SoundStringIdentifierPositionedWorldSpawnedEventBuilder extends StringIdentifierPositionedWorldSpawnedEventBuilder implements ISoundWorldSpawnedEvent {
Modifiers should be declared in the correct order.
```java
private abstract static class
```
The Java Language Specification recommends listing modifiers in the following order:
1. Annotations
2. public
3. protected
4. private
5. abstract
6. static
7. final
8. transient
9. volatile
10. synchronized
11. native
12. strictfp

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/util/WorldSpawnedEventBuilder.java
> +    public final static class SoundToNearExceptEventBuilder extends WorldSpawnedEventBuilder implements ISoundWorldSpawnedEvent, IStringIdentifierWorldSpawnedEvent, IEntityPlayerWorldSpawnedEvent {
```java
public static final class
```

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/util/WorldSpawnedEventBuilder.java
> +    public final static class ParticleEventBuilder extends StringIdentifierPositionedWorldSpawnedEventBuilder {
```java
public static final class
```

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/util/WorldSpawnedEventBuilder.java
> +    public final static class SoundEffectEventBuilder extends SoundStringIdentifierPositionedWorldSpawnedEventBuilder {
```java
public static final class
```

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/util/WorldSpawnedEventBuilder.java
> +    public final static class SoundEventBuilder extends SoundStringIdentifierPositionedWorldSpawnedEventBuilder {
```java
public static final class
```

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/util/WorldSpawnedEventBuilder.java
> +    public final static class RecordEffectEventBuilder extends StringIdentifierPositionedWorldSpawnedEventBuilder {
```java
public static final class
```

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/util/WorldSpawnedEventBuilder.java
> +    public final static class ExplosionEffectEventBuilder extends PositionedEntityWorldSpawnedEventBuilder {
```java
public static final class
```

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/util/WorldSpawnedEventBuilder.java
> +    public final static class ExtinguishFireEffectEventBuilder extends PositionedWorldSpawnedEventBuilder implements IEntityPlayerWorldSpawnedEvent {
```java
public static final class
```

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/util/WorldSpawnedEventBuilder.java
> +    public final static class SoundAtEntityEventBuilder extends EntityWorldSpawnedEventBuilder implements ISoundWorldSpawnedEvent, IStringIdentifierWorldSpawnedEvent {
```java
public static final class
```

2021-03-11 18:12 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
>                              aZ - 0.5 + XSTR_INSTANCE.nextFloat()
missing Indentation

2021-03-12 02:55 UTC, basdxz requested changes

2021-03-12 02:55 UTC, basdxz commented on src/main/java/gregtech/api/interfaces/tileentity/IEnergyConnected.java
> +                                        .setWorld(tWorld);
Mentioned this in dm's too, we're missing a .run()

2021-03-12 02:55 UTC, basdxz commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +                    .setIdentifier("largesmoke")
Also discussed, there should be a nice collection of public static strings for this

2021-03-12 02:55 UTC, basdxz commented on src/main/java/gregtech/api/util/GT_FoodStat.java
> +                .setWorld(aPlayer.worldObj)
The whole intent of builders here seems to be due to the sheer number of arguments, but doesn't seem to do that. Even the book you mention lists different reasons to do this one of which this solves if you happen to be using Intellij or another advanced IDE (annotation of what arg to an extent, you can still even with this put X into Y etc as before).

We do not have the symptom of doing too much, since each method still only does one thing (show x particle play y sound. One thing, one thing well etc.)

I suggest wrapping Volume and Pitch into it's own data type along with the xyz pos and dimension. Along with extracting both from the entity if it's an event being played at one. This way the number of arguments is actually reduced and not just stacked vertically instead of horizontally.

2021-03-12 07:19 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaPipeEntity_Fluid.java
> +                    .setIdentifier("largesmoke")
> Also discussed, there should be a nice collection of public static strings for this

I wondered this a few days ago and searched Forge and Minecraft particles class and all strings are hard-coded there with a chain of if else if because older java did not allow case statement switches over string literals. Maybe there is something in CoFhCore or other library already required by Gregtech before one decide to implement an enum or som other particles literals collection.

2021-03-12 07:29 UTC, leagris commented on src/main/java/gregtech/api/util/GT_FoodStat.java
> +                .setWorld(aPlayer.worldObj)
This is indeed common-sense.
The main class has all common properties (world and location).
Each sub-class is aware only of its specific.
Now there are often little data to setup and as long as a constructor does not take more than 5 arguments a builder pattern is overkill.
The setup and run separately is nice to keep though.

2021-03-12 08:39 UTC, bartimaeusnek commented on src/main/java/gregtech/api/util/GT_FoodStat.java
> +                .setWorld(aPlayer.worldObj)
Im against overloading custom elements, since world needs to be seperated from coordinates, due to the differences between entity based and coordinate based events. Even tho pitch and volume are basically just parameters, i think they should be kept seperated. There is little reason of boxing these, when a builder pattern is used.

2021-03-12 14:41 UTC, leagris approved these changes

2021-03-12 14:49 UTC, Dream-Master commented
@basdxz can I merge this?

2021-03-12 15:50 UTC, basdxz approved these changes

2021-03-12 15:50 UTC, merged