Made machine control covers disable themselves upon power loss
GTNewHorizons/GT5-Unofficial pull request #486
Opened 2021-03-30 17:49 UTC by johnch18

Previously an activated machine controller cover would continuously try to run a recipe even if the multiblock had run out of energy, burning through resources every tick.
This change makes a machine controller attached to a tile entity that has run out of power change its state to "Disable Machine" in order to prevent further resource burn.

2021-03-30 18:06 UTC, botn365 requested changes

2021-03-30 18:06 UTC, botn365 commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +    public boolean _wasShutdown = false;
naming should be somhat consistent this should be `mWasShutdown`

2021-03-30 18:18 UTC, johnch18 commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +    public boolean _wasShutdown = false;
Gotcha

2021-03-30 18:46 UTC, botn365 requested changes

2021-03-30 18:47 UTC, johnch18 commented on src/main/java/gregtech/common/covers/GT_Cover_ControlsWork.java
> +            if (!((IMachineProgress) aTileEntity).wasShutdown()) {
Like in the configs or as a parameter?

2021-03-30 18:48 UTC, botn365 commented on src/main/java/gregtech/common/covers/GT_Cover_ControlsWork.java
> +            if (!((IMachineProgress) aTileEntity).wasShutdown()) {
a screwdriver click should be able to chance it

2021-03-30 19:04 UTC, johnch18 commented on src/main/java/gregtech/common/covers/GT_Cover_ControlsWork.java
> +            if (!((IMachineProgress) aTileEntity).wasShutdown()) {
Gotcha, I will work on that in a bit. I'm not familiar enough with the cover gui interface to do that but I'll take a look at it tonight.

2021-03-31 02:26 UTC, johnch18 commented on src/main/java/gregtech/common/covers/GT_Cover_ControlsWork.java
> +            if (!((IMachineProgress) aTileEntity).wasShutdown()) {
Okay, so I added two extra "safe" modes corresponding to normal and inverted behavior and I updated the GUI accordingly.

2021-03-31 02:27 UTC, johnch18 commented on src/main/java/gregtech/common/covers/GT_Cover_ControlsWork.java
> +            if (!((IMachineProgress) aTileEntity).wasShutdown()) {
I made sure that the safe modes use 3 and 4 for backwards compatibility. I wasn't sure how to setup the lang file stuff for this.

2021-03-31 16:00 UTC, johnch18 commented
> looks fine as it is now but
> having to renable save mode and the machine trough the cover is ennoying compared to a swing with the mallet
> and what would be realy nice to have is that the status of mWasShutdown to be displayed when using the tricorder so people can now if a lack of power disabled the machine

Gotcha, I'll get on it. I'll see about showing it in WAILA as well

2021-03-31 22:30 UTC, johnch18 commented
I'm just putting this here as a note for myself, I need to modify GT_Utility.getCoordinateScan

2021-04-01 16:54 UTC, Dream-Master commented
@johnch18 still wip or is this pr done ?

2021-04-01 20:24 UTC, johnch18 commented
Still WIP, have college stuff to attend to

2021-04-02 22:56 UTC, johnch18 commented
I made it so that:
- the player receives a chat if a machine shuts down with its name and position.
- the scanner can see if an involuntary shutdown occurred. As well as if the device was disabled.

2021-04-03 14:42 UTC, Dream-Master commented
@johnch18 let me know when it is done.

2021-04-03 14:44 UTC, johnch18 commented
It is as far as things that can be done on this end, barring any other modifications being suggested. Only thing I could really add is WAILA integration but that's in a completely different mod.

2021-04-03 15:03 UTC, botn365 approved these changes

2021-04-03 15:12 UTC, merged