Added sorting of buffer inventories
GTNewHorizons/GT5-Unofficial pull request #490
Opened 2021-04-02 14:16 UTC by johnch18

Implemented changes #7741

2021-04-02 16:19 UTC, Skiftcha commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +                if (mInventory[j] != null && mInventory[j].stackSize <= 0 && (mInventory[i] == null || GT_Utility.areStacksEqual(mInventory[i], mInventory[j])))
i think this wont work because of mInventory[j].stackSize <= 0

2021-04-02 16:23 UTC, johnch18 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +                if (mInventory[j] != null && mInventory[j].stackSize <= 0 && (mInventory[i] == null || GT_Utility.areStacksEqual(mInventory[i], mInventory[j])))
`mInventory[i]` is an `ItemStack` and I don't think it can be negative.

2021-04-02 16:39 UTC, Skiftcha commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +                if (mInventory[j] != null && mInventory[j].stackSize <= 0 && (mInventory[i] == null || GT_Utility.areStacksEqual(mInventory[i], mInventory[j])))
i mean it wont move stacks with size > 0 which is main case

2021-04-02 16:46 UTC, alphaNOVAircraft commented
It could potentially ruin setups that require the stacks to not be sortet (some ass line automations get fcked up by sorting of the buffer). 

Would be avoidable if it maybe could be disabled manually

2021-04-02 16:51 UTC, Skiftcha commented
actually it is not sort. it is just moving from right to left saving order

2021-04-02 16:52 UTC, johnch18 commented
> It could potentially ruin setups that require the stacks to not be sortet (some ass line automations get fcked up by sorting of the buffer).
> 
> Would be avoidable if it maybe could be disabled manually

On it, both screwdriver and shift+screwdriver behavior is already defined so I'm either going to have to use some weird tool or add it into the GUI :(.

2021-04-02 17:02 UTC, johnch18 commented
I'm going to make it use the soldering iron and shift+rightclick

2021-04-02 17:33 UTC, johnch18 commented
That ought to do it.

2021-04-02 19:09 UTC, johnch18 commented
Through some cursory testing, sort mode being on seems to actually lower the tick time of the buffer when it's active.

2021-04-02 19:38 UTC, Glease requested changes

2021-04-02 19:38 UTC, Glease commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +                GT_Utility.sendChatToPlayer(aPlayer, "Auto-Sort Enabled");
Use `trans(<some unused translation key>, "Auto-Sort Enabled")` instead so it can be translated.

2021-04-02 19:38 UTC, Glease commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +        else {
Let's just remove this else branch as it can't ever do anything. Negative sized stacks are removed at L309 anyway.

2021-04-02 19:41 UTC, johnch18 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +                GT_Utility.sendChatToPlayer(aPlayer, "Auto-Sort Enabled");
Where do I modify that? Gregtech.lang isn't tracked in the repo

2021-04-02 19:41 UTC, johnch18 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +        else {
Done

2021-04-02 19:47 UTC, Glease commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +                GT_Utility.sendChatToPlayer(aPlayer, "Auto-Sort Enabled");
You don't need to modify it. AFAIK lang files are updated automatically. Not sure who is doing the saving though.

2021-04-02 20:09 UTC, alphaNOVAircraft commented
> Through some cursory testing, sort mode being on seems to actually lower the tick time of the buffer when it's active.

Doesnt lower the tick time for me but doesnt rise it either

2021-04-02 22:16 UTC, johnch18 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +                GT_Utility.sendChatToPlayer(aPlayer, "Auto-Sort Enabled");
Got it, since I'm just adding output bus code I went ahead and re-used the string from there.

2021-04-02 22:18 UTC, johnch18 commented
I suppose that's not the worst thing in the world haha.

2021-04-02 22:40 UTC, Glease approved these changes

2021-04-02 23:12 UTC, johnch18 commented
If this gets merged, should I do something similar for item pipes?

2021-04-02 23:13 UTC, alphaNOVAircraft commented
I dont know what the use case of it would be in a pipe tbh, but if it also doesnt have any negativ effects it shouldnt do any harm i guess.

2021-04-02 23:22 UTC, johnch18 commented
Pipes have a similar issue, so a pipe with a 4 slot inventory could have 4 separate stacks of 16 items.

2021-04-03 04:37 UTC, johnch18 commented
Loaded my personal world with the change, seems that the default state is filter on even though I went out of my way to not do that. I'll check the code tomorrow.

2021-04-03 05:26 UTC, merged