Added Configuration tool support
GTNewHorizons/GT5-Unofficial pull request #491
Opened 2021-04-03 06:43 UTC by johnch18

Added support for a type of tool that uses numbers to configure MetaTileEntity objects and the corresponding behavior. This is here so that people adding features to blocks aren't pigeonholed into using obscure tools and sneaking and such.
I did this in response to having to hunt through the code for a machine in order to figure out what tool I could use to change a setting I had added.

2021-04-03 07:18 UTC, johnch18 commented
This is purely groundwork, I'm not expecting anyone to change existing code to use this, it's intended purely as an option for the future.

2021-04-03 14:46 UTC, Glease commented
Is this PR ready for review? If not please mark it as a draft.

2021-04-03 14:48 UTC, johnch18 commented
I'm gonna be honest, I'm new to this whole git thing, but I've converted this to a draft if that helps.

2021-04-03 14:51 UTC, Glease commented
Basically if you want to show off something that isn't quite complete yet, you mark it as a draft, so people don't start to criticize bugs that exists only because it's still WIP.

2021-04-03 14:56 UTC, johnch18 commented
Thanks, I'm kind of learning on the fly. This at its current stages is intended merely as an extra way for people to implement interactions with TEs.

2021-04-05 18:56 UTC, johnch18 commented
Should I add demo behavior?

2021-04-26 11:51 UTC, leagris requested changes
1. This implementation works only as along as `MIN_SETTING=0` and only for `setting > 0`.
2. No reason for this method to change the state of the instance by modifying the `setting` member.
I'd use a pure utility method like that instead:
```java
/**
 * Adjust the integer value to an inclusive range
 * @param aValue value to adjust
 * @param aMin the inclusive minimum of range
 * @param aMax the inclusive maximum of range
 * @return the range adjusted value
 * @throws IllegalArgumentException if {@code aMin > aMax}
 */
public int adjust(final int aValue, final int aMin, final int aMax) {
    if(aMin > aMax) throw new IllegalArgumentException("Min greater than Max");
    final int range = aMax - aMin + 1;
    return (((aValue - aMin) % range) + range) % range + aMin;
}
```

2021-05-14 18:04 UTC, johnch18 commented
I'm admittedly not familiar with what you mean by that, my java isn't that sophisticated yet.

2021-08-03 15:22 UTC, Dream-Master commented
@johnch18 any news on this ?

2021-11-16 10:57 UTC, TheElan commented on src/main/java/gregtech/api/items/GT_Configurator_Item.java
> +    }
You could do it like:
```
public int bumpDown() {
        return changeSetting(setting-1);
}

... same for all other mutating methods ...

public int changeSetting(int newSetting) { // replaces set and adjust
        setting = newSetting % MAX_SETTING
        return setting;
}
```

2021-11-16 11:24 UTC, TheElan commented
While having a tool that can help mode authors to quickly add new configs is really nice. I don't think it's a good idea from a player perspective, it would require them to memorize which numbers do for which machine (e.g. I need to lookup most of the circuits each time I check the recipes in assembler, which is not engaging in any way).

Maybe it would be better to make some kind of a multi-tool in which you switch between more user-friendly mods, like "removing covers", "managing pipe connections", "managing wire connections", "switching machine off\on", etc in a chat and having corresponding icons on item. All effects would be added when configuring the machine via tool's API, e.g.:

```java
interface MultiToolExtensionAPI {

   // you could add icon texture if you would want to make this change in-gui or display it's mode somehow (e.g. in item icon). 
   // `unlocalisedEffect` would explain how it affects a machine
   // `unlocalisedMachineName` would help to know on which machine it mode has said effect
   // this way you can add many machines and effects to same mode
   void addMode(unlocalisedName: String, unlocalisedEffect: String, unlocalisedMachineName: String) 
}
```

Or you could even go a step further and allow doing something similar the present tools, they would have this extension API and could implement some general tool interface e.g.:
```java
interface Tool {
    String getCurrentMode()  // returns uniqueUnlocalisedName
}

class WrenchTool implements Tool {
   @Override
   public String getCurrentMode() {
       return "wrench"
   }
}
// or a extensible tool
abstract class AbstractExtensibleTool implements Tool {
   //... code to manage adding new modes, switching by player,  and return current...
   abstract String defaultMode() // so tools start out with their original mode, returns unlocalised name
}

class CrowbarTool implements AbstractExtensibleTool {
   @Override
   public String defaultMode() {
       return "mode.crowbar"
   }
}
```

And when integrating said tool with machine, author would just check if item implements `Tool` interface and if so - they can just get mode it is in and check if that somehow applies to machine.

And plater would just switch modes by opening some generic tool UI or hotkey.

2021-12-02 15:53 UTC, closed without merging