Made higher tier buffers attempt to move multiple stacks/tick
GTNewHorizons/GT5-Unofficial pull request #493
Opened 2021-04-03 16:55 UTC by johnch18

Pretty self explanatory.

2021-04-03 16:59 UTC, alphaNOVAircraft reviewed
128 Stacks a ticks seems a bit extreme / overkill? You always have to keep in mind that some ppl just spam the really high tier ones cz they already have the high voltage around

2021-04-03 17:00 UTC, johnch18 commented
That's just something I put to fill the array, if you look closely at the code it maxes out at 8.

2021-04-03 17:04 UTC, Dream-Master commented
@johnch18 can you resolve the conflict.

2021-04-03 17:47 UTC, johnch18 commented
Hopefully this fixed it? When I pushed initially I could have sworn repaired this already.

2021-04-03 17:55 UTC, johnch18 commented
This git stuff is still a learning curve

2021-04-05 18:53 UTC, johnch18 commented
Anything else I need to do?

2021-04-12 15:16 UTC, botn365 requested changes

2021-04-12 15:16 UTC, botn365 commented on src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_ChestBuffer.java
> +                super.moveItems(aBaseMetaTileEntity, aTimer);
instead of looping this 8 times change move items to have a argument for stack size

2021-04-12 15:16 UTC, botn365 commented on README.md
> +GT5-Unofficial-chuck
what

2021-04-12 15:16 UTC, botn365 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +    public int maxStackSize = 64;
mMaxStackSize

2021-04-12 22:10 UTC, johnch18 commented on src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_ChestBuffer.java
> +                super.moveItems(aBaseMetaTileEntity, aTimer);
Gotcha, will work on this probably tomorrow

2021-04-12 22:10 UTC, johnch18 commented on README.md
> +GT5-Unofficial-chuck
Didn't mean to push that lmao, my bad

2021-04-14 04:47 UTC, Dream-Master commented
@botn365

2021-04-14 15:11 UTC, botn365 requested changes

2021-04-14 15:11 UTC, botn365 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +        for (int i = 0; i < stacks; i++) {
GT_Utility.moveMultipleItemStacks
it has a argument for amount of stacks its ther ebecous calling this multiple times gets lagy defnetly with big inventorys
yet why is it in a for loop and not use that argument

2021-04-14 15:13 UTC, johnch18 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +        for (int i = 0; i < stacks; i++) {
I'm not following tbh, do you mind explaining it to me again?

2021-04-14 15:17 UTC, botn365 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +        for (int i = 0; i < stacks; i++) {
moveMultipleItemStacks it is then name move multiple item stacks it can move more then 1 item stack 
last argument of it is how many stacks it is allowed to move

2021-04-14 15:18 UTC, johnch18 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +        for (int i = 0; i < stacks; i++) {
Ohhh so don't have a different signature but separate it into different methods?

2021-04-14 15:22 UTC, botn365 commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java
> +        for (int i = 0; i < stacks; i++) {
no get rid of that horible for loop and moveMultipleItemStacks should only be called once

2021-04-16 17:37 UTC, Dream-Master commented
@johnch18

2021-05-13 17:35 UTC, botn365 approved these changes

2021-05-13 17:36 UTC, merged