Change UV transformer cable to bedrockium so you can actually make it in UV
GTNewHorizons/GT5-Unofficial pull request #532
Opened 2021-05-13 19:26 UTC by Prometheus0000

See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7611

Change anycopper to copper for LV one to reduce confusion, and because I doubt anyone would use annealed

Change size from x2 or x4 to x1, because it doesn't make sense for them to be larger, they're not high-amp transformers, they send the same amount of amps as the earlier tiers. The cables already cost more

2021-05-13 19:28 UTC, botn365 commented
people should still be able to use anneald copper if they want

2021-05-13 19:34 UTC, Prometheus0000 commented
Is there really a use case for that though? And personally I found it confusing, like maybe using annealed would make it better somehow, when I first made one.

2021-05-13 19:54 UTC, Dream-Master requested changes

2021-05-13 19:54 UTC, Dream-Master commented on src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
> +        GT_ModHandler.addCraftingRecipe(ItemList.Transformer_MV_LV.get(1L), bitsd, new Object[]{" BB", "CM ", " BB", 'M', ItemList.Hull_LV, 'C', OrePrefixes.cableGt01.get(Materials.Copper), 'B', OreP
please change it back.

2021-05-13 20:07 UTC, Prometheus0000 commented on src/main/java/gregtech/loaders/preload/GT_Loader_MetaTileEntities.java
> +        GT_ModHandler.addCraftingRecipe(ItemList.Transformer_MV_LV.get(1L), bitsd, new Object[]{" BB", "CM ", " BB", 'M', ItemList.Hull_LV, 'C', OrePrefixes.cableGt01.get(Materials.Copper), 'B', OreP
Changed back, but I stand by my opinion that it's confusing and unnecessary.

2021-05-13 20:09 UTC, Dream-Master approved these changes

2021-05-13 20:09 UTC, merged

2021-05-14 17:51 UTC, johnch18 commented
Wish this was in a month ago :'( had to make UHV supes for my transformers.

2021-05-14 17:52 UTC, Prometheus0000 commented
It's always faster to do it yourself. Also, it's not in a release or anything yet.

2021-05-14 18:16 UTC, Dream-Master commented
will be in 2.1.0.7dev