StructureLib integration
GTNewHorizons/GT5-Unofficial pull request #551
Opened 2021-05-29 15:59 UTC by Glease

StructureLib is a cleaner way to declare the structure of multiblocks. It's a standalone version of TecTech's structure check api. The integration of StructureLib will make all future multiblocks to be implemented easier.

TODO:
- [x] Port over rest of structure check API that is specific to GT, i.e. meta tile entities.
- [x] Add some form GT_MetaTileEntity_MultiblockBase_EM
- [ ] Make rotated texture work @leagris please help here 
- [x] Migrate EBF to use new Multiblock base class to show it actually works
- [ ] Migrate all other multiblocks to use new Multiblock base class
- [ ] Ensure addons don't get broken by this huge change.

2021-05-29 16:38 UTC, leagris commented
@Glease 
>  Make rotated texture work @leagris please help here
On it

2021-05-30 17:00 UTC, leagris requested changes
`alignment.getDirection().ordinal()` will always return a value between 0 and 3 since the Direction enum has only 4 values.

so:
`Math.max(alignment.getDirection().ordinal(), 5)` will be always equal to 5, since 5 will be always greater than values between 0 an 3.

Is it really intentional?

Also I'd like we could get ride of raw integer values for directions, rather than 5, please use `ForgeDirection.EAST.ordinal()` as it avoids scratching head.

2021-05-30 17:02 UTC, leagris requested changes

2021-05-30 17:02 UTC, leagris commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +        @Override
`alignment.getDirection().ordinal()` will always return a value between 0 and 3 since the Direction enum has only 4 values.

so:
`Math.max(alignment.getDirection().ordinal(), 5)` will be always equal to 5, since 5 will be always greater than values between 0 an 3.

Is it really intentional?

Also I'd like we could get ride of raw integer values for directions, rather than 5, please use `ForgeDirection.EAST.ordinal()` as it avoids scratching head.

2021-05-30 17:10 UTC, Glease commented on src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java
> +        @Override
Fixed. Though I'd use `ForgeDirection.UNKNOWN.ordinal() - 1` instead, as it is more obvious the call is made to rule out UNKNOWN facings.

2021-05-31 13:59 UTC, leagris requested changes

2021-05-31 13:59 UTC, leagris commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiFurnace.java
> +    public GT_MetaTileEntity_MultiFurnace newMetaEntity(IGregTechTileEntity aTileEntity) {
Modified public method signature will break GregTech add-ons.

2021-05-31 13:59 UTC, leagris commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ElectricBlastFurnace.java
> +    public GT_MetaTileEntity_ElectricBlastFurnace newMetaEntity(IGregTechTileEntity aTileEntity) {
Modified public method signature will break GregTech add-ons. (Specifically breaks bartworks overrides this method with the original signature inside the MegaBlastFurnace here: https://github.com/GTNewHorizons/bartworks/blob/master/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaBlastFurnace.java#L323-L324)
```java
    @Override
            public IMetaTileEntity newMetaEntity(IGregTechTileEntity iGregTechTileEntity) {
                return new GT_TileEntity_MegaBlastFurnace(this.mName);
            }
```

2021-05-31 14:03 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_MultiFurnace.java
> +    public GT_MetaTileEntity_MultiFurnace newMetaEntity(IGregTechTileEntity aTileEntity) {
I thought stuff in `gregtech.common` package is not public API, no?

2021-05-31 14:03 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ElectricBlastFurnace.java
> +    public GT_MetaTileEntity_ElectricBlastFurnace newMetaEntity(IGregTechTileEntity aTileEntity) {
🤦‍♂️ let's go change the bartworks after this.

2021-05-31 14:05 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ElectricBlastFurnace.java
> +    public GT_MetaTileEntity_ElectricBlastFurnace newMetaEntity(IGregTechTileEntity aTileEntity) {
Or maybe not. I'll change it back. This change does not bring about anything good.

2021-05-31 14:05 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ElectricBlastFurnace.java
> +    public GT_MetaTileEntity_ElectricBlastFurnace newMetaEntity(IGregTechTileEntity aTileEntity) {
Or maybe not. I'll change it back. This change does not bring about anything good.

2021-05-31 14:14 UTC, leagris commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ElectricBlastFurnace.java
> +    public GT_MetaTileEntity_ElectricBlastFurnace newMetaEntity(IGregTechTileEntity aTileEntity) {
Yes please, Gregtech common public method are used in-place because lots of API are missing. And lot of Gregtech API wrongly contains implementations rather than interfaces or more modern implementation-free API constructs. Also as said in Discord:
> replacing an interface by an implementation is an anti-pattern.

2021-06-05 18:25 UTC, Glease commented
I'm having some trouble IRL so I'll pause working on this for a week or two, but I'll come back eventually.

2021-06-16 03:57 UTC, Glease commented
After deliberation they will not be ported over. The only change is heat exchanger cooling plasma, which is quite a niche functionality. If anyone wants please leave a comment below.

2021-06-16 03:59 UTC, Prometheus0000 commented
Huh? I think you deleted some words

2021-06-16 04:11 UTC, Prometheus0000 commented
About the BW-moved multis, are they being moved back to GT? Staying in BW? They have broken tooltips right now as a result of being in BW.

Also, I'm not sure what you mean about your last point?

> After features exclusive to bartworks replacements will not be ported over. The only change is heat exchanger cooling plasma, which is quite a niche functionality. If anyone wants please leave a comment below.

These seem opposite? No features, but also no changes?

> ~~Port over bart's change on his TT replacement of base GT multis.~~ After deliberation they will not be ported over. The only change is heat exchanger cooling plasma, which is quite a niche functionality. If anyone wants please leave a note below.

So is the change to coils being removed? The cracker being broken again? Or unbroken? Will you be able to have more than one hatch on a side? This is quite unclear.

> Make GT tool usable to rotate the front face somehow

Why is this important? What's wrong with the scrench? I remember you showing it off in discord, but I can't remember you answering this. Just so that TT isn't necessary to rotate stuff? Why not just copy/move the scrench files? BTW, is the scrench being removed? Otherwise, it'll be confusing.

2021-06-16 04:51 UTC, Glease commented
> About the BW-moved multis, are they being moved back to GT? Staying in BW? They have broken tooltips right now as a result of being in BW.

They will move back

>> After features exclusive to bartworks replacements will not be ported over. The only change is heat exchanger cooling plasma, which is quite a niche functionality. If anyone wants please leave a comment below.
> These seem opposite? No features, but also no changes?
>> ~~Port over bart's change on his TT replacement of base GT multis.~~ After deliberation they will not be ported over. The only change is heat exchanger cooling plasma, which is quite a niche functionality. If anyone wants please leave a note below.
> So is the change to coils being removed? The cracker being broken again? Or unbroken? Will you be able to have more than one hatch on a side? This is quite unclear.

My bad wording. The the only thing that will not be ported over is heat exchanger's extra functionality. The other structural changes will be kept

>> Make GT tool usable to rotate the front face somehow
> Why is this important? What's wrong with the scrench? I remember you showing it off in discord, but I can't remember you answering this. Just so that TT isn't necessary to rotate stuff? Why not just copy/move the scrench files? BTW, is the scrench being removed? Otherwise, it'll be confusing.

Because scrench is from TT not GT. TT depends on GT, not the other way around. You cannot have something in vanilla depends on an addon without creating a circular dependency. 

TT scrench will remain in GT. TT scrench will not work on GT structures unless TT is modified to allow so. I do not feel like inventing a new tool as we already have too many of it, so I reused wrench here.

2021-06-16 04:56 UTC, Prometheus0000 commented
K, thanks for the clarification.

2021-06-17 15:32 UTC, Glease commented
I've finished the integration effort with bartworks (locally, not pushed yet). I expect to start the testing cycle once 2.1.1.0 stable is released.

2021-07-17 06:37 UTC, iouter commented
did you forget this:
![YNOCZ_Z~ 1OW{ }`9`PAWIW](https://user-images.githubusercontent.com/62897714/126028210-b2c45039-2c7d-440d-832f-7a5b830815bb.png)

then it crashed after adding it.
crash-report:https://paste.ubuntu.com/p/6z3Kx7NKwC/

2021-07-18 00:22 UTC, Glease commented
@iouter should be fixed by http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1378/artifact/build/libs/gregtech-5.09.35.00.jar

2021-07-18 02:31 UTC, iouter commented
I tried, now i have two questions.

Will the structure introduction that was deleted by bart come back?

Will blueprints be added to show the structure? I didn't found a blueprint from gt.

2021-07-18 02:58 UTC, Glease commented
Blueprint functionaltiy is added by the blueprint item (sorry forget the name) from structurelib mod. Search `@structurelib` in NEI and it should be pretty obvious as which it is.

Structure Introduction - what? Sounds like tooltip something. Since you are in game already you could probably just check them yourself, as I don't fully understand what you are refering to.

2021-07-18 03:21 UTC, iouter commented
> Blueprint functionaltiy is added by the blueprint item (sorry forget the name) from structurelib mod. Search `@structurelib` in NEI and it should be pretty obvious as which it is.

I found it. Does it work? it show nothing when I use it to right click on the multiblock controller.

> Structure Introduction - what? Sounds like tooltip something. Since you are in game already you could probably just check them yourself, as I don't fully understand what you are refering to.

The tooltip of ebf wil show this when you hold shift at 2100. That‘s Structure Introduction.
![image](https://user-images.githubusercontent.com/62897714/126054471-830a7741-9500-437f-81a5-6e61edea0f57.png)
Now it be deleted by bart, the tooltip was changed to this.
![image](https://user-images.githubusercontent.com/62897714/126054534-adbbf22b-39a0-4fef-bfcd-2e952ca9aa63.png)
I want it back.

2021-07-18 23:40 UTC, Glease commented
> 
> 
> > Blueprint functionaltiy is added by the blueprint item (sorry forget the name) from structurelib mod. Search `@structurelib` in NEI and it should be pretty obvious as which it is.
> 
> I found it. Does it work? it show nothing when I use it to right click on the multiblock controller.

Make sure you aren't using the tectech one. They are not compatible with each other as of now. They could be made compatible in a future patch when we settle the basic functionality with this patch.

> 
> > Structure Introduction - what? Sounds like tooltip something. Since you are in game already you could probably just check them yourself, as I don't fully understand what you are refering to.
> 
> The tooltip of ebf wil show this when you hold shift at 2100. That‘s Structure Introduction.
> ![image](https://user-images.githubusercontent.com/62897714/126054471-830a7741-9500-437f-81a5-6e61edea0f57.png)
> Now it be deleted by bart, the tooltip was changed to this.
> ![image](https://user-images.githubusercontent.com/62897714/126054534-adbbf22b-39a0-4fef-bfcd-2e952ca9aa63.png)
> I want it back.

I made a copy paste error on discord. Use [this bartworks](http://jenkins.usrv.eu:8080/job/Bartworks/138/artifact/build/libs/bartworks%5B1.7.10%5D-%5Bc9836c6%5D-0.5.18.jar) instead. Sorry for that.

2021-07-20 02:40 UTC, iouter commented
crash:https://paste.ubuntu.com/p/2jqJzqMMbp/

2021-07-20 03:18 UTC, Glease commented
@iouter Log says gt++ something and you seem to be using a gt++ jar not from us.

2021-07-20 04:29 UTC, iouter commented
no it's yours.

2021-07-20 10:37 UTC, Glease commented
We didn't hand out jars with `_2` in names.

2021-07-20 11:44 UTC, iouter commented
that's because my downloader want to download a jar with same name. you know, sometimes people don't bump version after they changing the code.

2021-07-21 06:18 UTC, Glease commented
Sorry I misuploaded a broken (unobfuscated) structurelib. Get the correct jar from here: http://jenkins.usrv.eu:8080/job/StructureLib/lastSuccessfulBuild/artifact/build/libs/StructureLib-1.0.6.jar

2021-07-21 06:30 UTC, iouter commented
do you have a way to fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7364?

2021-07-21 10:36 UTC, iouter commented
crash: https://paste.ubuntu.com/p/zJq3qKm6JF/
at that time I was using the blueprint to right click the vacuum freezer controller block.

2021-07-21 11:15 UTC, Glease commented
> 
> 
> do you have a way to fix [GTNewHorizons/GT-New-Horizons-Modpack#7364](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7364)?

No.

> 
> 
> crash: [paste.ubuntu.com/p/zJq3qKm6JF](https://paste.ubuntu.com/p/zJq3qKm6JF/)
> at that time I was using the blueprint to right click the vacuum freezer controller block.

Fixed. [Fixed jar can be downloaded here.](http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1384/artifact/build/libs/gregtech-5.09.35.00.jar) There is [a small update to StructureLib](http://jenkins.usrv.eu:8080/job/StructureLib/24/artifact/build/libs/StructureLib-1.0.7.jar) but it is not required to run the game.

2021-07-21 12:16 UTC, iouter commented
alright

2021-07-22 09:10 UTC, iouter commented
![Q} }HGY)KR3XEPI2KOEV)MD](https://user-images.githubusercontent.com/62897714/126614634-dafa0a3c-b428-44a0-81ef-99616781eefa.png)

i used the blueprint to shift+right click the multiblock miner controller block in creative .

2021-07-22 10:00 UTC, iouter commented
server crash: https://paste.ubuntu.com/p/3CJGmdDYcV/

2021-07-22 10:18 UTC, GreyElaina commented
> server crash: https://paste.ubuntu.com/p/3CJGmdDYcV/

This looks like the client class is called on the server side, you need to add a check or something...probably.

2021-07-22 11:42 UTC, Glease commented
@iouter @GlodBlock both fixed by [this jar](http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1395/artifact/build/libs/gregtech-5.09.35.00.jar)

2021-07-22 12:09 UTC, iouter commented
![image](https://user-images.githubusercontent.com/62897714/126636634-5599acfb-8d17-4199-97e4-5fffb61aae5d.png)

the vacuum freezer controller block will disapper after i shift+right click it in creative.

2021-07-22 12:40 UTC, Glease commented
> 
> 
> ![image](https://user-images.githubusercontent.com/62897714/126636634-5599acfb-8d17-4199-97e4-5fffb61aae5d.png)
> 
> the vacuum freezer controller block will disapper after i shift+right click it in creative.

Fixed via [build 1396](http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1396/artifact/build/libs/gregtech-5.09.35.00.jar)

2021-07-29 19:49 UTC, repo-alt commented on src/main/java/gregtech/common/blocks/GT_Block_Casings4.java
> +    private static int[][] mapping = new int[][]{
Extracting that info was a truly heroic act, but now as it is nice and compact, it would be also nice to have a comment explaining _what_ mapping is that, so that the next reader would not have to look up usage.

2021-07-29 20:02 UTC, repo-alt commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_FusionComputer.java
> +                    .addShape(STRUCTURE_PIECE_MAIN, transpose(new String[][]{
That's just, wow

2021-07-29 20:07 UTC, repo-alt approved these changes
With this PR merged, overall GT code quality will jump up a notch...
(of course it not realistic to review all the changes in detail, they are massive, but let's test that live first, minor bugs, if any, would be easier to locate later)

2021-07-30 07:00 UTC, Glease commented on src/main/java/gregtech/common/blocks/GT_Block_Casings4.java
> +    private static int[][] mapping = new int[][]{
Good idea.

2021-07-30 08:48 UTC, leagris approved these changes
This is great work worth worth a SemVer minor step-up, be we can't because GT5 does not really use SemVer.

As @repo-alt said, this is a significant code improvement. Gregtech code is becoming more professional.

2021-07-30 09:54 UTC, merged