Made the wireless redstone recievers safer to use on public servers
GTNewHorizons/GT5-Unofficial pull request #553
Opened 2021-06-01 21:46 UTC by MatthewCOwen

The wireless redstone covers aren't currently public server safe if you right click an item onto the face of the cover. The value set by right clicking an item onto the face of the cover should now be personalized to the player.

![image](https://user-images.githubusercontent.com/16054364/120393866-81738e80-c2e7-11eb-8d6f-7ebbd7ad8e66.png)
This was a quick test of right clicking a sign onto the face of the cover using two different usernames.

2021-06-02 21:53 UTC, botn365 requested changes

2021-06-02 21:53 UTC, botn365 commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +            aCoverVariable = playerHash << 16 | aCoverVariable >> 16;
make aCoverVariable a modulo operation 
also this needs to be changed for the gui as well and make sure screw driver clicks cant change the the value in a way that the player can enter somone elses space
their also needs to be a public channel as well and have the option for people to use it

2021-06-03 00:18 UTC, repo-alt commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +            aCoverVariable = playerHash << 16 | aCoverVariable >> 16;
That will break existing setups, but I agree that something like that needs to be done.

2021-06-03 09:27 UTC, Dream-Master commented
@MatthewCOwen

2021-06-03 11:10 UTC, MatthewCOwen commented
yes?

2021-06-03 11:45 UTC, Dream-Master commented
@MatthewCOwen can you change the code like bot said ?

2021-06-03 14:23 UTC, MatthewCOwen commented
Yeah I'm working on it

2021-06-04 23:53 UTC, MatthewCOwen commented
Current setups *shouldn't* break, as long as you don't touch them. at all.

2021-06-05 02:24 UTC, MatthewCOwen commented
never mind it's not quite working

2021-06-05 08:33 UTC, MatthewCOwen commented
Alright everything should be working now

2021-06-05 09:51 UTC, repo-alt approved these changes
I don't see logic bugs just looking at the code, need to test in game, but otherwise I think it's fine

2021-06-05 15:36 UTC, botn365 requested changes

2021-06-05 15:36 UTC, botn365 commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +            aCoverVariable = (aCoverVariable & (PRIVATE_MASK | CHECKBOX_MASK)) | (((Integer)GT_Utility.stackToInt(aPlayer.inventory.getCurrentItem())).hashCode() & PUBLIC_MASK);
this should also reset the private channel so if a person never interacts with the GUI it wont have a private chanel that is 0

2021-06-05 16:53 UTC, Glease requested changes

2021-06-05 16:53 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +                aCoverVariable = aCoverVariable & (PRIVATE_MASK | CHECKBOX_MASK);
This condition will never happen. `PUBLIC_MASK` has its highest bit set to 0, i.e. the bitmask result will always be positive.

2021-06-05 16:53 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +            GT_Values.NW.sendToServer(new GT_Packet_TileEntityCover(side, coverID, coverVariable, tile));
Please create a new subclass of `GT_Packet_TileEntityCover` and figure out the player's hash on server side instead. Something like this would work:
```java
package gregtech.api.net;

import com.google.common.io.ByteArrayDataInput;
import gregtech.api.interfaces.tileentity.ICoverable;
import gregtech.api.interfaces.tileentity.IGregTechTileEntity;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.network.INetHandler;
import net.minecraft.network.NetHandlerPlayServer;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.world.IBlockAccess;
import net.minecraft.world.World;
import net.minecraftforge.common.DimensionManager;

public class GT_Packet_WirelessRedstoneCover extends GT_Packet_TileEntityCover {
    protected int mX;
    protected short mY;
    protected int mZ;

    protected byte side;
    protected int coverID, coverData, dimID;

    private EntityPlayerMP mPlayer;

    public GT_Packet_WirelessRedstoneCover() {
        super();
    }

    public GT_Packet_WirelessRedstoneCover(int mX, short mY, int mZ, byte coverSide, int coverID, int coverData, int dimID) {
        super(mX, mY, mZ, coverSide, coverID, coverData, dimID);
    }
    public GT_Packet_WirelessRedstoneCover(byte coverSide, int coverID, int coverData, ICoverable tile) {
        super(coverSide, coverID, coverData, tile);
    }

    @Override
    public byte getPacketID() {
        return 10;
    }

    @Override
    public void setINetHandler(INetHandler aHandler) {
        if (aHandler instanceof NetHandlerPlayServer) {
            mPlayer = ((NetHandlerPlayServer) aHandler).playerEntity;
        }
    }

    @Override
    public GT_Packet_New decode(ByteArrayDataInput aData) {
        return new GT_Packet_WirelessRedstoneCover(
                aData.readInt(),
                aData.readShort(),
                aData.readInt(),

                aData.readByte(),
                aData.readInt(),
                aData.readInt(),

                aData.readInt());
    }

    @Override
    public void process(IBlockAccess aWorld) {
        World world = DimensionManager.getWorld(dimID);
        if (world != null && world.blockExists(mX, mY, mZ)) {
            TileEntity tile = world.getTileEntity(mX, mY, mZ);
            if (tile instanceof IGregTechTileEntity && !((IGregTechTileEntity) tile).isDead()) {
                ((IGregTechTileEntity) tile).receiveCoverData(side, coverID, (mPlayer.getUniqueID().hashCode() & PRIVATE_MASK) | (coverData & PUBLIC_MASK | CHECKBOX_MASK));
            }
        }
    }
}
```
You will also need to register the packet in the constructor of `gregtech.common.GT_Network`.

2021-06-05 16:53 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +                coverVariable = (coverVariable & (PUBLIC_MASK | CHECKBOX_MASK)) | (lastPlayer.getDisplayName().hashCode() & PRIVATE_MASK);
display name can be changed for both online and offline players. Please use the `getUniqueId` instead.

2021-06-05 16:53 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +            aCoverVariable += tAdjustVal;
A player using channel 0x0000FFFF and with the checkbox set will have its new channel in other player's namespace. Need additional checks for overflow/underflow.

2021-06-05 17:04 UTC, Dream-Master commented
@MatthewCOwen can you re check?

2021-06-05 22:26 UTC, MatthewCOwen commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +            GT_Values.NW.sendToServer(new GT_Packet_TileEntityCover(side, coverID, coverVariable, tile));
I'm not familiar with the packet system in GT5, so I'll go ahead and copy paste this in the proper location

2021-06-06 03:46 UTC, Glease requested changes

2021-06-06 03:46 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +            int tCoverVariable = (aCoverVariable & PUBLIC_MASK) + tAdjustVal;
Did you forget to write back the tCoverVariable if it neither underflow nor overflow?

2021-06-06 03:46 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +            GT_Values.NW.sendToServer(new GT_Packet_TileEntityCover(side, coverID, coverVariable, tile));
You will also need to use the new class here. Replace the line with `GT_Values.NW.sendToServer(new GT_Packet_WirelessRedstoneCover(side, coverID, coverVariable, tile));`

2021-06-06 04:15 UTC, MatthewCOwen commented
I'm currently changing this right now. I should have another commit done soon.

2021-06-06 04:15 UTC, Glease commented
Sure take your time.

2021-06-06 06:02 UTC, MatthewCOwen commented on src/main/java/gregtech/common/covers/GT_Cover_RedstoneWirelessBase.java
> +            int tCoverVariable = (aCoverVariable & PUBLIC_MASK) + tAdjustVal;
Yeah I did forget that thanks.

2021-06-06 06:17 UTC, MatthewCOwen commented
I've done my best to incorporate the new `GT_Packet_WirelessRedstoneCover` class into my existing code, however I am unsuccessful in getting the same results as I had without the new class

2021-06-06 07:40 UTC, Glease commented
There is a few problems in my code. I have made some updates to it. Now it should work just fine.
```java
package gregtech.api.net;

import com.google.common.io.ByteArrayDataInput;
import gregtech.api.interfaces.tileentity.ICoverable;
import gregtech.api.interfaces.tileentity.IGregTechTileEntity;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.network.INetHandler;
import net.minecraft.network.NetHandlerPlayServer;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.world.IBlockAccess;
import net.minecraft.world.World;
import net.minecraftforge.common.DimensionManager;

public class GT_Packet_WirelessRedstoneCover extends GT_Packet_TileEntityCover {
    private static final int PRIVATE_MASK = 0xFFFE0000;
    private static final int PUBLIC_MASK = 0x0000FFFF;
    private static final int CHECKBOX_MASK = 0x00010000;

    private EntityPlayerMP mPlayer;

    public GT_Packet_WirelessRedstoneCover() {
        super();
    }

    public GT_Packet_WirelessRedstoneCover(int mX, short mY, int mZ, byte coverSide, int coverID, int coverData, int dimID) {
        super(mX, mY, mZ, coverSide, coverID, coverData, dimID);
    }
    public GT_Packet_WirelessRedstoneCover(byte coverSide, int coverID, int coverData, ICoverable tile) {
        super(coverSide, coverID, coverData, tile);
    }

    @Override
    public byte getPacketID() {
        return 10;
    }

    @Override
    public void setINetHandler(INetHandler aHandler) {
        if (aHandler instanceof NetHandlerPlayServer) {
            mPlayer = ((NetHandlerPlayServer) aHandler).playerEntity;
        }
    }

    @Override
    public GT_Packet_New decode(ByteArrayDataInput aData) {
        return new GT_Packet_WirelessRedstoneCover(
                aData.readInt(),
                aData.readShort(),
                aData.readInt(),

                aData.readByte(),
                aData.readInt(),
                aData.readInt(),

                aData.readInt());
    }

    @Override
    public void process(IBlockAccess aWorld) {
        World world = DimensionManager.getWorld(dimID);
        if (world != null && world.blockExists(mX, mY, mZ)) {
            TileEntity tile = world.getTileEntity(mX, mY, mZ);
            if (tile instanceof IGregTechTileEntity && !((IGregTechTileEntity) tile).isDead()) {
                ((IGregTechTileEntity) tile).receiveCoverData(side, coverID, (  mPlayer.getUniqueID().hashCode() & PRIVATE_MASK) | (coverData & (PUBLIC_MASK | CHECKBOX_MASK)));
            }
        }
    }
}
```

2021-06-07 10:35 UTC, Glease requested changes

2021-06-07 10:35 UTC, Glease commented on src/main/java/gregtech/api/net/GT_Packet_WirelessRedstoneCover.java
> +                int tCoverData = tPrivateChannel | mCheckBoxValue | mPublicChannel;
Both `mPublicChannel` and `mCheckBoxValue` needs masking. The client could well sent forged data to get into other people's namespace.

2021-06-07 10:35 UTC, Glease commented on src/main/java/gregtech/api/net/GT_Packet_WirelessRedstoneCover.java
> +        aOut.writeInt(coverData);
You don't need to send coverData if you are sending mPublicChannel and mCheckBoxValue instead.

2021-06-07 15:55 UTC, MatthewCOwen commented
Alright both changes have been made

2021-06-07 15:56 UTC, Glease approved these changes

2021-06-07 17:12 UTC, botn365 approved these changes

2021-06-07 17:15 UTC, merged