No auto-output rendering for steam basic machines
GTNewHorizons/GT5-Unofficial pull request #560
Opened 2021-06-13 15:36 UTC by YannickMG

Removes the visual aspect of the Auto-Output slots on Bronze and Steam basic machines.

I originally wanted to remove the slots altogether, but I wasn't comfortable with either the amount of code duplication or the depth of the basic machine rewrite it seemed to require.

If you feel like code duplication is a lesser evil than changing the behavior of GT_GUIContainer_BasicMachine based on the texture prefix, then this could easily be turned into GT_GUIContainer_BasicMachine_Bronze instead.

### Screenshots
The un-pressed buttons were removed from the sprites, the tooltip is disabled and the pressed state of the buttons is not displayed.
![steel-alloy-smalter](https://user-images.githubusercontent.com/5321549/121813582-9aab0200-cc3a-11eb-9f72-1d6871428725.png)

The slot is still there and can be highlighted, like other hidden Gregtech slots.
![steam-extractor](https://user-images.githubusercontent.com/5321549/121813566-849d4180-cc3a-11eb-8eeb-7639bb1a1833.png)

Works with [Machines titleboxes (enhance) #557](https://github.com/GTNewHorizons/GT5-Unofficial/pull/557)
![titleboxes-no-autooutput](https://user-images.githubusercontent.com/5321549/121813545-69323680-cc3a-11eb-894c-1d116c6e862d.png)

Regular basic machines unaffected
![cutting-machine](https://user-images.githubusercontent.com/5321549/121813552-76e7bc00-cc3a-11eb-9c6a-b66e10f29dba.png)

2021-06-14 16:27 UTC, leagris requested changes

2021-06-14 16:27 UTC, leagris commented on src/main/java/gregtech/api/gui/GT_GUIContainer_BasicMachine.java
> +        mRenderAutoOutputSlots = !(aTextureFile.startsWith("Steel") || aTextureFile.startsWith("Bronze"));
This is too hacky. I am sure there are other mean to probe if the machine has this capability.

2021-06-14 23:11 UTC, YannickMG commented on src/main/java/gregtech/api/gui/GT_GUIContainer_BasicMachine.java
> +        mRenderAutoOutputSlots = !(aTileEntity.getMetaTileEntity() instanceof GT_MetaTileEntity_BasicMachine_Bronze);
This could also be ((GT_MetaTileEntity_BasicMachine) aTileEntity.getMetaTileEntity()).isElectric(); if we assume there will never be a non-steam non-electric basic machine.

2021-06-14 23:13 UTC, Prometheus0000 commented on src/main/java/gregtech/api/gui/GT_GUIContainer_BasicMachine.java
> +        mRenderAutoOutputSlots = !(aTileEntity.getMetaTileEntity() instanceof GT_MetaTileEntity_BasicMachine_Bronze);
Name remover? Seismic prospector?

2021-06-14 23:15 UTC, YannickMG commented on src/main/java/gregtech/api/gui/GT_GUIContainer_BasicMachine.java
> +        mRenderAutoOutputSlots = !(aTextureFile.startsWith("Steel") || aTextureFile.startsWith("Bronze"));
Indeed, thanks for the push. Replaced by an explicit check that the machine is a steam basic machine.

I was also able to remove the 2 underlying slots and get GT_Container_BasicMachine.slotClick to behave properly, but I think that would need a lot of testing to make sure one caught all the places where the number of slots existing in a machine is assumed, so I'm not including that in this commit.

2021-06-14 23:34 UTC, YannickMG commented on src/main/java/gregtech/api/gui/GT_GUIContainer_BasicMachine.java
> +        mRenderAutoOutputSlots = !(aTileEntity.getMetaTileEntity() instanceof GT_MetaTileEntity_BasicMachine_Bronze);
Good call. Better stick to the current method then.

2021-06-15 06:42 UTC, Dream-Master commented
@YannickMG so more changes needed ?

2021-06-15 12:31 UTC, YannickMG commented
Not for now if that's alright with you, should be good as is. This is a very simple cosmetic change that works and has no apparent foreseeable side effects, unlike removing the actual slots.

2021-06-15 17:06 UTC, leagris approved these changes
Good to merge

2021-06-15 17:15 UTC, merged