add item filter cover
GTNewHorizons/GT5-Unofficial pull request #574
Opened 2021-06-25 14:26 UTC by GlodBlock

This stuff will be rewritten when cover supports NBT.

2021-06-25 17:01 UTC, Glease requested changes
Don't forget to also rename the various occasion of `model` in variable names to `mode`. 

The UI looks a bit too sparse. Maybe it could be made a bit shorter.

2021-06-25 17:01 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_ItemFilter.java
> +            itemFilterButtons = new GT_GuiFakeItemButton(this ,startX + spaceX*0, startY+spaceY*3, GT_GuiIcon.SLOT_GRAY);
Would be great if you can draw a line of text explaining what this slot means.

2021-06-25 17:02 UTC, GlodBlock commented on src/main/java/gregtech/common/covers/GT_Cover_ItemFilter.java
> +            GT_Utility.sendChatToPlayer(aPlayer, trans("124", "Black List Model"));
my fault. it should be Mode

2021-06-25 21:07 UTC, Prometheus0000 commented on src/main/java/gregtech/common/covers/GT_Cover_ItemFilter.java
> +            GT_Utility.sendChatToPlayer(aPlayer, trans("125", "White List Model"));
Black List->Blacklist. Same for white

2021-06-25 21:10 UTC, Prometheus0000 commented on src/main/java/gregtech/common/covers/GT_Cover_ItemFilter.java
> +                GT_Utility.sendChatToPlayer(aPlayer, trans("300", "Clear Filter!"));
This looks like it should be filter cleared, but I can't tell from just the code

2021-06-26 04:43 UTC, GlodBlock commented
the typo has been fixed.
i can't shorten the UI because the height of the texture is fixed.

2021-06-26 05:09 UTC, Glease requested changes

2021-06-26 05:09 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_ItemFilter.java
> +            b = new GT_GuiIconButton(this, 0, startX + spaceX*0, startY+spaceY*0, GT_GuiIcon.WHITELIST).setTooltipText(trans("125","Whitelist"));
In above code you referred to translation 125 as `Whitelist Mode`, and here it becomes `Whitelist`. This is not going to work very well. Please use different identifiers.

2021-06-26 05:09 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_ItemFilter.java
> +            GT_Utility.sendChatToPlayer(aPlayer, ""+aCoverVariable);
the result of stackToInt is unintelligible to an ordinary user. Best not send it. What are you trying to acheive here?

2021-06-26 05:09 UTC, Glease commented on src/main/java/gregtech/common/covers/GT_Cover_ItemFilter.java
> +        if (mode == 1) mode = 0;
Preferably collapse the two `if (mode ==1)` if into one. The current code style is not very readably, but that may be just me.

2021-06-26 06:12 UTC, Glease approved these changes

2021-06-26 06:15 UTC, Prometheus0000 commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java
> +        ItemList.ItemFilter_Export.set(addItem(270,"Item Filter Cover (Export)", "Right click with Item to set filter (Only support Export Mode)"));
Right click with Item to set filter (Only support Export Mode)
Right click with an item to set filter (Only supports Export Mode)

2021-06-26 06:15 UTC, Prometheus0000 commented on src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java
> +        ItemList.ItemFilter_Import.set(addItem(271,"Item Filter Cover (Import)", "Right click with Item to set filter (Only support Import Mode)"));
Right click with Item to set filter (Only support Import Mode)
Right click with an item to set filter (Only supports Import Mode)

2021-06-26 09:24 UTC, merged

2021-06-26 18:23 UTC, Prometheus0000 commented
Dream, why did you merge this before they fixed the grammar problems? Now someone needs to do a separate PR.

2021-06-26 18:24 UTC, Dream-Master commented
oh didnt see it sorry. Just do a another pr please @Prometheus0000 thanks