allow input hatch accept more fluids
GTNewHorizons/GT5-Unofficial pull request #643
Opened 2021-08-20 09:02 UTC by GlodBlock

to make these recipes viable.
![image](https://user-images.githubusercontent.com/60341015/130208685-dc23b8ec-1c40-4b9f-b451-35e6f0ae14df.png)
![image](https://user-images.githubusercontent.com/60341015/130208762-f9161857-8193-412d-bc23-ff2a7484ccca.png)
![image](https://user-images.githubusercontent.com/60341015/130208958-8ed7fd40-8db2-4fd6-a010-b985c3a38228.png)

2021-08-20 14:26 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OilCracker.java
> +                if (tStack.isFluidEqual(GT_ModHandler.getSteam(1000)) || tStack.isFluidEqual(Materials.Hydrogen.getGas(1000)) || tStack.isFluidEqual(FluidRegistry.getFluidStack("molten.atomic separat
The list is getting a bit too long. I'd rather prefer a better solution than a super duper long line.

BTW please avoid using space in fluid names. use underscores instead. There is no hard limit, but it's by convention to use underscores instead.

2021-08-20 14:31 UTC, GlodBlock commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OilCracker.java
> +                if (tStack.isFluidEqual(GT_ModHandler.getSteam(1000)) || tStack.isFluidEqual(Materials.Hydrogen.getGas(1000)) || tStack.isFluidEqual(FluidRegistry.getFluidStack("molten.atomic separat
these space are auto generated by GT/BW material system. there's nothing I can do about it.
maybe i can make a config for the fluid list.

2021-08-20 14:41 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_OilCracker.java
> +                if (tStack.isFluidEqual(GT_ModHandler.getSteam(1000)) || tStack.isFluidEqual(Materials.Hydrogen.getGas(1000)) || tStack.isFluidEqual(FluidRegistry.getFluidStack("molten.atomic separat
We can probably add a hook into the recipe adder system.

2021-08-20 16:59 UTC, botn365 requested changes
1. just lock hydrogen and steam out of the side input bus sinse imo it doesent realy matter for the other recipes

2. you could be smart with the recipe and check if that fluid is the first or second fluid but that would happen evry time you try to put in fluid so would be prety lagy

3. you could also allow all fluids in evry input bus and have a modifyed recipe check this would be a better option sinse it would be way more tps frendly

4. you could do a global hash map that stores all primary fluids and a second for all secondery fluids and modify the addRecipe code to put it in there 

this would be more tps frendly then the second option but still feels prety bad

but this here NO its horible

2021-08-21 03:08 UTC, GlodBlock commented
i make another recipe find method for the cracker.
use the order of recipe input fluid to determine whether it should be input at side or the middle. it won't be slower than the origin one, because it only search in `sCrakingRecipes` instead of the whole recipe collection.

2021-08-21 07:40 UTC, Dream-Master commented
@Glease @botn365

2021-08-21 11:54 UTC, Glease approved these changes

2021-08-21 17:44 UTC, Dream-Master commented
@botn365

2021-08-21 19:31 UTC, DualBallers commented
![image](https://user-images.githubusercontent.com/30087707/130332906-814f2c59-956d-4769-93c0-35ad966affba.png)

![image](https://user-images.githubusercontent.com/30087707/130332938-1ef88f2b-77df-4dd5-a544-9f70e5f6b0f3.png)

Spelling here?

2021-08-22 08:50 UTC, merged