rework(RC Rails)
GTNewHorizons/GT5-Unofficial pull request #650
Opened 2021-08-26 20:09 UTC by Dream-Master

buff recipes for rebars, tracks and rails
add circuit support to Bender
add Boster Tracks to Assembler
add Vanadium Gallium and Naquada small Gears for recipes

* Script changes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/8459
* Core Mod changes https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/205

2021-08-28 20:20 UTC, Glease commented
Can people somehow disassemble rails or turn it into raw metal? If yes we might need to remove those recipes.

2021-08-29 11:27 UTC, Dream-Master commented
> Can people somehow disassemble rails or turn it into raw metal? If yes we might need to remove those recipes.

beside Mc rails no

2021-08-29 12:19 UTC, leagris requested changes
Test Railcraft is loaded before adding Railcraft related recipes, because otherwise it creates a hard dependency on Railcraft in Gregtech.
If the Railcraft dependency is intentional, then the mod dependency must be configured in mcmod.info and `@mod`

2021-08-29 12:19 UTC, leagris commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingSlab.java
> +            GT_Values.RA.addChemicalBathRecipe(GT_Utility.copyAmount(3L, aStack), Materials.Creosote.getFluid(300L), ItemList.RC_Tie_Wood.get(3L), null, null, null, 200, 4);
missing a check Railcraft is loaded

2021-08-29 12:19 UTC, leagris commented on src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java
> +        GT_Values.RA.addBenderRecipe(GT_OreDictUnificator.get(OrePrefixes.stick, Materials.Aluminium, 20L), (GT_Utility.getIntegratedCircuit(10)), ItemList.RC_Rail_Standard.get(32L), 300, 30);
missing a check Railcraft is loaded

2021-08-29 12:19 UTC, leagris commented on src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java
> +        GT_Values.RA.addAssemblerRecipe(new ItemStack[] {new ItemStack(Blocks.stone_slab, 1, 0), ItemList.RC_Rebar.get(1L), GT_Utility.getIntegratedCircuit(1)}, GT_Values.NF, ItemList.RC_Tie_Stone.ge
Will crash if Railcraft is not present

2021-08-29 12:19 UTC, leagris commented on src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java
> +        GT_Values.RA.addAssemblerRecipe(new ItemStack[] {ItemList.RC_Tie_Wood.get(1L), GT_OreDictUnificator.get(OrePrefixes.stick, Materials.Iron, 1L), GT_Utility.getIntegratedCircuit(1)}, GT_Values.
Will crash if Railcraft is not present

2021-08-29 14:32 UTC, Glease commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingSlab.java
> +            GT_Values.RA.addChemicalBathRecipe(GT_Utility.copyAmount(3L, aStack), Materials.Creosote.getFluid(300L), ItemList.RC_Tie_Wood.get(3L), null, null, null, 200, 4);
Honestly this is not needed. GT will default to null and RecipeAdder will ignore all recipe registration attempts with null output.

2021-08-29 15:37 UTC, leagris commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingSlab.java
> +            GT_Values.RA.addChemicalBathRecipe(GT_Utility.copyAmount(3L, aStack), Materials.Creosote.getFluid(300L), ItemList.RC_Tie_Wood.get(3L), null, null, null, 200, 4);
It is needed because the process manipulates Railcraft items and address NBT tags in it.

2021-08-29 15:49 UTC, Glease commented on src/main/java/gregtech/loaders/oreprocessing/ProcessingSlab.java
> +            GT_Values.RA.addChemicalBathRecipe(GT_Utility.copyAmount(3L, aStack), Materials.Creosote.getFluid(300L), ItemList.RC_Tie_Wood.get(3L), null, null, null, 200, 4);
Yes for other stuff, but not this particular line.

2021-09-10 05:52 UTC, merged