Implemented limiting mode for input busses (same as in singleblocks)
GTNewHorizons/GT5-Unofficial pull request #674
Opened 2021-09-27 15:49 UTC by Florexiz

2021-09-27 15:57 UTC, boubou19 commented
Can you explain what is the purpose of this pull request please?

2021-09-27 16:01 UTC, Florexiz commented
As for now there are no way to limit amount of items inserted into input bus except complex automation like SFM/OC or laggy translocators with diamond nugget and PR pipes(maybe?). This can be helpful for some machines like bacterial vat to reduce amount of input busses from 4-5 to 1 and LCR with crop leaves for example

2021-09-27 16:19 UTC, GTNH-Colen commented
How is it enabled? With some tool?

2021-09-27 16:24 UTC, Florexiz commented
Shift + RMB with screwdriver. There are third option now, not only sort on/off

2021-09-27 17:16 UTC, repo-alt commented
This is really useful stuff actually, just PR name is not very clear.

2021-09-28 00:18 UTC, Glease requested changes

2021-09-28 00:18 UTC, Glease commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_InputBus.java
> +            if (GT_Utility.areStacksEqual(GT_OreDictUnificator.get(aStack), mInventory[i]))
Use `GT_OreDictUnificator.get_nocopy()` instead.

2021-09-28 00:20 UTC, Glease commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_InputBus.java
> +            if (GT_Utility.areStacksEqual(GT_OreDictUnificator.get(aStack), mInventory[i]))
Actually, is there a reason to unify the input stack at all?

2021-09-28 06:49 UTC, Dream-Master commented
@Florexiz

2021-09-28 07:07 UTC, Glease approved these changes

2021-09-28 07:10 UTC, Florexiz commented on src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_InputBus.java
> +            if (GT_Utility.areStacksEqual(GT_OreDictUnificator.get(aStack), mInventory[i]))
This check was copied straight from singleblocks `allowPutStack()`, so I thought It can useful in some scenarios

2021-09-28 16:17 UTC, merged