display tooltip for fluid
GTNewHorizons/GT5-Unofficial pull request #676
Opened 2021-09-29 13:35 UTC by GlodBlock

![图片](https://user-images.githubusercontent.com/60341015/135279074-75326d3b-2398-4927-93ed-a538aa97f964.png)

2021-09-29 17:00 UTC, Glease commented on src/main/java/gregtech/api/util/GT_Utility.java
> +                            else sFluidTooltips.put(aFluid.getFluid(), tMaterial.mChemicalFormula);
Fix your indentation please.

2021-09-29 17:12 UTC, Glease commented on src/main/java/gregtech/api/util/GT_Utility.java
> +                List tTooltip = tContainer.getTooltip(null, true);
This won't do. This method is only present in client jar but not in dedicated server. However this method is certainly called on server side as well (e.g. inside those input hatches, quantum tanks and every single blocks machines), so it will crash the server when basically any GT tile entity is being looked at. 

Let's move the thing off GT_Utility. You don't need these display info on the server side anyway.

2021-09-29 17:33 UTC, Glease commented on src/main/java/gregtech/common/items/GT_FluidDisplayItem.java
> +            if (!aNBT.getString("mFluidTooltip").equals(""))
You should not be using NBT to store this tooltip at all. Half of the fluid display item is generated by server and sent over the wire to client, which might have very different localization than client. Just use that fluid id to look into the cache instead.

2021-09-30 06:00 UTC, GlodBlock commented
have tested in full pack on Client and Server side, no crush or error happen

2021-09-30 12:37 UTC, Glease requested changes
Looks good

2021-09-30 12:37 UTC, Glease commented on src/main/java/gregtech/common/items/GT_FluidDisplayItem.java
> +        return sFluidTooltips.get(aRealFluid.getFluid());
Use `sFluidTooltips.computeIfAbsent(aFluid.getFluid(), aFluid -> {//that wall of text inside if})`

2021-09-30 12:41 UTC, TimeConqueror commented on src/main/java/gregtech/common/items/GT_FluidDisplayItem.java
> +            for(ItemStack tContainer : GT_Utility.getContainersFromFluid(aRealFluid)) {
Shouldn't you break the loop after finding the tooltip?

2021-09-30 12:58 UTC, GlodBlock commented on src/main/java/gregtech/common/items/GT_FluidDisplayItem.java
> +            for(ItemStack tContainer : GT_Utility.getContainersFromFluid(aRealFluid)) {
after changed to lambda expression, it will return after finding the tooltip

2021-09-30 12:59 UTC, Glease requested changes

2021-09-30 12:59 UTC, Glease commented on src/main/java/gregtech/common/items/GT_FluidDisplayItem.java
> +        return sFluidTooltips.get(aRealFluid.getFluid());
`computeIfAbsent` has a return value, which is just what you need here 🤦‍♂️

2021-09-30 13:02 UTC, Glease approved these changes

2021-09-30 13:10 UTC, merged