Unify build script draft
GTNewHorizons/GT5-Unofficial pull request #720
Opened 2021-11-07 15:39 UTC by SinTh0r4s

DO NOT MERGE IT YET!

Do we want to implement the version passing to GT_mod.java? We would need to adapt some minor things internally, then. Since GT uses hardcoded integers for versioning.

Also, when this is merged, it is likely to break some other build scripts. Which will be more work. But when that is done we could also provide gregtech with a master branch instead of experimental.

2021-11-07 15:50 UTC, glowredman commented on repositories.gradle
> +        url = "http://maven.tterrag.com"
Can use HTTPS

2021-11-07 15:50 UTC, glowredman commented on repositories.gradle
> +        url = 'http://dvs1.progwml6.com/files/maven'
Can use HTTPS

2021-11-07 15:50 UTC, glowredman commented on repositories.gradle
> +        url = "http://www.ryanliptak.com/maven/"
Can use HTTPS

2021-11-07 15:51 UTC, glowredman commented on repositories.gradle
> +// Add any additional repositiroes for your dependencies here
Typo: repositories

2021-11-07 15:52 UTC, glowredman commented on repositories.gradle
> +        url = "https://nexus.covers1624.net/repository/maven-hosted/"
Why do you use covers1624's maven instead of chickenbones' maven?

2021-11-20 20:46 UTC, bombcar commented on build.gradle
>          classpath 'com.github.GTNH2:ForgeGradle:FG_1.2-SNAPSHOT'
Isn't this the now-out-of date one and we should be on com.github.GTNewHorizons:ForgeGradle:FG_1.2-SNAPSHOT or similar?

2021-11-20 21:04 UTC, mitchej123 commented on build.gradle
>          classpath 'com.github.GTNH2:ForgeGradle:FG_1.2-SNAPSHOT'
https://github.com/GTNewHorizons/ForgeGradle/releases/tag/stable-2021-11-20

2021-12-01 16:49 UTC, Glease requested changes
I'm skeptic at changing the version. It's an invitation to distaster. I'd imagine every single addon or weird mod that depends on gregtech in an unexpected way to break.

2021-12-01 16:49 UTC, Glease commented on .github/workflows/build-and-test.yml
> +        timeout 10 ./gradlew runServer || true
Did you actually just have this same line in your template? 10 second == 1min?

2021-12-01 16:49 UTC, Glease commented on .github/workflows/gradle.yml
> -  test-scala-presence:
This should not be just deleted. Maybe remove the build job and name this file like `test-scala-presence.yml`

2021-12-01 16:56 UTC, bombcar commented
> I'm skeptic at changing the version. It's an invitation to distaster. I'd imagine every single addon or weird mod that depends on gregtech in an unexpected way to break.

At some point we bite that bullet; but doesn't dream up the version each release?

2021-12-01 16:59 UTC, Glease commented
> At some point we bite that bullet; but doesn't dream up the version each release?

No. What dream change is really just produced archive version. What is supplied to fml hasn't really changed for more than half a decade.

2021-12-01 16:59 UTC, Glease commented on .github/workflows/build-and-test.yml
> +        timeout 10 ./gradlew runServer || true
@TheElan

2021-12-01 16:59 UTC, SinTh0r4s commented on .github/workflows/gradle.yml
> -  test-scala-presence:
That files is gone completely

2021-12-01 17:01 UTC, SinTh0r4s commented
The old internal version is in code is still there, but marked deprecated. That way we won't break any addons!

2021-12-01 17:01 UTC, SinTh0r4s commented on .github/workflows/build-and-test.yml
> +        timeout 10 ./gradlew runServer || true
@TheElan

2021-12-01 17:01 UTC, mitchej123 commented
He's referring to this - 
![image](https://user-images.githubusercontent.com/1894689/144279282-8943684c-c4e2-4d3f-bd4a-e8baed4c092e.png)

2021-12-01 17:02 UTC, bombcar commented
Let me guess, code should use `modid` but will depend on `name` instead ...

2021-12-01 17:16 UTC, SinTh0r4s commented
> the version MC1710 --> GRADLETOKEN_VERSION

You are correct! Should stick with the constant. Gonna push the change in a second!

2021-12-01 17:17 UTC, Glease commented
Also in mcmod.info. I'm not sure which will take precedence.

2021-12-01 17:18 UTC, mitchej123 commented
I think the mcmod.info is fine; but I do agree with the GT_MOD.java -> @MOD(version) revert

2021-12-01 17:20 UTC, mitchej123 commented
My (possibly incorrect) interpretation is that launchers (mutlimc) and FML uses the mcmod.info for version detection, and other mods use the @MOD annotation version.

2021-12-01 18:54 UTC, glowredman commented
Afaik Forge or FML also uses the version in the @Mod annotation to check dependencies

2021-12-01 19:10 UTC, TheElan commented on .github/workflows/build-and-test.yml
> +        timeout 10 ./gradlew runServer || true
That's odd, it shoild be 1min so server got moretime to fail

2021-12-01 19:16 UTC, glowredman commented
As far as I'm concerned it should be handled like this (in general):
- modid: have a constant field somewhere (e.g. main mod class or Reference/Constants/... class). @Mod refers to that, same text in mcmod.info (no placeholder). The modid should NOT be changed *ever*, so having a token for it is just redundant and error prone.
- modname: same as above, not as important to keep the exact same String, but still not necessary to have the script replace it every single time the mod is built.
- modversion: use of a token to replace version in mcmod.info and @Mod-annotation (like currently implemented)
- mcversion: could use a token - but why? we aren't going to change it, so just don't. It's essentially voided processing power.

2021-12-01 19:19 UTC, mitchej123 commented
I tend to agree with you @glowredman   I think what is happening here though is there is a template mod repo that instead of having to change it in 15 different places, it's limited to the build script.  Easier to fork and start new mods, but it does come across as a bit weird when refactoring existing build scripts.  

That being said, I'm fine with it as a part of the build script standardization effort.

2021-12-01 19:25 UTC, glowredman commented
As far as I understand the gradle.properties file, not setting the fields will result in the script not attempting to replace them. So it would be easy to leave that part of the script as-is  and only have the version field be poulated. This way the buildscript can be used as a template, my points above are still met and it would increase the amount of work.

2021-12-01 19:26 UTC, TheElan commented
By me having modid in token is fine, you use it in different places, beside code and to avoid any accidental inconsistencies it's better to have it in one place, and most convenient one here is `gradle.properties`

I also like the approach of keeping all metadata in one place (mod name, version, MC version, etc) it's more consistent then values scattered around the project, and processing cost here is minimal, probably a fraction of a sec when building (constants are inlined anyway).

2021-12-01 19:38 UTC, SinTh0r4s commented
> As far as I understand the gradle.properties file, not setting the fields will result in the script not attempting to replace them. So it would be easy to leave that part of the script as-is and only have the version field be poulated. This way the buildscript can be used as a template, my points above are still met and it would increase the amount of work.

Increase it will^^
The replacement in mcmod.info is not optional in the current implementation (absolutely an oversight on my part). All 4 values must be replaced. Changing it now will create PRs to all migrated build scripts again and half a day of tedious work. I don't think this is worth the effort.

And there are upsides to it as well. As Elan said: consistency! And with 1/3 or all mods I have migrated so far the consistency was NOT given.

2021-12-01 19:45 UTC, glowredman commented
> By me having modid in token is fine, you use it in different places, beside code and to avoid any accidental inconsistencies it's better to have it in one place, and most convenient one here is `gradle.properties`
> 
> I also like the approach of keeping all metadata in one place (mod name, version, MC version, etc) it's more consistent then values scattered around the project, and processing cost here is minimal, probably a fraction of a sec when building (constants are inlined anyway).

I disagree. Using tokens would increase the chance of errors: if you want to reference the modid/modname from anywhere, you need to copy/retype the string each time. With a constant from the Main mod calls or some type of reference class, you can just reference that. This is the way it is handled for years now and there were never problems with it. Using a constant also allows dependants to reference it, which is not possible with a token (not to mention that with the ccurrent script you can't replace the token in more than one file anyway). Having a constant holding a token would be possible but defeats the purpose. Having something so important like the modid accidentally change while converting 200+ repos is a far greater risk than anything one gains from this.
Outside of the code the only places I can think of are the mcmod.info file and the namespace of the assets folder and this namespace is not necessarily coupled to the modid anyways.


> > As far as I understand the gradle.properties file, not setting the fields will result in the script not attempting to replace them. So it would be easy to leave that part of the script as-is and only have the version field be poulated. This way the buildscript can be used as a template, my points above are still met and it would increase the amount of work.
> 
> Increase it will^^
> The replacement in mcmod.info is not optional in the current implementation (absolutely an oversight on my part). All 4 values must be replaced. Changing it now will create PRs to all migrated build scripts again and half a day of tedious work. I don't think this is worth the effort.
> 
> And there are upsides to it as well. As Elan said: consistency! And with 1/3 or all mods I have migrated so far the consistency was NOT given.

That is really unfortunate. I really appreciate the effort you guys have put into this, but imo this is just overkill and not good practice.

2021-12-01 19:51 UTC, TheElan commented
> I disagree. Using tokens would increase the chance of errors: if you want to reference the modid/modname from anywhere, you need to copy/retype the string each time.

I agree, you shouldn't use it as a adhock string injection. The intention here is to use token only to inject value in a class with constants and reference it's members in code. (probably @SinTh0r4s injected it directly into annotation values by mistake, there should be a central constant class like https://github.com/SinTh0r4s/ExampleMod1.7.10/blob/main/src/main/java/com/myname/mymodid/Tags.java)

> Outside of the code the only places I can think of are the mcmod.info file and the namespace of the assets folder and this namespace is not necessarily coupled to the modid anyways.

There are other small things, like jar name, actual artifact name for referencing purposes, if using mixins - configuration file which is generated, etc.

2021-12-01 19:52 UTC, mitchej123 commented
It's being replaced into a constant, in the main mod file, so any other mod can continue relying on it as usual.

Having forked and maintained a bunch of mods, they all do it slightly differently and I appreciate it being standardized.

2021-12-01 19:55 UTC, merged

2021-12-01 19:55 UTC, glowredman commented
> There are other small things, like jar name, actual artifact name for dependency purposes, if using mixins - configuration file which is generated, etc.

Sure but those cannot break worlds like a changed modid when registering items/blocks/entities/... can.

2021-12-01 19:58 UTC, mitchej123 commented
I do agree any replacement should be done into a constant that can be relied upon externally!

2021-12-01 20:01 UTC, TheElan commented
> > There are other small things, like jar name, actual artifact name for dependency purposes, if using mixins - configuration file which is generated, etc.
> 
> Sure but those cannot break worlds like a changed modid when registering items/blocks/entities/... can.

Agree, that would be a disaster, and for that we have review, so people can double check that modid is the same after refactor

2021-12-03 06:36 UTC, Glease commented
Why merge this when there is unresolved requested changes?

2021-12-03 06:38 UTC, Glease commented on .github/workflows/gradle.yml
> -  test-scala-presence:
What do you mean? test-scala-presence is not needed whatsoever?