Improve ghost circuit slot handling
GTNewHorizons/GT5-Unofficial pull request #821
Opened 2021-12-17 13:01 UTC by Glease

Add tooltip to ghost circuit slot

Also tweaked allowPutStack to consider configured circuits as well.

2021-12-17 13:02 UTC, Glease commented
![scrn](https://user-images.githubusercontent.com/4586901/146548487-270acf3a-491e-4cb0-b507-6be0b478f40a.png)

2021-12-17 13:43 UTC, GlodBlock commented on src/main/java/gregtech/api/gui/GT_GUIContainer_BasicMachine.java
> +            "Ghost Circuit Slot",
it is not a good practice to hard code these info. people can't translate it

2021-12-17 13:59 UTC, GlodBlock requested changes

2021-12-17 13:59 UTC, GlodBlock commented on src/main/java/gregtech/api/gui/GT_GUIContainer_BasicMachine.java
> +            EnumChatFormatting.GRAY + "GT5U.machines.select_circuit.tooltip.1",
the color breaks the lang key

2021-12-18 02:49 UTC, GlodBlock approved these changes

2021-12-18 15:59 UTC, merged