Large Boiler Rebalance
GTNewHorizons/GT5-Unofficial pull request #866
Opened 2022-01-12 17:12 UTC by Steelux8

- Changed Large Steel Boiler to output 1000 instead of 600 EU/t.
- Changed Large Titanium Boiler to output 6000 instead of 800 EU/t.
- Changed Large Titanium Boiler to output 6000 instead of 800 EU/t.
- Changed Large Tungstensteel Boiler to output 18750 instead of 1000 EU/t.
- Changed Titanium and Tungstensteel Boilers to output Superheated Steam instead of regular Steam.
- Added an upper bound for the burn value that can be processed by the boilers, in order to prevent an overflow.
- Added a lower bound for the burn value that can be processed by the boilers. This is a placeholder limitation intended to prevent the player from using the improved Titanium and Tungstensteel boilers to generate lots of power from easy solid fuels like Charcoal. A better way to implement this would be to make a whitelist of accepted fuels. The one I had in mind for these boilers was the Super Fuels, both the magic and non-magic ones.

The last two boilers had terrible numbers for their tier. High numbers would allow for charcoal powergen up to IV or LuV, though, so the better boilers should only accept solid fuels that are difficult to make and need a processing chain.

2022-01-13 01:50 UTC, kenken244 commented
Basing it on burn value won't work because you can just compress charcoal. It probably needs a whitelist. I would suggest allowing coal and/or coke  too. Also we could do with a stainless steel or aluminum boiler

2022-01-13 05:25 UTC, repo-alt commented
There are underused "Super Fuel" and "Magic Super Fuel"

2022-01-13 06:00 UTC, repo-alt commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java
> +    final private int superToNormalSteam = 3;
Why are you dividing by 3? You will lose water this way. Heat exchanger divides by 2

2022-01-13 09:49 UTC, Steelux8 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java
> +        if (isSuperheated()) {
I tried adding the if statement in the place where the lines would be different, but the addInfo after it was giving me an error, I was probably doing it wrong. If there's a way to do this without making a second tooltip, I'd rather do it that way.

2022-01-13 09:52 UTC, Steelux8 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java
> +    final private int superToNormalSteam = 3;
I didn't take that into account since water is normally free, I forgot the LHE chain recycles the water it uses. I divided by 3 because I wanted the value of getEUt to match the EU/t that superheated steam would make (at 100% efficiency). Superheated steam makes twice as much EU/t as normal steam, and it adds onto the steam amount, it doesn't replace it, so it's 1x steam + 2x steam = 3x steam, so I divided it by 3.

2022-01-13 09:56 UTC, repo-alt commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java
> +        if (isSuperheated()) {
What kind of error can it give? addInfo() just adds lines to the internal list and returns Tooltip_Builder itself

2022-01-13 10:02 UTC, Dream-Master commented
Didn’t know what is a good balance but your buff are massive. I want to hear more player first.

2022-01-13 10:06 UTC, repo-alt commented
Those EU/t values - do they take into account turbines efficiency?

2022-01-13 12:09 UTC, Steelux8 commented
> Those EU/t values - do they take into account turbines efficiency? (I think they don't, so they should be toned down a bit, like 12k for IV one and 4k for EV base production values)

I measured the EU/t of the titanium boiler by comparing the superheated steam output with the LHE. This value should mean that a quad titanium boiler matches a LHE processing the max amount of hot coolant it can take. On one hand, matching an LHE with EV titanium boilers might seem excessive, but it's also true that one LHE needs less titanium than one boiler, and 4 boilers would be needed to match one, while also accepting only fuels that need a chain.

The tungstensteel boiler is arbitrary, I didn't really know what to compare it to. The current value produces 250k superheated steam per second, or 12.5k superheated steam/t. Definitely an excessive number, but I want to decide on the correct numbers with other people involved.

2022-01-13 12:10 UTC, Steelux8 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java
> +        if (isSuperheated()) {
I did not write tt.addInfo on the addInfo right after the if condition, that's why it was giving me an error. I fixed it, the tooltips are as before but without copypasting the whole tooltip.

2022-01-13 14:45 UTC, Steelux8 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java
> +    final private int superToNormalSteam = 3;
I've fixed the water consumption. Superheated Steam boilers now recycle the water perfectly when the steam goes through HP and normal Large Steam Turbines.

2022-01-13 15:19 UTC, repo-alt approved these changes
Well, code-wise it's ok, balance-wise I've stated my opinion, but I won't really object to 18k EU for IV version either (because you e.g. have vac nukes at that moment already)

2022-01-14 01:03 UTC, Sphyix commented
Just remember that the amount of power at IV to jump to the next power source (fusions) is just massive.
Like wiki says 

>Once you reach LuV, fusion opens up as a power option ....  It will take you roughly 20h to process everything you need, assuming you can provide 2A zpm for that duration.

Not sure if any power production was added at LuV, I passed that tier a long time ago, but I remember needing multiple vacuum nukes to make the 1st fusion in a decent time, since bigger vac nuke is around 40k eu/t
Having alternatives is good for sure.

2022-01-14 01:31 UTC, 0lafe commented
Would you consider balancing combustable fuels a little better than the normal boiler? Iirc the base is 1/4 efficiency which makes them pretty useless. Could be cool to see HOG in there as another option for IV-LuV power gen, but something like diesel/cbd might be too simple

2022-01-14 02:04 UTC, vovaksenov commented
Circuit throttle may have to be adjusted as well. Iirc it is now 1000L/s per circuit number, which would probably make little sense if the output is increased so much.

2022-01-14 17:22 UTC, Steelux8 commented
> Would you consider balancing combustable fuels a little better than the normal boiler? Iirc the base is 1/4 efficiency which makes them pretty useless. Could be cool to see HOG in there as another option for IV-LuV power gen, but something like diesel/cbd might be too simple

I don't really see these boilers as the right place to burn those fluid fuels for power, given there are other multis for it already. The titanium boiler would be doing the same function as the LCE, and the tungstensteel boiler would end up the same way with the ECE (very underpowered, needs a big reduction to the LOX needed to make it worth) and the Universal Chemical Engine, which I think also does combustion.

I'm not sure why the large boilers can burn the diesels, really. It might be from old code, in the original Gregtech, but in GTNH I find it hard to believe that it's worth burning diesel fuels at 25% efficiency in _any_ of the boilers. I am unsure as to what to do with this mechanic.

2022-01-14 17:24 UTC, bombcar commented
The only thing I can think of is allowing you to keep your boiler when you transition from coal to light fuel/diesel (there IS a note about semifluid in the code there, so perhaps the idea was burning waste semifluid, but the semi gens are fixed now).

I'd be fine removing it, if you want to be silly the rail craft boilers can be used.

2022-01-15 11:21 UTC, Dream-Master commented
> **The new numbers are not final.** Please share your opinion for what they should be, I'm not fit to decide on balanced numbers by myself.
> 
> * Changed Large Steel Boiler to output 1000 instead of 600 EU/t.
> * Changed Large Titanium Boiler to output 6000 instead of 800 EU/t.
> * Changed Large Tungstensteel Boiler to output 18750 instead of 1000 EU/t.
> * Changed Titanium and Tungstensteel Boilers to output Superheated Steam instead of regular Steam.
> * Added an upper bound for the burn value that can be processed by the boilers, in order to prevent an overflow.
> * Added a lower bound for the burn value that can be processed by the boilers. This is a placeholder limitation intended to prevent the player from using the improved Titanium and Tungstensteel boilers to generate lots of power from easy solid fuels like Charcoal. A better way to implement this would be to make a whitelist of accepted fuels. The one I had in mind for these boilers was the Super Fuels, both the magic and non-magic ones.
> 
> The last two boilers had terrible numbers for their tier. High numbers would allow for charcoal powergen up to IV or LuV, though, so the better boilers should only accept solid fuels that are difficult to make and need a processing chain.

new suggestiones:
* Changed Large Steel Boiler to output 1000 instead of 600 EU/t.
* Changed Large Titanium Boiler to output 4000 instead of 800 EU/t.
* Changed Large Tungstensteel Boiler to output 16000 instead of 1000 EU/t.

2022-01-15 11:24 UTC, Dream-Master requested changes

2022-01-15 11:24 UTC, Dream-Master commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler_Titanium.java
> +        return 6000;
4000 better

2022-01-15 11:24 UTC, Dream-Master commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler_TungstenSteel.java
> +        return 18750;
16000 better

2022-01-15 16:38 UTC, Steelux8 commented
I think the new values are good, too, but keep in mind that the Superheated Steam values on the tooltip will not be round numbers with these changes, and it'll look a bit ugly. Not sure how to fix that.

2022-01-15 16:49 UTC, Steelux8 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler_Titanium.java
> +        return 6000;
Changed.

2022-01-15 16:49 UTC, Steelux8 commented on src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler_TungstenSteel.java
> +        return 18750;
Changed.

2022-01-15 17:33 UTC, bombcar commented
Can you show the tooltip number examples? Maybe we can tune it slightly up

2022-01-15 18:22 UTC, Dream-Master approved these changes

2022-01-15 18:23 UTC, merged