Bit flag fix
GTNewHorizons/GT5-Unofficial pull request #888
Opened 2022-01-23 05:06 UTC by MrJakobLaich

I fixed the `aTypes` bitflags in `Materials.java` which weren't used in `OrePrefixes.java`

![image](https://user-images.githubusercontent.com/40965742/150665629-d5bb0402-2456-409f-b95d-14639f015d4b.png)

Tested by looking at recipes in singleplayer, so far I don't know a way to automatically compare this yet...

Also, just to make sure nobody misses this:
(because this was too annoying to clean up, please don't make me do it again)
![image](https://user-images.githubusercontent.com/40965742/150665692-16332ade-e818-43ab-baf8-145614dedc70.png)

2022-01-23 05:10 UTC, YannickMG commented
Could we use that NEI dumping tool to do a recipe change diff?

Actually we could do that as a workflow on every PR to highlight recipe changes.

2022-01-27 07:39 UTC, repo-alt commented on src/main/java/gregtech/api/enums/OrePrefixes.java
> +                if ((aMaterial.mTypes & 0x01) == 0 && (aMaterial.mTypes & 0x02) == 0 && (aMaterial.mTypes & 0x04) == 0 && (aMaterial.mTypes & 0x08) == 0)
Wouldn't it be a bit more readable as `aMaterial.mTypes & 0x0F` or at least as `aMaterial.mTypes & (1|2|4|8)` ?

2022-01-27 07:40 UTC, repo-alt commented on src/main/java/gregtech/api/enums/OrePrefixes.java
> +                if ((aMaterial.mTypes & 0x01) == 0 && (aMaterial.mTypes & 0x02) == 0 && (aMaterial.mTypes & 0x04) == 0 && (aMaterial.mTypes & 0x08) == 0)
Also aren't there public static final names for these values? (if not maybe it makes sense to add them?)

2022-01-27 08:10 UTC, MrJakobLaich commented on src/main/java/gregtech/api/enums/OrePrefixes.java
> +                if ((aMaterial.mTypes & 0x01) == 0 && (aMaterial.mTypes & 0x02) == 0 && (aMaterial.mTypes & 0x04) == 0 && (aMaterial.mTypes & 0x08) == 0)
Can't be 0x0F because then 64 bit flag wouldn't work correctly iirc

just woke up so I might be wrong on this one

Also, idk if there are public static final names for this, if they exist I didn't notice them

I'd still prefer to not use tripple negation (if it is not 0x01 then it gets disabled and all disabled items don't get generated)
Better would be to have a list of things that DO get generated but I haven't gotten that far yet

2022-01-27 09:34 UTC, riking commented on src/main/java/gregtech/api/enums/OrePrefixes.java
> +                if ((aMaterial.mTypes & 0x01) == 0 && (aMaterial.mTypes & 0x02) == 0 && (aMaterial.mTypes & 0x04) == 0 && (aMaterial.mTypes & 0x08) == 0)
Confirming that the proposed `mTypes & 0xF == 0` is equivalent to the code here. Conceptually you can think of the RHS as `== (0 & 0xF)` instead if you want.

2022-01-27 11:19 UTC, MrJakobLaich commented on src/main/java/gregtech/api/enums/OrePrefixes.java
> +                if ((aMaterial.mTypes & 0x01) == 0 && (aMaterial.mTypes & 0x02) == 0 && (aMaterial.mTypes & 0x04) == 0 && (aMaterial.mTypes & 0x08) == 0)
Oh god, yeah xD

I will no longer write github comments the second I wake up, I read that as "if bitflag == 0 then" and thought that would break 64 bit flags

Yeah, now I agree, 0x0F would work

2022-01-30 06:26 UTC, mitchej123 requested changes
Yay, thanks for getting rid of those ugly ass if statements... big fan of bitsets.

1) Please add some constants for easier understanding of the bits
2) [Optional] Make a function to check for the bits being set/not set etc, instead of doing inline
3) [Mandatory] Let's figure out a way to ensure the before and after of this is the same.  Dump before and after items, check counts, etc.

2022-01-30 06:26 UTC, mitchej123 commented on src/main/java/gregtech/api/enums/Materials.java
> +     * @param aTypes                which kind of Items should be generated. Bitmask as follows:
I'm not a fan of magic numbers.  I'd prefer if we had either an ENUM or final int variables we could use in place, even if they are a bit longer.  See RecipeBits in GT_ModHandler.java as an example

2022-01-30 06:26 UTC, mitchej123 commented on src/main/java/gregtech/api/enums/OrePrefixes.java
> +                if ((aMaterial.mTypes & 0x01) == 0 && (aMaterial.mTypes & 0x02) == 0 && (aMaterial.mTypes & 0x04) == 0 && (aMaterial.mTypes & 0x08) == 0)
As above.  Please swap these out with descriptive constants like RecipeBits. 

nit:  blah & TEST == 0 is little ugly  A nice helper function would be more clear.
`aMaterial.notSet(SOME_BIT_FLAG)`

```java
boolean noneSet(int bits) {
    return (this.mTypes & bits) == 0;    
}
boolean isSet(int bits) {
    return this.mTypes & bits == bits;
}
boolean anySet(int bits) {
    return mTypes & bits != 0;
}
```

2022-01-31 10:41 UTC, draknyte1 commented on src/main/java/gregtech/api/enums/OrePrefixes.java
>                      wireFine.mDisabledItems.add(aMaterial);
You don't need wire to make fine wire.

2022-07-15 02:07 UTC, closed without merging