Mining behaviour rework
GTNewHorizons/GT5-Unofficial pull request #936
Opened 2022-02-14 05:51 UTC by Relvl

Everything related to mining machines, managing a mining pipe is placed in a separate class. It is assumed that all machines that can dig and have a pipe will use this object instead of inventing another bicycle that "works a little differently".
At the moment, only the miner has been transferred to this object.
As time goes on, I am rewriting the pump and in the plans - a multi-block miner and a pump.

It is assumed that the review will be carried out as for new mechanics, and not just for changes (too many changes).

Also fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9733

2022-02-14 05:52 UTC, Relvl commented
@GTNewHorizons/core review this pr please

2022-02-19 10:41 UTC, Glease requested changes
Most are cosmetic changes, but there is indeed one real bug in `pushOutputs` that needs addressing.

2022-02-19 10:41 UTC, Glease commented on src/main/java/gregtech/common/misc/GT_MiningPipeAddon.java
> +public class GT_MiningPipeAddon {
Why an `Addon`? This name is honestly a bit puzzling. How about `GT_DrillingController`? This is just a suggestion though.

2022-02-19 10:41 UTC, Glease commented on src/main/java/gregtech/common/misc/GT_IMiningPipeOwner.java
> +public interface GT_IMiningPipeOwner extends IMetaTileEntity {
I'd go with `IGT_Driller`

2022-02-19 10:41 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +            else if (slot.stackSize <= stack.getMaxStackSize() - count) {
Need to check if `GT_Utility.areStacksEqual(slot, stack)`, otherwise retracting pipes would allow exploits.

2022-02-21 07:28 UTC, Relvl commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +        return mTier == 1 ? 4096 : V[mTier] * 64;
It was in the old code, just didn't notice

2022-02-21 07:30 UTC, Relvl commented on src/main/java/gregtech/common/misc/GT_MiningPipeAddon.java
> +public class GT_MiningPipeAddon {
'Controller' word may seem like a conflict with the multiblock controllers. 
I don’t think it’s a good name either, but I didn’t come up with anything more logical and independent.

2022-02-21 07:32 UTC, Relvl commented on src/main/java/gregtech/common/misc/GT_IMiningPipeOwner.java
> +public interface GT_IMiningPipeOwner extends IMetaTileEntity {
Same as above, аirst we need to come up with a correct name for the 'addon', and only then decline the interface name from it.

2022-02-21 10:12 UTC, Glease commented on src/main/java/gregtech/common/misc/GT_MiningPipeAddon.java
> +public class GT_MiningPipeAddon {
Maybe `GT_DrillingLogicDelegate`?

2022-02-21 10:13 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +    /** @deprecated This method are obsolete, and may be removed in further updates. Please use 'this.pipe.getFakePlayer(te)' access! */
You forget to change the javadoc here ;)

2022-02-21 10:15 UTC, Relvl commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +    /** @deprecated This method are obsolete, and may be removed in further updates. Please use 'this.pipe.getFakePlayer(te)' access! */
Do you mean annotation?

2022-02-21 10:25 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +    /** @deprecated This method are obsolete, and may be removed in further updates. Please use 'this.pipe.getFakePlayer(te)' access! */
The javadoc still refers to `this.pipe.getFakePlayer(te)`, not `this.getPipe().getFakePlayer(te)`.

2022-02-21 10:25 UTC, Glease commented on src/main/java/gregtech/common/tileentities/machines/basic/GT_MetaTileEntity_Miner.java
> +    /** @deprecated This method are obsolete, and may be removed in further updates. Please use 'this.pipe.getFakePlayer(te)' access! */
This is not annotation. Annotation are stuff outside the comment block.

2022-02-21 10:28 UTC, Glease approved these changes

2022-02-21 12:35 UTC, merged