remove autogenerated recipes (electrolyzer)
GTNewHorizons/GT5-Unofficial pull request #953
Opened 2022-02-25 21:59 UTC by Dream-Master

added it to core mod

2022-04-24 07:30 UTC, GlodBlock commented
why silicon electronic grade only obtainable from crush or cutting silicon boule? it is impossible to have monocrystal silicon **dust** or smelt monocrystal silicon dust into monocrystal silicon ingot. crystal structure will be disrupted when you crush or heat it

2022-04-24 07:32 UTC, GlodBlock commented
> why silicon electronic grade only obtainable from crush or cutting silicon boule? it is impossible to have monocrystal silicon **dust** or smelt monocrystal silicon dust into monocrystal silicon ingot. crystal structure will be disrupted when you crush or heat it. they are more similar to gem material instead of metal

2022-04-24 08:39 UTC, Dream-Master commented
> why silicon electronic grade only obtainable from crush or cutting silicon boule? it is impossible to have monocrystal silicon **dust** or smelt monocrystal silicon dust into monocrystal silicon ingot. crystal structure will be disrupted when you crush or heat it. they are more similar to gem material instead of metal

Mh any suggestion how we can change this? or should we remove SIeg completly so you can only make boules with Sisg ?

2022-04-24 09:11 UTC, GlodBlock commented
i have a rough idea to get SIeg:
silicon boule -- crush --> SIeg crystal nucleus
SIeg crystal nucleus + molten SIsg -- fluid solidifer --> SIeg ingot

2022-04-24 21:29 UTC, Pxx500 commented
Simple solution is to remove "(Mono Si)" from items name since it doesn't make sense, but having Sieg doesn't make any sense in itself since it's made just like Sisg (getting it from cutting is still counts) so they're technically the same thing.

2022-04-24 21:52 UTC, Dream-Master commented
> Simple solution is to remove "(Mono Si)" from items name since it doesn't make sense, but having Sieg doesn't make any sense in itself since it's made just like Sisg (getting it from cutting still counts) so they're technically the same thing.

Ok will look tomorrow into it.

2022-04-25 06:36 UTC, GlodBlock commented
they are not the same thing, after the poly silicon become silicon boule, they are mono silicon. if you still don't understand i can explain that in chinese @Pxx500

2022-04-25 08:19 UTC, Pxx500 commented
I understand that they are different things but when monocrystaline silicon is broken into a powder it's properties are effectively lost and it can be considered polycrystaline (not because it's polycrystaline but because it's useless as a monocrystaline silicone [unless you add a process to use it as a crystal base for more boules])

2022-04-25 08:21 UTC, GlodBlock commented
> I understand that they are different things but when monocrystaline silicon is broken into a powder it's properties are effectively lost and it can be considered polycrystaline (not because it's polycrystaline but because it's useless as a monocrystaline silicone [unless you add a process to use it as a crystal base for more boules])

https://github.com/GTNewHorizons/GT5-Unofficial/pull/953#issuecomment-1107798681

2022-04-25 08:47 UTC, Pxx500 commented
"they are the same thing" as in their properties are essentially the same since monocrystaline powder is similar to polycrystaline

2022-04-25 09:12 UTC, leagris commented
I think this detail from reality, does not matter at all in the scope of GTNH. `Silicon` is good enough for this context.

2022-04-25 09:59 UTC, Glease commented
The whole spirit of this change is realism. I don't value this as much as others do but I guess at this point we need to emphasis this a bit in this PR.

2022-06-02 17:54 UTC, GlodBlock requested changes
strange chemical recipe

2022-06-02 17:54 UTC, GlodBlock commented on src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java
> +        GT_Values.RA.addMultiblockChemicalRecipe(new ItemStack[]{GT_Utility.getIntegratedCircuit(1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.SiliconDioxide, 3), GT_OreDictUnificator.get(
`GT_Values.RA.addMultiblockChemicalRecipe(new ItemStack[]{GT_Utility.getIntegratedCircuit(1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.SiliconDioxide, 9), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Aluminium, 4)}, null, null, new ItemStack[]{GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Silicon, 3), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Aluminiumoxide, 10)}, 10, 120)`

2022-06-03 17:43 UTC, Dream-Master commented on src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java
> +        GT_Values.RA.addMultiblockChemicalRecipe(new ItemStack[]{GT_Utility.getIntegratedCircuit(1), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.SiliconDioxide, 3), GT_OreDictUnificator.get(
will check why that was added/changed

2022-06-24 16:37 UTC, merged